Allow `undefined` onBarCodeScanned prop
expo/expo pull request #10068
Opened 2020-09-04 17:32 UTC by josmithua

# Why

Currently this line in the example code in the official docs produces a type error: 
```
onBarCodeScanned={code ? undefined : handleBarCodeScanned}
``` 
because the prop doesn't expect `undefined`. Yet it's a valid, documented value that enables the user to pause scanning. 

# How

This PR changes the type of the onBarCodeScanned prop to allow `undefined`

# Test Plan

1. Create a managed typescript expo project
1. `expo install expo-barcode-scanner`
1. Copy the official example from the docs (https://docs.expo.io/versions/latest/sdk/bar-code-scanner/)
1. Notice the type error as described above.
1. Pull this PR, and notice no more error.

2020-09-07 08:32 UTC, lukmccall requested changes
Thanks for contributing 🎉🎉🎉  Awesome work ;)
However, you need to do two things:
- run `yarn build` in `expo-barcode-scanner` directory
- add an entry to changelog -> https://github.com/expo/expo/blob/master/packages/expo-barcode-scanner/CHANGELOG.md

2020-09-14 20:53 UTC, josmithua commented
@lukmccall I've updated the CHANGELOG, and built the package (builds fine).

Cheers

2020-09-15 07:11 UTC, lukmccall requested changes

2020-09-15 07:11 UTC, lukmccall commented on packages/expo-barcode-scanner/CHANGELOG.md
> +- Allow `onBarCodeScanned` prop to be `undefined`
```suggestion
- Allow `onBarCodeScanned` prop to be `undefined`. ([#10068](https://github.com/expo/expo/pull/10068) by [@josmithua](https://github.com/josmithua))
```

2020-09-15 07:12 UTC, lukmccall commented
Please, add rebuild files to this PR ;)

2020-09-15 14:23 UTC, josmithua commented
Sorry, not sure how I missed the changed build files before!

2020-09-15 14:27 UTC, lukmccall approved these changes
LGTM 🎉🎉🎉

2020-09-15 14:35 UTC, merged