[docs] Add <Tabs/> component plugin
expo/expo pull request #10213
Opened 2020-09-17 12:05 UTC by barthap

# Why

Resolves #10189 and it's direct answer to https://github.com/expo/expo/issues/10189#issuecomment-692996355
I haven't found support for Tabs in current Expo docs.

# How

Added `<Tabs/>` component to docs plugins. Updated notifications guide to use the component. Demo GIF's below.

Usage:
```js

import { Tab, Tabs } from '~/components/plugins/Tabs';

// ...

<Tabs>
  <Tab label="First tab">First tab content</Tab>
  <Tab label="Second tab">Lorem ipsum</Tab>
</Tabs>
```

# Test Plan

Renders correctly in `yarn dev`.

---

![tabs1](https://user-images.githubusercontent.com/278340/93467873-7eb64200-f8ee-11ea-88b5-afbc2e5f51ee.gif)

Demo below has random text copied, please ignore this 😅 

![tabs2](https://user-images.githubusercontent.com/278340/93467902-84138c80-f8ee-11ea-9384-08ca6a9540ea.gif)

2020-09-17 12:12 UTC, barthap commented on docs/components/plugins/Tabs.js
> +
```suggestion
```

2020-09-17 12:12 UTC, barthap commented on docs/components/plugins/Tabs.js
> +          if (child.props.label !== activeTab) return;
```suggestion
          if (child.props.label !== activeTab) {
            return;
          }
```

2020-09-17 16:35 UTC, bbarthec commented
Why not to use some 3rd party library? For example: https://github.com/reactjs/react-tabs?

2020-09-18 06:09 UTC, barthap commented
I just wanted to keep it as simple and lightweight as possible. IMO most of these libraries look like an overkill. My implementation is only ~80 lines of code and IMO it's easier to use than the one you linked. But if you prefer to, I can just replace my implementation with that library.

2020-09-18 09:17 UTC, bbarthec approved these changes
I'm not a fun of this linked library as well. I just wanted to know whether you've checked what's already there is the wild world of internet 😉

2020-09-18 12:12 UTC, byCedric commented
I think Evan already added [`@react/tabs`](https://github.com/expo/expo/blob/master/docs/package.json#L23) for the [authentication guides](https://docs.expo.io/guides/authentication/#coinbase).

![Screenshot 2020-09-18 at 02 06 35](https://user-images.githubusercontent.com/1203991/93595915-dcaf5c00-f9b8-11ea-8dfb-5f03e1307e7b.png)

We might get away with just re-exporting these components somewhere from `~/components/plugins/tabs` 😄

2020-09-18 15:10 UTC, barthap commented
Indeed, I didn't notice that, looks like AuthSession components might be made more universal:

https://github.com/expo/expo/blob/7db65dee00cc9fb0395fd8a766deb3cb8a20131c/docs/components/plugins/AuthSessionElements.js#L121-L166

The question is which style we want? I don't see auth tabs being affected by latest styling update, IMO they're looking cool as they are

2020-09-21 07:53 UTC, bbarthec commented
@barthap, indeed, your approach seems easier to be used IMO. To keep things consistent you can now update this other component with the idea of yours and use the single component in all places 😉

2020-09-21 11:21 UTC, barthap commented
To ensure I understand correctly, you mean:
- Rework tabs API to look my way
- Leave CSS styling as it was in [Authentication Guide](https://docs.expo.io/guides/authentication/#dropbox)

But shall we keep using `@reach/tabs` library or switch to my plain solution? 🤔

2020-09-21 11:46 UTC, bbarthec commented
@barthap, if refactoring this API is not going to take long let's do this. Let's keep `@reach/tabs` 👍

2020-09-22 10:27 UTC, barthap commented
Ok, I've updated it, now it:
- Has _Authentication Guide_ look
- Uses `@reach/tabs` library
- Works using both mine and little modified Evan's syntax

2020-09-22 12:42 UTC, bbarthec requested changes

2020-09-22 12:42 UTC, bbarthec commented on docs/pages/guides/authentication.md
> +import { SocialGrid, SocialGridItem, CreateAppButton, AuthMethodTabSwitcher, AuthMethodTab } from '~/components/plugins/AuthSessionElements';
```suggestion
import { SocialGrid, SocialGridItem, CreateAppButton } from '~/components/plugins/AuthSessionElements';
import { Tab, Tabs } from '~/components/plugins/Tabs';
```
Why not ot use these Tabs of your directly? 🤔

2020-09-22 12:42 UTC, bbarthec commented on docs/components/plugins/AuthSessionElements.js
> +import { Tab, Tabs } from './Tabs';
```suggestion
```

2020-09-22 12:42 UTC, bbarthec commented on docs/components/plugins/AuthSessionElements.js
> +export const AuthMethodTabSwitcher = Tabs;
```suggestion
```

2020-09-22 12:42 UTC, bbarthec commented on docs/pages/guides/authentication.md
>  <AuthMethodTabSwitcher tabs={["Auth Code", "Implicit Flow"]}>
```suggestion
<Tabs tabs={["Auth Code", "Implicit Flow"]}>
```

2020-09-22 12:42 UTC, bbarthec commented on docs/pages/guides/authentication.md
> +<AuthMethodTab>
```suggestion
<Tab>
```

2020-09-22 12:42 UTC, bbarthec commented on docs/pages/guides/authentication.md
> +<AuthMethodTab>
And so on ... 😉

2020-09-22 15:09 UTC, bbarthec approved these changes

2020-09-28 11:28 UTC, merged