spinner icon animation example added
expo/expo pull request #10254
Opened 2020-09-21 07:04 UTC by anandchakru

# Why

https://github.com/expo/vector-icons/issues/141

# How

Added an example in the documentation for future reference

# Test Plan

Not required/Not Applicable, since the update was only on documentation.

2020-10-30 19:40 UTC, cruzach requested changes
just some styling changes so that the icon rotates around itself 👍

2020-10-30 19:40 UTC, cruzach commented on docs/pages/guides/icons.md
> +      <Animated.View style={{ transform: [{ rotate: rotateAnimation }] }}>
```suggestion
      <Animated.View style={{ marginTop: '10%', transform: [{ rotate: rotateAnimation }] }}>
```

2020-10-30 19:40 UTC, cruzach commented on docs/pages/guides/icons.md
> +    color: '#076b22',
```suggestion
    alignSelf: 'center',
    color: '#076b22',
```

2020-11-11 01:30 UTC, anandchakru commented
anyone to approve the PR?

2022-01-26 01:06 UTC, closed without merging

2022-01-26 19:33 UTC, anandchakru commented
@brentvatne Closed without PR merge, does this mean the example is insignificant?
Or was this part of a mass-close-all-old-PRs without reviewing each one?