[expo-updates] handle ./ in assetUrlOverride
expo/expo pull request #10342
Opened 2020-09-23 22:54 UTC by esamelson

# Why

regression in the current iOS client -- opening self-hosted projects with `./assets` in `assetUrlOverride` (which is the default for projects exported by `expo export`) is broken because the URL logic on iOS does not properly handle the `./`.

# How

- attempting to use `NSURL URLWithString:relativeToPath:` does not seem to handle `./` properly either (in both cases it just appends the entire string to the base URL) so we just special case this and remove the `./` manually if it exists.
- do the same logic on the Android client to maintain as much consistency as possible between the clients.

# Test Plan

test opening https://esamelson.github.io/self-hosting-test/ios-index.json in the iOS and Android clients. Will also add unit tests for this case and #10337 but don't want that to block landing this PR and getting a fix out to the App Store.

2020-09-24 01:32 UTC, ide requested changes
Use path normalization/standardization methods. Ideally we'd comply with https://www.ietf.org/rfc/rfc3986.txt (section 3.3 on paths), but I imagine using the built-in Java URI and Foundation NSURL are OK for now (NSURLComponents would be ideal as it complies with that RFC instead of an older one).

2020-09-24 01:32 UTC, ide commented on packages/expo-updates/ios/EXUpdates/Update/EXUpdatesLegacyUpdate.m
> +      }
Replace this with the more robust https://developer.apple.com/documentation/foundation/nsurl/1411073-standardizedurl?language=objc

2020-09-24 01:32 UTC, ide commented on packages/expo-updates/android/src/main/java/expo/modules/updates/manifest/LegacyManifest.java
> +        if (hostname.contains(expoDomain)) {
This should be `equals expoDomain or ends with "." + expoDomain` (expo.io.uhoh.com)

2020-09-24 01:32 UTC, ide commented on packages/expo-updates/android/src/main/java/expo/modules/updates/manifest/LegacyManifest.java
>          }
java.net.URI has `normalize` which we might want to use here and then convert to an Android Uri. This will take care of `../` as well.

2020-10-02 01:02 UTC, ide approved these changes

2020-10-02 01:03 UTC, ide commented
Looks good for now. We might want to support `..` to go up the base URL path in the future but need to think through the implications of that.

2020-10-02 01:51 UTC, merged

2020-10-02 22:09 UTC, RodolfoGS commented
Hi @esamelson, I'm experimenting this issue in a Bare workflow iOS project, this fix Bare or only fix Managed workflows?

2020-10-02 23:31 UTC, esamelson commented
This fix has just now been released to the bare workflow in expo-updates@0.3.5. Managed workflow users will need to hold tight a little longer! https://github.com/expo/expo/issues/10464 will have status updates on the bugfix release for the managed workflow.

2020-10-03 23:50 UTC, brentvatne commented
https://github.com/expo/expo/issues/10464#issuecomment-703178030