[expo-permissions] Add rename `CAMERA_ROLL` to `MEDIA_LIBRARY` & add write only permission
expo/expo pull request #10643
Opened 2020-10-12 14:08 UTC by lukmccall

# Why

Since iOS 14, we can add write-only permission to the media library. Moreover, we want to remove `CAMERA_ROLL` to `MEDIA_LIBRARY`. 

# How

- `CAMERA_ROLL` -> `MEDIA_LIBRARY`
- added `WRITE_ONLY_MEDIA_LIBRARY`:
  - [x] media-library
  - [x] permissions
  - [x] image-picker
- updated documentation

# Test Plan

- NCL ✅

2020-10-13 09:11 UTC, bbarthec requested changes
That is looking good, but I prefer `MEDIA_LIBRARY_WRITE_ONLY` name for this permission 💅 I believe having `<context/subject>_<specifier>` is closely related to the idea of following [Node.JS error codes convention](https://nodejs.org/dist/latest-v14.x/docs/api/errors.html).

2020-10-13 09:11 UTC, bbarthec commented on docs/pages/versions/unversioned/sdk/permissions.md
> +| `MEDIA_LIBRARY`<br /> `WRITE_ONLY_MEDIA_LIBRARY` | `expo-image-picker`<br /> `expo-media-library`                                                                                 |
```suggestion
| `MEDIA_LIBRARY`<br /> `MEDIA_LIBRARY_WRITE_ONLY` | `expo-image-picker`<br /> `expo-media-library`                                                                                 |
```
After a small inner struggle I believe that'a a better name for this permission 🤔

2020-10-14 09:42 UTC, bbarthec approved these changes
LGTM 👍 
Found two small things 😉

2020-10-14 09:42 UTC, bbarthec commented on docs/pages/versions/unversioned/sdk/permissions.md
> +- [`Permissions.WRITE_ONLY_MEDIA_LIBRARY`](#permissionsmedia_library_write_only) -- writing to media library
```suggestion
- [`Permissions.MEDIA_LIBRARY_WRITE_ONLY`](#permissionsmedia_library_write_only) -- writing to media library
```

2020-10-14 09:42 UTC, bbarthec commented on packages/expo-permissions/src/Permissions.types.ts
> +  // iOS only - Permission.MEDIA_LIBRARY/MEDIA_LIBRARY_WRITE_ONLY
```suggestion
  /**
   * iOS only - Permission.MEDIA_LIBRARY/MEDIA_LIBRARY_WRITE_ONLY
   **/
```
~I'm not sure~ if non-block comments are applied to the signatures/variables and presented in VSCode 🤔 
_edit_: I've just confirmed that they're not 😉

2020-10-20 13:51 UTC, merged

2020-12-27 18:57 UTC, gregfenton commented
Consider marking this as a "breaking change" for the SDK 40 release notes.

2020-12-31 06:49 UTC, KemaneWright commented
Any updates on this?

2020-12-31 06:53 UTC, gregfenton commented
> Any updates on this?

What update are you looking for?  The change is merged and was released with SDK 40.  My latest comment is about updating the SDK 40 release notes to reflect that this change requires existing apps to make adjustments to their code (i.e. this is a "breaking change").

2020-12-31 07:28 UTC, KemaneWright commented
Oh sorry I meant to reference this thread https://github.com/MonstroDev/expo-image-picker-multiple/issues/30

For the image-picker-multiple package