feat(expo-task-manager): Add isAvailableAsync
expo/expo pull request #10657
Opened 2020-10-13 13:06 UTC by pranshuchittora

# Why

Closes #9659

# How

Added isAvailableAsync
# Test Plan
NA - WIP

2020-10-13 13:08 UTC, pranshuchittora commented
Need some help
- for iOS module
- Exported the method only for the web, is there be any export from the root file i.e. `TaskManager.ts`

2020-10-13 13:29 UTC, sjchmiela reviewed
Let's use one or the other way of checking if task manager is available. 👍

2020-10-13 13:29 UTC, sjchmiela commented on packages/expo-task-manager/src/ExpoTaskManager.web.ts
> +    return true;
```suggestion
    return false;
```
I don't think task manager is available on web. 😃

2020-10-13 13:29 UTC, sjchmiela commented on packages/expo-task-manager/android/src/main/java/expo/modules/taskManager/TaskManagerModule.java
> +    promise.resolve(true);
```suggestion
    promise.resolve(mTaskService != null);
```

2020-10-13 13:29 UTC, sjchmiela commented on packages/expo-task-manager/ios/EXTaskManager/EXTaskManager.m
> +  resolve(@([_taskService ]));
```suggestion
  resolve(@(_taskService != nil));
```

2020-10-13 13:34 UTC, sjchmiela commented
Don't forget to update the CHANGELOG too and export the method!

2020-10-13 14:07 UTC, pranshuchittora commented
r

> Don't forget to update the CHANGELOG too and export the method!

You mean exporting the method from `TaskManager.ts` as well ?

2020-10-13 14:41 UTC, bbarthec requested changes

2020-10-13 14:41 UTC, bbarthec commented on CHANGELOG.md
> +
```suggestion
```
If there's a package-level CHANGELOG, the change description goes there. This one is filled during the release of the Expo Client 😉

2020-10-13 14:41 UTC, bbarthec commented on packages/expo-task-manager/CHANGELOG.md
> +- Add isAvailableAsync to expo-task-manager ([#10657](https://github.com/expo/expo/pull/10657) by [@PranshuChittora](https://github.com/pranshuchittora))
```suggestion
- Added `isAvailableAsync` method. ([#10657](https://github.com/expo/expo/pull/10657) by [@PranshuChittora](https://github.com/pranshuchittora))
```

2020-10-14 10:03 UTC, bbarthec requested changes
The missing thing is the docs adjustment: https://github.com/expo/expo/blob/master/docs/pages/versions/unversioned/sdk/task-manager.md

Do you ming adding this method to the docs as the first method under [this section](https://github.com/expo/expo/blob/master/docs/pages/versions/unversioned/sdk/task-manager.md#api)

2020-10-14 11:09 UTC, pranshuchittora commented
> The missing thing is the docs adjustment: https://github.com/expo/expo/blob/master/docs/pages/versions/unversioned/sdk/task-manager.md
> 
> Do you ming adding this method to the docs as the first method under [this section](https://github.com/expo/expo/blob/master/docs/pages/versions/unversioned/sdk/task-manager.md#api)

Done :+1:

2020-10-14 12:07 UTC, bbarthec approved these changes

2020-10-14 12:08 UTC, merged

2020-10-14 12:10 UTC, pranshuchittora commented
Thanks :)