Guard against null FragmentActivity
expo/expo pull request #10679
Opened 2020-10-14 14:42 UTC by vascofg

# Why

Fix issue #10678 

# How

Guard against null FragmentActivity when creating BiometricPrompt.

# Test Plan

Not sure how to test this since I'm unaware what causes the activity to be null. Might be a timing issue where we prompt for authentication too soon in the app lifecycle.

2020-10-15 13:23 UTC, lukmccall requested changes
LGTM 🚀🚀🚀

But you should add an changelog entry -> https://github.com/expo/expo/blob/master/packages/expo-local-authentication/CHANGELOG.md.

And I think you can test it with `Don't keep activities` options turn on in the `Developer Settings` on your device.

2020-10-15 13:29 UTC, vascofg commented
@lukmccall updated Changelog

2020-10-16 06:51 UTC, lukmccall approved these changes

2020-10-16 06:51 UTC, merged

2020-11-05 14:02 UTC, vascofg commented
@lukmccall do you have an ETA when will this be released?

2020-11-09 10:17 UTC, lukmccall commented
I think it'll be published this month, but I'm not sure.