[expo-av] add opt-in metering info to status
expo/expo pull request #10759
Opened 2020-10-21 17:53 UTC by danieloi

# Why

Adds decibel information to the status object. 
This makes it so sound level information can be visualized and/or displayed on android and ios.
# How

- added withMeteringFlag parameter to prepareAudioRecorder function in js and native land
- added necessary logic and API calls for getting metering values in getAudioRecorderStatus function in native land
- return the status object in native land, with or without the metering key, based on the flag value in the prepareAudioRecorder call.
# Test Plan

All tests pass. 
The Recorder example doesn't take in audio in the android emulator but runs as usual with the feature enabled.

2020-10-23 16:06 UTC, bbarthec requested changes
Ok, so I've got a couple of questions:

1. Why in the `results` object you've created:
```ts
{
  ...
  metering: {
    value: number
  }
  ...
}
```
instead of:
```ts
{
  ...
  metering: number
  ...
}
```
I don't see any additional info for this key apart from a single number.

2. Why you've created another parameter `isMeteringEnabled` instead of adding it to the `RecordingOptions`? Change it.

3. As far as I can see when `isMeteringEnabled = true` you're just simply querying the system, so maybe let's abandon this flag all together and add this information always? 🤔 Let's go this way 👍 

4. Why have you used the word `metering`? 🤔 Does it have some specific meaning in regards to decibels/volume/amplitude? 🤔 

Once you give me answers for these questions & adjust the PR according to 2. and 3. I'll resume reviewing.

And there're are parts that are missing:
- CHANGELOG entry
- docs change

2020-10-23 18:40 UTC, danieloi commented
> he PR accord

1. That makes sense. I started off with porting this feature from [react-native-sound-level](https://github.com/punarinta/react-native-sound-level) and they used an object with a "value" key and a "raw value" key because android returned a different value from ios. Changed my mind last minute from adding the "raw value" key and should've just used the number instead of an object

2. Because it didn't have to do with ios or android. What do you say I make it a key at the same depth as "ios" and "android"? 

3. [_" Because metering uses computing resources, turn it on only if you intend to use it."_](https://developer.apple.com/documentation/avfoundation/avaudiorecorder/1386355-meteringenabled?language=objc)

4. see No. 3. I borrowed the term from the ios docs. Also noticed [react-native-audio-toolkit](https://github.com/react-native-audio-toolkit/react-native-audio-toolkit/blob/master/docs/API.md) used similar naming.

What are your thoughts  @bbarthec ?

2020-10-26 09:51 UTC, bbarthec commented
@danieloi, yeah, the observations of yours seem legit 👍 
Please proceed with this PR work according to your reply 💪

The other thing is that we'll need some explanation in Android codebase (some inline comment) why you're using this piece of code with given constants:
```java
    int amplitude = mAudioRecorder.getMaxAmplitude();
    if (amplitude == 0) {
      result = -160;
    } else {
      result = (int) (20 * Math.log(((double) amplitude) / 32767d));
    }
```

2020-11-25 11:19 UTC, danieloi commented
Pardon the delay.

I've made the changes. 

Added comments on the constants per your request. 

I asked to further explain the hex constant (32767d) in the issues of the source repos I mentioned. 
It's supposed to be a ratio between the base sound level and the measured one. Decibels is a relative measurement. 

That value gives levels info comparable to iOS's values.

2020-12-10 09:30 UTC, bbarthec reviewed
Overall it looks fine 👍 
I've suggested a few style improvements.

2020-12-10 09:30 UTC, bbarthec commented on packages/expo-av/android/src/main/java/expo/modules/av/AVManager.java
> +    return result;
```suggestion
    int amplitude = mAudioRecorder.getMaxAmplitude();
    if (amplitude == 0) {
      return -160;
    }
     
    // Amplitude to decibel conversion.
    // Code copied from https://github.com/punarinta/react-native-sound-level
    // It's supposed to be a ratio between the base sound level and the measured one.
    // Decibels is a relative measurement.
	// Value `32767d` gives levels info comparable to iOS's values.
	// see: https://github.com/punarinta/react-native-sound-level/issues/20
    return = (int) (20 * Math.log(((double) amplitude) / 32767d));
```

2020-12-10 09:30 UTC, bbarthec commented on packages/expo-av/android/src/main/java/expo/modules/av/AVManager.java
> +      }
```suggestion
      map.putBoolean("canRecord", true);
      map.putBoolean("isRecording", mAudioRecorderIsRecording);
      map.putInt("durationMillis", (int) getAudioRecorderDurationMillis());

      if (mAudioRecorderIsMeteringEnabled) {
        map.putInt("metering", (int) getAudioRecorderLevels());
      }
```

2020-12-10 09:30 UTC, bbarthec commented on packages/expo-av/android/src/main/java/expo/modules/av/AVManager.java
> +    }
```suggestion
    mAudioRecorderIsMeteringEnabled
 = options.getBoolean(RECORDING_OPTION_IS_METERING_ENABLED_KEY);
```

2020-12-10 09:30 UTC, bbarthec commented on packages/expo-av/ios/EXAV/EXAV.m
>               @"durationMillis": @(durationMillis)};
```suggestion

    NSMutableDictionary *result = [@{
      @"canRecord": @(YES),
      @"isRecording": @([_audioRecorder isRecording]),
      @"durationMillis": @(durationMillis),
    } mutableCopy];

    if (_audioRecorder.meteringEnabled) {
      [_audioRecorder updateMeters];
      float currentLevel = [_audioRecorder averagePowerForChannel: 0];
      result[@"metering"] = @(currentLevel);
    }

    return result;
```

2020-12-10 14:18 UTC, bbarthec reviewed
LGTM 👍 
Please, rebase it so there is no conflict anymore and we're ready to go 😉

2020-12-10 14:18 UTC, bbarthec commented on packages/expo-av/ios/EXAV/EXAV.m
> +        }
```suggestion
      if (options[EXAudioRecordingOptionsIsMeteringEnabledKey]) {
        _audioRecorder.meteringEnabled = true;
      }
```

2020-12-11 15:41 UTC, bbarthec commented
@danieloi, I'm not sure what've done here, but it seems that you've pulled in to this PR quite a number of commits that are completely unrelated to the topic 😰

2020-12-11 16:31 UTC, danieloi commented
Haha 
I “rebased” to get rid of conflicts. 
I’ll undo it and push again.

2020-12-15 13:56 UTC, danieloi commented
I'm getting a lot of baggage when I try to resolve the conflict. @bbarthec. 

It's in the CHANGELOG, it floods my repo with a lot of changes I didn't have before when I click through the resolve flow. 

Help?

2020-12-15 14:01 UTC, danieloi commented
Tried adding it to another branch and it looks like there are no more issues.

2020-12-15 20:54 UTC, bbarthec approved these changes
Yeah, looks good now 😊 
Thank you for all the effort you've put into this PR (rebasing, providing context, comments, etc.).
Really great job! 🎉
I hope you'll create some more PRs as you're more experienced with `expo/expo` repository now 😊

2020-12-15 20:55 UTC, merged

2020-12-15 21:39 UTC, danieloi commented
Y’all are doing great work. 

Looking for employment at the moment if y’all have anything open for a self starter. 
Shameless plug but there it is 😄. 

Thanks for the timely, valuable feedback and improvements all the way.

2021-01-13 14:38 UTC, blainekasten commented
Any chance this can be published in a new version? 😄

2021-01-14 11:37 UTC, bbarthec commented
@blainekasten, I've just published a new version of this package to `npm` under the `next` tag. (https://www.npmjs.com/package/expo-av/v/9.0.0). 🎉

2021-01-14 16:16 UTC, blainekasten commented
@bbarthec i just installed `next` and it appears to have updated from the js side (type defs are updated, and preset includes the metering flag). But the stats update is not including the `meter` flag. Is there anything special I need to do to make sure the new native code is loaded?

Running on ios through the expo app.

2021-01-14 18:23 UTC, bbarthec commented
@blainekasten, this is not going to work in Expo Client until the new SDK containing this change is released 😟