[expo-constants] Add support for running on simulators on M1
expo/expo pull request #11445
Opened 2020-12-22 21:17 UTC by sjchmiela

# Why

`devicePlatform` on a simulator running on an M1 computer resolves to `"arm64"` for which a human-readable value isn't defined, thus returning `nil` which we don't expect when building a dictionary which causes `ExponentConstants` to not be available.

# How

Added support for new device platform in all places I could find it (`expo-constants`, `expo-device`).

# Test Plan

Applying this patch on an M1 computer does fix the issue.

2020-12-22 21:48 UTC, tsapeta approved these changes
👍

2020-12-22 22:32 UTC, ide requested changes

2020-12-22 22:32 UTC, ide commented on packages/expo-constants/ios/EXConstants/EXConstantsService.m
> +  return deviceModel ?: @"Unsupported";
nil seems like a better value than Unsupported here -- callers need to handle it anyway

2020-12-23 10:55 UTC, bbarthec approved these changes

2020-12-30 15:44 UTC, ide approved these changes
Thank you!

2020-12-30 15:44 UTC, ide commented on docs/pages/versions/unversioned/sdk/constants.md
> +  The human-readable model name of this device, e.g. `iPhone 7 Plus` if it can be determined, otherwise will be `null`.
```suggestion
  The human-readable model name of this device, e.g. `"iPhone 7 Plus"` if it can be determined, otherwise will be `null`.
```

2020-12-30 15:46 UTC, merged