[expo-updates] add unit tests for manifest classes
expo/expo pull request #11562
Opened 2021-01-08 02:40 UTC by esamelson

# Why

Slowly but surely improving the automated test coverage of this module!

# How

Added native unit tests for the following things:
- legacy manifest required fields
- new (EAS) manifest required fields
- manifest creation (that the correct class is used depending on the type of manifest)
- added a bit more coverage to the existing tests around asset base urls

Additionally, writing these tests exposed some discrepancies between/within platforms about handling possibly null manifest fields, so I fixed those. Thanks, tests!

# Test Plan

All tests pass ✅ 

# To do

- setup a CI job for Xcode unit tests

2021-01-08 23:40 UTC, ide requested changes
Would be good to add tests with an origin-relative override like `/my_assets` too.

2021-01-08 23:40 UTC, ide commented on packages/expo-updates/android/src/androidTest/java/expo/modules/updates/manifest/ManifestFactoryTest.java
> +  private String newManifestJson = "{\"manifest\":{\"runtimeVersion\":\"1\",\"id\":\"0eef8214-4833-4089-9dff-b4138a14f196\",\"createdAt\":\"2020-11-11T00:17:54.797Z\",\"launchAsset\":{\"url\":\"https
```suggestion
  private String newManifestJson = "{\"manifest\":{\"runtimeVersion\":\"1\",\"id\":\"0eef8214-4833-4089-9dff-b4138a14f196\",\"createdAt\":\"2020-11-11T00:17:54.797Z\",\"launchAsset\":{\"url\":\"https://d1wp6m56sqw74a.cloudfront.net/%40esamelson%2Fnative-component-list%2F39.0.0%2F01c86fd863cfee878068eebd40f165df-39.0.0-ios.js\",\"contentType\":\"application/javascript\"}}}";
```
this is more realistic

2021-01-08 23:40 UTC, ide commented on packages/expo-updates/android/src/androidTest/java/expo/modules/updates/manifest/NewManifestTest.java
> +    String manifestJson = "{\"runtimeVersion\":\"1\",\"id\":\"0eef8214-4833-4089-9dff-b4138a14f196\",\"createdAt\":\"2020-11-11T00:17:54.797Z\",\"launchAsset\":{\"url\":\"https://url.to/bundle.js\",\
```suggestion
    String manifestJson = "{\"runtimeVersion\":\"1\",\"id\":\"0eef8214-4833-4089-9dff-b4138a14f196\",\"createdAt\":\"2020-11-11T00:17:54.797Z\",\"launchAsset\":{\"url\":\"https://url.to/bundle.js\",\"contentType\":\"application/javascript\"}}";
```

2021-01-08 23:40 UTC, ide commented on packages/expo-updates/android/src/androidTest/java/expo/modules/updates/manifest/NewManifestTest.java
> +  @Test(expected = Exception.class)
Is there a more precise type of Exception that's always expected?

2021-01-08 23:40 UTC, ide commented on packages/expo-updates/android/src/androidTest/java/expo/modules/updates/manifest/NewManifestTest.java
> +    String manifestJsonWithRootLevelKeys = "{\"data\":{\"publicManifest\":{\"manifest\":{\"runtimeVersion\":\"1\",\"id\":\"0eef8214-4833-4089-9dff-b4138a14f196\",\"createdAt\":\"2020-11-11T00:17:54.7
Conflating this with a JSON manifest seems like it will cause confusion later on. This is an EAS-specific API server response.

2021-01-08 23:40 UTC, ide commented on packages/expo-updates/ios/Tests/EXUpdatesNewUpdateTests.m
> +    @"launchAsset": @{@"url": @"https://url.to/bundle.js", @"contentType": @"js"}
```suggestion
    @"launchAsset": @{@"url": @"https://url.to/bundle.js", @"contentType": @"application/javascript"}
```

2021-01-12 00:27 UTC, ide commented on packages/expo-updates/android/src/androidTest/java/expo/modules/updates/manifest/NewManifestTest.java
> +    String manifestJsonWithRootLevelKeys = "{\"data\":{\"publicManifest\":{\"manifest\":{\"runtimeVersion\":\"1\",\"id\":\"0eef8214-4833-4089-9dff-b4138a14f196\",\"createdAt\":\"2020-11-11T00:17:54.7
Talking with Eric -- we're going to make the change on the server first before changing the client-side code. This PR just adds tests for code that's already there.

2021-01-12 02:22 UTC, esamelson commented
addressed all code comments; re: origin-relative URLs, it looks like we don't actually handle those correctly right now (!) . I will open a new PR (with tests) to address that rather than doing it all in this PR.

2021-01-12 05:24 UTC, ide approved these changes

2021-01-12 18:53 UTC, merged