[expo-updates] fix origin-relative URL support in assetUrlOverride
expo/expo pull request #11601
Opened 2021-01-12 03:28 UTC by esamelson

# Why

https://github.com/expo/expo/pull/11562#pullrequestreview-564638536

# How

Got rid of all custom logic around this and now just using `java.net.URI.resolve` and `[NSURL URLWithString: relativeToURL:]` which takes care of everything (including the problematic case) for us.

# Test Plan

Added tests for the new case on both platforms. These and all existing tests pass. (Had to change the iOS tests to compare the URLs' `absoluteString` properties rather than the objects themselves, since with the new construction the `isEqual` property was not returning true even though the string representation was equal.)

2021-01-12 06:37 UTC, ide requested changes
Requesting more tests but otherwise this looks good (and must have been a lot easier to code because the prior tests!)

2021-01-12 06:37 UTC, ide commented on packages/expo-updates/android/src/main/java/expo/modules/updates/manifest/LegacyManifest.java
> -          normalizedAssetsPath = assetsPathURI.normalize().toString();
Add a test case that tests the normalization behavior, perhaps with an asset path like `./a/../b`. URI.resolve normalizes so the tests should pass. (Also I'm curious what happens if the asset path has enough `..`s that it goes back past the hostname.)

2021-01-12 06:37 UTC, ide commented on packages/expo-updates/ios/EXUpdates/Update/EXUpdatesLegacyUpdate.m
> +    return [NSURL URLWithString:assetsPathOrUrl relativeToURL:manifestUrl.standardizedURL];
Same comment about adding tests for normalization. There's some chance this needs to return `.standardizedURL` of the resolved URL.

2021-01-12 20:54 UTC, esamelson commented
Added tests for `./a/../b` and `../b`, both of which behave correctly.

I also tried adding a test for `../../b` which goes back past the hostname. Android handles this in probably the most common-sense way, just going back to the hostname and removing extra `../` path segments, but iOS just keeps the extra path segments (so you end up with something like `https://hostname.com/../b`). AFAICT, confusingly, this is actually the correct behavior according to RFC 2396... at least how [Android documents it](https://docs.oracle.com/javase/7/docs/api/java/net/URI.html#normalize%28%29). Using `[NSURL standardizedURL]` on the result actually makes things worse (seems to just ignore the `../` segments entirely -- I think it standardizes the two URL fragments **before** resolving them).

Since this is a pathological case, I think we should just say the behavior is undefined, rather than adding and maintaining extra logic and tests just for this one case... does that seem reasonable?

2021-01-12 23:52 UTC, ide commented
> Since this is a pathological case, I think we should just say the behavior is undefined, rather than adding and maintaining extra logic and tests just for this one case... does that seem reasonable?

Yes, I think so. If we want to settle on some behavior in the long term, Android's behavior of just stripping out excess `..` matches Chrome's.

One last thing I'd try is computing `url.absoluteURL.standardizedURL` in case that forces the URL to be treated as one whole string before normalizing.

2021-01-12 23:53 UTC, ide approved these changes

2021-01-13 01:44 UTC, esamelson commented
Ah, thanks for the tip -- that worked, and also allowed me to compare the NSURL objects in tests directly rather than converting them to strings first 🎉  I've made those changes and added tests on both platforms for the `../../b` case.

2021-01-13 03:59 UTC, ide approved these changes

2021-01-13 19:28 UTC, merged