[expo] stop exporting LegacyNotifications in SDK 41
expo/expo pull request #11807
Opened 2021-02-01 20:57 UTC by cruzach

# Why

This module has been deprecated for the past 2 SDK releases, we said we'd remove it in SDK 40 but didn't so let's remove it now

# How

Removed export, and changed some logic in `ExpoFirebaseMessagingDelegate.java` (which was already preventing any remote notifications from using the legacy API in SDK 40 😬 )

Remaining questions:
- Should we keep the web implementation around, or move it to `expo-notifications`?
- Should I delete the related native code for legacynotifications, or keep it around in case of emergency?

# Revert plan

Are you trying to revert this PR after releasing SDK 41 because you want to re-enable the legacy notifications module? Since we were preventing remote notifications from using the legacy API in SDK 40, it's not as simple as just rolling back this PR, but it is _almost_ that simple. Revert this PR, then apply this diff to `ExpoFirebaseMessagingDelegate.java`:
```diff
--- a/android/expoview/src/main/java/host/exp/exponent/fcm/ExpoFirebaseMessagingDelegate.java
+++ b/android/expoview/src/main/java/host/exp/exponent/fcm/ExpoFirebaseMessagingDelegate.java
@@ -53,6 +53,16 @@ public class ExpoFirebaseMessagingDelegate extends FirebaseMessagingDelegate {
         // If an experience is on SDK newer than 39, that is SDK40 and beyond up till UNVERSIONED
         // we only use the new notifications API as it is going to be removed from SDK40.
         if (sdkVersion >= 40) {
+          // BEGIN- IN CASE OF EMERGENCY
+          JSONObject androidSection = manifest.optJSONObject("android");
+          if (androidSection != null) {
+          boolean useNextNotificationsApi = androidSection.optBoolean("useNextNotificationsApi", true);
+            if (!useNextNotificationsApi) {
+              dispatchToLegacyNotificationModule(remoteMessage);
+              return;
+            }
+          }
+          // END- IN CASE OF EMERGENCY
           dispatchToNextNotificationModule(remoteMessage);
           return;
         } else if (sdkVersion == 38 || sdkVersion == 39) {
```
 and instruct users to set `android.useNextNotificationsApi` in their app.json file to `false`. Then republish the `expo` package and rebuild android shell apps.

2021-03-03 01:23 UTC, ide approved these changes
Rename apps/test-suite/tests/NewNotifications.ts to apps/test-suite/tests/Notifications.ts.

2021-03-03 01:23 UTC, ide commented on docs/scripts/schemas/unversioned/app-config-schema.js
> +          'A Boolean value that indicates whether the app should use the new notifications API. Only applies to SDK 40 and below- in SDK 41, you must use the new API.',
```suggestion
          'A Boolean value that indicates whether the app should use the modern notifications API. Only applies to SDK 40 and below - SDK 41 and later do not include the legacy notifications API.',
```

2021-03-03 03:05 UTC, brentvatne commented
I think we can remove `badgin` now as well:
https://github.com/expo/expo/blob/master/packages/expo/package.json#L58

2021-03-03 03:10 UTC, brentvatne requested changes
just a few small things! i'm very pleased that we're finally able to do this. thanks!

2021-03-03 03:10 UTC, brentvatne commented on android/expoview/src/main/java/host/exp/exponent/fcm/ExpoFirebaseMessagingDelegate.java
> +        if (sdkVersion > 40) {
```suggestion
        if (sdkVersion >= 41) {
```

this matches more closely with the comment and imo is slightly easier to grok at a glance

2021-03-03 03:10 UTC, brentvatne commented on docs/scripts/schemas/unversioned/app-config-schema.js
> +          'A Boolean value that indicates whether the app should use the new notifications API. Only applies to SDK 40 and below- in SDK 41, you must use the new API.',
we should mark this as deprecated

2021-03-03 03:10 UTC, brentvatne commented on packages/expo/src/launch/withExpoRoot.tsx
> -      if (props.exp?.notification) {
it looks like we can get rid of the didInitialize ref entirely

2021-03-04 00:38 UTC, brentvatne approved these changes

2021-03-04 00:38 UTC, merged