[docs][expo-av] Document that Audio web support is pending
expo/expo pull request #11833
Opened 2021-02-03 23:33 UTC by Jamedjo

## What

Updates `<PlatformsSection ...>` to pending state, with reference to https://github.com/expo/expo/issues/8721.

## Why

The docs confusingly state that web is supported at https://docs.expo.io/versions/v40.0.0/sdk/audio/, when at least some of the functionality is not supported.

This can be reverted when https://github.com/expo/expo/pull/8791/ merges.

2021-05-10 19:27 UTC, cruzach requested changes
great! can you update `v410.0.0/sdk/audio.md` with the same change?

2021-05-13 10:37 UTC, Jamedjo commented
> great! can you update v410.0.0/sdk/audio.md with the same change?

@cruzach Added and rebased on a recent master

2021-05-13 13:23 UTC, cruzach approved these changes

2021-05-13 13:23 UTC, merged

2021-06-22 12:34 UTC, Basums commented
Hopefully in the future you'll be able to call web recordings just like Android does