[github] Better node_modules caching in SDK workflow
expo/expo pull request #11879
Opened 2021-02-09 14:29 UTC by tsapeta

# Why

Just trying different method of caching node modules.

# How

# Test Plan

2021-02-09 21:02 UTC, brentvatne approved these changes
i believe this should work well as long as we don't add any postinstall scripts that produce side effects that we gitignore and don't cache.

would like @ide to review also though.

2021-02-10 04:48 UTC, ide requested changes
This restores `node_modules` in the workspace root directory but doesn't restore `node_modules` in each of the workspaces. Lots of files will be missing if we don't run `yarn install` when there is a cache hit.

I think this approach works for `tools` since it is not a workspace or a workspace root, but it's not robust for the main root directory.

2021-02-10 07:08 UTC, tsapeta commented
Right. What if we use `**/node_modules` as a cache path? The action supports glob paths 🙂

2021-02-10 18:26 UTC, ide approved these changes

2021-02-10 18:26 UTC, ide commented on .github/workflows/sdk.yml
> +            **/node_modules
```suggestion
            # See "workspaces" → "packages" in the root package.json for the source of truth of
            # which node_modules are affected by the root yarn.lock
            **/node_modules
```

2021-02-10 22:15 UTC, merged