[Android][gradle] Add plugin for dependencies' versions detection
expo/expo pull request #11919
Opened 2021-02-11 17:56 UTC by bbarthec

# Why

Our Android native dependencies are quite out-of-date.
To keep them up to date we have to open every single `gradle.build` file, locate dependency and bump it's version (Android Studio also has some mechanism for updating dependencies, but I've failed to see all the dependencies in it 😞).

I've concluded that (following Brent's suggestion) that maybe we'll benefit from some tooling for this process.
There is a tool out there: https://github.com/kevcodez/gradle-upgrade-interactive, but it is lacking in many areas (eg. no option to change the suggested version of the dependency).
This tool bases on https://github.com/ben-manes/gradle-versions-plugin that seems very fancy and I followed along with it by creating a separate `expotools command` that tries to gather all the dependencies in all android sub-projects we have in `expo/expo` monorepo.

Additionally, what I think is most critical, searching every time for libraries changelogs is very dull process, so I've created `dependenciesChangelog.json` file that contains encountered Android native dependencies. This file is leveraged by the proposed command as well.

# How

I've created an expotools command `android-update-native-dependencies` that does the followings:
- launches `gradle updateDependency` task provided by https://github.com/ben-manes/gradle-versions-plugin for Expo Go project and `bare-expo` project (the latter includes some more `packages/*` only available in bare workflow). This task produces some `json` file describing detected dependencies is each android project.
- caches the results basing on daily timestamps and command params (I've checked that changing the `revision` gradle task params brings no visible change to the results produces by this task, bu who knows for sure 🤷)
- reads these projects' dependencies descriptions and presents them for some selection
- enables manual version input for each library (presents links with each dependency's changelog)
- modifies `gradle` files according to the final decision
- adds changelogs entries in each package describing the native dependency update with the link to the dependency's changelog.

# Test Plan

Just run `et android-update-native-dependencies -h` and follow along.

# Showcase

![command](https://user-images.githubusercontent.com/16623003/107677513-a4c3f080-6c9a-11eb-8cb7-27fb212b233b.gif)

# TODOs

- [ ] Create a similar tool for iOS native dependencies.
- [ ] Use this tool to bump native dependencies with some mindful strategy 🧘.

2021-02-13 12:10 UTC, tsapeta requested changes
Good job Bartek! 👏 💪 
Left a few comments, but I really like what you've done! 😍

2021-02-13 12:10 UTC, tsapeta commented on tools/src/android-update-native-dependencies/index.ts
> +export interface Options {
Why not a type? I think it's not going to be implemented by any class 🤔

2021-02-13 12:10 UTC, tsapeta commented on tools/src/android-update-native-dependencies/dependenciesChangelogs.json
> +{
We will need to find a better place for such jsons 🤔 We also have `changelogVersions.json` in the root folder (which is updated by `et merge-changelogs`) — might be good to keep them close — maybe `tools/data`?. What do you think?

2022-03-11 07:00 UTC, barthap reviewed
Not sure if you requested my review on purpose or accidentally, but anyway I took a quick look and left some comments 😅

2022-10-31 11:57 UTC, closed without merging