[expo-camera] ability to modify video bitrate on android
expo/expo pull request #11932
Opened 2021-02-12 18:50 UTC by makzee

# Why

This is just a merge conflict of https://github.com/expo/expo/pull/4878.

# How

All the code is taken from the original PR. I just fixed the conflicts and tested it.

# Test Plan

Recorded 2 videos (10 seconds each - same scene):

**1. Input: No videoBitrate set**

![image](https://user-images.githubusercontent.com/778391/107809102-94625300-6d38-11eb-95ef-8637ff3c52c7.png)

**2. Input: videoBitrate set to 1000**

![image](https://user-images.githubusercontent.com/778391/107809192-ae9c3100-6d38-11eb-93e6-81675c927d26.png)

**Code used to test:**
```
this.camera.recordAsync({
    quality: Camera.Constants.VideoQuality['720p'],
    videoBitrate: 1000
});
```
I had to set `useCamera2Api={true}` on `<Camera />` otherwise this flag has no effect.

2021-02-15 09:17 UTC, lukmccall requested changes
Good job 💯

Please add information about `useCamera2Api={true}` to the documentation. Someone can try to use the `videoBitrate` with the first API and will be confused why it doesn't work.

2021-02-15 22:03 UTC, makzee commented
Thanks @lukmccall, I have added the information in the docs.

2021-02-16 10:15 UTC, lukmccall approved these changes

2021-02-16 10:15 UTC, lukmccall commented on CHANGELOG.md
> +  - Added `videoBitrate` option for camera on Android by [@xHeinrich] ([#4878])
```suggestion
  - Added `videoBitrate` option for camera on Android. ([#4878](https://github.com/expo/expo/pull/4878) by [@xHeinrich](https://github.com/xHeinrich))
```

2021-02-16 13:23 UTC, merged