[expo-updates][android] only require signatures with expo go
expo/expo pull request #12027
Opened 2021-02-24 14:45 UTC by jkhales

# Why

Only require signatures with expo go.

# How

Add an `isExpoGo` field that is default false. Set it true when calling from Expo Go.

# Test Plan

Logged the response body of an update in Expo Go and a bare app to make sure they returned, respectively, signed and unsigned responses.

2021-02-25 03:50 UTC, esamelson requested changes
This looks good, and let's add one other change in here -- after downloading the manifest, if `expectsSignedManifest` is false, we should just proceed with the manifest unmodified rather than mutating it to add `isVerified: false`.

(A bit of explanation -- this `isVerified` key we add is a bit of a hack for Expo Go. Ideally we'd just reject unsigned manifests if we're expecting a signature, but there are a few cases in Expo Go where we do actually want to use the unsigned manifest anyway. It isn't ideal that this has bled into expo-updates, though 😕 Maybe sometime in the future we can take another pass at that whole scenario, but no need to right now.)

2021-02-25 03:50 UTC, esamelson commented on packages/expo-updates/android/src/main/java/expo/modules/updates/UpdatesConfiguration.java
> +    Boolean isExpoGo = readValueCheckingType(map, "isExpoGo", Boolean.class);
Let's go with `"expectsSignedManifest"` for the name of this property instead -- that more clearly communicates its effect, and will be clearer if we want to set it to true in cases other than Expo Go in the future (e.g. the dev client).

2021-02-25 03:50 UTC, esamelson commented on packages/expo-updates/android/src/main/java/expo/modules/updates/UpdatesConfiguration.java
> +    if ( isExpoGo != null){
```suggestion
    if (isExpoGo != null) {
```

2021-02-25 13:58 UTC, jkhales commented
> This looks good, and let's add one other change in here -- after downloading the manifest, if `expectsSignedManifest` is false, we should just proceed with the manifest unmodified rather than mutating it to add `isVerified: false`.

Is this where you were thinking?

https://github.com/expo/expo/pull/12027/files#diff-2e2ccf9c4e723912462ae8b4f17dd87433be7cb5ede026d320edabad1504b797R169

2021-02-26 20:00 UTC, esamelson approved these changes
Yes! lgtm 😎

2021-02-26 20:11 UTC, merged