[docs] add react vs react native page
expo/expo pull request #12025
Opened 2021-02-24 00:01 UTC by cruzach

# Why

popular SO question, let's put it in our docs!

for now, this is just going to be discoverable via search

2021-02-24 05:17 UTC, brentvatne requested changes
i think this is a good topic to cover, but let's talk on slack about what we want to communicate in this. it'd be good to outline what the specific questions users have about this are, for example.

some initial thoughts:
- "i always find the "x vs y" positioning in software to be off-putting but there may be some utility to using it if that's the language that people approach this with. i'd want to make it clear in the doc that this kind of framing doesn't make sense, though.
- react-dom and react-native both use react, so we should probably call this out here. i think the in "react vs react-native" people are often thinking "react-dom vs react-native" but maybe don't know that terminology, this is a good chance for education
- i like the easy-going tone of writing but i think it feels a bit salesy in some places. we could turn that a bit down and focus more on communicating understanding

2021-02-24 20:15 UTC, caelan-io commented on docs/pages/faq/react-vs-react-native.md
> +On the surface, there's very little difference between React and React Native- that's one of the great parts about React Native (RN for short). If you're a web developer and have used React, good new
I would change: "Let's go over some of their similarities, differences, and where each of them shines brightest."

To this on its own line so it's super clear what the reader gets from the content:
Below we cover their similarities, differences, and in what situations it makes sense to use React vs. React Native.

2021-02-24 20:17 UTC, caelan-io commented on docs/pages/faq/react-vs-react-native.md
> +## Should I use React or React Native?
I like this a lot because I imagine people are thinking this when they type in "react vs. react native", especially the people who would be ready to install Expo right after reading this. 

Let's chat about how we can visualize this point, via table, graphic, etc. 

This could potentially command its own docs page with more elaboration. I think the amount of copy here is perfect for this page, though.

2023-04-19 14:52 UTC, amandeepmittal commented
@brentvatne, I think we've come quite a bit far with the original objective of adding this guide. Do you think its still relevant?

2023-05-08 09:13 UTC, closed without merging