Update to latest AdMob iOS Dependency
expo/expo pull request #12033
Opened 2021-02-25 04:35 UTC by SethuSenthil

# Why

Issue #11934 - support AdMob on iOS 14.5 

# How
Changed the Cocopod Admob dependency version to the latest version as seen on Google's developers site

# Test Plan

Add all currently supported Admob components as seen on the documentation  
https://docs.expo.io/versions/latest/sdk/admob/

2021-02-26 01:53 UTC, brentvatne commented
@cruzach did some investigation into this and it looks like we probably only want to update to the latest minor version that supports SKAdNetwork, so the latest 7.x version, in order to defer dealing with [breaking changes](https://developers.google.com/admob/ios/migration) until we have more time to do so

2021-02-26 05:52 UTC, yuta-hidaka requested changes

2021-02-26 05:52 UTC, yuta-hidaka commented on packages/expo-ads-admob/ios/EXAdsAdMob.podspec
> +  s.dependency 'Google-Mobile-Ads-SDK', "8.1.0"
```suggestion
  s.dependency 'Google-Mobile-Ads-SDK', "7.69.0"
```

This version is latest miner version of 7.X . 

Ref. https://developers.google.com/admob/ios/rel-notes

2021-03-08 19:26 UTC, brentvatne commented
more changes were required to make this actually work, handled in https://github.com/expo/expo/pull/12125

thanks for the pr nonetheless! :)

2021-03-08 19:26 UTC, closed without merging