[mail-composer] add doc comments in source
expo/expo pull request #12278
Opened 2021-03-22 12:46 UTC by Simek

# Why

To utilize the auto generation feature for API section the package source code must contain the relevant documentation.

# How

This small PR moves the current documentation of `MailComposer` API - https://docs.expo.io/versions/latest/sdk/mail-composer/ - (with minor tweaks) to the package source code.

# Test Plan

N/A

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.io and README.md).
- [ ] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

2021-03-24 11:19 UTC, bbarthec approved these changes

2021-03-29 20:44 UTC, brentvatne commented on packages/expo-mail-composer/src/MailComposer.types.ts
> +   * Subject of the mail.
above we say "e-mail addresses" and here we say "mail" - maybe it should be "e-mail" here for consistency? same as for the `body` field

2021-03-29 20:45 UTC, brentvatne requested changes

2021-03-29 20:45 UTC, brentvatne commented on packages/expo-mail-composer/src/MailComposer.types.ts
> +   * An array of app's internal file uris to attach.
```suggestion
   * An array of app's internal file URIs to attach.
```

2021-03-31 21:17 UTC, brentvatne approved these changes

2021-03-31 23:53 UTC, merged