[home] Change Profile to be a list of accounts and organizations
expo/expo pull request #12344
Opened 2021-03-29 20:34 UTC by wschurman

# Why

A follow-up to https://github.com/expo/expo/pull/12342 that moves the Profile page back to a user query, but just displays the user's accounts and organizations in a standard list view and detail view like UI. This brings the home app up to date with our changes to UX on the website and in www.

# How

1. Add profile screen that queries information about the user and their accounts/organizations and displays it in a list view. Tapping an account list view item will push an account screen. This screen is now responsible for displaying the logged-out UX and showing networking issues.
2. Remove user-specific information from the account screens since they're only shown as detail views (no longer a top-level tab screen). Now they are just containers for projects and snacks.

# Test Plan

Same as https://github.com/expo/expo/pull/12342.

<img width="416" alt="Screen Shot 2021-03-29 at 12 59 28 PM" src="https://user-images.githubusercontent.com/189568/112896545-63916f80-9093-11eb-81bf-1f88cc12e30c.png">
<img width="414" alt="Screen Shot 2021-03-29 at 1 09 52 PM" src="https://user-images.githubusercontent.com/189568/112896557-67bd8d00-9093-11eb-9012-ef29453da8e0.png">

2021-03-31 20:39 UTC, cruzach reviewed
In the `Profile` screen, it might be nice to keep the "All Projects" list that shows all the projects you have permission to view (and same as before it shows the 3 most recently published as a preview, then you can click to view all). that way:
- there's still one place you can view with all your projects, and 
- we aren't adding an additional click to find a recently published project

2021-03-31 20:41 UTC, wschurman commented
> In the `Profile` screen, it might be nice to keep the "All Projects" list that shows all the projects you have permission to view (and same as before it shows the 3 most recently published as a preview, then you can click to view all). that way:
> 
> * there's still one place you can view with all your projects, and
> * we aren't adding an additional click to find a recently published project

That's a good idea. I'll see what I can do.

2021-03-31 23:19 UTC, brentvatne commented
I agree with @cruzach's feedback about keeping an "All Projects" list around  - otherwise this looks really good.

2021-04-02 20:44 UTC, cruzach commented
thanks for adding back recent projects & see all projects 🙏 i imaged that listed first, then the accounts/orgs listed, but I actually think I like it better in the current order!


nitpicky, but we maybe want to just rely labeling the back botton `Back` here on the `account` > `see all projects` screen, rather than the account or organization name (longer names can make it look a little wonky:
<img width="431" alt="Screen Shot 2021-04-02 at 4 41 10 PM" src="https://user-images.githubusercontent.com/35579283/113452569-3f56cb00-93d2-11eb-94ad-f1e4fe939ca1.png">

2021-04-05 16:47 UTC, wschurman commented
![26203431](https://user-images.githubusercontent.com/189568/113599749-e6667d00-95f3-11eb-917c-fbf2e55285f5.jpg)

2021-04-05 18:17 UTC, brentvatne requested changes
### flicker with signed out state on first load of profile screen

https://user-images.githubusercontent.com/90494/113608578-a0afb180-95ff-11eb-800e-f803f22639a5.mov

### a few changes to details

![notes](https://user-images.githubusercontent.com/90494/113608665-b7ee9f00-95ff-11eb-8d53-a8365edfa86f.png)

- let's change the snack link to https://docs.expo.io/workflow/snack -- it doesn't currently exist but @byCedric is working on a doc for it

2021-04-05 18:24 UTC, brentvatne commented
<img width="518" alt="Screen Shot 2021-04-05 at 11 23 01 AM" src="https://user-images.githubusercontent.com/90494/113609908-4adc0900-9601-11eb-93f6-fcdc4917b063.png">

what do you think about hiding the "Accounts & Organizations" section when the user is not part of any other teams/orgs?

2021-04-05 18:35 UTC, wschurman commented
> what do you think about hiding the "Accounts & Organizations" section when the user is not part of any other teams/orgs?

Yeah, that makes sense, especially now that we're adding back recent project and snacks to the profile.

2021-04-05 19:08 UTC, brentvatne commented
this commit adds the snack docs page referenced above: https://github.com/expo/expo/commit/4e1107e246acb48ab410ea188332cc9990554390

2021-04-08 05:52 UTC, brentvatne approved these changes

2021-04-08 15:55 UTC, merged