[apps] update Readme, improve readability
expo/expo pull request #12554
Opened 2021-04-15 10:01 UTC by Simek

# Why

To improve readability and overall clarity.

# How

Alphabetic order of apps, formatting and links to the packages.

# Test Plan

N/A

2021-04-15 13:17 UTC, bbarthec requested changes
Nice idea, but let's go with relative links instead of absolute ones 😉

2021-04-15 13:17 UTC, bbarthec commented on apps/README.md
> +  End-to-end tests that run on Expo.
I would rather suggest using [relative links](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-readmes#relative-links-and-image-paths-in-readme-files)
```suggestion
- #### [bare-expo](apps/bare-expo)
  A project that uses the bare workflow and can load the Test Suite and Native Component List's JS.
- #### [jest-expo Mock Generator](apps/jest-expo-mock-generator)
  An app that uses reflection to generate Jest mocks for native modules. Eventually we can remove the need for this once we have a JSON schema for each module definition (Turbomodules) and generate the Jest mock from the JSON schema.
- #### [Home](home) (not in this directory)
  The UI for the development client.
- #### [Native Component List](apps/native-component-list)
  A showcase of the components and APIs in the default Expo preset.
- #### [Sandbox](apps/sandbox)
  A project excluded from Git where you can try out things locally.
- #### [Test Suite](apps/test-suite)
  End-to-end tests that run on Expo.
```

2021-04-15 14:39 UTC, Simek commented
> Nice idea, but let's go with relative links instead of absolute ones 😉

Thank you for catching this up, I have forgot about relative links.

2021-04-16 05:23 UTC, bbarthec approved these changes

2021-04-16 05:23 UTC, merged