[docs] add help post about showing toasts in RN
expo/expo pull request #12577
Opened 2021-04-16 17:04 UTC by FiberJW

# Why

React Native devs often want to use Toasts in their apps, so this short doc will help guide them in the right direction.

# How

- added docs page under ui-programming
- covers RN ToastAndroid
- covers https://github.com/magicismight/react-native-root-toast
- ImageOptim'ed the screenshot

# Test Plan

`yarn dev` in docs and visit http://localhost:3002/ui-programming/react-native-toast/ to read the page.

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.io and README.md).
- [ ] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

2021-04-19 23:01 UTC, tcdavis commented on docs/pages/ui-programming/react-native-toast.md
> +[`react-native-root-toast`](https://github.com/magicismight/react-native-root-toast) is one such
Would be nice to talk to why you are recommending this module over the other community solutions

2021-04-19 23:13 UTC, tcdavis commented on docs/pages/ui-programming/react-native-toast.md
> +This library also has a lot of options for customizing appearance and behavior, so check out [their
```suggestion
This library has many options for [customizing the appearance and behavior](https://github.com/crazycodeboy/react-native-easy-toast#api) of your toast.
```

2021-04-19 23:18 UTC, tcdavis commented on docs/pages/ui-programming/react-native-toast.md
> +According to the [Android Developers
Something about why you might use a toast: Toasts are the standard technique to notify your users about something without interrupting what they are doing.

2021-04-19 23:19 UTC, tcdavis commented on docs/pages/ui-programming/react-native-toast.md
> +## `ToastAndroid`
Android-only: `ToastAndroid`

2021-04-19 23:20 UTC, tcdavis commented on docs/pages/ui-programming/react-native-toast.md
> +## `react-native-root-toast`
Cross-platform: `react-native-root-toast`

2021-04-19 23:21 UTC, tcdavis requested changes
A couple changes, but looking good

2021-04-26 01:15 UTC, ide requested changes

2021-04-26 01:15 UTC, ide commented on docs/pages/ui-programming/react-native-toast.md
> +title: How to display a toast in React Native
```suggestion
title: How to display a popup toast
```

something like this fits in better with the docs and also hints at what a toast is. also would name this file just toast.md.

2021-04-26 01:15 UTC, ide commented on docs/pages/ui-programming/react-native-toast.md
> +To present a toast, we recommend two solutions: an API from React Native itself and a library
```suggestion
To present a toast, we recommend two solutions: an API from the `react-native` package and a library
```
this wording communicates better that it's not really a core component and more an arbitrary component

2021-04-26 01:15 UTC, ide commented on docs/pages/ui-programming/react-native-toast.md
> +To use `react-native-root-toast`, you have to [install the module](https://github.com/magicismight/react-native-root-toast) from NPM with `npm install react-native-root-toast`.
npm is lowercase
```suggestion
To use `react-native-root-toast`, you have to [install the module](https://github.com/magicismight/react-native-root-toast) from npm with `npm install react-native-root-toast`.
```

2021-04-28 19:10 UTC, ide approved these changes

2021-04-28 19:10 UTC, ide commented on docs/constants/navigation.js
> +      'How to display a toast in React Native',
```suggestion
      'How to display a popup toast',
```

2021-04-28 19:42 UTC, merged