[camera][ios] add video codec option to expo camera
expo/expo pull request #12772
Opened 2021-04-29 04:09 UTC by ajsmth

# Why

# How

# Test Plan

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.io and README.md).
- [ ] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

2021-04-30 13:19 UTC, bbarthec requested changes
Pay attention to the code style/indentation. I know this iOS code style of ours is questionable a lot, but let's stick to it 🙏 
Left some other idea/suggestions in the code.

2021-04-30 13:19 UTC, bbarthec commented on packages/expo-camera/ios/EXCamera/EXCamera.m
> +
```suggestion
    if (options[@"codec"]) {
      AVVideoCodecType videoCodecType = [EXCameraUtils videoCodecForType: [options[@"codec"] integerValue]];

      if ([self.movieFileOutput.availableVideoCodecTypes containsObject:videoCodecType]) {
        [self.movieFileOutput setOutputSettings: @{AVVideoCodecKey: videoCodecType} forConnection: connection];    
        self.videoCodecType = videoCodecType;
      } else {
        NSString *videoCodecErrorMessage = [NSString stringWithFormat: @"Video Codec '%@' is not supported on this device", videoCodecType];
        reject(@"E_RECORDING_FAILED", videoCodecErrorMessage, nil);

        [self cleanupMovieFileCapture];
        _videoRecordedResolve = nil;
        _videoRecordedReject = nil;

        return;
      }
    }

```
We don't want some extra `warns` that pollutes the user-space. Rejecting with proper, descriptive error message is sufficient 😉

2021-04-30 13:19 UTC, bbarthec commented on packages/expo-camera/ios/EXCamera/EXCamera.m
> +      _videoRecordedResolve(@{ @"uri": outputFileURL.absoluteString, @"codec": videoCodec });
```suggestion
    AVVideoCodecType videoCodec = self.videoCodecType;       
    if (!videoCodec) {
      videoCodec = [self.movieFileOutput.availableVideoCodecTypes firstObject];
    }  
    _videoRecordedResolve(@{ @"uri": outputFileURL.absoluteString, @"codec": videoCodec });
```

2021-04-30 13:19 UTC, bbarthec commented on packages/expo-camera/ios/EXCamera/Utilities/EXCameraUtils.h
> ++(AVVideoCodecType) videoCodecForType: (EXCameraVideoCodec)videoCodecType;
```suggestion
+ (AVVideoCodecType)videoCodecForType:(EXCameraVideoCodec)videoCodecType;
```

2021-04-30 13:19 UTC, bbarthec commented on packages/expo-camera/ios/EXCamera/Utilities/EXCameraUtils.m
> +
```suggestion
+ (AVVideoCodecType)videoCodecForType:(EXCameraVideoCodec)videoCodecType
{
  switch (videoCodecType) {
    case EXCameraVideoCodecH264:
      return AVVideoCodecTypeH264;
    case EXCameraVideoCodecHEVC:
      return AVVideoCodecTypeHEVC;
    case EXCameraVideoCodecJPEG:
      return AVVideoCodecTypeJPEG;
    case EXCameraVideoCodecAppleProRes422:
      return AVVideoCodecTypeAppleProRes422;
    case EXCameraVideoCodecAppleProRes4444:
      return AVVideoCodecTypeAppleProRes4444;
    default:
      return AVVideoCodecTypeHEVC;
  }
}

```

2021-04-30 13:19 UTC, bbarthec commented on packages/expo-camera/ios/EXCamera/EXCameraManager.m
> +
```suggestion
```

2021-04-30 13:19 UTC, bbarthec commented on packages/expo-camera/ios/EXCamera/EXCameraManager.m
> +
```suggestion
UM_EXPORT_METHOD_AS(getAvailableVideoCodecsAsync,
                    resolve:(UMPromiseResolveBlock)resolve
                    rejecter:(UMPromiseRejectBlock)reject)
{
  AVCaptureSession *session = [AVCaptureSession new];   
  [session beginConfiguration];

  NSError *error = nil;
  AVCaptureDevice *captureDevice = [EXCameraUtils deviceWithMediaType:AVMediaTypeVideo preferringPosition: AVCaptureDevicePositionFront];
  AVCaptureDeviceInput *captureDeviceInput = [AVCaptureDeviceInput deviceInputWithDevice:captureDevice error:&error];   
 
  if ([session canAddInput:captureDeviceInput]) {
     [session addInput:captureDeviceInput];
  }

  [session commitConfiguration];

  AVCaptureMovieFileOutput *movieFileOutput = [AVCaptureMovieFileOutput new];
  if ([session canAddOutput:movieFileOutput]) {
    [session addOutput:movieFileOutput];
  }
  
  resolve([movieFileOutput availableVideoCodecTypes]);
}

```

I'm curious about creating the whole AVCaptureSession here 🤔 
Aren't the lines
```
AVCaptureMovieFileOutput *movieFileOutput = [AVCaptureMovieFileOutput new];
resolve([movieFileOutput availableVideoCodecTypes]);
```
covering the whole functionality? 🤔 
I'm looking at the Apple Docs: https://developer.apple.com/documentation/avfoundation/avvideocodectype and https://developer.apple.com/documentation/avfoundation/avcapturemoviefileoutput/1648381-availablevideocodectypes
and wondering if these are not sufficient here? 
Or maybe I'm missing the point and we actually need to create the whole camera session to get the actual data 🤔

2021-04-30 13:19 UTC, bbarthec commented on packages/expo-camera/src/Camera.tsx
> +  async recordAsync(options?: CameraRecordingOptions): Promise<{ uri: string; codec: VideoCodec }> {
```suggestion
  async recordAsync(options?: CameraRecordingOptions): Promise<{ uri: string }> {
```
I don't think we need to return this value here 🤔 
1. Use provide it explicitly, so it's known already
2. Default one is described in the docs? 🤔

2021-05-03 17:39 UTC, ajsmth commented
@bbarthec it looks like the CI deleted a bunch of your comments, sorry about that :\

The two I wanted to talk about were the `getAvailableVideoCodecsAsync()` - I was hoping the implementation would have been simple like docs suggest but after trial and error I had to create a session and add input/output to get that method to return the available codecs

The second was returning the codec from the `recordAsync()` - returning an optional codec string makes this method much easier to test, also the values from the enum are not exactly matching to what's returned from the device

2021-05-04 11:48 UTC, bbarthec reviewed
Regarding these deleted comments - what a surprise we have here 😱 (I know the fix is coming though 😅)
Re `getAvailableVideoCodesAsync()` - Apple 🔔  shame 🔔  shame ... 🚶‍♂️ 
Re `recordAsync()` - TBH, I'm not convinced 🤔 Testing apart, but what does this sentence mean specifically?
> values from the enum are not exactly matching to what's returned from the device

Are we having different values on input (`method parameter`) and output (`optional codec string`)? 🤔


So, let me ask more specifically: does this optional codec return value bring any new information to the user? And by `any new information` I mean something that is not already known (either from docs or input values/params? 🤔)
If the answer is `yes` I can live with that optional codec string, other way I'm rather against the idea of introducing this, because why don't we provide similar return info regarding any other video parameter/meta-parameter? (`bitrate`, `length`, `dimensions`, etc.) 🤔

2021-05-04 11:48 UTC, bbarthec commented on packages/expo-camera/CHANGELOG.md
> +- On iOS added new `codec` parameter in `recordVideo()` method and new method `getAvailableVideoCodecsAsync()` that queries the device for available video codecs. ([#12772](https://github.com/expo/ex
```suggestion
- On iOS added new `codec` parameter in `recordVideo()` method and new method `getAvailableVideoCodecsAsync()` that queries the device for available video codecs. ([#12772](https://github.com/expo/expo/pull/12772)) by [@ajsmth](https://github.com/ajsmth))

```

2021-05-04 19:18 UTC, ajsmth commented
> Re `getAvailableVideoCodesAsync()` - Apple 🔔 shame 🔔 shame ... 🚶‍♂️

Hahah

> Re `recordAsync()` - TBH, I'm not convinced 🤔 Testing apart, but what does this sentence mean specifically?
> 
> > values from the enum are not exactly matching to what's returned from the device
> 
> Are we having different values on input (`method parameter`) and output (`optional codec string`)? 🤔
> 
> So, let me ask more specifically: does this optional codec return value bring any new information to the user? And by `any new information` I mean something that is not already known (either from docs or input values/params? 🤔)
> If the answer is `yes` I can live with that optional codec string, other way I'm rather against the idea of introducing this, because why don't we provide similar return info regarding any other video parameter/meta-parameter? (`bitrate`, `length`, `dimensions`, etc.) 🤔

What I was getting at it that we are passing in an enum and that is being converted to a string, however that string isn't any more valuable to the user than the enum would be, so you make a good point. I'm not sure the best way to test that the codec is being applied - any thoughts on this?

2021-05-05 07:09 UTC, bbarthec commented
@ajsmth, 
1. > I'm not sure the best way to test that the codec is being applied - any thoughts on this?

Good question 🤔 I can only guess that we need to check meta-params of the recorded video, but I have no idea how we can achieve this 😞 
Ultimately, we can skip writing tests for this specific feature hoping it works as expected (or we can describe how to check it manually) 😅 

2. > do you think it's worth it to wrap some of these options in an async block regardless

If it doesn't break anything and possibly it improves/fixes something then refactoring for the win 🎉

2021-05-05 19:31 UTC, ajsmth commented
@bbarthec 

> 1. > I'm not sure the best way to test that the codec is being applied - any thoughts on this?
> 
> Good question 🤔 I can only guess that we need to check meta-params of the recorded video, but I have no idea how we can achieve this 😞
> Ultimately, we can skip writing tests for this specific feature hoping it works as expected (or we can describe how to check it manually) 😅

I think the simplest way to do this is to return the codec used from the native side and restrict it in the JS implementation. Another option would be to provide a metadata argument similar to `exif` on the photo side wherein we could return the codec used and other data if needed

2021-05-05 23:26 UTC, brentvatne requested changes

2021-05-05 23:26 UTC, brentvatne commented on packages/expo-camera/ios/EXCamera/EXCamera.m
> +    [self setVideoOptions:options forConnection:connection onReject: reject];
```suggestion
    [self setVideoOptions:options forConnection:connection onReject:reject];
```

2021-05-05 23:26 UTC, brentvatne commented on packages/expo-camera/ios/EXCamera/EXCamera.m
> +  dispatch_async(_sessionQueue, ^{
add comment indicating why this is invoked in async block

2021-05-05 23:26 UTC, brentvatne commented on packages/expo-camera/ios/EXCamera/EXCameraManager.m
> +                    resolve:(UMPromiseResolveBlock)resolve
```suggestion
                    resolver:(UMPromiseResolveBlock)resolve
```

convention is to use `resolver` and `rejecter`

2021-05-05 23:26 UTC, brentvatne commented on packages/expo-camera/src/Camera.types.ts
> +export enum VideoCodec {
let's add a docblock here about video codec to save @Simek the hassle of copying over from docs when he gets to this module for auto gen docs

2021-05-05 23:26 UTC, brentvatne commented on scripts/git-hooks/post-checkout
> -./scripts/check-cocoapods-lockfiles.sh
revert

2021-05-05 23:26 UTC, brentvatne commented on scripts/git-hooks/post-merge
> -./scripts/check-cocoapods-lockfiles.sh
revert

2021-05-05 23:26 UTC, brentvatne commented on packages/jest-expo/src/preset/expoModules.js
> +          { key: 0, argumentsCount: 0, name: 'flushAsync' },
revert unrelated mocks changes, just update ExpoCameraManager for now

2021-05-06 06:25 UTC, bbarthec approved these changes
Cleanup @brentvatne's suggestions and we're ready to merge 👍

2021-05-07 11:20 UTC, bbarthec approved these changes

2021-05-07 22:52 UTC, brentvatne approved these changes

2021-05-07 23:06 UTC, merged

2021-05-19 20:19 UTC, ajcpwnz commented
Is there a way to use this locally?