@dsokal/convert document picker to kotlin
expo/expo pull request #12852
Opened 2021-05-07 11:53 UTC by dsokal

# Why

This is part of the effort to convert our Android codebase to Kotlin. This PR converts `expo-document-picker` to Kotlin.

# How

- I used the auto-converter from Android Studio (`Code > Covert Java File to Kotlin File`).
- Then, I went over the code and refactored it here and there. 
- I handled more errors: 
  - When `getDocumentAsync` receives invalid `options`.
  - When the module fails to read the selected document.
  - When the module fails to copy the document to the cache directory.

# Test Plan

I tested the module with NCL (in `bare-expo`). I haven't seen any regression.

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.io and README.md).
- [x] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

2021-05-07 13:15 UTC, lukmccall requested changes
LGTM ✅
However, I've left some suggestions ;) 

Also, I think it will be better in `onActivityResult` to get rid of the nullable promise type earlier. After first if, you can create a local variable with not nullable type:
```kt
val promise = mPromise!!
mPromise = null
```
In that way, you don't have to unwrap a promise whenever you want to use it.

2021-05-07 13:15 UTC, lukmccall commented on packages/expo-document-picker/android/src/main/java/expo/modules/documentpicker/DocumentPickerModule.kt
> +            originalDocumentDetails.copy(uri=copyPath)
```suggestion
            originalDocumentDetails.copy(uri = copyPath)
```

2021-05-07 13:15 UTC, lukmccall commented on packages/expo-document-picker/android/src/main/java/expo/modules/documentpicker/DocumentPickerModule.kt
> +    }
```suggestion
	try {
	  context.contentResolver.openInputStream(documentUri).use { inputStream -> 
	    FileOutputStream(File(outputFilePath)).use { outputStream -> 
	  	  IOUtils.copy(inputStream, outputStream)
	  	}
	  }
	} catch (e: IOException) {
      e.printStackTrace()
      return null
	}
```

2021-05-07 14:21 UTC, lukmccall approved these changes
🚀🚀🚀

2021-05-10 10:05 UTC, bbarthec approved these changes
Solid wo, just this one inverted condition 😉

2021-05-10 14:29 UTC, merged