To include missing UMPermissionsInterface dependency inside UMReactNativeAdapter.podspec
expo/expo pull request #12862
Opened 2021-05-08 02:28 UTC by budiTjendra

# Why

Fixes: 

```
In file included from .../node_modules/@unimodules/react-native-adapter/ios/UMReactNativeAdapter/Services/Permissions/EXReactNativeUserNotificationCenterProxy.m:5:
.../node_modules/@unimodules/react-native-adapter/ios/UMReactNativeAdapter/Services/Permissions/EXReactNativeUserNotificationCenterProxy.h:7:9: fatal error: 'UMPermissionsInterface/UMUserNotificationCenterProxyInterface.h' file not found
#import <UMPermissionsInterface/UMUserNotificationCenterProxyInterface.h>
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

# How

Dependency UMPermissionsInterface is missing declaration inside UMReactNativeAdapter.podspec. And this will throw a compilation error when using with  use_framework!

# Test Plan

Tested locally. 

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.io and README.md).
- [ ] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

2021-05-08 09:08 UTC, tsapeta requested changes
Thanks and congrats on your first contribution! 👏 Just two small suggestions below 😉

2021-05-08 12:58 UTC, budiTjendra commented on packages/@unimodules/react-native-adapter/package.json
> +  "version": "6.2.3",
done.

2021-05-08 12:58 UTC, budiTjendra commented on packages/@unimodules/react-native-adapter/CHANGELOG.md
> +
done

2021-05-08 13:00 UTC, budiTjendra commented
> Thanks and congrats on your first contribution! 👏 Just two small suggestions below 😉

You are welcome @tsapeta

2021-05-09 18:46 UTC, tsapeta approved these changes

2021-05-09 18:46 UTC, merged