[apps] Add minimal app with dev-client
expo/expo pull request #12890
Opened 2021-05-11 14:32 UTC by lukmccall

# Why

Added a bare-bone app that includes dev-client. 

# How

- run `expo init` 
- added dev-client plugin
- run `expo eject` 
- removed all unused dependencies (expo-updates was removed too - will be added in the future)
- used a new liking module 

# Test Plan

- Android & iOS ✅

2021-05-11 14:47 UTC, fson commented on apps/dev-client/android/build.gradle
> +        buildToolsVersion = "29.0.3"
In the template this had to be updated to `buildToolsVersion = "30.0.3"` for the Android build to work – does it need to be updated here as well?  Or is that only when using the upstream React Native version?

2021-05-11 14:47 UTC, fson commented on apps/dev-client/ios/Podfile
> +  pod 'expo-dev-menu-interface', path: '../../../packages/expo-dev-menu-interface', :configurations => :debug
IIRC this pod needed to be included in the release builds too?

2021-05-11 14:47 UTC, fson commented on apps/dev-client/package.json
> +    "ios": "react-native run-ios",
```suggestion
    "android": "expo run:android",
    "ios": "expo run:ios",
```
Maybe?

2021-05-11 22:05 UTC, fson approved these changes
🚀

2021-05-11 22:58 UTC, esamelson requested changes
Could we rename this to something else (maybe `bare-sandbox` since it's sort of an analog of the existing `sandbox` app)? In the past there has been pushback to adding more apps to this repo's workspace, to avoid cluttering it with mostly unused apps that must be kept up to date (like we used to have in universe). IMO there is justification for adding this app in part because it's useful when developing many different modules, not just the dev client, so it would be great to have the name communicate as such! 🙂 

And to add to the test plan, could you confirm/verify (maybe by doing a dry run) that `et publish` updates dependencies in this app automatically, like it does with NCL/bare-expo/etc?

2021-05-21 11:11 UTC, lukmccall commented
> And to add to the test plan, could you confirm/verify (maybe by doing a dry run) that `et publish` updates dependencies in this app automatically, like it does with NCL/bare-expo/etc?

Project dependencies will be updated by `et publish`. This script looks at the output of `yarn workspaces info`. If a project is on that list, it will update dependencies. All projects from the apps folder are included in our workspace.

2021-05-25 00:34 UTC, esamelson approved these changes

2021-05-25 12:39 UTC, merged