Added detailed code on how to implement aws s3 and firebase with image picker.
expo/expo pull request #12924
Opened 2021-05-13 21:43 UTC by EvanErickson

…o added detailed instructions on firebase as well.

# Why

# How

# Test Plan

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.io and README.md).
- [ ] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

2021-05-13 21:52 UTC, brentvatne requested changes
i think we should not have this information on this page but instead link out to the example in [expo/examples](http://github.com/expo/examples). we should also link out to the other examples we have in that repo for integrating with a node backend and with firebase :)

for the additional context in this example (like about `amplify configure`) we should add it to the readme in the example repo

2021-05-14 00:17 UTC, EvanErickson commented
Sounds great! I will make the changes soon and re push.

2021-05-14 21:28 UTC, EvanErickson commented
I added examples

2021-05-20 00:10 UTC, brentvatne approved these changes

2021-05-20 00:10 UTC, brentvatne commented on docs/pages/versions/unversioned/sdk/imagepicker.md
> +Please refer to our example [here](https://github.com/expo/examples/tree/master/with-aws-storage-upload). Make sure you follow Amplify's docs to set your project up correctly.
```suggestion
Please refer to the [with-aws-storage-upload example](https://github.com/expo/examples/tree/master/with-aws-storage-upload). Follow [Amplify docs](https://docs.amplify.aws/) to set your project up correctly.
```

2021-05-20 00:10 UTC, brentvatne commented on docs/pages/versions/unversioned/sdk/imagepicker.md
> +Please refer to our example [here](https://github.com/expo/examples/tree/master/with-firebase-storage-upload). Make sure you follow Firebases' docs to set your project up correctly.
```suggestion
Please refer to the [with-firebase-storage-upload example](https://github.com/expo/examples/tree/master/with-firebase-storage-upload). Make sure you follow the ["Using Firebase"](/guides/guides/using-firebase.md) docs to set your project up correctly.
```

2021-05-20 00:11 UTC, merged