[docs] remove top level sections from sidebar in /guides
expo/expo pull request #13005
Opened 2021-05-21 18:09 UTC by cruzach

# Why

pretty much all of these sections have content for bare and managed users, not one or the other. Plus in the current state it’s pretty hard to get a handle on the sidebar since it’s just so much content

# How

Removed top level "managed workflow" and "bare workflow" sections
this shows the new order of sections:

<img width="633" alt="Screen Shot 2021-05-21 at 2 06 52 PM" src="https://user-images.githubusercontent.com/35579283/119180075-ccff8000-ba3d-11eb-83d3-3580d33fdfc5.png">

The 'Deprecated', 'Regulatory Compliance', and 'Assorted Guides' sections will be unexpanded by default (first two are very niche docs, the last is basically just our catch-all section)

# Test Plan

`yarn dev`

2021-05-21 21:32 UTC, brentvatne approved these changes
one thing to check up on -- i'm not sure if anywhere in the docs we refer people to the "managed workflow" section of the guides. we should get rid of that text if so. otherwise lgtm

2021-05-21 21:33 UTC, brentvatne commented
actually.. i'm not so sure about assorted guides being so low in the sidebar. there is some pretty important basic stuff there, like assets, fonts, icons, routing

2021-05-21 21:34 UTC, brentvatne requested changes
revert reordering of sections :)

2021-05-29 00:05 UTC, brentvatne commented on docs/constants/navigation.js
> -      'Assets',
intentional?

2021-05-29 00:05 UTC, brentvatne commented on docs/constants/navigation.js
> -      'Routing & Navigation',
intentional?

2021-06-01 17:05 UTC, cruzach commented on docs/constants/navigation.js
> -      'Assets',
nope, good catch!

2021-06-01 17:05 UTC, cruzach commented on docs/constants/navigation.js
> -      'Routing & Navigation',
nope, good catch! x2

2021-07-21 01:09 UTC, brentvatne approved these changes

2021-07-21 01:09 UTC, brentvatne commented on docs/constants/navigation.js
> +const unexpandedSections = ['Deprecated', 'Regulatory Compliance', 'UI Programming'];
```suggestion
const unexpandedSections = ['Deprecated', 'Regulatory Compliance', 'UI Programming', 'Technical Specs'];
```

2021-07-21 01:09 UTC, brentvatne commented on docs/constants/navigation.js
> +//These sections will NOT be expanded by default in the sidebar
```suggestion
// These sections will NOT be expanded by default in the sidebar
```

2021-07-21 01:09 UTC, brentvatne commented on docs/constants/navigation.js
> +const unexpandedSections = ['Deprecated', 'Regulatory Compliance', 'UI Programming'];
the commonly used term for "unexpanded" in this context is "collapsed"

2021-07-22 15:29 UTC, merged