[android][expo-battery] Add method to check if battery optimization is enabled
expo/expo pull request #13138
Opened 2021-06-03 02:37 UTC by FelipeACP

# Why

Many manufacturers restrict background tasks in favor of longer battery life. They make battery optimization default for every app. Therefore, it's useful to know whether it is enabled for your app so that you can handle your logic accordingly. 

Example issues where battery optimization disturbed the normal behavior:  #7485 #10700 #8830

# How

PowerManager has one public method called `isIgnoringBatteryOptimizations`  which "returns whether the given application package name is on the device's power allowlist". So this PR basically adds a wrapper for the given method with the opposite logic.

# Test Plan

Run the test app, on Battery Screen, check if `batteryOptimizationState` matches the battery optimization setting.

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.io and README.md).
- [ ] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

2021-06-06 13:58 UTC, tsapeta requested changes
Except some formatting stuff, it looks good! Thanks for your contribution 🙇‍♂️ 
Would you mind implementing this on iOS too? Looks like we can use [NSProcessInfo.processInfo.lowPowerModeEnabled](https://developer.apple.com/documentation/foundation/nsprocessinfo/1617047-lowpowermodeenabled?language=objc) for this 🤔

2021-06-06 13:58 UTC, tsapeta commented on packages/expo-battery/android/src/main/java/expo/modules/battery/BatteryModule.java
> +    if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
```suggestion
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
```

2021-06-06 13:58 UTC, tsapeta commented on packages/expo-battery/src/Battery.ts
> +    return await ExpoBattery.isBatteryOptimizationEnabledAsync();
```suggestion
  if (!ExpoBattery.isBatteryOptimizationEnabledAsync) {
    return false;
  }
  return await ExpoBattery.isBatteryOptimizationEnabledAsync();
```

2021-06-06 16:48 UTC, FelipeACP commented
> Except some formatting stuff, it looks good! Thanks for your contribution 🙇‍♂️
> Would you mind implementing this on iOS too? Looks like we can use [NSProcessInfo.processInfo.lowPowerModeEnabled](https://developer.apple.com/documentation/foundation/nsprocessinfo/1617047-lowpowermodeenabled?language=objc) for this 🤔
No, I wouldn't mind! The reason I haven't done so already is because AFIK iOS doesn't discriminate against any app battery-wise, that is, the user cannot enable or ignore battery optimizations for specific apps. 
On the other hand, on Android, you have a list of app that ignore battery optimizations, so this method is essential to know beforehand if the OS might restrict your background activities when the device go into doze mode.

2021-06-07 14:43 UTC, tsapeta commented
Ok, gotcha! I misunderstood the intention at the beginning, but it makes sense after your explanation 😉 I think it's fine as if only `false` is returned on other platforms. Thanks!

2021-06-07 14:47 UTC, tsapeta approved these changes

2021-06-07 14:48 UTC, merged