[docs] Add react-native-gradients to ui-programming guides
expo/expo pull request #13247
Opened 2021-06-11 00:17 UTC by animeeples

# Why

Add a Guides page to help answer a common question that new developers have: how to create a gradient in RN.

# How

There were a few ways to do this, but went with the Expo-maintained package.

# Test Plan

Visited http://localhost:3002/ui-programming/react-native-gradients/ and verified that it displayed correctly. Checked links and Snack.

<img width="584" alt="Screen Shot 2021-06-09 at 2 27 38 PM" src="https://user-images.githubusercontent.com/671491/121612499-60115180-ca0f-11eb-8d07-be80848e3de8.png">

2021-06-11 16:16 UTC, tcdavis commented on docs/pages/ui-programming/react-native-gradients.md
> +To add linear gradients to our Expo and React Native apps, we're going to use `expo-linear-gradient`. We're using this package because it is included in the Expo SDK and also because gradients are no
```suggestion
This page will demonstrate how to style components with linear gradients using the `expo-linear-gradient`. This package provides a simple API and comes pre-installed in the Expo Go and will work in any React Native project, however you are choose to build it.
```

2021-06-11 16:17 UTC, tcdavis commented on docs/pages/ui-programming/react-native-gradients.md
> +To add linear gradients to our Expo and React Native apps, we're going to use `expo-linear-gradient`. We're using this package because it is included in the Expo SDK and also because gradients are no
A screenshot of the component you've created so folks can immediately see what is being made and confirm its what they're looking for would be great.

2021-06-11 16:18 UTC, tcdavis commented on docs/pages/ui-programming/react-native-gradients.md
> +<ImageSpotlight style={{ maxWidth: 276 }} containerStyle={{ marginTop: 0 }} src="/static/images/linear-gradient-expo-rn-example.png" alt="Button with Text over Gradient" />
I'd move this towards the top of the page

2021-06-11 16:23 UTC, tcdavis commented on docs/pages/ui-programming/react-native-gradients.md
> +In this example, we are creating a button with text over a gradient.
I think a button needs to have an interaction.  I'd either style the background or make an actual button

2021-06-11 16:23 UTC, tcdavis commented on docs/pages/ui-programming/react-native-gradients.md
> +        // Button Linear Gradient
Not sure this comment makes sense

2021-06-11 16:25 UTC, tcdavis commented on docs/pages/ui-programming/react-native-gradients.md
> +      <LinearGradient
Another example using start and end to change the direction of the gradient would be cool

2021-06-11 16:25 UTC, tcdavis requested changes
Thanks for getting this up!

2024-09-12 08:32 UTC, amandeepmittal commented
Hi @animeeples, thank you for your contribution!

Unfortunately, I'm closing this PR since we have a working example `expo-linear-gradient` API reference: https://docs.expo.dev/versions/latest/sdk/linear-gradient/. This example also provides a Snack link to quickly run or extend it further and covers the same information. Plus, the contents of this PR are a bit outdated.

2024-09-12 08:32 UTC, closed without merging