Bump compare-urls to 3.0.0 (security flaw)
expo/expo pull request #13309
Opened 2021-06-17 03:46 UTC by BigZ

# Why

security flaw reported in npm audit

# How
simple bump

# Test Plan
up to you

# Checklist

- [x ] Documentation is up to date to reflect these changes (eg: https://docs.expo.io and README.md).
- [ x] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [ x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

# Why

# How

# Test Plan

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.io and README.md).
- [ ] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

2021-06-21 15:45 UTC, bbarthec requested changes
@BigZ, I need you to address CHANGELOG entry request mentioned by the CI.

2021-11-03 12:22 UTC, Simek commented on packages/expo-web-browser/package.json
> +  "version": "9.2.1",
Please revert this line, update the PR branch and address the Bartek request, so we can merge this bump in. 😉

2021-11-08 17:17 UTC, BigZ commented
hello @Simek  @bbarthec thanks a lot for considering my PR
i did the request change, i hope everything is fine
all the best to you ! greetings !

2024-06-20 19:24 UTC, Simek commented
Hey @BigZ, sorry for letting this slip trough, and we did not follow up on that contribution.

Since `expo-web-browser` no longer uses the problematic dependency I think we can close this PR, see:
* https://github.com/expo/expo/blob/337828590b3c7f98339f6dd1ae16d12a2b7ea12c/packages/expo-web-browser/package.json#L35-L43

Thanks anyway!

2024-06-20 19:24 UTC, closed without merging