[expo-battery][android] rewrite batterymodule to kotlin
expo/expo pull request #13504
Opened 2021-07-06 13:32 UTC by mstach60161

# Why

Modules written in java are rewritten to Kotlin.

# How

I generated Kotlin code from Java, fix problems and made code cleaner.

# Test Plan

I launched bare expo app and tested battery module with different parameters.

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.io and README.md).

2021-07-06 15:29 UTC, tsapeta approved these changes
Looks good to me except the `!!` and missing empty lines at the end of the files. Congrats for your first contribution! 👏

2021-07-06 15:29 UTC, tsapeta commented on packages/expo-battery/android/src/main/java/expo/modules/battery/BatteryLevelReceiver.kt
> +}
```suggestion
}

```

2021-07-06 15:29 UTC, tsapeta commented on packages/expo-battery/android/src/main/java/expo/modules/battery/BatteryModule.kt
> +}
```suggestion
}

```

2021-07-06 15:29 UTC, tsapeta commented on packages/expo-battery/android/src/main/java/expo/modules/battery/BatteryPackage.kt
> +}
```suggestion
}

```

2021-07-06 15:29 UTC, tsapeta commented on packages/expo-battery/android/src/main/java/expo/modules/battery/BatteryStateReceiver.kt
> +}
```suggestion
}

```

2021-07-06 15:29 UTC, tsapeta commented on packages/expo-battery/android/src/main/java/expo/modules/battery/PowerSaverReceiver.kt
> +}
```suggestion
}

```

2021-07-06 15:29 UTC, tsapeta commented on packages/expo-battery/android/src/main/java/expo/modules/battery/BatteryLevelReceiver.kt
> +    val level = batteryIntent!!.getIntExtra(BatteryManager.EXTRA_LEVEL, -1)
There is no guarantee that the `batteryIntent` won't be `null`, so I'd recommend unwrapping it and maybe print an error if it's not available. Generally I would advise not to use `!!` 😉

2021-07-07 07:52 UTC, lukmccall requested changes
Looks good just a couple of comments. Greate job 🥇 

And don't forget about the changelog entry 😉

2021-07-07 07:52 UTC, lukmccall commented on packages/expo-battery/android/src/main/java/expo/modules/battery/BatteryModule.kt
> +    ifilter.addAction(Intent.ACTION_BATTERY_OKAY)
```suggestion
    val ifilter = IntentFilter().apply { 
      addAction(Intent.ACTION_BATTERY_LOW)
      addAction(Intent.ACTION_BATTERY_OKAY)
    }
```

2021-07-07 07:52 UTC, lukmccall commented on packages/expo-battery/android/src/main/java/expo/modules/battery/BatteryModule.kt
> +  private var moduleRegistry: ModuleRegistry? = null
```suggestion
```
We don't use this property outside of `onCreate` function. So it can be removed 😉

2021-07-07 07:52 UTC, lukmccall commented on packages/expo-battery/android/src/main/java/expo/modules/battery/BatteryModule.kt
> +    this.moduleRegistry = moduleRegistry
```suggestion
```

2021-07-07 07:52 UTC, lukmccall commented on packages/expo-battery/android/src/main/java/expo/modules/battery/BatteryModule.kt
> +    val batteryLevel = if (level != -1 && scale != -1) level / scale.toFloat() else -1f
```suggestion
    val batteryLevel = if (level != -1 && scale != -1) {
      level / scale.toFloat() 
    } else { 
      -1f
    }
```

2021-07-07 07:52 UTC, lukmccall commented on packages/expo-battery/android/src/main/java/expo/modules/battery/BatteryModule.kt
> +
```suggestion
```
🧹

2021-07-07 07:52 UTC, lukmccall commented on packages/expo-battery/android/src/main/java/expo/modules/battery/BatteryPackage.kt
> +    return listOf(BatteryModule(context) as ExportedModule)
```suggestion
    return listOf(BatteryModule(context))
```
I belive this cast isn't needed 🤔

2021-07-07 07:52 UTC, lukmccall commented on packages/expo-battery/android/src/main/java/expo/modules/battery/BatteryStateReceiver.kt
> +  }
We have the same function in `BatteryModule.kt`. Please, extract it into a separate file. We don't want to have the same code in multiple places.

2021-07-07 07:52 UTC, lukmccall commented on packages/expo-battery/android/src/main/java/expo/modules/battery/BatteryStateReceiver.kt
> +  private val BATTERY_CHARGED_EVENT_NAME = "Expo.batteryStateDidChange"
This value can be moved on top of the file.

2021-07-07 07:52 UTC, lukmccall commented on packages/expo-battery/android/src/main/java/expo/modules/battery/PowerSaverReceiver.kt
> +  private val POWERMODE_EVENT_NAME = "Expo.powerModeDidChange"
This value can be moved on top of the file too 😉

2021-07-07 11:02 UTC, lukmccall approved these changes

2021-07-07 11:02 UTC, lukmccall commented on packages/expo-battery/android/src/main/java/expo/modules/battery/BatteryStatusNativeToJS.kt
> +}
```suggestion
}

```

2021-07-07 11:02 UTC, lukmccall commented on packages/expo-battery/android/src/main/java/expo/modules/battery/PowerSaverReceiver.kt
> +
```suggestion
```

2021-07-08 08:11 UTC, merged