[image] Add SVG support
expo/expo pull request #13503
Opened 2021-07-06 13:18 UTC by jakub-gonet

# Why

To extend supported formats.
Superseding #7385.

# How

Used SDWebImageSVGKitPlugin & androidsvg, copied SVG example from Glide repository.
Currently, there's a problem with SVGKit which doesn't compile on the 3.0 version (required by a newer version of SVGKitPlugin) so I didn't allow changing plugin version on iOS.

# Test Plan

Tested on bare-expo. Note I didn't update Podfile.lock - bare-expo doesn't work well with Flipper and I applied a patch removing it which changes the state of the lock file.

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.io and README.md).
- [ ] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

2021-07-08 15:25 UTC, bbarthec approved these changes
Looks fine to me 👍 
I'll try it myself and see how it works and then I'll merge 💪

2021-07-08 15:25 UTC, bbarthec commented on packages/expo-image/android/src/main/java/expo/modules/image/svg/SVGDecoder.kt
> +}
```suggestion
}

```

2021-07-08 15:25 UTC, bbarthec commented on packages/expo-image/android/src/main/java/expo/modules/image/svg/SVGDrawableTranscoder.kt
> + * and rewritten to Kotlin
```suggestion
 * Convert the [SVG]'s internal representation to an Android-compatible one ([Picture]).
 *
 * Copied from https://github.com/bumptech/glide/blob/10acc31a16b4c1b5684f69e8de3117371dfa77a8/samples/svg/src/main/java/com/bumptech/glide/samples/svg/SvgDrawableTranscoder.java
 * and rewritten to Kotlin.
```

2021-07-08 15:25 UTC, bbarthec commented on packages/expo-image/android/src/main/java/expo/modules/image/svg/SVGDrawableTranscoder.kt
> +}
```suggestion
}

```

2021-07-08 15:25 UTC, bbarthec commented on packages/expo-image/android/src/main/java/expo/modules/image/svg/SVGModule.kt
> + * and rewritten to Kotlin
```suggestion
 * [LibraryGlideModule] registering support for SVG to Glide.
 *
 * Copied from https://github.com/bumptech/glide/blob/10acc31a16b4c1b5684f69e8de3117371dfa77a8/samples/svg/src/main/java/com/bumptech/glide/samples/svg/SvgModule.java
 * and rewritten to Kotlin.
```

2021-07-08 15:25 UTC, bbarthec commented on packages/expo-image/android/src/main/java/expo/modules/image/svg/SVGModule.kt
> +}
```suggestion
}

```

2021-07-08 15:25 UTC, bbarthec commented on packages/expo-image/android/src/main/java/expo/modules/image/svg/SVGSoftwareLayerSetter.kt
> + * and rewritten to Kotlin
```suggestion
 * Copied from https://github.com/bumptech/glide/blob/10acc31a16b4c1b5684f69e8de3117371dfa77a8/samples/svg/src/main/java/com/bumptech/glide/samples/svg/SvgSoftwareLayerSetter.java
 * and rewritten to Kotlin.
```

2021-07-08 15:25 UTC, bbarthec commented on packages/expo-image/android/src/main/java/expo/modules/image/svg/SVGSoftwareLayerSetter.kt
> +}
```suggestion
}

```

2021-07-09 11:49 UTC, bbarthec requested changes
I believe I've spotted a problem 🤔
I've tried running the example screen on both platforms and obtained different results. 

On iOS image is not sharp 🤔 

Android | iOS
-|-
<img src="https://user-images.githubusercontent.com/16623003/125073509-5cc7bf00-e0bc-11eb-8787-80d8e03dc3c0.png" width=400 /> | <img src="https://user-images.githubusercontent.com/16623003/125073248-f3e04700-e0bb-11eb-8a2a-70a095e526d1.png" width=400 />

2021-07-15 19:18 UTC, jakub-gonet commented
Sorry for the pings, pull with rebase messed up history a bit 😞

2021-07-19 09:34 UTC, merged