[docs] add "Components" section to the generated docs, migrate `AppleAuthenticationButton`
expo/expo pull request #13567
Opened 2021-07-09 13:55 UTC by Simek

# Why & How

Refs ENG-910

This PR adds the missing "Components" section to the API auto generation feature.

During the development of this section I have use the `AppleAuthenticationButton` component from `expo-apple-authentication` package, which docs are now fully auto generated.

I have also applied small simplifications in the `AppleAuthenticationButton` code, which should not require the changelog entry (but I'm not 100% sure about `FunctionalComponent` => `FC` type change, please let me know if this change should be listed).

The changes have been only applied to the `unversioned` docs, please let me know if I should backport this to the SDK 42 docs.

# Test Plan

I have tested the new section and docs change by running Expo docs website locally.

<img width="1537" alt="Screenshot 2021-07-09 at 15 53 55" src="https://user-images.githubusercontent.com/719641/125088625-e59b2680-e0cd-11eb-8e9d-0f08749c0e6f.png">

# Checklist

- [X] Documentation is up to date to reflect these changes (eg: https://docs.expo.io and README.md).
- [X] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [X] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

2021-07-13 09:10 UTC, bbarthec requested changes
Regarding your questions:
- `FunctionComponent` === `FC` (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f09b036e3d1842821eb0c2dc2746981c515ed87a/types/react/index.d.ts#L541) so it's perfectly fine to use this alias
- regarding deriving the type from the `View` component, let's add some types inheritance to enable TS magical features 🧙

2021-07-13 09:10 UTC, bbarthec commented on packages/expo-apple-authentication/src/AppleAuthentication.types.ts
>  import { StyleProp, ViewStyle } from 'react-native';
```suggestion
import { StyleProp, ViewStyle, ViewProps } from 'react-native';
```

2021-07-13 09:10 UTC, bbarthec commented on packages/expo-apple-authentication/src/AppleAuthentication.types.ts
>  export type AppleAuthenticationButtonProps = {
As the docs suggest we can derive the props from the `View` component, so let's do it, shall we? 😊 
```suggestion
export interface AppleAuthenticationButtonProps extends ViewProps {
```

2021-07-13 09:36 UTC, bbarthec approved these changes
Once the CI is done I'm going to merge this 💪 
Great job, as always! 👏

2021-07-13 09:40 UTC, Simek commented
@bbarthec JSON data and package JS files need to be regenerated, but extending the component currently broke the props section. I will need to tak a look at this first. 

Also should we add the changelog entry now for `apple-authentication`, after the `Button` extension by `View`?

2021-07-13 09:46 UTC, bbarthec commented
@Simek, unfortunately I need you to rebuild the `build` directory 😞

2021-07-13 09:48 UTC, Simek commented
Sure, no problem. I have done the rebuild locally already, but I want to fix the missing props issue and push everything within the same commit 😉

2021-07-13 09:58 UTC, bbarthec commented
I think we can add some changelog entry for excluding `backgroundColor` and `borderRadius` from available `style` and for the fact that the `AppleButtonProps` now extends `ViewProps`.

2021-07-13 10:12 UTC, Simek commented
Unfortunately, fixing the props problem was not that trivial and it will need a bit more of work. 

I had to change the way in which `AppleAuthenticationButtonProps` and it's extension has been defined, otherwise TypeDoc exports all of the inherited props with the custom ones and there is no easy way to filter out them:
<img width="675" alt="Screenshot 2021-07-13 at 11 56 40" src="https://user-images.githubusercontent.com/719641/125433599-41a29021-6a30-44d2-a7da-94e089bb5017.png">

One idea to address that might be generating from code or just hardcoding the `ViewProps` list, but I think that the declaration refactor is a bit tidier way. Let me know if you will be happy with definition like this:
```ts
export declare type AppleAuthenticationButtonProps = ViewProps & {
  [...]
};
```

It works almost fine without any other code alteration, but I will need to address two more, small issue which has been introduce by types changes:
* better support for types with `Omit`, currently type is rendered just like in TS, but this should be altered a bit to be more descriptive and straight-forward
* there is an issue with Inheritance part in props section, `ViewProps` are listed, but not visible on the page for some reason, need to investigate this further.

2021-07-13 10:54 UTC, bbarthec commented on packages/expo-apple-authentication/CHANGELOG.md
> +- Exclude `backgroundColor` and `borderRadius` from the `style` type
- Exclude `backgroundColor` and `borderRadius` properties from the `AppleAuthenticationButton`'s `style` prop. These two are invalid for `AppleAuthenticationButton`, but TypeScript allowed the usage of them; instead use `buttonStyle` and `cornerRadius` props repsectively. ([#13567](https://github.com/expo/expo/pull/13567) by [@Simek](https://github.com/Simek))

2021-07-13 10:54 UTC, bbarthec commented on packages/expo-apple-authentication/CHANGELOG.md
> +- Extend the `AppleAuthenticationButton` component by `View`
- Extend the `AppleAuthenticationButton` component type by the `View` component type. ([#13567](https://github.com/expo/expo/pull/13567) by [@Simek](https://github.com/Simek))

2021-07-13 11:07 UTC, Simek commented
@bbarthec Thank you for updating the changelog entries, your suggestions were more detailed and way better overall! 🙂

2021-07-14 03:59 UTC, brentvatne commented on packages/expo-apple-authentication/src/AppleAuthentication.types.ts
> +  style?: StyleProp<Omit<ViewStyle, 'backgroundColor' | 'borderRadius'>>;
:+1:

2021-07-15 10:08 UTC, Simek commented
@bbarthec Is there something else which you want me to address in this PR? It would be nice to have this merged, to prevent the conflicts with upcoming API migration PR for `expo-font` package. 🙂

2021-07-15 19:22 UTC, merged