[expo-localauthentication][android] Fix missing message definition
expo/expo pull request #13636
Opened 2021-07-15 16:31 UTC by mstach60161

# Why

Fixes  #10682.

# How

- Added missing parameter message to LocalAuthenticationResult.
- Added missing parameter message in promise.resolve in LocalAuthenticationModule.
- Updated native component list with result message.

# Test Plan

- Native component list.

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.io and README.md).

2021-07-16 08:43 UTC, lukmccall requested changes
I think it's not a good way to go. I inspected the iOS code and it sometimes returns the `warning` property, which is automatically piped to the console. We should the same here. So please rename `message` to `warning` on Android 😉

2021-07-16 08:43 UTC, lukmccall commented on packages/expo-local-authentication/src/LocalAuthentication.types.ts
> +export type LocalAuthenticationResult = { success: true } | { success: false; error: string; message: string };
```suggestion
export type LocalAuthenticationResult = { success: true } | { success: false; error: string; warning?: string };
```
It should be called a warning and should be optional.

2021-07-16 08:43 UTC, lukmccall commented on packages/expo-local-authentication/android/src/main/java/expo/modules/localauthentication/LocalAuthenticationModule.kt
> +          putString("message", "isAuthenitcating returned false")
```suggestion
```

2021-07-21 09:38 UTC, lukmccall requested changes
You still need to change every "message" that occurs in LocationModule to "warning" in the Android codebase.

2021-07-22 09:42 UTC, lukmccall commented
Please, resolve conflicts 😉

2021-07-26 09:12 UTC, lukmccall commented
Please run `./gradlew :expo-local-authentication:spotlessApply` in `apps/bare-expo/android`

2021-07-27 17:16 UTC, mstach60161 commented
- [x] Please run `./gradlew :expo-local-authentication:spotlessApply` in `apps/bare-expo/android`

> BUILD SUCCESSFUL in 57s
> 3 actionable tasks: 3 executed

2021-07-28 11:45 UTC, lukmccall commented
Bump - fix CI and resolve confilits

2021-07-28 15:59 UTC, lukmccall approved these changes
LGTM 🥇

2021-07-28 15:59 UTC, merged