[expo-document-picker][android] Fix file uri
expo/expo pull request #13678
Opened 2021-07-19 12:13 UTC by mstach60161

# Why

- Fixes #13627.
- File uri didn't have prefix "file://".

# How

- Added file prefix to output file path.

# Test Plan

- Native component list.

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.io and README.md).

2021-07-21 10:01 UTC, lukmccall requested changes

2021-07-21 10:01 UTC, lukmccall commented on packages/expo-document-picker/android/src/main/java/expo/modules/documentpicker/DocumentPickerModule.kt
> +    return "file://$outputFilePath"
```suggestion
    return "file://$outputFilePath"
```
Are we sure if the `outputFilePath` won't contain a file scheme even if someone using a custom document picker? 
I think no. We need to wrap it in something which will be a little more intelligent. Maybe something like:
https://github.com/expo/expo/blob/22b3ce370fa3848e1046177201e5daa57ca2bc09/packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/tasks/ImageResultTask.kt#L36

2021-07-21 16:49 UTC, pedrohenriquebraga commented
Merge this with urgency

2021-07-22 01:10 UTC, adanielyan commented
Is there any workaround to this issue until the fix is merged?

2021-07-22 09:28 UTC, lukmccall commented
@adanielyan, you can add the 'file' scheme manually if not exists.

2021-07-22 09:29 UTC, lukmccall approved these changes
LGTM ✅

2021-07-22 09:30 UTC, merged

2021-07-23 00:42 UTC, syazwancode commented
> @adanielyan, you can add the 'file' scheme manually if not exists.

Hi im not sure appending the 'file' manually will fix this issue. I have mention in the issue that I raised (https://github.com/expo/expo/issues/13627) that appending the uri to include file:// at the front does not work.

2021-07-23 01:18 UTC, adanielyan commented
> > @adanielyan, you can add the 'file' scheme manually if not exists.
> 
> Hi im not sure appending the 'file' manually will fix this issue. I have mention in the issue that I raised (#13627) that appending the uri to include file:// at the front does not work.

Indeed, I tried making changes from this commit manually on the file in node_modules, but if didn't fix the issue. Had to rollback to sdk 41.