[android][cellular] Rewrite cellular module to kotlin
expo/expo pull request #13694
Opened 2021-07-20 10:42 UTC by M1ST4KE

# Why

Modules written in Java are being rewritten to Kotlin

# How

Generated Kotlin code from java.
Clean up code.

# Test Plan

Checked in the bare-expo app

2021-07-21 02:55 UTC, ide commented on packages/expo-cellular/android/src/main/java/expo/modules/cellular/CellularModule.kt
> +    val telephonyManager = mContext.getSystemService(Context.TELEPHONY_SERVICE) as TelephonyManager
Android does not guarantee this value is non-null so we need to handle that case. There are some cases like Instant Apps where some system services are null.

2021-07-21 02:55 UTC, ide commented on packages/expo-cellular/android/src/main/java/expo/modules/cellular/CellularModule.kt
> +        mSystemService as TelephonyManager
I'm not sure why the Java code had the `m` prefix for these local variables (perhaps in an earlier version of the module's first PR they were member variables and were not cleaned up properly) but we can safely remove it here.
```suggestion
      val systemService = mContext.getSystemService(Context.TELEPHONY_SERVICE)
      val telephonyManager = if (systemService != null) {
        systemService as TelephonyManager
```

2021-07-21 17:15 UTC, ide approved these changes

2021-07-22 09:38 UTC, lukmccall requested changes

2021-07-22 09:38 UTC, lukmccall commented on packages/expo-cellular/android/src/main/java/expo/modules/cellular/CellularModule.kt
> +
```suggestion
```
❔

2021-07-22 09:38 UTC, lukmccall commented on packages/expo-cellular/android/src/main/java/expo/modules/cellular/CellularModule.kt
> +  private val moduleRegistryDelegate: ModuleRegistryDelegate = ModuleRegistryDelegate()
```suggestion
```
❔

2021-07-22 09:38 UTC, lukmccall commented on packages/expo-cellular/android/src/main/java/expo/modules/cellular/CellularModule.kt
> +  }
```suggestion
  override fun getConstants(): HashMap<String, Any?> = HashMap().apply {
    val systemService = mContext.getSystemService(Context.TELEPHONY_SERVICE)
    val telephonyManager = systemService as? TelephonyManager
    
    put("allowsVoip", SipManager.isVoipSupported(mContext))
    put("isoCountryCode", telephonyManager?.simCountryIso)

    // check if sim state is ready
    if (telephonyManager != null && telephonyManager.simState == TelephonyManager.SIM_STATE_READY) {
      put("carrier",  telephonyManager.simOperatorName)
      put("mobileCountryCode", telephonyManager.simOperator.substring(0, 3))
      put("mobileNetworkCode",  StringBuilder(telephonyManager.simOperator).delete(0, 3).toString())
    } else {
      put("carrier", null)
      put("mobileCountryCode", null)
      put("mobileNetworkCode", null)
    }
  }
```
or something like this

2021-07-22 09:38 UTC, lukmccall commented on packages/expo-cellular/android/src/main/java/expo/modules/cellular/CellularModule.kt
> +      }
extract to a separate function

2021-07-22 09:38 UTC, lukmccall commented on packages/expo-cellular/android/src/main/java/expo/modules/cellular/CellularPackage.kt
> +    listOf(CellularModule(context) as ExportedModule)
```suggestion
    listOf(CellularModule(context))
```

2021-07-22 11:04 UTC, lukmccall approved these changes
LGMT 💪

2021-07-22 11:04 UTC, merged