[expo-document-picker][android][ios] Add mime type to response of getDocumentAsync()
expo/expo pull request #13702
Opened 2021-07-20 14:51 UTC by mstach60161

# Why
Fixes #12764.
DocumentPicker.getDocumentAsync(options) didn't return mime type which can be useful to handle file correctly.

# How

- Added mimeType parameter on android.
- Added mimeType parameter on ios.
- Updated docs.

# Test Plan

- Native component list.

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.io and README.md).

2021-07-21 09:47 UTC, lukmccall requested changes
Looks good ✅ 
I've left some comments 😉

2021-07-21 09:47 UTC, lukmccall commented on packages/expo-document-picker/android/src/main/java/expo/modules/documentpicker/DocumentPickerModule.kt
> +
```suggestion
```

2021-07-21 09:47 UTC, lukmccall commented on packages/expo-document-picker/android/src/main/java/expo/modules/documentpicker/DocumentPickerModule.kt
> +          }
```suggestion
		 documentDetails.mimeType?.let {
           putString("mimeType", documentDetails.mimeType)
		 }
```
You don't have to put null if the value isn't present. You can omit such value.

2021-07-21 09:47 UTC, lukmccall commented on packages/expo-document-picker/ios/EXDocumentPicker/EXDocumentPickerModule.m
> +
```suggestion
```

2021-07-21 09:47 UTC, lukmccall commented on packages/expo-document-picker/src/types.ts
> +      mimeType: string;
```suggestion
      mimeType?: string;
```

2021-07-23 12:32 UTC, bbarthec reviewed
Looks good to me 👍

2021-07-23 12:32 UTC, bbarthec commented on packages/expo-document-picker/CHANGELOG.md
> +
```suggestion
- Added mimetype to getDocumentAsync result. ([#13702](https://github.com/expo/expo/pull/13702) by [@mstach60161](https://github.com/mstach60161))

```

2021-07-26 08:35 UTC, bbarthec approved these changes
Looks good! 👏 
I'm landing this one! 🥳

2021-07-26 08:36 UTC, merged