[expo-modules] Move code from `unimodules` into `expo-modules-core`
expo/expo pull request #13703
Opened 2021-07-20 15:23 UTC by lukmccall

# Why

Migrated `unimodules-core`, `unimodules-react-native-adapter`, `unimodules-app-loader` into `expo-modules-core`

# How

- Change package using AS refactor tools 
- Fix some places where AS wasn't able to do automatically 
- Fix compatibility with new auto-linking 
- Ensure that classes which are used during installation steps are still available in the old place 

# Test Plan

- expo-go (tested using unversioned and 41)
- bare-expo

2021-07-21 09:53 UTC, tsapeta approved these changes

2021-07-22 21:19 UTC, brentvatne approved these changes

2021-07-23 12:12 UTC, bbarthec requested changes
LGTM 👍 
Things to do:
- ~[ ] Add CHANGELOG entries for the packages similar to this one: (https://github.com/expo/expo/pull/13750#pullrequestreview-713616254)~ _@tsapeta mentioned he will handle it module by module in his work on iOS side_

2021-07-23 13:54 UTC, bbarthec approved these changes

2021-07-26 14:32 UTC, merged