[document-picker][android][ios][web] Allow multiple mimetypes and fix bug
expo/expo pull request #13751
Opened 2021-07-23 11:18 UTC by mstach60161

# Why

- Fixes #4263.
- Fixes #8029.

# How

- Added possibility to pass array of mimetypes.
- Changed UTType for "*/*" mimetype from public.data to public.item. [IOS]

# Test Plan

- Native component list.

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.io and README.md).

2021-07-23 11:50 UTC, bbarthec requested changes
Looks fine to me 👍 
Things to do before we merge:
- [ ] Apply CI suggestion for CHANGELOG
- [ ] Back away from using abbreviations that could be full variables names

2021-07-23 11:50 UTC, bbarthec commented on packages/expo-document-picker/ios/EXDocumentPicker/EXDocumentPickerModule.m
> +      if ((@available(iOS 14, *))) {
```suggestion
      if (@available(iOS 14, *)) {
```

2021-07-23 11:50 UTC, bbarthec commented on packages/expo-document-picker/ios/EXDocumentPicker/EXDocumentPickerModule.m
> +        NSMutableArray *uttArray = [mimeTypes mutableCopy];
We prefer verbosity 👍 
It's always good to omit almost all abbreviations in open source software, or even in software altogether 😉 
```suggestion
        NSMutableArray *utTypes = [mimeTypes mutableCopy];
```

2021-07-23 11:50 UTC, bbarthec commented on packages/expo-document-picker/ios/EXDocumentPicker/EXDocumentPickerModule.m
> +          uttArray[i] = (NSString *)EXConvertMimeTypeToUTType(mimeTypes[i]);
```suggestion
          utTypes[i] = (NSString *)EXConvertMimeTypeToUTType(mimeTypes[i]);
```

2021-07-23 11:50 UTC, bbarthec commented on packages/expo-document-picker/ios/EXDocumentPicker/EXDocumentPickerModule.m
> +        documentPickerVC = [[UIDocumentPickerViewController alloc] initForOpeningContentTypes:uttArray asCopy:true];
```suggestion
        documentPickerVC = [[UIDocumentPickerViewController alloc] initForOpeningContentTypes:utTypes asCopy:true];
```

2021-07-26 09:18 UTC, lukmccall requested changes
I'm not a big fan of passing string or array to the native side. I think it will be better to wrap a single string into an array in js. In that way, we don't have to check the type of this argument on the native side.

2021-07-26 09:18 UTC, lukmccall commented on packages/expo-document-picker/android/src/main/java/expo/modules/documentpicker/DocumentPickerOptions.kt
> +data class DocumentPickerOptions(val type: String, val copyToCacheDirectory: Boolean, val types: Array<String>?) {
Do we have `types` and `type`? Can we merge it?

2021-07-29 08:21 UTC, bbarthec reviewed
I believe something is wrong in the native iOS and Android code 🤔 
I see that you've changed the ReactNative native method signature in the JS realm to `getDocumentAsync({ type: string[], ... }`, but on the native level you handle both cases `string | string[]`. I believe we could simplify to `string[]`.

2021-07-29 08:21 UTC, bbarthec commented on packages/expo-document-picker/src/ExpoDocumentPicker.web.ts
> +    input.setAttribute('accept', type as string);
Here we've got a problem 🤔 
This is the available typing: `type: string | string[]` and you narrow it down to `string` without any check. What about `string[]`? Is it impossible to pass `string[]` on the web? 🤔 If so we need to document this and properly handle `string[]` here 🤔

2021-08-02 16:51 UTC, bbarthec approved these changes
It looks neat now! 😊

2021-08-02 16:51 UTC, bbarthec commented on packages/expo-document-picker/ios/EXDocumentPicker/EXDocumentPickerModule.m
> +            utiTypes[i] = (NSString *)EXConvertMimeTypeToUTI(mimeTypes[i]);
```suggestion
          utiTypes[i] = (NSString *)EXConvertMimeTypeToUTI(mimeTypes[i]);
```

2021-08-02 16:57 UTC, bbarthec commented
Fix the CI, `yarn build` and we're ready to merge it 😉

2021-08-04 13:03 UTC, merged