[analytics-amplitude][ncl][android] Add API tests
expo/expo pull request #13774
Opened 2021-07-26 12:22 UTC by kkafar

# Why

Amplitude module lacks test tools. 

# How

Added separate screen in API section of BareExpo app for testing Amplitude module. 

Note: testing requires Amplitude API key

# Test Plan

[android]
Tested on demo Amplitude account 

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.io and README.md).
- [x] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).

2021-07-27 08:49 UTC, kkafar commented
cc @lukmccall @bbarthec

2021-07-28 22:27 UTC, bbarthec requested changes
Overall it looks interesting 👍 Good work on it 😉 
I've got a couple remarks apart from what's in the suggestions comments:
- keep up the good coding & ReactNative practices everywhere all the time
- if you repeat something for the 2nd time then it's the time to use some loop or refactor your approach 😉

2021-07-28 22:27 UTC, bbarthec commented on apps/native-component-list/src/screens/Amplitude/AmplitudeScreen.tsx
> +    }
```suggestion
    if (this.state.clientAPIKey) {
      try {
        await Amplitude.initializeAsync(this.state.clientAPIKey);
        this.setState({ result: 'Module initialized', initialized: true });
        this._deferredResultCleanup();
      } catch {
        this.setState({ error: 'Failed to initialize module' });
        this._deferredErrorCleanup();
      }
    } else {
      this.setState({ error: 'Invalid api key' });
      this._deferredErrorCleanup();
    }
```

2021-07-28 22:27 UTC, bbarthec commented on apps/native-component-list/src/screens/Amplitude/AmplitudeScreen.tsx
> +    );
```suggestion
    try {
      await Amplitude.setUserIdAsync(this.testUserId);
      this.setState({ result: `User ID set to ${this.testUserId}` });
      this._deferredResultCleanup();
    } catch {
      this.setState({ error: 'Failed to set UserId. Make sure that provided API key is valid.' });
      this._deferredErrorCleanup();
    }
```

2021-07-28 22:27 UTC, bbarthec commented on apps/native-component-list/src/screens/Amplitude/AmplitudeScreen.tsx
> +    );
```suggestion
    try {
      await Amplitude.logEventWithPropertiesAsync(this.testEventName, {
      this.setState({ result: `${this.testEventName} with mock properties logged` });
      this._deferredResultCleanup();
    } catch {
      this.setState({ error: 'Failed to log event. Make sure that provided API key is valid.' });
      this._deferredErrorCleanup();
    }
```

2021-07-28 22:27 UTC, bbarthec commented on apps/native-component-list/src/screens/Amplitude/AmplitudeScreen.tsx
> +    );
```suggestion
    try {
      await Amplitude.setGroupAsync(this.testGroupType, ['groupName1', 'groupName2']);
      this.setState({ result: 'Groups added' });
      this._deferredResultCleanup();
    } catch {
      this.setState({ error: 'Failed to add groups. Make sure that provided API key is valid.' });
      this._deferredErrorCleanup();
    }
```

2021-07-28 22:27 UTC, bbarthec commented on apps/native-component-list/src/screens/Amplitude/AmplitudeScreen.tsx
> +            <Text style={styles.errorText}>{this.state.errorMessage}</Text>
```suggestion
            <Text style={styles.errorText}>{this.state.error}</Text>
```

2021-07-28 22:27 UTC, bbarthec commented on apps/native-component-list/src/screens/Amplitude/TrackingOptionsSelector.tsx
> +    error: undefined,
```suggestion
```

2021-07-28 22:27 UTC, bbarthec commented on apps/native-component-list/src/screens/Amplitude/TrackingOptionsSelector.tsx
> +      <Text style={{ flex: 1, fontSize: 16 }}>{title}</Text>
Extract style to `StyleSheet.create`
```suggestion
    <View
      style={styles.toggleConatainer}>
      <Text style={styles.toggleLabel}>{title}</Text>
```

2021-07-28 22:27 UTC, bbarthec commented on apps/native-component-list/src/screens/Amplitude/TrackingOptionsSelector.tsx
> +    });
```suggestion
    this.setState(state => ({ showList: !state.showList });
```

2021-07-28 22:27 UTC, bbarthec commented on apps/native-component-list/src/screens/Amplitude/TrackingOptionsSelector.tsx
> +    );
```suggestion
    try {
      await setTrackingOptionsAsync(this.state.options);
      this.setState({ result: 'Request for tracking options change has been sent' });
      setTimeout(() => this.setState({ result: undefined }), 5000);
    } catch {
      this.setState({ error: 'Failed to send request for tracking options change' });
      setTimeout(() => this.setState({ error: undefined }), 5000);
    }
```

2021-07-28 22:27 UTC, bbarthec commented on apps/native-component-list/src/screens/Amplitude/TrackingOptionsSelector.tsx
> +      <View style={{ marginTop: 20 }}>
```suggestion
      <View style={styles.container}>
```

2021-07-28 22:27 UTC, bbarthec commented on apps/native-component-list/src/screens/Amplitude/TrackingOptionsSelector.tsx
> +          })}
Use [`Fragments`](https://reactjs.org/docs/fragments.html#short-syntax) and reduce boilerplate:
```suggestion
        {this.state.showList && (
          <>
            {
              [
            	{ title: 'Disable Adid', valueName: 'disableAdid' },
            	{ title: 'Disable Carrier', valueName: 'disableCarrier' },
            	{ title: 'Disable City', valueName: 'disableCity' },
            	{ title: 'Disable Country', valueName: 'disableCountry' },
            	{ title: 'Disable DMA', valueName: 'disableDMA' },
                { title: 'Disable Device brand', valueName: 'disableDeviceBrand' }
            	{ title: 'Disable Device manufacturer', valueName: 'disableDeviceManufacturer' },
            	{ title: 'Disable Device model', valueName: 'disableDeviceModel' },
            	{ title: 'Disable IDFV', valueName: 'disableIDFV' },
            	{ title: 'Disable IP Address', valueName: 'disableIPAddress' },
            	{ title: 'Disable Language', valueName: 'disableLanguage' },
            	{ title: 'Disable Geo?', valueName: 'disableLatLng' },
                { title: 'Disable OS Name', valueName: 'disableOSName' },
                { title: 'Disable OS version', valueName: 'disableOSVersion' },
                { title: 'Disable Platform', valueName: 'disablePlatform' },
                { title: 'Disable Region', valueName: 'disableRegion' },
                { title: 'Disable version name', valueName: 'disableVersionName' },
              ].map(this._renderToggle)
            }
          </>
        )}
```
You can extract these toggles definitions into some meaningful variable 😉

2021-08-02 17:36 UTC, bbarthec approved these changes
Looks awesome 🎉

2021-08-02 17:44 UTC, merged