[android] Kotlinize ReactNativeActivity and ExperienceActivity
expo/expo pull request #13870
Opened 2021-07-30 23:49 UTC by wschurman

# Why

Part 4 of #13685.

# How

1. Convert file to kotlin
2. Manually compare before and after, manually fix inconsistencies, check nullabilities
3. `gradlew spotlessApply`

# Test Plan

Run app, open some experiences.

2021-08-07 09:00 UTC, ide requested changes

2021-08-08 20:48 UTC, wschurman commented on android/app/src/main/java/host/exp/exponent/MainActivity.kt
> +  }
https://linear.app/expo/issue/ENG-1762/investigate-removal-of-the-nullable-type-for

2021-08-08 20:48 UTC, wschurman commented on android/expoview/src/main/java/host/exp/exponent/experience/BaseExperienceActivity.kt
> +      reactRootView.assign(null)
nice catch!!

2021-08-09 01:24 UTC, ide approved these changes

2021-08-09 15:38 UTC, merged