[android][barcode-scanner] Rewrite barcode scanner to kotlin
expo/expo pull request #13914
Opened 2021-08-04 08:45 UTC by M1ST4KE

# Why

It's a part of modules kotlinisation

# How

# Test Plan

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.io and README.md).
- [x] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

2021-08-04 11:13 UTC, lukmccall requested changes

2021-08-04 11:13 UTC, lukmccall commented on packages/expo-barcode-scanner/android/src/main/java/expo/modules/barcodescanner/BarCodeScannerViewManager.kt
> +      }
apply

2021-08-04 18:03 UTC, bbarthec reviewed
Looks very nice 👍 
Thank you for taking care of this module 💪 🙇 
Left just a couple of comments, take care of them and we're ready to go 👍

2021-08-05 13:12 UTC, M1ST4KE commented on packages/expo-barcode-scanner/android/src/main/java/expo/modules/barcodescanner/BarCodeScannerViewFinder.kt
> +      return (width.toFloat() / height.toFloat()).toDouble()
It's a good point, but it would require to change logic, so I suppose this should be done in a separate PR.

2021-08-05 14:02 UTC, lukmccall requested changes

2021-08-05 14:02 UTC, lukmccall commented on packages/expo-barcode-scanner/android/src/main/java/expo/modules/barcodescanner/scanners/ZxingBarCodeScanner.kt
> +    get() = true
```suggestion
  override val isAvailable = true
```

2021-08-05 14:02 UTC, lukmccall commented on packages/expo-barcode-scanner/android/src/main/java/expo/modules/barcodescanner/utils/ImageDimensions.kt
> +class ImageDimensions(
It can be converted into a data class

2021-08-06 09:52 UTC, lukmccall requested changes

2021-08-06 09:52 UTC, lukmccall commented on packages/expo-barcode-scanner/android/src/main/java/expo/modules/barcodescanner/BarCodeScannerView.kt
> +
```suggestion
```

2021-08-06 09:52 UTC, lukmccall commented on packages/expo-barcode-scanner/android/src/main/java/expo/modules/barcodescanner/BarCodeScannerView.kt
> +  }
```suggestion

  override fun onDetachedFromWindow() {
    super.onDetachedFromWindow()
    orientationListener.disable()
  }
```

2021-08-06 09:52 UTC, lukmccall commented on packages/expo-barcode-scanner/android/src/main/java/expo/modules/barcodescanner/BarCodeScannerViewFinder.kt
> +
```suggestion
```

2021-08-06 09:52 UTC, lukmccall commented on packages/expo-barcode-scanner/android/src/main/java/expo/modules/barcodescanner/BarCodeScannerViewManager.kt
> +      }
```suggestion
      val settings = BarCodeScannerSettings().apply {
        putTypes(barCodeTypes)
      }
```

2021-08-06 09:52 UTC, lukmccall commented on packages/expo-barcode-scanner/android/src/main/java/expo/modules/barcodescanner/scanners/GMVBarCodeScanner.kt
> +  private var mBarcodeDetector =
rename to `barcodeDetector`

2021-08-06 09:52 UTC, lukmccall commented on packages/expo-barcode-scanner/android/src/main/java/expo/modules/barcodescanner/utils/ImageDimensions.kt
> +  }
Do we need those functions? It should be generated by data class.

2021-08-09 13:43 UTC, lukmccall requested changes

2021-08-09 13:43 UTC, lukmccall commented on packages/expo-barcode-scanner/android/src/main/java/expo/modules/barcodescanner/BarCodeScannerViewFinder.kt
> +  private val moduleRegistryDelegate: ModuleRegistryDelegate = ModuleRegistryDelegate()
```suggestion
  private val moduleRegistryDelegate: ModuleRegistryDelegate
```

2021-08-09 13:43 UTC, lukmccall commented on packages/expo-barcode-scanner/android/src/main/java/expo/modules/barcodescanner/BarCodeScannerViewManager.kt
> +class BarCodeScannerViewManager(
You can't remove `onCreate` method from `BarCodeScannerViewManager`. Something need to provide `ModuleRegistry` to `ModuleRegistryDelegate`.

2021-08-09 13:43 UTC, lukmccall commented on packages/expo-barcode-scanner/android/src/main/java/expo/modules/barcodescanner/ExpoBarCodeScanner.kt
> +  private var mCameraType = 0
rename to `camera` and `cameraType`

2021-08-09 13:43 UTC, lukmccall commented on packages/expo-barcode-scanner/android/src/main/java/expo/modules/barcodescanner/scanners/GMVBarCodeScanner.kt
> +    }
I think it can be easily converted to a `reduce` function.

2021-08-11 13:34 UTC, lukmccall approved these changes
LGTM 💪

2021-08-11 14:00 UTC, merged