Rewrite from AsyncTask to Kotlin coroutines
expo/expo pull request #14029
Opened 2021-08-12 12:00 UTC by M1ST4KE

# Why

`AsyncTask` is deprecated since api level 30, it's recommended to use the standard java.util.concurrent or Kotlin concurrency utilities instead.

# How

Rewrote classes extending AsyncTask, to use kotlin concurrency utilities

# Test Plan

Checked module in bare-expo app
Ran test-suite tests

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.io and README.md).
- [x] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

2021-08-13 12:13 UTC, lukmccall commented on packages/expo-barcode-scanner/android/src/main/java/expo/modules/barcodescanner/BarCodeScannerViewFinder.kt
> +//              }
```suggestion
```
?

2021-08-13 12:13 UTC, lukmccall commented on packages/expo-barcode-scanner/android/src/main/java/expo/modules/barcodescanner/BarCodeScannerViewFinder.kt
> +
```suggestion
```
?

2021-08-13 12:13 UTC, lukmccall commented on packages/expo-barcode-scanner/android/src/main/java/expo/modules/barcodescanner/BarCodeScannerViewFinder.kt
> +    private val moduleRegistryDelegate: ModuleRegistryDelegate
?

2021-08-13 12:13 UTC, lukmccall commented on packages/expo-barcode-scanner/android/src/main/java/expo/modules/barcodescanner/BarCodeScannerViewFinder.kt
> +              )
?

2021-08-18 14:03 UTC, bbarthec requested changes
I've got a few remarks, but overall the code looks solid 👍

2021-08-18 14:03 UTC, bbarthec commented on packages/expo-barcode-scanner/android/src/main/java/expo/modules/barcodescanner/BarCodeScannerViewFinder.kt
> +  private fun barCodeScannerAsyncTask(camera: Camera?, mImageData: ByteArray) {
I dislike the idea of using `*AsyncTask` sufix in the method name, while it has nothing with it anymore.
```suggestion
  private fun scanForBarcodes(camera: Camera?, mImageData: ByteArray) {
```

2021-08-18 14:03 UTC, bbarthec commented on packages/expo-barcode-scanner/android/src/main/java/expo/modules/barcodescanner/BarCodeScannerViewManager.kt
> +import android.util.Log
Unused import? 🤔 
```suggestion
```

2021-08-18 14:03 UTC, bbarthec commented on packages/expo-barcode-scanner/android/src/main/java/expo/modules/barcodescanner/BarCodeScannerViewManager.kt
> +import kotlinx.coroutines.cancel
Unused imports? 🤔 
```suggestion
```

2021-08-18 14:03 UTC, bbarthec commented on packages/expo-sharing/CHANGELOG.md
> +- Migrated from `AsyncTask` to Kotlin concurrency utilities. ([#14029](https://github.com/expo/expo/pull/14029) by [@m1st4ke](https://github.com/m1st4ke))
Why not to name them explicitly? 😅 
```suggestion
- Migrated from `AsyncTask` to Kotlin coroutines. ([#14029](https://github.com/expo/expo/pull/14029) by [@m1st4ke](https://github.com/m1st4ke))
```

2021-08-30 11:39 UTC, M1ST4KE commented on packages/expo-barcode-scanner/android/build.gradle
> +  implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.4.1")
Latest coroutines version requires latest kotlin version - `1.5.20`, we are using `1.4.21`

2021-08-30 13:59 UTC, bbarthec approved these changes
LGTM 👍

2021-08-30 14:00 UTC, merged