[android][web-browser] Fix `openAuthSessionAsync` stating browser is already open
expo/expo pull request #14181
Opened 2021-08-25 19:59 UTC by sumnerwarren

# Why

As shown in expo/expo#12045, it is possible for `openBrowserAsync` to fail before the browser opens. When this was prompted by a call to `openAuthSessionAsync` it should be possible to call `openAuthSessionAsync` again without seeing the error `WebBrowser is already open, only one can be open at a time`. An example where this may prove useful is if the user leaves the app to change their default browser settings (or which browsers are installed) and returns to attempt authentication again. Without this fix, `openAuthSessionAsync` will think a browser is open when it is not.

# How

I fixed this bug by improving the internal state check for whether a browser was open and returning the appropriate error in both cases.

# Test Plan

Added a unit test to make sure `_onWebBrowserCloseAndroid` is cleared properly when the browser fails to open to do intent resolution issues. The original issue and fix can be observed in a Pixel 4 API 30 emulator with the DuckDuckGo app set as the default browser. Before this change all `openAuthSessionAsync` attempts except the first would erroneously state a browser was already open. After this change all `openAuthSessionAsync` attempts should throw the `No matching activity!` error.

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.io and README.md).
- [ ] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

2021-08-28 15:35 UTC, bbarthec requested changes
@sumnerwarren, thank you very much for finding the culprit for this erroneous scenario 👏 
I think the approach you're proposing is fine, but I would say that we can cleanup the state no matter the type of error 🧹 
Let's remove the `if` condition and we're almost ready to merge it 👍

2021-08-28 15:35 UTC, bbarthec commented on packages/expo-web-browser/src/WebBrowser.ts
> +    if (e.message === 'No matching activity!') {
I believe we should clear the state no matter the type of error 🤔

2021-08-28 19:11 UTC, sumnerwarren commented
> Let's remove the `if` condition and we're almost ready to merge it 👍

All set! I updated the test to demonstrate multiple error types as well.

2021-08-29 01:21 UTC, ide commented on packages/expo-web-browser/src/__tests__/WebBrowser-test.native.ts
> +  }
```suggestion
  await expect(WebBrowser.openAuthSessionAsync(pageUrl, redirectUrl))
    .rejects
    .toThrowError('No matching activity!');
```
etc..

2021-08-29 01:22 UTC, ide commented on packages/expo-web-browser/src/__tests__/WebBrowser-test.native.ts
> +  expect.assertions(3);
then don't need this
```suggestion
```

2021-08-30 10:33 UTC, bbarthec reviewed
@sumnerwarren thank you for taking care of the suggestions 👏 
Make sure you're replied to all of them and we're ready to merge it (if only CI is green) 👍

2021-08-30 14:24 UTC, merged