[android][kernel] Fix ReactNativeStaticHelpers.getBundleUrlForActivityId argument order
expo/expo pull request #14222
Opened 2021-08-30 18:59 UTC by wschurman

# Why

Noticed this while converting this to kotlin. Not sure of the effects of this bug, though since it's only used in `DevServerHelper` I'm assuming it isn't too bad, but this PR fixes it.

# How

Update ordering to match kernel. 

For reviewers: if there's something I'm missing here about old SDKs needing the `ReactNativeStaticHelpers` method parameter order not to change let me know, but as far as I can tell `DevServerHelper.java` is not versioned so we're in the clear to change the parameter ordering.

# Test Plan

Build.

2021-08-31 00:40 UTC, Kudo commented
should also update [the codegen here](https://github.com/expo/expo/blob/b97121ff873c4db8c384056ff1a8443dc67eeb76/android/tools/src/main/java/host/exp/exponent/tools/ReactAndroidCodeTransformer.java#L142-L147) where we used to run from react-native code sync.

2021-08-31 01:08 UTC, ide requested changes
Think it's safe to rearrange ReactNativeStaticHelpers's signature.

2021-08-31 23:08 UTC, ide approved these changes

2021-09-01 01:29 UTC, Kudo approved these changes

2021-09-01 01:56 UTC, merged