[local-authentication] Fix isEnrolledAsync issue
expo/expo pull request #14411
Opened 2021-09-14 14:08 UTC by M1ST4KE

# Why

Reported in issue #14118. According to documentation, everything works as expected, but the name and behavior of the function may mislead users, so it's better to provide new functions allowing users to explicitly decide if they want to check biometrics or any available authentication.

# How

Added new functions, allowing to check explicitly biometrics only or any authentication method.

# Test Plan

Checked in bare-expo app

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.io and README.md).
- [x] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

2021-09-15 10:24 UTC, Simek reviewed
Currently, to see the docs changes on the website you need to manually regenerate the JSON data file using command:
```
et gdad -p expo-local-authentication
```

Also, since the feature is still in development it's nice to launch the docs website locally and verify in `unversioned` that the added parts are there and they are correctly rendered.

2021-09-16 07:48 UTC, lukmccall requested changes
Looks good ✅

2021-09-16 07:48 UTC, lukmccall commented on packages/expo-local-authentication/android/src/main/java/expo/modules/localauthentication/LocalAuthenticationModule.kt
>      promise.resolve(result == BiometricManager.BIOMETRIC_SUCCESS)
just call `isDeviceAuthenticationWithBiometricsEnrolledAsync`

2021-09-16 09:34 UTC, lukmccall commented
Fix CI

2023-08-30 15:43 UTC, closed without merging