[android][network] Rewrite Android code to Kotlin
expo/expo pull request #14474
Opened 2021-09-20 10:30 UTC by kkafar

# Why

This task was done as a part of migrating expo modules to Kotlin project.

# How

The code had been initially converted from Java to Kotlin with help of Android Studio's conversion tool. Then it was manually adjusted / improved.

# Test Plan

in progress....

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.io and README.md).
- [ ] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

2021-10-01 10:30 UTC, kkafar reviewed
Notes:

2021-10-01 10:30 UTC, kkafar commented on packages/expo-network/android/src/main/java/expo/modules/network/NetworkModule.kt
> +    if (netCapabilities == null) NetworkStateType.UNKNOWN
`null` case is handled separately in the beginning in order to avoid using safe calls `?.` later on

2021-10-01 12:24 UTC, barthap approved these changes
👍

2021-10-01 12:44 UTC, kkafar commented on packages/expo-network/android/src/main/java/expo/modules/network/NetworkModule.kt
> +    else NetworkStateType.UNKNOWN
Thank you!

2021-10-01 21:48 UTC, ide requested changes

2021-10-01 21:48 UTC, ide commented on packages/expo-network/android/src/main/java/expo/modules/network/NetworkModule.kt
> +      Log.e(TAG, e.message ?: "Wifi information could not be acquired")
```suggestion
      Log.e(TAG, e.message ?: "Wi-Fi information could not be acquired")
```

2021-10-01 21:48 UTC, ide commented on packages/expo-network/android/src/main/java/expo/modules/network/NetworkModule.kt
> +        }
The `also` scope function looks safe to remove:

```suggestion
        val connectionType = if (isInternetReachable) {
          val netCapabilities = connectivityManager.getNetworkCapabilities(network)
          getConnectionType(netCapabilities)
        } else {
          null
        }

        result.apply {
          putString("type", connectionType?.value ?: NetworkStateType.NONE.value)
          putBoolean("isInternetReachable", isInternetReachable)
          putBoolean("isConnected", connectionType != null && connectionType.isDefined)
        }
```

2021-10-01 21:48 UTC, ide commented on packages/expo-network/android/src/main/java/expo/modules/network/NetworkModule.kt
> +      Log.e(TAG, e.message ?: "Could not get ip address")
```suggestion
      Log.e(TAG, e.message ?: "Could not get IP address")
```

2021-10-01 21:48 UTC, ide commented on packages/expo-network/android/src/main/java/expo/modules/network/NetworkModule.kt
> +    promise.resolve(isAirPlaneMode)
```suggestion
    val isAirplaneMode = Settings.Global.getInt(appContext.contentResolver, Settings.Global.AIRPLANE_MODE_ON, 0) != 0
    promise.resolve(isAirplaneMode)
```

2021-10-01 21:48 UTC, ide commented on packages/expo-network/android/src/main/java/expo/modules/network/NetworkModule.kt
> +    }
Move this into module scope since it's private and we don't need a companion object.

2021-10-05 00:58 UTC, ide approved these changes

2021-10-06 10:54 UTC, bbarthec approved these changes
Nice job 👍

2021-10-07 16:43 UTC, merged