[iOS][Expo Go] Remove legacy code
expo/expo pull request #14690
Opened 2021-10-08 18:21 UTC by bbarthec

# Why

Followup for #14650 & #14649 
We're past some points in time that allows us to slim down some mechanics used in the Expo Go codebase by removing unreachable code paths.

# How

Ive searched for the old SDK versions references in the code and found a few places with `marked-to-remove-code`.

# Test Plan

I've tried compiling the Expo Go in both `versioned` and `unversioned` versions and run a few tests from `test-suite` app that might have been affected the the code removal and observed **no** regressions.

# Areas of interest

I've got a few requests regarding some parts of this PR:
- @ide, @wschurman, @cruzach or any other person familiar with device's ID and notifications - I've removed a few `deviceInstallationID`-related things and it would be good if that's safe
- @esamelson - I've removed small part of `updates`/`loader`-related code, so please take a look if nothing (that I'm not aware of) would break

2021-10-08 18:53 UTC, ide requested changes

2021-10-11 17:07 UTC, wschurman approved these changes

2021-10-11 17:24 UTC, esamelson approved these changes
the changes in EXUpdatesManager and EXAppLoaderExpoUpdates look good to me 👍

2021-10-12 16:53 UTC, ide approved these changes

2021-10-13 12:12 UTC, merged