[docs] add docs for submit webhooks
expo/expo pull request #15285
Opened 2021-11-23 14:27 UTC by dsokal

# Why

Follow-up to https://github.com/expo/eas-cli/pull/777
The PR added support for submit webhooks.

# How

- It's now possible to create submit webhooks. I decided to make the current build webhooks page generic so we don't need to maintain two similar pages.
- The code in `navigation-data.js` is really hacky but I had no clue how to do it better (suggestions with code that I can copy/paste are welcome).

# Test Plan

yarn dev

New EAS section:
<img width="1357" alt="Screenshot 2021-11-23 at 15 24 51" src="https://user-images.githubusercontent.com/5256730/143041954-dd19d809-519f-490c-921c-a6b07a31f3f3.png">

2021-11-23 22:21 UTC, brentvatne requested changes

2021-11-23 22:21 UTC, brentvatne commented on docs/pages/eas/webhooks.md
> +EAS calls your webhook using an HTTP POST request. All the data is passed in the request body. EAS sends the data as a JSON object. The most notable fields are:
"The most notable fields are:"

it looks like we aren't listing any fields here anymore. we should probably add some documentation for the fields for both build and submit webhooks

2021-11-23 22:21 UTC, brentvatne commented on docs/pages/eas/webhooks.md
> +> If you want to test the above webhook locally, you have to use a service like [ngrok](https://ngrok.com/docs) to forward `localhost:8080` via a tunnel and make it publicly accessible to anyone with
```suggestion
> If you want to test the above webhook locally, you have to use a service like [ngrok](https://ngrok.com/docs) to forward `localhost:8080` via a tunnel and make it publicly accessible with the URL `ngrok` gives you.
```

2021-11-24 09:37 UTC, wkozyra95 approved these changes

2021-11-24 11:56 UTC, wkozyra95 approved these changes

2021-11-24 11:56 UTC, wkozyra95 commented on docs/pages/eas/webhooks.md
> +```ts
```suggestion
```json
```

2021-11-25 10:03 UTC, merged