[dev-launcher] add dev sessions and update deep link modal
expo/expo pull request #15584
Opened 2021-12-15 19:26 UTC by ajsmth

# Why

# How

# Test Plan

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

2021-12-16 12:52 UTC, lukmccall requested changes
Just a couple of suggestions ;)

2021-12-16 12:52 UTC, lukmccall commented on packages/expo-dev-launcher/bundle/hooks/useRecentlyOpenedApps.tsx
> +
```suggestion
```
🧹

2021-12-16 12:52 UTC, lukmccall commented on packages/expo-dev-launcher/bundle/native-modules/DevLauncherInternal.ts
> +export const isDevice = !!DevLauncher.isDevice;
```suggestion
export const isDevice = !!DevLauncher.isDevice;

```

2021-12-16 12:52 UTC, lukmccall commented on packages/expo-dev-launcher/bundle/components/redesign/DeepLinkModal.tsx
> +export function DeepLinkModal({ onClosePress, pendingDeepLink }) {
Could you split this component into smaller ones? Currently, it's hard to understand what going on there.

2021-12-16 12:52 UTC, lukmccall commented on packages/expo-dev-launcher/bundle/components/redesign/Modal.tsx
> +    if (!hasModal) {
```suggestion
    } else {
```

2021-12-16 20:08 UTC, esamelson approved these changes
looks great! 🎉

2021-12-16 20:08 UTC, esamelson commented on packages/expo-dev-launcher/bundle/screens/HomeScreen.tsx
> +          Alternatively, open the Camera app and scan the QR code that appears in your terminal
```suggestion
          Alternatively, open the Camera app and scan the QR code that appears in your terminal.
```
tiny nit, just to match the rest of the text :)

2021-12-17 13:54 UTC, lukmccall approved these changes

2021-12-20 18:46 UTC, merged