[blur] tweak types for docs extraction
expo/expo pull request #15654
Opened 2021-12-20 11:43 UTC by Simek

# Why

Refs: 
* #15373
* #14946

This PR includes small tweaks to the Blur types after latest refactor which fixes some of the problems reported by Bartek in "Fix docs layout" PR.

# How

This changeset:
* removes the internal comment about `forwardedRef` from public export, 
* moves `forwardedRef` prop to the `BlurViewProps` and mark is as `@hidden` (not visible in docs, but exported)
* removes unnecessary `ViewProps` type in `setNativeProps` call

I have also regenerated the docs JSON file for the `unversioned` docs as well as for `SDK 44`.

# Test Plan

The package builds correctly, tests did not report any issues. I have also tested the BlurViews in NCL app.

The docs changes have been tested by running the website on `localhost`, but without the changes from #15373 there is no difference in the BlurView page content.

# Checklist

- [X] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

2021-12-20 12:03 UTC, bbarthec requested changes
I'm against exposing `forwardedRef` to the component's public API, because it would allow such scenario:
<img width="196" alt="Screenshot 2021-12-20 at 12 59 25" src="https://user-images.githubusercontent.com/16623003/146764178-8f05bf76-27ed-436a-8953-aa1d8e03b4c5.png">

I imagine we should have typings & docs consistent 🤔 
Moreover I've observed that generated built files are stripped from docs and that's not so good as well 🤔 
<img width="473" alt="Screenshot 2021-12-20 at 13 03 14" src="https://user-images.githubusercontent.com/16623003/146764572-0a5ffd67-8907-4e85-b50d-9be838af83dd.png">

2021-12-20 12:18 UTC, Simek commented
> I'm against exposing `forwardedRef` to the component's public API, because it would allow such scenario

Understandable, I will create non exported type for the ref prop instead (this is necessary to avoid unnamed types).

> I imagine we should have typings & docs consistent 🤔 Moreover I've observed that generated built files are stripped from docs and that's not so good as well 🤔

I'm not sure which file exactly you are mentioning here, bit it looks like is not issue related exactly to this PR, as the content of those files is based on the TS settings. 

I can see that the props comments in build folder are only available in `.d.ts` files for few other packages. For some reason in case like here (ref forward) TS do not propagate comments up, but I'm not sure if it should 🤷‍♂️

2022-01-30 21:19 UTC, tsapeta approved these changes

2022-02-08 14:02 UTC, bbarthec approved these changes

2022-02-08 14:02 UTC, merged