[av] fix build error on Expo SDK 44
expo/expo pull request #15661
Opened 2021-12-20 15:51 UTC by schiller-manuel

# Why

There is a name clash of property `moduleRegistry` that is already declared in `RCTModuleRegistry`.

This fixes #15627.

# How

Renamed property `moduleRegistry` to `expoModuleRegistry` to resolve this.

# Test Plan

1.  `npx react-native init ExpoAvError`
2.  `npx install-expo-modules`
3.  `npm install expo-av && npx pod-install`

❌ `npm run ios` now fails 

4. Apply this PR

✅ `npm run ios` now succeeds.

2021-12-29 13:39 UTC, Simek requested changes
Thank you @schiller-manuel for finding the root cause and working on the fix! 👍 

Changes looks good, I have left only small suggestion for the changelog entry.

2021-12-29 13:39 UTC, Simek commented on packages/expo-av/CHANGELOG.md
> +- Fix iOS build with Expo SDK 44. [#15661](https://github.com/expo/expo/pull/15661)
```suggestion
- Fix iOS build with Expo SDK 44 and React Native 0.65+. [#15661](https://github.com/expo/expo/pull/15661)
```

Just a small clarification for the changelog entry. 

It looks like the code adding conflicting variable name on the RN side has landed in `0.65` release:
* https://github.com/facebook/react-native/commit/6f02942dc12fe95a153c2a4cc17ae9bcaa7b0154

2021-12-29 15:45 UTC, bbarthec approved these changes
Hello @schiller-manuel 👋 Thank you for this contribution 😊 
It looks fine to me 👍

2021-12-29 15:46 UTC, merged

2022-01-01 15:07 UTC, Dajust commented
The expo-av node_module is yet to get this fix.

2022-01-02 19:48 UTC, eurobob commented
@bbarthec when will this be deployed into the cli tool?

2022-01-06 08:20 UTC, nero2009 commented
please has this been merged and published @bbarthec

2022-01-06 08:39 UTC, nomi9995 commented
@Dajust @eurobob @nero2009 for now, you can install this as a temp solution
```
"expo-av": "https://gitpkg.now.sh/expo/expo/packages/expo-av?master"
```

2022-01-15 15:43 UTC, Dajust commented
@nomi9995 This 

> ```
> "expo-av": "https://gitpkg.now.sh/expo/expo/packages/expo-av?master"
> ```

This is throwing some timeout error after I ran `yarn install`.

```js
error An unexpected error occurred: "https://gitpkg.now.sh/expo/expo/packages/expo-av?master: Request failed \"504 Gateway Timeout\"".
```

2022-01-20 20:55 UTC, joebarrero commented
Is there a way to add the GitHub commit to an existing project until this is released via node?

2022-01-21 07:16 UTC, nomi9995 commented
@Dajust @joebarrero 
you can use patch `expo-av+9.2.3.patch` by [patch-package](https://www.npmjs.com/package/patch-package)
```
diff --git a/node_modules/expo-av/android/build.gradle b/node_modules/expo-av/android/build.gradle
index bfca4ca..749b89c 100644
--- a/node_modules/expo-av/android/build.gradle
+++ b/node_modules/expo-av/android/build.gradle
@@ -1,6 +1,6 @@
 apply plugin: 'com.android.library'
 apply plugin: 'kotlin-android'
-apply plugin: 'maven'
+apply plugin: 'maven-publish'
 
 group = 'host.exp.exponent'
 version = '9.2.3'
@@ -36,11 +36,10 @@ artifacts {
   archives androidSourcesJar
 }
 
-uploadArchives {
+publishing {
   repositories {
-    mavenDeployer {
-      configuration = configurations.deployerJars
-      repository(url: mavenLocal().url)
+    maven {
+      url = uri("${rootProject.projectDir}/maven-repo")
     }
   }
 }

```

2022-01-25 11:02 UTC, tarkcelk commented
when this is going to be deployed ?

2022-01-25 14:58 UTC, joebarrero commented
@Dajust thank you.  This patch worked perfectly.

2022-02-02 13:45 UTC, Kudo commented
`expo-av@10.2.1` is published with the fix. thanks!