Add web support to expo-keep-awake
expo/expo pull request #15826
Opened 2022-01-07 00:39 UTC by EvanBacon

# Why

Reimplements https://github.com/expo/expo/pull/9467 which is stale.

# How

- `KeepAwake.activateKeepAwake` now returns a promise to accommodate web.
- Added `KeepAwake.isAvailableAsync` which returns false on certain web browsers.
- Added `KeepAwake.addListener` to observe state changes on web.

# Test Plan

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

2022-01-10 09:31 UTC, bbarthec requested changes
Looking awesome 🚀 
I just have a small remark regarding missing typings.

2022-01-10 09:31 UTC, bbarthec commented on packages/expo-keep-awake/src/ExpoKeepAwake.web.ts
> +    const wakeLock = await (navigator as any).wakeLock.request('screen');
I would rather go with polyfilling the type system with the missing typings. The very same way we do it in other modules:
https://github.com/expo/expo/blob/cd195fb2d1fd09d1d1ea8dad569065690b884a6e/packages/expo-cellular/src/ts-declarations/lib.dom.d.ts#L7-L18
and then no `as any` casting is happening:
https://github.com/expo/expo/blob/cd195fb2d1fd09d1d1ea8dad569065690b884a6e/packages/expo-cellular/src/ExpoCellular.web.ts#L20-L21

2022-01-18 22:21 UTC, brentvatne approved these changes

2022-01-18 22:21 UTC, brentvatne commented on packages/expo-keep-awake/src/index.ts
> +  return ExpoKeepAwake.addListener(tag, 'ExpoNavigationBar.didChange', _listener);
ExpoNavigationBar?

2022-01-18 22:21 UTC, brentvatne commented on packages/expo-keep-awake/src/index.ts
> +export async function activateKeepAwake(tag: string = ExpoKeepAwakeTag): Promise<void> {
maybe create new method `activateKeepAwakeAsync` then keep the old one around and add a deprecation warning?

2022-02-08 15:39 UTC, bbarthec approved these changes

2022-08-01 10:43 UTC, dvkellerman commented
Hello @EvanBacon, @brentvatne !
Do you need some help with this PR?

2023-01-11 14:52 UTC, Simek commented on packages/expo-keep-awake/src/KeepAwake.types.ts
> +  /** A callback that is invoked when the keep-awake state changes (web-only). */
```suggestion
  /** 
   * A callback that is invoked when the keep-awake state changes.
   * @platform web
   */
```

We can use the `@platform` tag here.

2023-01-12 11:22 UTC, merged