[cli] Added modules for interacting with Apple and Android platforms
expo/expo pull request #16516
Opened 2022-03-03 20:42 UTC by EvanBacon

# Why

- Split out Platform modules from https://github.com/expo/expo/pull/16160
- Pending https://github.com/expo/expo/pull/16508

# How

- Pull in all `cli/start/platforms` code from https://github.com/expo/expo/pull/16160
- Based on the `Simulator` and `Android` modules from [`xdl`](https://github.com/expo/expo-cli/tree/main/packages/xdl/src).
- Does not implement [AppleDevice](https://github.com/expo/expo-cli/blob/main/packages/xdl/src/apple/AppleDevice.ts) or [CoreSimulator](https://github.com/expo/expo-cli/blob/main/packages/xdl/src/apple/CoreSimulator.ts) beta modules. Both were still behind flags and we can pull them in later as a way to reduce the initial review complexity.
- The majority of features are implemented using cross-platform logic as a way to reduce the amount of testing required to get full coverage (unclear if this is even achieved).
- Most code is doc blocked to add design clarity.
- Most 'iOS' stuff has been renamed to 'Apple' to account for the fact that Expo supports most platforms under the Apple umbrella.

# Test Plan

- Added a lot of unit testing.
- Heavy fixtures add to the PR line count.
- No E2E is currently implemented for simulator/emulator setup.

2022-03-04 07:58 UTC, EvanBacon commented on packages/expo/cli/start/platforms/android/__tests__/emulator-test.ts
> +  startDeviceAsync: jest.fn(() => Promise.resolve()),
```suggestion
  listDevicesAsync: jest.fn(async () => []),
  startDeviceAsync: jest.fn(async () => {}),
```

2022-03-05 02:41 UTC, ide commented on packages/expo/cli/start/platforms/AppIdResolver.ts
> +export class AppIdResolver {
Add a docblock explaining this is for application identifiers like the Android application ID and Apple bundle identifier (as opposed to the EAS project ID)

2022-03-07 22:16 UTC, ide requested changes
The mockClear calls can likely be replaced with one global clearMocks setting.

2022-03-07 22:16 UTC, ide commented on packages/expo/cli/start/platforms/ios/simctl.ts
> +  }, []);
```suggestion
  return Object.values(simulatorDeviceInfo.devices).flatMap(
    (runtime) => runtime.filter((device) => device.state === 'Booted')
  );
```

2022-03-07 22:16 UTC, ide commented on packages/expo/cli/start/platforms/ios/simctl.ts
> +    if (error.message.match('Unexpected token')) {
```suggestion
    if (error.message.includes('Unexpected token')) {
```

2022-03-07 22:16 UTC, ide commented on packages/expo/cli/start/platforms/ios/simctl.ts
> +  );
```suggestion
  return Object.values(simulatorDeviceInfo.devices).flat();
```

2022-03-07 22:33 UTC, EvanBacon commented on packages/expo/cli/start/platforms/android/ADBServer.ts
> +  getAdbExecutablePath(): string {
Good suggestion, I added this as a TODO so we can keep the PR minimal.

2022-03-07 22:34 UTC, EvanBacon commented on packages/expo/cli/start/platforms/android/ADBServer.ts
> +    // await Binaries.addToPathAsync('adb');
Probably will have to move away from vendoring this since it would add a ton of bloat to each project.

2022-03-07 22:39 UTC, EvanBacon commented on packages/expo/cli/start/platforms/android/AndroidPlatformManager.ts
> +      getCustomRuntimeUrl: (props?: { scheme?: string }) => string | null;
We use "custom runtime" in a few places since this logic is generally agnostic from Expo and dev clients.

2022-03-07 22:43 UTC, EvanBacon commented on packages/expo/cli/start/platforms/android/adb.ts
> +/** Uninstall an app given its Android package name. */
adb requires the package name:
```
 uninstall [-k] PACKAGE
     remove this app package from the device
     '-k': keep the data and cache directories
```

2022-03-08 00:44 UTC, EvanBacon commented on packages/expo/cli/start/platforms/android/AndroidDeviceManager.ts
> +        )}`;
We ensure Expo Go is installed automatically so we'd probably want to assert that before running the method. Currently we never use this method for opening on Expo Go.

2022-03-08 03:23 UTC, ide approved these changes

2022-03-08 03:23 UTC, ide commented on packages/expo/cli/utils/exit.ts
> +    }
Useful to let the listener be freed if the caller holds onto the function to remove the listeners even after removing them (matters more in website programming though)

```suggestion
    if (!listener) {
      return;
    }
    for (const signal of killSignals) {
      process.off(signal, listener);
    }
    // Allow the listener to be GC'd
    listener = null;
```

2022-03-08 03:23 UTC, ide commented on packages/expo/cli/start/platforms/android/adbReverse.ts
> +  installExitHooks(() => {
Remove exit hooks when stopAdbReverseAsync is called

2022-03-08 03:23 UTC, ide commented on packages/expo/cli/start/platforms/android/ADBServer.ts
> +      }
```suggestion
      if (this.isRunning) {
        this.stopAsync();
      }
      this.removeExitHook = () => {};
```

2022-03-08 17:46 UTC, merged