Upgrade ruby from 2.7.0 to 2.7.2
expo/expo pull request #16624
Opened 2022-03-14 16:47 UTC by ajsmth

# Why

From what I can understand -- ruby 2.7.0 doesn't compile w/ arm, but ruby 2.7.2 does - here is the output from trying to install 2.7.0 on a M1 machine: 

<img width="1231" alt="Screen Shot 2022-03-14 at 9 43 44 AM" src="https://user-images.githubusercontent.com/40680668/158220344-0699dbf5-a660-4f0e-94a6-fddfb30328c6.png">

This has been a long standing issue w/ M1 Macs - I usually just manually bump this file and don't commit it with my PRs, but I figured as adoption for M1 increases this might be something we want to address 

# How

Bump the version in `ruby-version`

# Test Plan

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

2022-03-15 09:18 UTC, tsapeta approved these changes
Cool 👍 Client job on Android is failing, but it doesn't seem to be caused by Ruby upgrade. I already retried the job, but it failed too.

2022-03-15 16:26 UTC, ajsmth commented
my CI luck is always bad

2022-03-15 17:41 UTC, nicknovitski approved these changes
The latest ruby 2.7.x is 2.7.5, and it would be fine to use that, or an even newer one, as long as the tools supported it.

If we're sure that the CI failure isn't related to the change, I don't object to merging it.  But does this check fail often?

2022-03-15 18:16 UTC, tsapeta commented
Actually, at second glance I think it might be related. Take a look at the stacktrace at the end — you can find both Ruby versions in those paths 🤔

2022-03-18 19:47 UTC, nicknovitski requested changes
Then it looks like something else needs to change in the android gha workflow to support this, maybe in how it's using the setup-ruby action?  Or is fastlane itself being setup to expect the old version?

2022-05-11 21:58 UTC, ajsmth commented
seems to be fixed now?

2022-05-11 22:02 UTC, nicknovitski approved these changes
Great!

2022-05-11 22:03 UTC, merged

2022-05-11 22:05 UTC, tsapeta approved these changes
Would you mind updating to the newest 2.x version? That is `2.7.6` now. It introduces mostly just security fixes since `2.7.2`.

2022-05-11 22:05 UTC, tsapeta commented on .ruby-version
> +2.7.2
```suggestion
2.7.6

```