[iOS][BarCodeScanner] Add support for Codabar
expo/expo pull request #16703
Opened 2022-03-21 07:24 UTC by 7nohe

# Why

Added support for Codabar barcode type, since iOS SDK does not support it.

# How

I've added zxing's`ZXCodaBarReader` for scanning Codebar barcode type.

# Test Plan

- Ran the `bare-expo` project on a physical device, scanned a Codabar barcode (e.g. image from https://en.wikipedia.org/wiki/Codabar)

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

2022-03-21 13:42 UTC, bbarthec requested changes
Key @7nohe 👋 Thank you for this PR 🤩 
The code looks good, but CI is failing (https://github.com/expo/expo/runs/5625155998?check_suite_focus=true), because `AVMetadataObjectTypeCodabarCode` is not available on the iOS 🤔 I've checked the documentation and it seems this variable is added in iOS 15.4 (https://developer.apple.com/documentation/avfoundation/avmetadataobjecttypecodabarcode/), so we'll need to add some compatibility layer for older iOS versions (check [@availbale(..., ...) syntax](https://developer.apple.com/documentation/swift/objective-c_and_c_code_customization/marking_api_availability_in_objective-c)).

2022-03-24 13:44 UTC, 7nohe commented
Thank you for the review @bbarthec!
I fixed the code to support older iOS versions by using `@available()` syntax.
It seems to be working fine on the `bare-expo`, but not sure about the tests 😭

2022-04-04 13:59 UTC, bbarthec commented on packages/expo-barcode-scanner/CHANGELOG.md
> +- Added support for Codabar barcode type on iOS. ([#16703](https://github.com/expo/expo/pull/16703) by [@7nohe](https://github.com/7nohe))
```suggestion
-  On iOS 15.4+ added support for `Codabar` barcode type. ([#16703](https://github.com/expo/expo/pull/16703) by [@7nohe](https://github.com/7nohe))
```

2022-04-04 14:02 UTC, bbarthec approved these changes
It looks fine now 👍 
Thank you for taking care of this 😁

2022-04-04 14:03 UTC, merged