Update additional-resources.md
expo/expo pull request #16745
Opened 2022-03-24 20:05 UTC by Norfeldt

# Why

I had good experience with this course.

# How

N/A

# Test Plan

N/A

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

2022-05-03 18:07 UTC, Norfeldt commented
@AdamJNavarro Who needs to review this PR?

2022-08-03 20:16 UTC, amandeepmittal requested changes

2022-08-03 20:16 UTC, amandeepmittal commented on docs/pages/next-steps/additional-resources.md
> +- [ES6 by Wes Bos](https://wesbos.com/es6-for-everyone) - ES6 for Everyone! (free)
```suggestion
- [ES6 by Wes Bos](https://es6.io/) (paid)
```

Seems like the course is paid and the link is now https://es6.io/. Left a suggestion to update the changes.

2022-08-05 09:12 UTC, amandeepmittal approved these changes

2022-08-05 09:48 UTC, merged

2022-08-05 09:48 UTC, amandeepmittal commented
Thanks for the PR @Norfeldt! appreciate it 👍