[sqlite] Add `close` and `deleteAsync` method
expo/expo pull request #16831
Opened 2022-03-30 16:53 UTC by Kudo

# Why

requested from AWS Amplify to add Expo integration for the `@aws-amplify/datastore` package.

# How

- exposing `close` method publicly
- add `deleteAsync` method

# Test Plan

test-suite SQLite
  - added a `should delete db on filesystem from the `deleteAsync()` call` test case

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

2022-03-31 15:07 UTC, bbarthec requested changes
Looking good 👍 
My remarks:
- let's name all newly exposed methods following our convention with `Async` sufix
- let's make `close` method return actual promise and let's expose it as `closeAsync`
- let's add some more info to the error messages, like the name of the database that failed to be deleted

2022-03-31 15:07 UTC, bbarthec commented on packages/expo-sqlite/src/SQLite.types.ts
> +  close(): void;
```suggestion
  closeAsync(): void;
```

2022-03-31 15:07 UTC, bbarthec commented on packages/expo-sqlite/src/SQLite.ts
>      ExponentSQLite.close(this._name);
```suggestion
    return ExponentSQLite.close(this._name);
```

2022-03-31 15:07 UTC, bbarthec commented on apps/test-suite/tests/SQLite.js
> +          db.close();
```suggestion
          db.closeAsync();
```

2022-03-31 15:07 UTC, bbarthec commented on apps/test-suite/tests/SQLite.js
> +        db.close();
```suggestion
        await db.closeAsync();
```

2022-04-06 11:45 UTC, Kudo commented
> Looking good 👍 My remarks:
> 
> * let's name all newly exposed methods following our convention with `Async` sufix
> * let's make `close` method return actual promise and let's expose it as `closeAsync`
> * let's add some more info to the error messages, like the name of the database that failed to be deleted

thanks for the super great review comment 🤩

2022-04-11 08:50 UTC, bbarthec reviewed
Looking very good 👍 
I've looked into the error messages once more 👀

2022-04-11 08:50 UTC, bbarthec commented on packages/expo-sqlite/android/src/main/java/expo/modules/sqlite/SQLiteModule.kt
> +      promise.reject(errorCode, "Unable to delete opened database '$dbName'")
```suggestion
      promise.reject(errorCode, "Unable to delete database '$dbName' that is currently open. Close it prior to deletion.")
```

2022-04-11 08:50 UTC, bbarthec commented on packages/expo-sqlite/android/src/main/java/expo/modules/sqlite/SQLiteModule.kt
> +      promise.reject(errorCode, "Database not found")
```suggestion
      promise.reject(errorCode, "Database '$dbName' not found")
```

2022-04-11 08:50 UTC, bbarthec commented on packages/expo-sqlite/android/src/main/java/expo/modules/sqlite/SQLiteModule.kt
> +      promise.reject(errorCode, "Unable to delete the database file")
```suggestion
      promise.reject(errorCode, "Unable to delete the database file for '$dbName' database")
```

2022-04-11 08:50 UTC, bbarthec commented on packages/expo-sqlite/ios/EXSQLite/EXSQLite.m
> +      reject(errorCode, [NSString stringWithFormat:@"Unable to delete opened database '%@'", dbName], nil);
```suggestion
      reject(errorCode, [NSString stringWithFormat:@"Unable to delete database '%@' that is currently open. Close is prior to deletion.", dbName], nil);
```

2022-04-11 08:50 UTC, bbarthec commented on packages/expo-sqlite/ios/EXSQLite/EXSQLite.m
> +    reject(errorCode, @"Database not found", nil);
```suggestion
    reject(errorCode, [NSString stringWithFormat:@"Database '%@' not found", dbName], nil);
```

2022-04-11 08:50 UTC, bbarthec commented on packages/expo-sqlite/ios/EXSQLite/EXSQLite.m
> +    reject(errorCode, @"Unable to delete the database file", error);
```suggestion
    reject(errorCode, [NSString stringWithFormat:@"Unable to delete the database file for '%@' database", dbName], error);
```

2022-04-11 08:50 UTC, bbarthec commented on packages/expo-sqlite/src/SQLite.ts
> +      throw new Error('Unable to delete an opening database');
```suggestion
      throw new Error(`Unable to delete '${this._name}' database that is currently open. Close it prior to deletion.`);
```

2022-04-11 08:50 UTC, bbarthec commented on packages/expo-sqlite/src/SQLite.types.ts
> +   * Delete the database file.
```suggestion
   * Delete the database file.
   * > The database has to be closed prior to deletion.
```

2022-04-11 13:04 UTC, bbarthec approved these changes
Superb work 👏

2022-04-11 16:00 UTC, merged