[expotool] add rn version option to generate-bare-app
expo/expo pull request #16978
Opened 2022-04-08 21:12 UTC by ajsmth

# Why

The current iteration of this tool manually sets the version of react-native based on whatever is specified in `resolutions` of our monorepo - its likely that people will want to be able to use other versions of RN to test functionality as well

# How

Added `--rnVersion` option which takes a string that specifies which version of RN to install in the bare app

# Test Plan

Specify rnVersion, verify that this version is installed in a generated app

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

2022-04-09 23:41 UTC, tsapeta requested changes

2022-04-09 23:41 UTC, tsapeta commented on tools/src/commands/GenerateBareApp.ts
> +    rnVersion = rnVersionOnMain
It's a bad practice to reassign function arguments. It's better to move resolving the version to a separate function, like this:
```javascript
function getLocalReactNativeVersion() {
  const mainPkg = require(path.resolve(EXPO_DIR, 'package.json'));
  return mainPkg.resolutions?.['react-native'];
}
// and then
const reactNativeVersion = rnVersion || getLocalReactNativeVersion();
```

2022-04-09 23:41 UTC, tsapeta commented on tools/src/commands/GenerateBareApp.ts
> +    const rnVersionOnMain = mainPkg.resolutions['react-native'];
We can't assume the `resolutions` object is there 😉 
```suggestion
    const rnVersionOnMain = mainPkg.resolutions?.['react-native'];
```

2022-04-12 07:16 UTC, tsapeta approved these changes

2022-04-14 08:07 UTC, bbarthec approved these changes

2022-04-20 15:37 UTC, merged