[docs] don't highlight empty tooltips in code
expo/expo pull request #16985
Opened 2022-04-09 17:21 UTC by kbrandwijk

# Why

Code annotated with `@info`, but without a description, renders an empty tooltip. This change hides the tooltip.

# How

# Test Plan

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

2022-04-11 16:46 UTC, Simek requested changes
Unfortunately, after testing the code locally, it looks like the fix do not work and removing `data-tippy-content` is not enough.

But it looks like we can switch approach and add another class to the Tippy handler, which provides an easy fix (sorry for the screenshot, but you cannot suggest changes on unmodified lines):
<img width="909" alt="Screenshot 2022-04-11 at 18 37 38" src="https://user-images.githubusercontent.com/719641/162789718-29429df1-6f1b-4e12-8506-24a03929ff5e.png">

P.S. Let me know if you need any help with running website locally.

2022-04-11 16:52 UTC, Simek commented
Also it would be nice to move `:hover` effect (opacity & cursor change) to selector with the `.with-message` class.

2022-04-24 11:48 UTC, kbrandwijk commented
Sorry, this one got overlooked. Thank you for your patience :)

2022-04-24 14:41 UTC, Simek approved these changes
No problem, thank you for the updates, LGTM! 🙂

2022-04-24 17:41 UTC, merged