@eric/eng 267 tests
expo/expo pull request #17151
Opened 2022-04-20 23:13 UTC by esamelson

# Why

# How

# Test Plan

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

2022-04-21 08:28 UTC, tsapeta approved these changes

2022-04-22 08:16 UTC, ide requested changes

2022-04-25 22:18 UTC, esamelson commented on packages/expo-updates/e2e/__tests__/Updates-e2e-android.test.ts
> +    createdAt: new Date().getTime(),
ah, thank you, good catch

2022-04-25 22:19 UTC, esamelson commented on .github/workflows/updates-e2e.yml
> +        run: echo "{\"name\":\"updates-e2e\",\"runtimeVersion\":\"1.0.0\",\"plugins\":[\"expo-updates\"],\"android\":{\"package\":\"dev.expo.updatese2e\"},\"ios\":{\"bundleIdentifier\":\"dev.expo.upd
Actually, 10.0.2.2 is a special IP address that Android emulators always map to localhost on the host machine, so it should work regardless of the test runner's network config: https://developer.android.com/studio/run/emulator-networking. Will add a comment about this in one of the other PRs.

2022-04-26 00:13 UTC, ide approved these changes

2022-04-26 00:21 UTC, merged