Notifications topic subscribe
expo/expo pull request #17674
Opened 2022-05-28 15:09 UTC by mmomtchev

# Why

Firebase topics are a very commonly used feature in smaller-scale Android apps. They allow subscribing to special broadcast ids, called *topics* for sending a single push notifications to all subscribed devices. The feature does not have an iOS equivalent (AFAIK) - which is probably the reason it was absent from expo.

As smaller applications are the bread and butter of expo, this will also allow you, once you get everyone hooked on *topics*, to implement this in your server for iOS - it will be a unique Apple feature that could incite people to switch to expo.

The feature is frequently mentioned in issues, that last one is here:
https://github.com/expo/expo/issues/13949

# How

It is a Java one-liner - `FirebaseMessaging.getInstance().subscribeToTopic(topic)`

# Test Plan

Alas, Firebase is currently not really unit-tested - this will require to set up infrastructure

edit(vonovak): this relies on firebase, so I tested it manually from firebase console. Unfortunately we don't have automation for this type of thing.

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

2022-06-01 19:06 UTC, mmomtchev commented
@tsapeta, is the Android failure a problem on my end?

2022-06-06 08:18 UTC, tsapeta approved these changes
@mmomtchev Great work! Congrats on making your first contribution 👏

> is the Android failure a problem on my end?

It's not related to your changes so don't worry 😉 This failure is one of the most common intermittent issue in Detox 😅

2022-06-08 11:20 UTC, Kudo commented
thanks for the nice contribution. do you mind to share how you test the topic notifications? if it's feasible, i would like to have some test in our [test workflows](https://github.com/expo/expo/blob/main/apps/test-suite/tests/Notifications.js) and make sure the function works well.

2022-06-08 11:52 UTC, Kudo commented
thanks @mmomtchev! let me figure out how to integrate this to our test code.

2023-08-22 03:40 UTC, bitlab-code commented
> thanks @mmomtchev! let me figure out how to integrate this to our test code.

Hi,
any news about this?

2023-08-28 09:03 UTC, mmomtchev commented
https://firebase.google.com/docs/cloud-messaging/send-message#send-messages-to-topics

2024-08-26 10:04 UTC, davlasq commented
What about this? Why it's not merged?

2025-05-28 11:26 UTC, Pradeet commented
Hi, Why is this not merged?

2025-12-11 11:31 UTC, vonovak approved these changes

2025-12-11 11:38 UTC, vonovak commented
@mmomtchev thank you for your PR and I'm really sorry for the wait.

We probably won't make it to the newspapers but I think there will be a mention of this in the changelog soon! 🚀

2026-01-06 10:49 UTC, amandeepmittal requested changes

2026-01-06 10:49 UTC, amandeepmittal commented on packages/expo-notifications/src/topicSubscription.ts
> + * @return A Promise which resolves to `null` once the device is subscribed to the topic.
```suggestion
 * @return a Promise which resolves to `null` once the device is subscribed to the topic.
```

This is prefixed as "Returns A ...". So lets update it so that it becomes "Returns a ..."

2026-01-06 10:49 UTC, amandeepmittal commented on packages/expo-notifications/src/topicSubscription.ts
> + * @return A Promise which resolves to `null` once the device is unsubscribed from the topic.
```suggestion
 * @return a Promise which resolves to `null` once the device is unsubscribed from the topic.
```

2026-01-06 11:09 UTC, amandeepmittal approved these changes

2026-01-06 12:03 UTC, merged