[constants] fix ExpoClient config types
expo/expo pull request #18030
Opened 2022-06-29 12:11 UTC by Simek

# Why

Refs:
* #17865
* https://github.com/expo/expo-cli/blob/main/packages/config/src/Config.types.ts#L89

# How

This PR changes the `ExpoConfig` type with `ExpoClientConfig` type in the `ManifestExtra`.

`ExpoClientConfig` is just an extension of `ExpoConfig` as seen in the reference from the CLI repo above.

# Test Plan

Home app CI should pass without the failure.

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

2022-06-29 14:05 UTC, bbarthec approved these changes

2022-06-30 21:02 UTC, wschurman requested changes
This type change actually found a bug in the home app! `publishedTime` doesn't exist in `manifest2`. I'll fix this in a separate PR.

2022-06-30 21:15 UTC, Simek commented
@wschurman Can we close this PR then, or there are still some changes that need to be made to the Constants package?

2022-06-30 21:19 UTC, wschurman commented
@Simek feel free to close this one. See https://github.com/expo/expo/pull/18061.

2022-06-30 21:20 UTC, closed without merging