Update document-picker.md
expo/expo pull request #18514
Opened 2022-08-05 08:58 UTC by StCyr

# Why

A configuration step is missing to get the DocumentPicker working in managed workflows.

See also https://forums.expo.dev/t/build-issue-after-enabling-the-icloud-application-service/65490/7

# How

# Test Plan

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

2022-08-19 12:15 UTC, amandeepmittal commented on docs/pages/versions/unversioned/sdk/document-picker.md
> +- Define a plugin in your `app.json` file to define a `iCloudContainerEnvironment` entitlement for your app:
- Add `expo-document-picker` [config plugin](/guides/config-plugins/) in **app.json** or **app.config.js** and pass `iCloudContainerEnvironment` entitlement as an option to the plugin:

2022-08-19 12:16 UTC, amandeepmittal commented on docs/pages/versions/unversioned/sdk/document-picker.md
> +```
```suggestion
```json
{
  "plugins": [
    [
      "expo-document-picker",
      {
        "iCloudContainerEnvironment": "Development | Production"
      }
    ]
  ]
}
```
```

The code block doesn't format as per the docs guidelines.

2022-08-19 12:16 UTC, amandeepmittal commented on docs/pages/versions/unversioned/sdk/document-picker.md
```suggestion

In the above snippet, `iCloudContainerEnvironment` takes either `Development` or `Production` as the value depending on which environment you create the iCloud container.

```

2022-08-19 12:17 UTC, amandeepmittal commented on docs/pages/versions/unversioned/sdk/document-picker.md
> +- Define a plugin in your `app.json` file to define a `iCloudContainerEnvironment` entitlement for your app:
```suggestion
- Add `expo-document-picker` [config plugin](/guides/config-plugins/) in **app.json** or **app.config.js** and pass `iCloudContainerEnvironment` entitlement as an option to the plugin:
```

2022-08-19 12:18 UTC, amandeepmittal commented on docs/pages/versions/unversioned/sdk/document-picker.md
> +
```suggestion
{
  "plugins": [
    [
      "expo-document-picker",
      {
        "iCloudContainerEnvironment": "Development | Production"
      }
    ]
  ]
}
```

2022-08-19 12:20 UTC, amandeepmittal requested changes
Thanks for creating this PR @StCyr!

Added some suggestions to improve and explain that 
- explains to add the library's config plugin 
- links to config plugin docs
- iCloudContainerEnvironment contains two values, let's add both of them with an explanation to whichever environment the developer is using in their app, they choose from one of those.
  - Refs: [Apple Docs](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_icloud-container-environment) & [Config plugin](https://github.com/expo/expo/blob/3ee85c4a2005d3da41669ce3346cd5ba27e277e5/packages/expo-document-picker/plugin/src/withDocumentPickerIOS.ts#L11)
- Format the code snippet to follow docs style guidelines.

2022-10-18 19:44 UTC, Simek commented
Oh, it looks like this has been addressed already in #18903, so I'm going to close this one, thank you for the contribution anyway!

2022-10-18 19:44 UTC, closed without merging