Improve doc
expo/expo pull request #18522
Opened 2022-08-05 15:59 UTC by BrodaNoel

# Why
Fix https://github.com/expo/expo/issues/18521

2022-08-06 03:01 UTC, brentvatne approved these changes

2022-08-06 03:01 UTC, brentvatne commented on docs/pages/guides/using-sentry.md
>  Sentry.Native.*
```suggestion
// Sentry.Native.*
```

2022-08-06 03:01 UTC, brentvatne commented on docs/pages/guides/using-sentry.md
>  Sentry.Browser.*
```suggestion
// Sentry.Browser.*
```

2022-08-06 03:01 UTC, brentvatne commented on docs/pages/guides/using-sentry.md
> +#### Config
```suggestion
#### Configuration
```

2022-08-06 03:10 UTC, BrodaNoel commented
@brentvatne done

2022-08-06 06:09 UTC, kbrandwijk requested changes

2022-08-06 06:09 UTC, kbrandwijk commented on docs/pages/guides/using-sentry.md
> +Depending on which platform you are (mobile or web), use the following functions in order to capture/catch exceptions:
```suggestion
Depending on which platform you are on (mobile or web), use the following functions in order to capture/catch exceptions:
```

2022-08-06 06:09 UTC, kbrandwijk commented on docs/pages/guides/using-sentry.md
> +Depending on which platform you are (mobile or web), use the following functions in order to capture/catch exceptions:
Aside from that, you are not listing functions, so 'the following functions' doesn't really apply. Also, those functions are not _just_ for capturing/catching exceptions, there's methods in there for instrumentation, performance, etc. so a more generic description would be better here.

2022-08-07 07:29 UTC, amandeepmittal commented on docs/pages/guides/using-sentry.md
>  Add the following to your app's main file (usually `App.js`):
```suggestion
Add the following to your app's main file such as **App.js**:
```

Unrelated to your PR, here is a small change to [bold the filenames as per Expo's writing style guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md).

2022-08-07 07:35 UTC, amandeepmittal commented on docs/pages/guides/using-sentry.md
> +Depending on which platform you are on (mobile or web), use the following functions in order to capture/catch exceptions:
```suggestion
Depending on which platform you are on (mobile or web), use the following functions to access any `@sentry/*` exports for instrumentation, performance, and so on:

- For React Native, access any `@sentry/react-native` exports with `Sentry.Native.*`
- For web, access any `@sentry/browser` exports with `Sentry.Browser.*`
```

As per Kim's suggestion, let's be more verbose about accusing any exports from `@sentry` packages.

2022-08-07 07:40 UTC, amandeepmittal commented on docs/pages/guides/using-sentry.md
>  ```
The example then, could be written as:

The following example uses `captureException()` from `Sentry.Native.*` to capture errors:

```js
try {
  // your code
} catch (error) {
  Sentry.Native.captureException(error);
}
```

2022-08-07 07:41 UTC, amandeepmittal commented on docs/pages/guides/using-sentry.md
>  ### Step 3: App Config
```suggestion
### Step 3: App Configuration
```

Let's also change `Config` here from `Configuration` for consistent writing.

2022-08-07 07:43 UTC, amandeepmittal requested changes
Here are some suggestions based on your changes to improve the doc and follow some of our Writing Style guide for consistency.

2022-08-10 04:02 UTC, BrodaNoel commented
Changes applied.
Anything else I could fix?
I'm not an english native speaker, so, if there is some working that "should be improved", please provide me the exact correct phrase because what I wrote was my best attempt :P

2022-08-10 06:59 UTC, amandeepmittal approved these changes
Everything looks great! Thanks for improving this doc @BrodaNoel 👍

2022-08-10 09:07 UTC, kbrandwijk approved these changes

2022-08-10 09:07 UTC, merged