Allow continued recording
expo/expo pull request #1887
Opened 2018-06-18 15:17 UTC by flippinjoe

Currently the camera component just creates a new path to record to on every `record`.  This does not allow for a "pause" functionality.  This PR adds the ability to pass a "path" param into the record options which will be used for the recording output instead of a new file

2018-07-23 17:52 UTC, maxence-lefebvre commented
Hi ! How about a ternary operator ?

2018-10-09 12:05 UTC, bbarthec commented
Hello @flippinjoe! I kinda don't like passing `path` parameter as you're suggesting. Let's go with `pauseAsync` and `resumeAsync`. Moreover you're providing no validation for this `path` parameter. And what about Android side and some documentation?

2018-10-09 12:07 UTC, bbarthec requested changes
Hello @flippinjoe! I kinda don't like passing path parameter as you're suggesting. Let's go with `pauseAsync` and `resumeAsync`. Moreover you're providing no validation for this `path` parameter. And what about Android side and some documentation?

2019-05-20 21:45 UTC, tsapeta commented
@bbarthec could you add such feature into your reworked camera component? this seems like a nice thing to have there 💪 
Anyway, I'm closing this due to inactivity.

2019-05-20 21:45 UTC, closed without merging