feat(docs): clean up app transfer docs
expo/expo pull request #18968
Opened 2022-09-03 16:27 UTC by EvanBacon

# Why

- follow up on "further work" from https://github.com/expo/expo/pull/18926

# How

Utilizing @brentvatne's feedback I deleted most of the extraneous info, then I realized we should just link to the actual guide in our docs.

2022-09-03 20:50 UTC, brentvatne requested changes

2022-09-03 20:50 UTC, brentvatne commented on docs/pages/distribution/app-transfers.md
> +Universal apps using EAS have two parts:
```suggestion
There are two different representations of your app to consider when handing over ownership to another entity: the app as it exists on Expo Application Services (in order to create builds with EAS Build, send updates with EAS Update, etc.) and the app records on the Apple App Store / Google Play Store (in order to distribute the app to end-users). The following guides explain how to handle app transfers in each of these cases.
```

2022-09-03 20:50 UTC, brentvatne commented on docs/pages/distribution/app-transfers.md
> +2. [Native runtime](/workflow/glossary-of-terms#native-runtime) hosted in the respective app stores. Used for rendering the static hosted assets.
```suggestion
```

2022-09-03 20:50 UTC, brentvatne commented on docs/pages/distribution/app-transfers.md
> +Learn more in the official guides for each:
```suggestion
```

2022-09-04 20:59 UTC, amandeepmittal approved these changes
Left a small change to follow our styleguide. Rest looks good to me 👍

2022-09-04 20:59 UTC, amandeepmittal commented on docs/pages/distribution/app-transfers.md
> +There are two different representations of your app to consider when handing over ownership to another entity: the app as it exists on Expo Application Services (in order to create builds with EAS Bu
```suggestion
There are two different representations of your app to consider when handing over ownership to another entity: the app as it exists on Expo Application Services (to create builds with EAS Build, send updates with EAS Update, etc.) and the app records on the Apple App Store/Google Play Store (to distribute the app to end-users). The following guides explain how to handle app transfers in each case.
```

As per our style guide, let's [avoid adding spaces before and after `/`](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md#do-not-add-a-space-between-the-words-and-).

2022-09-06 17:21 UTC, merged