Update documentation page for expo-updates
expo/expo pull request #19408
Opened 2022-10-05 07:15 UTC by ddeath

Adding references to more detailed information and adding missing configuration reference

# Why

I was playing with expo-updates as an alternative to codepush because I wanted to have a custom update server (because of compliance issues) and my experience could be better if documentation was clearly stated it is possible and linking example implementation.

Also documentation was missing configuration options. It is weird experience to be looking at documentation and not having the information there - I had to visit multiple pages & repos to have complete information...

# How

Mostly copy-paste from readme of expo-updates

# Test Plan
Ideally some native english speaker will read the update and correct possible mistakes

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

2022-10-21 13:24 UTC, amandeepmittal requested changes
Hey @ddeath!
Thanks for updating this doc 🙌 These changes look good!

Left some suggestions to improve readability and match our writing style guide. Let me know if anything is unclear 👍

2022-10-21 13:24 UTC, amandeepmittal commented on docs/pages/versions/unversioned/sdk/updates.mdx
> +Some build-time configuration options are available to configure the behavior of `expo-updates`. On iOS, these properties are set as keys in `Expo.plist` and on Android as `meta-data` tags in `Androi
```suggestion
Some build-time configuration options are available to configure the behavior of `expo-updates`. 

On Android, these options are set as `meta-data` tags adjacent to the tags added during installation in the **AndroidManifest.xml** file. You can also define these options at runtime by passing a `Map` as the second parameter of `UpdatesController.initialize()`, and the provided values will override any value specified in **AndroidManifest.xml**.

On iOS, these properties are set as keys in **Expo.plist** file. You can also set them at runtime by calling `[UpdatesController.sharedInstance setConfiguration:]` at any point before calling `start` or `startAndShowLaunchScreen`, and the values in this dictionary will override any values specified in **Expo.plist**.
```

I've updated this section to the following guidelines from our writing style guide:
- [Filenames as bold text](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md#filenames-as-bold-text) such as for **Expo.plist**.
- [Referencing Android before iOS](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md#referencing-android-ios-and-web)


The text was a bit hard to read so as per the second guideline I divided into sub-parts for both Android and iOS.
- The phrase ", and when provided the values..." seemed it was missing something. Changed it to " and the provided values will override any ..." for now but let me know or feel free to update if you originally meant something else by it.

2022-10-21 13:24 UTC, amandeepmittal commented on docs/pages/versions/unversioned/sdk/updates.mdx
> +| `EXUpdatesConfigCodeSigningAllowUnsignedManifests` | `codeSigningAllowUnsignedManifests` | `expo.modules.updates.CODE_SIGNING_ALLOW_UNSIGNED_MANIFESTS` | false | ❌        |
```suggestion
| iOS plist/dictionary key | Android Map key | Android meta-data name         | Default | Required? |
|--------------------------|---------------- | ------------------------------ | ------- | --------- |
| `EXUpdatesEnabled`       | `enabled`       | `expo.modules.updates.ENABLED` | `true`  | ❌        |
| `EXUpdatesURL`           | `updateUrl`     | `expo.modules.updates.EXPO_UPDATE_URL` | (none)  | ✅        |
| `EXUpdatesRequestHeaders`| `requestHeaders`| `expo.modules.updates.UPDATES_CONFIGURATION_REQUEST_HEADERS_KEY` | (none)  | ❌        |
| `EXUpdatesSDKVersion`    | `sdkVersion`    | `expo.modules.updates.EXPO_SDK_VERSION` | (none)  | (exactly one of `sdkVersion` or `runtimeVersion` is required, Required for apps hosted on Expo's server) |
| `EXUpdatesRuntimeVersion` | `runtimeVersion` | `expo.modules.updates.EXPO_RUNTIME_VERSION` | (none)  | (exactly one of `sdkVersion` or `runtimeVersion` is required) |
| `EXUpdatesReleaseChannel` | `releaseChannel` | `expo.modules.updates.EXPO_RELEASE_CHANNEL` | `default` | ❌        |
| `EXUpdatesCheckOnLaunch` | `checkOnLaunch` | `expo.modules.updates.EXPO_UPDATES_CHECK_ON_LAUNCH` | `ALWAYS` (`ALWAYS`, `NEVER`, `WIFI_ONLY`, `ERROR_RECOVERY_ONLY`)| ❌        |
| `EXUpdatesLaunchWaitMs`  | `launchWaitMs`  | `expo.modules.updates.EXPO_UPDATES_LAUNCH_WAIT_MS` | `0`     | ❌        |
| `EXUpdatesCodeSigningCertificate` | `codeSigningCertificate` | `expo.modules.updates.CODE_SIGNING_CERTIFICATE`    | (none)  | ❌        |
| `EXUpdatesCodeSigningMetadata`    | `codeSigningMetadata`    | `expo.modules.updates.CODE_SIGNING_METADATA`       | (none)  | ❌        |
| `EXUpdatesCodeSigningIncludeManifestResponseCertificateChain` | `codeSigningIncludeManifestResponseCertificateChain` | `expo.modules.updates.CODE_SIGNING_INCLUDE_MANIFEST_RESPONSE_CERTIFICATE_CHAIN` | false | ❌        |
| `EXUpdatesConfigCodeSigningAllowUnsignedManifests` | `codeSigningAllowUnsignedManifests` | `expo.modules.updates.CODE_SIGNING_ALLOW_UNSIGNED_MANIFESTS` | false | ❌        |
```

[We avoid using emojis in the docs](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md#do-not-use-emojis). For ❌ or ✅, I'd suggest replacing them with `<NoIcon />` and `<YesIcon />`. You can import them from [here](https://github.com/expo/expo/blob/938dd541005773f1ece1d8a2d7bd34c20fc55ffb/docs/ui/components/DocIcons/index.ts).

2022-10-21 13:26 UTC, amandeepmittal commented on docs/pages/versions/unversioned/sdk/updates.mdx
> +For detailed explanation check expo-updates [README.md](https://github.com/expo/expo/blob/main/packages/expo-updates/README.md)
```suggestion
For detailed explanation see [expo-updates](https://github.com/expo/expo/blob/main/packages/expo-updates/README.md) repository.
```

2022-10-24 06:46 UTC, ddeath commented
Thank you @amandeepmittal . Updated PR as per suggestions.

2022-10-25 09:46 UTC, amandeepmittal approved these changes

2022-10-26 06:55 UTC, jonsamp reviewed
Thanks for adding this extra documentation. After some wording alterations, I think we should merge this @amandeepmittal

2022-10-26 06:55 UTC, jonsamp commented on docs/pages/versions/unversioned/sdk/updates.mdx
> +### Using expo-updates with a private server
```suggestion
### Using expo-updates with a custom server
```
We use "custom" to describe this, so updating this wording

2022-10-26 06:55 UTC, jonsamp commented on docs/pages/versions/unversioned/sdk/updates.mdx
> +There is a requirement for every private server to implement [Expo Updates protocol](https://docs.expo.dev/technical-specs/expo-updates-0/).
```suggestion
Every custom updates server must implement the [Expo Updates protocol](https://docs.expo.dev/technical-specs/expo-updates-0/).
```

2022-10-26 06:55 UTC, jonsamp commented on docs/pages/versions/unversioned/sdk/updates.mdx
> +You can find an example implementation of a private server and an app using that server in the [custom-expo-updates-server](https://github.com/expo/custom-expo-updates-server) repository.
```suggestion
You can find an example implementation of a custom server and an app using that server in the [custom-expo-updates-server](https://github.com/expo/custom-expo-updates-server) repository.
```

2022-10-26 06:55 UTC, jonsamp commented on docs/pages/versions/unversioned/sdk/updates.mdx
> +Some build-time configuration options are available to configure the behavior of `expo-updates`.
```suggestion
There are build-time configuration options that control the behavior of `expo-updates`. 
```

2022-10-26 06:55 UTC, jonsamp commented on docs/pages/versions/unversioned/sdk/updates.mdx
> +For detailed explanation, see [`expo-updates`](https://github.com/expo/expo/blob/main/packages/expo-updates/README.md) repository.
```suggestion
For a detailed explanation, see the [`expo-updates`](https://github.com/expo/expo/blob/main/packages/expo-updates/README.md) repository.
```

2022-10-26 07:21 UTC, merged