[docs][packages] fix typo in setmented-control
expo/expo pull request #19565
Opened 2022-10-16 07:22 UTC by shrekuu

# Why

# How

# Test Plan

# Checklist

- [✅ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ✅] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ✅] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

2022-10-16 09:54 UTC, amandeepmittal requested changes
Hey @shrekuu, thanks for catching this and opening a PR. 
Can you please apply these changes and [update SDK versions of this page](https://github.com/expo/expo/tree/main/docs#a-note-about-versioning)?

2022-10-16 12:02 UTC, shrekuu commented
@amandeepmittal Oh I see. Let me try.

2022-10-16 21:02 UTC, amandeepmittal commented
@shrekuu, just a tip: you can copy/paste the changes in other SDK versions 😄

2022-10-21 12:35 UTC, amandeepmittal approved these changes

2022-10-21 12:36 UTC, merged