feat(repo): use better xcodebuild logging for updates-e2e test
expo/expo pull request #19738
Opened 2022-10-27 21:42 UTC by EvanBacon

# Why

- xcodebuild outputs a ridiculous amount of logging by default, this makes it hard to inspect what went wrong in GitHub console.

# How

- use `@expo/xcpretty` to format logs the same way we do in Expo CLI and EAS Build.
- use `create-expo-app` instead of `expo init`.
- make it a bit easier to re-run the test locally.

# Test Plan

- runs locally, will see how it does in CI

2022-10-27 22:11 UTC, wschurman approved these changes

2022-10-28 17:16 UTC, douglowder requested changes
I'm still not able to complete the setup script locally with these changes. I did have one code suggestion that at least for me gets past prebuild -- still seeing pod install fail, but that might be just my local setup. I'll keep investigating.

2022-10-28 17:16 UTC, douglowder commented on packages/expo-updates/e2e/__tests__/setup/project.js
> +  await spawnAsync(localCliBin, ['prebuild', '--template', localTemplatePathName], {
```suggestion
  await spawnAsync('npx', ['expo', 'prebuild', '--template', localTemplatePathName], {
```

2022-10-28 19:57 UTC, douglowder commented on packages/expo-updates/e2e/__tests__/setup/project.js
> +  await spawnAsync(localCliBin, ['prebuild', '--template', localTemplatePathName], {
Actually cancel this code suggestion, I figured out what the real problem is. The old global Expo CLI is still being used in several places in the setup.

2022-10-29 08:28 UTC, douglowder approved these changes

2022-10-29 08:57 UTC, douglowder commented on packages/expo-updates/e2e/__tests__/setup/project.js
> +  await spawnAsync(localCliBin, ['prebuild', '--template', localTemplatePathName], {
Ok @EvanBacon it looks like there were a few unrelated issues in the E2E flow :) I've added a few more commits and it is now working, so you can go ahead and merge. Thanks very much for this, the formatted logs are a lot better!

2022-10-30 17:35 UTC, merged