Updates uuid/v4 import to new format & upgrades package where necessary
expo/expo pull request #20013
Opened 2022-11-11 22:47 UTC by peterpme

# Why

After reading the [Expo Monorepo docs ](https://docs.expo.dev/guides/monorepos/)and setting `config.resolver.disableHierarchicalLookup = true;`, I wasn't able to successfully build our app anymore.

The error was `uuid/v5` not found. I'm using a newer version of `uuid` which metro is resolving.

`require("uuid/v5")` [has been removed in v7](https://github.com/uuidjs/uuid#default-export-removed)

The file I need working is `packages/expo/src/environment/getInstallationIdAsync.ts` but after searching your codebase, there were only 3 places where `uuid/v4` or `uuid/v5` were being used, so I updated those as well.

# How

- Updates import
- Upgrades package (where necessary)

# Test Plan

- Updated the import directly in node_modules
- Restarted Expo server
- Success

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

Thank you!

2022-11-14 15:49 UTC, wschurman requested changes
Change looks good. You'll need to run `et cp` on the changed packages to regenerate the built JS (to fix CI):
```
et cp expo-updates
et cp expo
```

2022-11-14 18:50 UTC, peterpme commented
Hi @wschurman,

Thank you for your help! I ran the commands, but unfortunately no updated js was built. There's nothing to commit, unless I'm missing something. Thanks!

```
~/Projects/expo @peterpme/update-uuid-library
❯ ./bin/expotools cp expo-updates
🔍 Checking expo-updates package
🏃‍♀️ Running yarn clean
🏃‍♀️ Running yarn build
🏃‍♀️ Running yarn test --watch false --passWithNoTests
🏃‍♀️ Running yarn lint --max-warnings 0
✨ expo-updates checks passed
🔌 Checking expo-updates plugin
🏃‍♀️ Running yarn clean plugin
🏃‍♀️ Running yarn build plugin
🏃‍♀️ Running yarn test plugin --watch false --passWithNoTests
🏃‍♀️ Running yarn lint plugin --max-warnings 0
✨ expo-updates checks passed

🏁 All packages passed.
```

```
~/Projects/expo @peterpme/update-uuid-library
❯ ./bin/expotools cp expo
🔍 Checking expo package
🏃‍♀️ Running yarn clean
🏃‍♀️ Running yarn build
🏃‍♀️ Running yarn test --watch false --passWithNoTests
🏃‍♀️ Running yarn lint --max-warnings 0
✨ expo checks passed

🏁 All packages passed.
```

2022-11-24 23:10 UTC, KingDoxik commented
Is there any update on this? @wschurman This is somewhat critical for our project and would love to see this merged as soon as possible.

2022-11-24 23:58 UTC, wschurman commented
Closed via https://github.com/expo/expo/pull/20211. (I didn't have permissions to push to @peterpme's branch).

2022-11-24 23:58 UTC, closed without merging

2022-11-28 17:05 UTC, wschurman commented
This was reverted unfortunately. https://github.com/expo/expo/pull/20211#issuecomment-1327669047