[modules][ios] Fix: Repeated requests for iOS notification permissions #20072
expo/expo pull request #20086
Opened 2022-11-17 09:50 UTC by below

# Why

On iOS, the permissions for Notification can be requested with a set of [options](https://developer.apple.com/documentation/usernotifications/unauthorizationoptions). The most common ones are to display alerts or play sounds, but they can also enable notifications on CarPlay displays, or enable critical alerts. Over the course of its lifetime, an app may introduce aditional capabilities, such as critical alerts or other, newly introduced iOS features and thus, must call `requestAuthorization(options:completionHandler:)` again with a new set of options. Expo Notifications supports all these [options](https://docs.expo.dev/versions/latest/sdk/notifications/#requestpermissionsasyncrequest-notificationpermissionsrequest-promisenotificationpermissionsstatus) for  `requestPermissionsAsync`.

The issue is, that after an app is newly installed on a device, the first call to `Notification.requestPermissionsAsync` will prompt the user, and set the given options. **However, subsequent calls will have no effect.** This means, for the user to take advantage of new features, they will have to de-install and re-install the app, which is completely unacceptable.

The root of the problem can be found in [EXPermissionsService.m:111](https://github.com/expo/expo/blob/168ee43f71f005baa11edf98e518593443e1807a/packages/expo-modules-core/ios/Services/Permissions/EXPermissionsService.m#L111):

```objc
  BOOL isGranted = [EXPermissionsService statusForPermission:permission] == EXPermissionStatusGranted;
  permission[@"granted"] = @(isGranted);

  if (isGranted) {
    return onResult(permission);
  }

  [self askForGlobalPermissionUsingRequesterClass:requesterClass
                                     withResolver:onResult
                                     withRejecter:reject];
```

This means that permissions are only ever requested again if permission has not previously been granted. This however **does not consider different options**, but only if any sort of notification permissions have been granted. This means that if previously only Alerts have been requested, a new request for Alerts and Sounds will be ignored.

# How

On iOS, it is perfectly acceptable to call `requestAuthorization(options:completionHandler:)` repeatedly:
> subsequent calls to this method (even with different options do not prompt the user again.

It is best practice on iOS to call this method liberally (e.g. at every startup), and the performance hit should not be different from getting the permission status.

Also not that several tutorials suggest to check the permission status first, and then requesting it. This is — at least for iOS — not advisable.

Therefore the method `askForPermissionUsingRequesterClass` was removed entirely, and instead the name and signature for the method `askForGlobalPermissionUsingRequesterClass` was changed appropriately.

# Test Plan

This was tested with my [test app](https://github.com/below/ExpoNotificationIssue).

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

2022-11-21 10:08 UTC, lukmccall requested changes
Hi @below, thanks for your contribution. You did a great job. Unfortunately, I can't merge that, because it will break Expo Go. I'll try to develop a better fix that can be applied to the bare project and in the Expo Go. Sorry for the inconvenience.

2022-11-21 10:29 UTC, below commented
@lukmccall Thank for the review! Would you mind pointing me somewhere to explain why this is breaking ExpoGo, and how I can check such things in the future?

2022-11-21 11:28 UTC, lukmccall commented
> @lukmccall Thank for the review! Would you mind pointing me somewhere to explain why this is breaking ExpoGo, and how I can check such things in the future?

I can try to explain why this is breaking Expo Go. You touched on a very specific part of the codebase. Internally we have a concept known as scoped modules. Those modules have some part of the code overridden for Expo Go to provide a custom logic that is required by the Go app. There's no simple way to know if your change will affect the scoped part of the codebase. However, I can provide you with a good rule of thumb. If you change something with permissions, notifications, or the file system, there's a good chance that you will affect the expo go too.

2023-04-01 11:55 UTC, rodneyrehm commented
@lukmccall how should we proceed here?

2025-11-25 14:11 UTC, lucadegasperi commented
Has there been any progress on this PR? It's frustrating that you cannot ask for notification permissions again when you add a new parameter. The only way right now is for users to reinstall the app and have all the requests for permissions prompted right away.

2026-02-24 19:04 UTC, closed without merging