fix: barcode import on case sensitive file systems
expo/expo pull request #20141
Opened 2022-11-21 21:35 UTC by hirbod

# Why

fixes #20075

The import naming was wrong, which caused issues on case-sensitive file systems 

# How

Fixed the import

# Test Plan

Locally tested

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

2022-11-21 22:23 UTC, tsapeta approved these changes
Thanks for fixing that! 🙏 

Just for clarity and future reference:
We do inconsistently use both "EXBarcode" and "EXBarCode" but only "EXBarcode" is correct as the package is `expo-barcode-scanner` and not `expo-bar-code-scanner`. However, we decided not to rename these files right now because it could introduce some compatibility issues and may lead to regressions. In the future we'll eventually rewrite this code to Swift and that would be much better occasion to fix this kind of issue.

2022-11-22 09:46 UTC, Simek requested changes
I have the PR for that ready, but @tsapeta decided that we should rewrite the code instead.

Also, to unify the names with package, we should rename EMC files instead of altering the imports.

2022-11-22 10:52 UTC, Simek approved these changes
After speaking with Tomek I have got the broader context and details on future changes, so it is fine for now to leave this file names inconsistency, and fix imports instead.

2022-11-22 10:59 UTC, Kudo commented
i'm sorry to jump in the discussion. we could try to land the pr first without touching expo-modules-core. because publishing expo-modules-core, we should also publish expo package as well as all templates.
for whatever names make more sense, we could do it on main branch after this pr landed, so we could fix everything from next sdk (if we haven't get a chance to rewrite the module as expo module api yet)

2022-11-22 12:24 UTC, merged