Using right protocol in redirect URI on iOS for openAuthSessionAsync
expo/expo pull request #20229
Opened 2022-11-27 11:13 UTC by MarcinNowak-codes

The correct setup of redirect URI in the authentication server and relationship to other setup is uncleared. In PR I add a detailed description.

# Why

# How

# Test Plan

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

2022-12-14 20:42 UTC, amandeepmittal requested changes
Thanks for the updates! I've left one suggestion.

2022-12-14 20:42 UTC, amandeepmittal commented on packages/expo-web-browser/src/WebBrowser.ts
> + * has to use the protocol provided as the scheme in `app.json` [expo.scheme](../../config/app/#scheme)
```suggestion
 * has to use the protocol provided as the scheme in **app.json** [`expo.scheme`](../../config/app/#scheme) 
```

As per our writing style guide, [filenames have to be bold](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md#filenames-as-bold-text).

2022-12-16 19:56 UTC, MarcinNowak-codes commented
Suggestion applied. Thank you @amandeepmittal

2022-12-19 12:38 UTC, amandeepmittal approved these changes

2022-12-19 13:33 UTC, amandeepmittal commented
@MarcinNowak-codes, you'll have to follow the following steps to further docs related changes for this package's API:
- You’ll have to manually update the `unversioned` docs for a specific `.ts` file you've edited and then regenerate the build content and data JSON file (via Expo Tools (`et`):  `et gdad -p <PACKAGE_NAME>`)
- For more info on how to access Expo tools, please have a look at this: https://github.com/expo/expo/tree/main/tools#development
- The data is generated in `.json` files. Once that file is generated, you will see the changes by running docs locally using `yarn dev` (assuming the changes are made to unversioned)

2023-01-10 06:37 UTC, amandeepmittal approved these changes
Thank you!

2023-01-10 11:04 UTC, amandeepmittal commented
@MarcinNowak-codes, looks like the check is failing. I guess, it's my fault that I forgot to share the details on updating TypeDoc code, sorry about that!

When you are updating the definition, you'll have to run the command `yarn build` to start the TypeScript build compilation and the make the change in the `src/` folder. This will update the types in the `build/` directory and then follow the steps to run the `et` command as I mentioned before.

Once again, sorry for the inconvenience.

2023-01-26 07:55 UTC, amandeepmittal approved these changes

2023-01-30 21:32 UTC, tsapeta approved these changes
Cool, thanks and congrats on your first contribution to expo! 🎉

2023-01-30 22:43 UTC, merged