Bump babel-plugin-module-resolver@5.0.0
expo/expo pull request #20902
Opened 2023-01-20 21:13 UTC by korenskoy

# Why

The previous version of the plugin contains a vulnerability in the dependency `json5`
https://github.com/tleunen/babel-plugin-module-resolver/blob/master/CHANGELOG.md#500-2023-01-09

2023-04-30 00:06 UTC, berkcoker commented
Any updates on this?

2023-04-30 02:13 UTC, ide requested changes
Requesting changes for an in-depth explanation of why this change is safe, the impact of the change, and how this change was tested. Dependency upgrade PRs change many lines of code and authors need to provide a test plan and an explanation of how each breaking change in the dependency is handled or why it doesn't apply.

2023-04-30 02:14 UTC, ide commented
On prioritization: Vulnerabilities in npm packages (like json5) need explanations of a threat model and why they impact the current context. In the case of json5, I suspect it doesn't create a vulnerability under a threat model where it's used only as a dev dependency and an attacker doesn't already have control over a victim's computer. Of course, security issues are prioritized. However, most npm package vulnerability errors don't create security issues in the contexts in which they're used.

2023-11-02 00:09 UTC, brentvatne commented
thanks! we ended up upgrading this in another pr, appreciated nonetheless

2023-11-02 00:09 UTC, closed without merging