Webmanifest
expo/expo pull request #21318
Opened 2023-02-21 01:33 UTC by bradjones1

# Why

The documentation is silent on the source of the manifest object for web builds.

# How

Added docblock to the type in the existing TS file, which feeds the online documentation pages.

# Test Plan

Manual review.

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

2023-04-13 13:12 UTC, EvanBacon requested changes
PR references is for expo Webpack and it works when used with Expo (e.g. not next), the value is also filled in when using Metro web with Expo Router.

2023-11-02 00:17 UTC, brentvatne commented
closing because not sure if anything is actionable here! cheers for the pr nonetheless

2023-11-02 00:17 UTC, closed without merging

2023-11-03 17:19 UTC, bradjones1 commented
@brentvatne The actionable change here is to provide a docblock that will feed in to the online docs. Not having a reference for this value in the docs is the reason I opened the PR initially. Not sure what more you'd be looking for?

2023-11-03 22:39 UTC, brentvatne commented
@bradjones1 - i'm not familiar with the context here, i was just looking at old PRs and noticed that @EvanBacon had left a comment on April 13 and there weren't any comments or commits since then - but perhaps i misunderstood. what do you think should be done?