feat(expo)!: drop `EXPO_USE_LOCAL_CLI` in favor of using `expo` for the local CLI and `expo-cli` for the global CLI.
expo/expo pull request #21388
Opened 2023-02-24 18:51 UTC by EvanBacon

# Why

Speeds up command invocations. Would be ideal to drop the `expo/bin/cli.js` file too.

2023-02-24 19:09 UTC, ide requested changes

2023-02-24 19:09 UTC, ide commented on docs/pages/build-reference/android-builds.mdx
> +1. Additional step for **managed** projects: Run `expo prebuild` to convert the project to a bare one. This step will use the versioned Expo CLI for projects that use Expo SDK 46+. You can still choo
Word this in a way that makes it easy to understand whether SDK 48 is included or excluded.

2023-02-24 19:09 UTC, ide commented on packages/expo/bin/cli.js
> -const { boolish } = require('getenv');
Can remove getenv from dependencies

2023-02-28 21:51 UTC, ide commented on packages/expo/package.json
> -    "cross-spawn": "^6.0.5",
Don't we still need cross-spawn since it's imported?

2023-02-28 22:11 UTC, ide approved these changes

2023-02-28 22:32 UTC, tsapeta approved these changes

2023-03-01 01:10 UTC, ide approved these changes

2023-03-01 08:20 UTC, amandeepmittal approved these changes

2023-03-02 17:08 UTC, merged