[ios][secure-store] Migrate to expo modules
expo/expo pull request #21393
Opened 2023-02-25 00:04 UTC by alanjhughes

# Why
Continue migrating old modules to Expo modules

# How
Followed typical migration steps

# Test Plan
Tested on real device and simulator. 
NCL ✅

2023-02-26 12:20 UTC, fobos531 requested changes

2023-02-27 13:09 UTC, Kudo approved these changes
just one comment here. otherwise looks good to me. thanks for having the awesome help as always.

2023-02-27 15:30 UTC, alanjhughes commented on packages/expo-secure-store/ios/SecureStoreAccessible.swift
> +  case whenUnlockedThisDeviceOnly
Thanks, @Kudo 👍 I'll wait for @tsapeta to respond and make the changes then

2023-02-28 22:14 UTC, tsapeta commented on packages/expo-secure-store/ios/SecureStoreAccessible.swift
> +  case whenUnlockedThisDeviceOnly
Yeah, I agree that explicitly assigning number would make this much more clear.

2023-03-07 08:44 UTC, Kudo approved these changes
🔥 thanks again for helping this migration 🚀

2023-03-07 08:44 UTC, merged