added support for desktop detection on ios
expo/expo pull request #21636
Opened 2023-03-09 12:55 UTC by robertherber

# Why

On iOS added support for deviceType detection of Desktop on MacOS, checking for Catalyst and iPad app running on Mac.

# How

By checking the `ProcessInfo.processInfo.isMacCatalystApp` and `ProcessInfo.processInfo.isiOSAppOnMac` flags.

# Test Plan

Tested in the bare-expo app. And used in production through `patch-package`.

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

2023-03-09 13:06 UTC, fobos531 requested changes

2023-03-09 13:06 UTC, fobos531 commented on packages/expo-device/ios/DeviceModule.swift
> +    case UIUserInterfaceIdiom.phone:
This can be fixed by running swiftlint against the `switftlint.yml` in this repository

2023-03-09 13:12 UTC, robertherber commented
@ide @tsapeta I'm all for linting - but getting linting feedback in CI is a recurring headscratcher when contributing to Expo packages. [Building SwifLint locally feels is definitely a threshold to contributing](https://github.com/realm/SwiftLint/blob/main/CONTRIBUTING.md)

2023-03-09 13:28 UTC, robertherber commented
> > @ide @tsapeta I'm all for linting - but getting linting feedback in CI is a recurring headscratcher when contributing to Expo packages. [Building SwifLint locally feels is definitely a threshold to contributing](https://github.com/realm/SwiftLint/blob/main/CONTRIBUTING.md?rgh-link-date=2023-03-09T13%3A12%3A41Z) - is there a simpler way?
> 
> There's no need to build it locally. If you're on macOS (which I assume you are), there's a `swiftlint` homebrew formula which you can easily install. After that, position yourself in the `packages/expo-device` folder, run `swiftlint --fix` and that's all. Maybe this could be added to the contributing guide @tsapeta ?

I tried it now. The whole file intendation was changed and it still doesn't pass the CI 🤔 Please advice 😄

2023-03-10 04:32 UTC, robertherber commented
@fobos531 @tsapeta @ide I've added #21654 with some notes about swiftlint in the contribution docs, I hope it can help other sporadic contributors as well, and keep the CI greener.. :)

2023-03-14 17:10 UTC, tsapeta commented
@robertherber I'm sorry that the bot and linter get you annoyed. Right now the number of comments it can include in the review is limited to 10, because GitHub's API counts every comment as a notification (even though they all are sent in one http request) which is the basis of rate-limiting mechanism. We'll keep working on improving the contributors experience though. Thanks for submitting the PR to the contribution docs 🙏

2023-03-14 17:12 UTC, tsapeta approved these changes

2023-03-14 17:13 UTC, merged