[expo-print][android] Rewritten the expo-print module to the new modules API
expo/expo pull request #21714
Opened 2023-03-14 16:32 UTC by behenate

# Why

Rewritten the expo-print module to new modules API. Updated the docs to make the differences between Android and iOS clearer. 

# How

Created a new module and moved the code in there, modified the module to use kotlin Coroutines.

# Test Plan

Tested the library on a physical printer and print to file on a physical device.

2023-03-15 11:04 UTC, lukmccall requested changes

2023-03-15 11:04 UTC, lukmccall commented on packages/expo-print/src/Print.ts
> + * > and won't be rejected if the window is closed without starting the print.
I think it would be better to put those lines under `> See ...`

2023-03-15 11:04 UTC, lukmccall commented on packages/expo-print/android/src/main/java/expo/modules/print/PrintOptions.kt
> +  @Field var markupFormatterIOS: String? = null
I think most of those options aren't supported on Android. If that's true, you should remove them from that type. If not, please update the TS type.

2023-03-16 12:20 UTC, behenate commented on packages/expo-print/android/src/main/java/expo/modules/print/PrintExceptions.kt
> +internal class GenericPrintException(message: String, cause: Throwable? = null) :
@lukmccall Maybe just `PrintException` without any adjectives?

2023-03-20 08:45 UTC, lukmccall approved these changes

2023-03-20 14:25 UTC, merged