Inherit shell environment
expo/expo pull request #21712
Opened 2023-03-14 15:19 UTC by phoenixiguess

# Why

Some version management tools (like `asdf`) and env configurations do not load into an empty shell. If the build is executed with these configs, commands that rely on them are not on PATH and the build fails.

# How

Groovy [.execute(String[], File)](http://docs.groovy-lang.org/latest/html/groovy-jdk/java/util/List.html#execute(java.lang.String[],%20java.io.File)) loads the first arg as env variables. By passing an empty array, nothing gets loaded. `null` is the correct arg to inherit from the user's shell.

# Test Plan

Remove any globally installed/available versions of node.
Set up asdf with nodejs.
Kick off a build and observe that it fails when the an empty array is used in execute. The script cannot be found.
Replace the empty array with null, and notice that the script can now be found.

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

# See also
#17254

2023-03-14 15:53 UTC, EvanBacon requested changes
Smart idea. Can you please update the templates/ to ensure this functionality is applied everywhere.

2023-03-14 15:57 UTC, phoenixiguess commented
good call

2023-03-14 16:49 UTC, tsapeta approved these changes

2023-03-20 13:27 UTC, phoenixiguess commented
@EvanBacon Would you mind approving or removing your change request, since no changes are needed?

2023-03-20 13:29 UTC, tsapeta commented
I'll just go ahead and merge it 😉 Thanks for contribution!

2023-03-20 13:33 UTC, merged