[DOCS] update code for Handle push notifications with React Navigation
expo/expo pull request #21742
Opened 2023-03-17 10:00 UTC by luluhoc

# Why

The code in latest sdk was flawed as the[emoveEventListener is deprecated
# How

by assigning event to const and using .remove()

# Test Plan

# Checklist

- [x ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

2023-03-31 09:21 UTC, amandeepmittal requested changes
Thanks for fixing this @luluhoc!

Left one suggestion. Can you please update `unversioned` docs for this module (https://github.com/expo/expo/blob/main/docs/pages/versions/unversioned/sdk/notifications.mdx) to reflect the same changes?

2023-03-31 09:21 UTC, amandeepmittal commented on docs/pages/versions/v48.0.0/sdk/notifications.mdx
> +          const subEvent = Linking.addEventListener('url', onReceiveURL);
```suggestion
          const eventListenerSubscription = Linking.addEventListener('url', onReceiveURL);
```
I'd suggest changing the name of the variable to something meaningful that represents the event listener.

2023-03-31 09:21 UTC, amandeepmittal commented on docs/pages/versions/v48.0.0/sdk/notifications.mdx
> +            subEvent.remove()
```suggestion
            eventListenerSubscription.remove()
```

2023-03-31 21:26 UTC, luluhoc commented
> Thanks for fixing this @luluhoc!
> 
> Left one suggestion. Can you please update `unversioned` docs for this module (https://github.com/expo/expo/blob/main/docs/pages/versions/unversioned/sdk/notifications.mdx) to reflect the same changes?

@amandeepmittal all one ;)

2023-04-01 08:38 UTC, amandeepmittal approved these changes
Thanks for following up and making these changes!

2023-04-01 10:00 UTC, merged