[expo-asset] add `assetUrlOverride` in `getManifest2`
expo/expo pull request #21787
Opened 2023-03-21 02:14 UTC by outsung

# Why

When using `custom updates server`, the cdn link can be changed when the asset is loaded

I think we can solve this issue as well.
https://github.com/expo/eas-cli/issues/1688

# How

Add the old `assetUrlOverride` to `getManifest2` as well

# Test Plan

add test `returns a URI using the assetUrlOverride` in `AssetSources-test.ts`

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

2023-03-21 18:23 UTC, wschurman requested changes
`assetUrlOverride` was a concept designed in classic manifests only. It seems to have been missed when implementing new manifests/`manifest2`. I'm assuming that's what this PR is trying to do.

The feature was originally added by @quinlanj in https://github.com/expo/expo/commit/ae9371ffbc7c167b453756a494326140d5f63a3b for legacy manifests.

- Grep'ing for `assetUrlOverride`/`getAssetUrlOverride` and `assetMapOverride` indicates that only LegacyManifest/LegacyUpdate use this field in native code.
- In JS code, this place in expo-assets is the only place that uses it.

So, we need to ask ourselves two questions:
1. Does `assetUrlOverride`/`assetMapOverride` still make sense for modern manifests and asset systems? I'm not super familiar with how assets work.
2. If so, where should these fields live? In the new manifest format, they wouldn't be top-level. Instead, they'd likely live at `.extra.expoAsset.assetUrlOverride` or maybe `.extra.['expo-asset'].assetUrlOverride`.

@outsung - I assume you are adding these fields manually to the served manifest from your custom server. If not, then can you detail how they are being added?

2023-03-22 00:54 UTC, outsung commented
@wschurman  Thank you!

To answer your first question.
Currently, when I update using the custom update server (including new assets), expo-asset is looking for the image by the CDN link.

For some reason, when I update with the custom update server, the images don't come up on the CDN.

It would be nice if expo could make it completely private (without going through the expo cdn).


The answer to your second question is
`.extra.expoAsset.assetUrlOverride`
would be better, thanks.

The answer to the last question is
`.extra.expoAsset.assetUrlOverride` This value is optional, and if you add it, the image will be found by that value.
Without it, the image will be found by CND link as before.

2023-03-28 00:49 UTC, wschurman reviewed
> Currently, when I update using the custom update server (including new assets), expo-asset is looking for the image by the CDN link.
> For some reason, when I update with the custom update server, the images don't come up on the CDN.
> It would be nice if expo could make it completely private (without going through the expo cdn).

Not sure I follow exactly, but if by the custom update server you mean https://github.com/expo/custom-expo-updates-server I don't think that prescribes asset handing. Maybe the problem is in the input that is fed into this function? I added @brentvatne, @quinlanj, and @ide as reviewers to help with the background knowledge that I am missing (or to add someone who is more familiar). I don't think I can review this without a huge investigation into how assets work.

I think we should also figure out `assetMapOverride` on L26 (it's in the same category as `assetUrlOverride`).

My sense is that both of these should go in:
```
{
   ...
   extra: {
     ...
     expoAsset: {
       assetUrlOverride: string;
       assetMapOverride: ...;
     }
   }
}
```

One other thing we need to figure out is whether this needs to be respected in `NewUpdateManifest` like it is in `LegacyUpdateManifest`. My sense is that it doesn't need to be, but I don't really fully understand this.

2023-03-28 02:33 UTC, ide reviewed
Someone will need to look at this in more depth but at a glance I suspect we want the correct asset URLs to be specified in the manifest and not provide a way to swap out the hostname at runtime.

@outsung from your posts, it sounds like you might be trying to use EAS CLI with a custom update server. EAS CLI supports only EAS Update, including assets published to EAS Update. If you're looking to write your own server, EAS CLI does not apply. Instead, your update manifest should specify your server's own hostname (ex. example.com):

```json5
{
  ...
  "launchAsset": {
    "url": "https://example.com/entry.js",
    "hash": ..., "key": ..., "contentType": ...
  },
  "assets": [
    {
      "url": "https://example.com/icon.png",
      "hash": ..., "key": ..., "contentType": ...
    },
    ...
  ]
}
```

If you are using EAS CLI + EAS Update, these are the answers to your question:

> When exactly are assets uploaded to the CDN? Is it when I enter the Expo export command, or when I apply a new update in the app

When you run `eas update`, an update manifest fragment and your assets are exported to a local directory. The assets in this directory are uploaded to EAS so they can be served later from the global CDN. The update manifest fragment is also uploaded to EAS and will be used to create the manifest that is served to end users checking for updates.

> I think we need to know where the problem occurred and why new assets did not appear on the CDN.

The issue you linked seems to be related to [classic updates](https://blog.expo.dev/sunsetting-expo-publish-and-classic-updates-6cb9cd295378), which are being phased out. The upload flow I described above ensures that assets are fully uploaded when publishing an update => if an update is published successfully, the assets will have been uploaded (unless there's an unexpected bug, of course).

2023-03-28 05:07 UTC, outsung commented
I also thought it would work that way at first.

My custom server provides the manifest in the same format as yours.
```
----------------------------546526792123520273885294
Content-Disposition: form-data; name="manifest"
Content-Type: application/json
content-type: application/json; charset=utf-8

{"id":"cd1d46c4-73ea-afca-21a8-9dccbe94629b","createdAt":"2023-03-22T09:46:28.000Z","runtimeVersion":"2.6.0","launchAsset":{"key":"b4e5b10d-d3f3-cc00-b71c-bea4b61b51f9","hash":"MWgwe4UYp9QUn7vVMT1qfmmz5RHkyjV11mSUdEqkggQ","fileExtension":".bundle","contentType":"application/javascript","url":"https://kcplaa-update.mommoss.com/api/update/expo/assets/b4e5b10d-d3f3-cc00-b71c-bea4b61b51f9","httpServerLocation":"https://kcplaa-update.mommoss.com/api/update/expo/assets"},"assets":[{"key":"71787088-9cc8-31c9-eb3b-c528453403b9","hash":"EBbvsbGgTFnXt9WSeHjC5ETiXduy32Q1ForsskFkcj8","fileExtension":".otf","contentType":"font/otf","url":"https://kcplaa-update.mommoss.com/api/update/expo/assets/71787088-9cc8-31c9-eb3b-c528453403b9","httpServerLocation":"https://kcplaa-update.mommoss.com/api/update/expo/assets"},{"key":"e52645d6-2876-9c53-27c6-ed398a918f5c","hash":"wcMBsGmPIj5uC7O1725PJCW1kIFL0B6t-oVBIJ_t5Jc","fileExtension":".otf","contentType":"font/otf","url":"https://kcplaa-update.mommoss.com/api/update/expo/assets/e52645d6-2876-9c53-27c6-ed398a918f5c","httpServerLocation":"https://kcplaa-update.mommoss.com/api/update/expo/assets"},{"key":"f8864554-2c68-b9e2-e6fc-3e7cb90a1ab0","hash":"mt2dTKookM1UtEayUaF5oc8cck25kJJze4MbmCZUoW0","fileExtension":".otf","contentType":"font/otf","url":"https://kcplaa-update.mommoss.com/api/update/expo/assets/f8864554-2c68-b9e2-e6fc-3e7cb90a1ab0","httpServerLocation":"https://kcplaa-update.mommoss.com/api/update/expo/assets"},{"key":"be2adee7-d110-6626-bb61-fa45d764c46d","hash":"zSmWh-rVxk_L76aXGRp9zGQ6Yf688sGjuCSyH6yrH1Y","fileExtension":".otf","contentType":"font/otf","url":"https://kcplaa-update.mommoss.com/api/update/expo/assets/be2adee7-d110-6626-bb61-fa45d764c46d","httpServerLocation":"https://kcplaa-update.mommoss.com/api/update/expo/assets"},{"key":"ada4b650-a0a6-a45a-ee85-e5c5a462c519","hash":"YS4Wi_CBbkpXrFqUJgSCZz-4Sc8J8sXfCw31iQrIW2g","fileExtension":".otf","contentType":"font/otf","url":"https://kcplaa-update.mommoss.com/api/update/expo/assets/ada4b650-a0a6-a45a-ee85-e5c5a462c519","httpServerLocation":"https://kcplaa-update.mommoss.com/api/update/expo/assets"},{"key":"6938489e-aa45-fdfd-c91b-4a4848233c6a","hash":"ApTmFK1GfvhMqWEPyjf353WmOSw7ZIxrS5KKWhDH6rM","fileExtension":".png","contentType":"image/png","url":"https://kcplaa-update.mommoss.com/api/update/expo/assets/6938489e-aa45-fdfd-c91b-4a4848233c6a","httpServerLocation":"https://kcplaa-update.mommoss.com/api/update/expo/assets"},{"key":"5223c8d9-b0d0-8b82-a567-0fb5f71faf78","hash":"LJXowmdeeZM1_QBGuwfb2gbLfs_1HtN5IsYwnWGcxNM","fileExtension":".png","contentType":"image/png","url":"https://kcplaa-update.mommoss.com/api/update/expo/assets/5223c8d9-b0d0-8b82-a567-0fb5f71faf78","httpServerLocation":"https://kcplaa-update.mommoss.com/api/update/expo/assets"},{"key":"ef80a7e9-6084-a908-a01a-dc658090f06c","hash":"PG8mVkKwJirr3OQWETgw_rSRL6tYIb3ovP_D4EI5Pak","fileExtension":".png","contentType":"image/png","url":"https://kcplaa-update.mommoss.com/api/update/expo/assets/ef80a7e9-6084-a908-a01a-dc658090f06c","httpServerLocation":"https://kcplaa-update.mommoss.com/api/update/expo/assets"},{"key":"74223e02-9d5a-30a8-f7a3-81bef87c1e24","hash":"eoq133l5pt4ml3vZaUwBx6VB2vx6UtMIcxbQ4TFFjBQ","fileExtension":".png","contentType":"image/png","url":"https://kcplaa-update.mommoss.com/api/update/expo/assets/74223e02-9d5a-30a8-f7a3-81bef87c1e24","httpServerLocation":"https://kcplaa-update.mommoss.com/api/update/expo/assets"},{"key":"3999a64e-6cf6-6d70-05ef-48daa7070368","hash":"LClWFCR6qjBqdd0WWMfWt-2BQIRYBkVBhlckWHk-RmA","fileExtension":".png","contentType":"image/png","url":"https://kcplaa-update.mommoss.com/api/update/expo/assets/3999a64e-6cf6-6d70-05ef-48daa7070368","httpServerLocation":"https://kcplaa-update.mommoss.com/api/update/expo/assets"},{"key":"b86aa3b9-a6e2-d4de-7584-7768ee74b4cd","hash":"GvOZ3YaoHb7VTr_Idt3K6wtaOUIHDXUKx87A_t-b1yQ","fileExtension":".png","contentType":"image/png","url":"https://kcplaa-update.mommoss.com/api/update/expo/assets/b86aa3b9-a6e2-d4de-7584-7768ee74b4cd","httpServerLocation":"https://kcplaa-update.mommoss.com/api/update/expo/assets"},{"key":"147f1ae7-45f8-114e-782e-599b36d018ce","hash":"sMUSJFfgc5VOF__iui9v-181Lo8XSXarovPgw2D8YgQ","fileExtension":".png","contentType":"image/png","url":"https://kcplaa-update.mommoss.com/api/update/expo/assets/147f1ae7-45f8-114e-782e-599b36d018ce","httpServerLocation":"https://kcplaa-update.mommoss.com/api/update/expo/assets"},{"key":"4ac3e650-4f00-2b58-cc80-7948b66beb30","hash":"jePWkDVZX3lym87NO1KsRA6G0XDOeJzbq8nY58Zl2yM","fileExtension":".png","contentType":"image/png","url":"https://kcplaa-update.mommoss.com/api/update/expo/assets/4ac3e650-4f00-2b58-cc80-7948b66beb30","httpServerLocation":"https://kcplaa-update.mommoss.com/api/update/expo/assets"},{"key":"289df7ae-efc8-d832-6585-0eadeeb47d02","hash":"iB20uH7FvrORWGGd4uobXldM_nC_kqI1pKrqj9IZ3Kw","fileExtension":".png","contentType":"image/png","url":"https://kcplaa-update.mommoss.com/api/update/expo/assets/289df7ae-efc8-d832-6585-0eadeeb47d02","httpServerLocation":"https://kcplaa-update.mommoss.com/api/update/expo/assets"},{"key":"bfb51a6b-1130-b4db-3b5f-3f39bbe3bfab","hash":"aey0QZVpzdRcmpmNsivw4BDiyxV1XD9_edDW19i4Hgc","fileExtension":".png","contentType":"image/png","url":"https://kcplaa-update.mommoss.com/api/update/expo/assets/bfb51a6b-1130-b4db-3b5f-3f39bbe3bfab","httpServerLocation":"https://kcplaa-update.mommoss.com/api/update/expo/assets"},{"key":"b6b6d04e-4c56-436c-5dea-034da6e106ed","hash":"6mUjclzIm2Jeg-mjs6rvdQr8VPCB5Rs2SVcEu3PjrVc","fileExtension":".png","contentType":"image/png","url":"https://kcplaa-update.mommoss.com/api/update/expo/assets/b6b6d04e-4c56-436c-5dea-034da6e106ed","httpServerLocation":"https://kcplaa-update.mommoss.com/api/update/expo/assets"},{"key":"002821a3-17c9-385e-33d5-55791294a4f9","hash":"bcSbjF0L7R5gBGeTe7YtF11j8NddQgnwncKTr7MdW-E","fileExtension":".png","contentType":"image/png","url":"https://kcplaa-update.mommoss.com/api/update/expo/assets/002821a3-17c9-385e-33d5-55791294a4f9","httpServerLocation":"https://kcplaa-update.mommoss.com/api/update/expo/assets"},{"key":"8bad70fe-d5ea-00bf-4efc-66b6499ab730","hash":"XxMC1hf7BryEduAOAhhyq5EpsbhKrWzrj8WmIfxGpsk","fileExtension":".png","contentType":"image/png","url":"https://kcplaa-update.mommoss.com/api/update/expo/assets/8bad70fe-d5ea-00bf-4efc-66b6499ab730","httpServerLocation":"https://kcplaa-update.mommoss.com/api/update/expo/assets"},{"key":"1acfa0ee-d3cc-a560-92ed-1b5654f83071","hash":"qinjj8maz1fzCC0ztGcJe3TYtxg8g8mhD8G-38K6mLY","fileExtension":".png","contentType":"image/png","url":"https://kcplaa-update.mommoss.com/api/update/expo/assets/1acfa0ee-d3cc-a560-92ed-1b5654f83071","httpServerLocation":"https://kcplaa-update.mommoss.com/api/update/expo/assets"},{"key":"1fb1da00-086c-67d9-a4ab-3e03438890d3","hash":"1WhIDWFdVRJCng9SE8285UwGTc46bVwRzaIZXkm5wqU","fileExtension":".png","contentType":"image/png","url":"https://kcplaa-update.mommoss.com/api/update/expo/assets/1fb1da00-086c-67d9-a4ab-3e03438890d3","httpServerLocation":"https://kcplaa-update.mommoss.com/api/update/expo/assets"},{"key":"7d25e0e8-87c1-9441-6ab1-d05fa316520e","hash":"vIn2eoAbwkDhg9YvcQTF1uBhCN40cFlY9jiL7Z4RulA","fileExtension":".png","contentType":"image/png","url":"https://kcplaa-update.mommoss.com/api/update/expo/assets/7d25e0e8-87c1-9441-6ab1-d05fa316520e","httpServerLocation":"https://kcplaa-update.mommoss.com/api/update/expo/assets"},{"key":"ee7091d5-0e42-6db8-fe7b-107a56bb2456","hash":"2YBEEks_2BQH1gngtojtjw1cHUxUizsdabvxlsqLP3g","fileExtension":".png","contentType":"image/png","url":"https://kcplaa-update.mommoss.com/api/update/expo/assets/ee7091d5-0e42-6db8-fe7b-107a56bb2456","httpServerLocation":"ht [...]

2023-05-02 05:56 UTC, closed without merging

2023-05-07 02:44 UTC, quinlanj commented
hey @outsung , sorry for the super late reply. [Here's an explanation](https://github.com/expo/eas-cli/issues/1688#issuecomment-1537273348) of what is happening in the Assets module, assuming you were relying on the `uri` field. For what you are trying to do with your custom server, the `uri` field should not be necessary as we already ensure the assets you specify in your manifest are on device before running your application logic.

2023-05-08 05:43 UTC, outsung commented
@quinlanj Thank you. I understand exactly!