[android][brightness] Migrate to Expo Modules API
expo/expo pull request #22037
Opened 2023-04-07 20:43 UTC by alanjhughes

# Why
Continue migration to Expo Modules API.

# How
Followed the typical migration steps.

# Test Plan
Tested in bare expo. All the system brightness methods currently don't work as they require permission only available to system apps. I suggest deprecating all the system methods. This would mean the permission request could be removed and the API would match what's available on iOS.

2023-04-12 09:59 UTC, lukmccall requested changes

2023-04-12 09:59 UTC, lukmccall commented on packages/expo-brightness/android/src/main/java/expo/modules/brightness/BrightnessModule.kt
>      }
```suggestion
    AsyncFunction("setBrightnessAsync") { brightnessValue: Float ->
      try {
        val lp = currentActivity.window.attributes
        lp.screenBrightness = brightnessValue
        currentActivity.window.attributes = lp // must be done on UI thread
      } catch (e: Exception) {
        throw SetBrightnessException())
      }    
    }.runOnQueue(Queues.MAIN)
```

2023-04-12 09:59 UTC, lukmccall commented on packages/expo-brightness/android/src/main/java/expo/modules/brightness/BrightnessModule.kt
>      }
```suggestion
    AsyncFunction("getBrightnessAsync") { ->
      val lp = currentActivity.window.attributes
      val brightness = if (lp.screenBrightness == WindowManager.LayoutParams.BRIGHTNESS_OVERRIDE_NONE) {
        // system brightness is not overridden by the current activity, so just resolve with it
        getSystemBrightness()
      } else {
        lp.screenBrightness
      }
      
      return@AsyncFunction brightness
    }.runOnQueue(Queues.MAIN)
```

2023-04-12 09:59 UTC, lukmccall commented on packages/expo-brightness/android/src/main/java/expo/modules/brightness/BrightnessModule.kt
> +      currentActivity.runOnUiThread {
Please, use `.runOnQueue(Queues.MAIN)` instead

2023-04-12 09:59 UTC, lukmccall commented on packages/expo-brightness/android/src/main/java/expo/modules/brightness/BrightnessModule.kt
> +      currentActivity.runOnUiThread {
Same here ;)

2023-04-13 10:42 UTC, lukmccall approved these changes

2023-04-14 08:18 UTC, tsapeta approved these changes

2023-04-14 08:18 UTC, merged