[Android][image] Fixed image disappears before navigation animation is complete
expo/expo pull request #22066
Opened 2023-04-10 15:48 UTC by sallen450

# Why

Resolve #21993 

# How

Destroy ExpoImageView after it was detached from the window.

# Test Plan

Tested on the Android phone

https://user-images.githubusercontent.com/4767115/230937139-46c6ebfe-b7b0-4c6b-a4ae-defca36db216.mp4

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

2023-04-11 16:43 UTC, gabrieldonadel approved these changes

2023-04-11 16:43 UTC, gabrieldonadel commented on packages/expo-image/CHANGELOG.md
> +- [Android] Fixed image disappears before navigation animation is complete. ([#22066](https://github.com/expo/expo/pull/22066) by [@sallen450](https://github.com/sallen450))
```suggestion
- [Android] Fixed image disappearing before navigation animation is complete. ([#22066](https://github.com/expo/expo/pull/22066) by [@sallen450](https://github.com/sallen450))
```

2023-04-12 09:35 UTC, lukmccall requested changes

2023-04-12 09:35 UTC, lukmccall commented on packages/expo-image/android/src/main/java/expo/modules/image/ExpoImageModule.kt
> +        view.doOnDetach {
You forgot to import this function.
Please add `import androidx.core.view.doOnDetach` on top of the file.

2023-04-17 08:47 UTC, lukmccall approved these changes

2023-04-17 08:47 UTC, merged