[Android][expo-barcode-scanner] update barcode scanner library in Android
expo/expo pull request #22107
Opened 2023-04-13 08:00 UTC by toshiyuki-suzuki-yukashikado

# Why
Until now, we were using 'com.google.android.gms:play-services-vision' for QR code scanning of expo-barcode-scanner in Android. However, it is deprecated and has not been updated since 2020. We have now switched to using the recommended project, 'com.google.mlkit:barcode-scanning'. Additionally, a bug that prevented QR codes with special characters from being read has been fixed.

Resolve: #21995

# How

We've replaced the `com.google.android.gms:play-services-vision` (gms) library with `com.google.mlkit:barcode-scanning` (mlkit), keeping the interface as intact as possible. MLKit is the successor of GMS and supports the same types of barcodes, so no features are lost. While MLKit only supports asynchronous barcode scanning, we've achieved synchronous processing using lightweight Kotlin coroutines.

The issue with QR codes containing specific characters likely occurs  when converting from `barcode.rawBytes` to `barcode.rawValue` within MLKit. As a result, `barcode.rawValue` becomes `null`. To address this, we use `String(barcode.rawBytes)` as a new value when barcode.rawValue is null and barcode.rawBytes has a value.

# Test Plan
bare-expo
- [x] can read barcode 128
- [x] can read qrcord include special characters (but garbled characters occur)

https://user-images.githubusercontent.com/95330519/231669557-1b56d248-8a6c-4173-89b2-ebd5934d4aad.mp4

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)

2023-04-24 06:16 UTC, toshiyuki-suzuki-yukashikado commented
@lukmccall 
Sorry for being so busy. I would like to know if there is any test, documentation, etc. needed for you to review. I would be happy to get a response!

2023-04-27 11:13 UTC, lukmccall commented
Hello @toshiyuki-suzuki-yukashikado, thank you for your contribution. My apologies for the delayed response, as I have been quite occupied lately. However, I will make it a priority to review your changes tomorrow.

2023-05-17 11:00 UTC, lukmccall requested changes
Looking good 🏅
I apologize for the delayed response, as I have been quite occupied lately.
Please, apply my suggestions then I will merge your pr.

2023-06-05 03:51 UTC, toshiyuki-suzuki-yukashikado commented on packages/expo-barcode-scanner/android/src/main/java/expo/modules/barcodescanner/scanners/MLKitBarCodeScanner.kt
> +      .setBarcodeFormats(Barcode.FORMAT_ALL_FORMATS) // Barcode.FORMAT_ALL_FORMATS
Comment out was removed.
[1511e1a](https://github.com/expo/expo/pull/22107/commits/1511e1ab408d33fbf3537aace13249dc5bbf376e)

2023-06-05 03:52 UTC, toshiyuki-suzuki-yukashikado commented on packages/expo-barcode-scanner/android/build.gradle
>    api 'com.google.android.gms:play-services-vision:19.0.0'
Yes, we can.  `play-services-vision` doesn't depend on anything. 

[7afd682](https://github.com/expo/expo/pull/22107/commits/7afd682e35cbb0552cac2a86b08bf583a154479d)

2023-06-05 04:09 UTC, toshiyuki-suzuki-yukashikado commented
@lukmccall 
Thank you for reviewing!  And, sorry for the late fix.  I fixed your suggestions.
Please review again!

2023-06-05 10:08 UTC, tsapeta approved these changes
Nice, this looks great to me! Thank you for your contribution. I only left a suggestion regarding the changelog entry, otherwise it's ready to go 🤩

2023-06-05 10:59 UTC, toshiyuki-suzuki-yukashikado commented
@tsapeta 
Thank you for reviewing! 
I should have write the chargelog descriptive. I fixed it!

@lukmccall
Can this PR be merged?

2023-06-05 12:00 UTC, tsapeta commented
@toshiyuki-suzuki-yukashikado thanks for applying these suggestions. Looks like some CI jobs are failing, see https://github.com/expo/expo/actions/runs/5173125149/jobs/9324047108#step:10:1597
Could you take a look why this is failing?

2023-06-06 00:53 UTC, toshiyuki-suzuki-yukashikado commented on packages/expo-barcode-scanner/android/build.gradle
>    api 'com.google.zxing:core:3.3.3'
Yes! Zxing was removed in 31b10c0

2023-06-07 00:20 UTC, toshiyuki-suzuki-yukashikado commented
@lukmccall
Only ios test is failed. I edited only android code, not ios code. 
Is it possible to merge with ios test errors? Please check it🙏

2023-06-07 08:37 UTC, tsapeta approved these changes

2023-06-07 08:37 UTC, merged

2024-01-28 07:57 UTC, younes0 commented on packages/expo-barcode-scanner/android/build.gradle
> +  api 'com.google.mlkit:barcode-scanning:17.1.0'
this adds `libbarhopper_v3.so` which dramatically increases the build size
see: https://github.com/expo/expo/issues/26749