[android][image-picker] Support for cameraType
expo/expo pull request #22143
Opened 2023-04-16 13:11 UTC by YoussefHenna

# Why
- Support for `cameraType` option was missing for android, and only implemented in iOS.
- Documentation and types for `cameraType` were missing

# How
- Implemented into Android by adding `Intent` extras that tell the camera app which camera to use by default
  - This of course is dependent on support from the camera app. I send out all known (that I could find) extras that a camera app might support and hope for the best.
- Added types and docs for `CameraType` similarly to how expo-camera currently implements it for consistency. (Maybe should be a shared type?)

# Test Plan
- Ran the `bare-expo` app on Android
- Imported `expo-image-picker` and launched the camera with different values for `cameraType`
- Logged the intent extras to ensure intent extras properly sent.
- It should be noted that this had no effect on my device (Samsung S22 Ultra), most likely my camera app does not support this.

# Checklist
- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

2023-04-17 09:11 UTC, lukmccall requested changes
Thanks for your contribution 🏅

2023-04-17 09:11 UTC, lukmccall commented on packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/contracts/CameraContract.kt
> +          putExtra( "android.intent.extra.USE_FRONT_CAMERA", false)
```suggestion
          putExtra("android.intent.extras.CAMERA_FACING", 0)
          putExtra("android.intent.extra.USE_FRONT_CAMERA", false)
```

2023-04-17 09:11 UTC, lukmccall commented on packages/expo-image-picker/CHANGELOG.md
> +- Added support for the `cameraType` option for Android + Updated types to include the `cameraType` option in `ImagePickerOptions` ([#22143](https://github.com/expo/expo/pull/22143) by [@YoussefHenna
```suggestion
- Added ability to choose the camera-facing type. ([#22143](https://github.com/expo/expo/pull/22143) by [@YoussefHenna](https://github.com/YoussefHenna))
```
That option wasn't documented, so I think we should treat that as it wasn't added before on iOS.

2023-04-17 09:17 UTC, YoussefHenna commented on packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/contracts/CameraContract.kt
> +          putExtra( "android.intent.extra.USE_FRONT_CAMERA", false)
Nice catch!

2023-04-17 09:19 UTC, YoussefHenna commented on packages/expo-image-picker/src/ImagePicker.types.ts
> +   * - **On Android**, effect of this option depends on support of installed camera app.
This was copied from expo-camera's description for `cameraType`, may be worth updating there as well?

2023-04-17 14:32 UTC, lukmccall commented
Please fix `Android Unit Tests` job by running `./gradlew :expo-image-picker:spotlessApply` in `bare-expo/android` directory

2023-04-20 10:37 UTC, YoussefHenna commented
@lukmccall You can retry the test now and all should be good.

2023-04-21 08:42 UTC, lukmccall approved these changes

2023-04-21 08:43 UTC, merged