[expo-updates] Add timeout info to reloadAsync() API doc
expo/expo pull request #22179
Opened 2023-04-18 18:00 UTC by douglowder

# Why

In some difficult to reproduce production cases, and in the Detox environment, `reloadAsync()` can fail if called directly. The issue seems to be that there is some running JS code that needs to complete in order for the reload to complete gracefully.

# How

~Add an optional `timeout` parameter to `Updates.reloadAsync()` API. If the timeout is greater than 0, the call to `reloadAsync()` will be wrapped in a setTimeout with that value. If no timeout is passed in, or the timeout is 0, the method will be called directly (existing behavior).~

Add documentation on the issue to the `reloadAsync()` API doc. 

# Test Plan

E2E tests have been slightly changed to note the issue. These should pass.

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

2023-04-18 20:33 UTC, wschurman reviewed
> This is useful for cases where it is desired to allow some long-running code to complete before reloading the app.
 
Curious how this works. Does this only work if the long-running code takes shorter than the timeout? Or does it work because it no longer awaits? Or does the await fail since it is running in the first JS instance?

At first glance, I think we need to understand the problem a bit more deeply before we add a new parameter to the API.

2023-04-18 20:33 UTC, wschurman commented on packages/expo-updates/src/Updates.ts
> +export async function reloadAsync(timeout?: number): Promise<void> {
```suggestion
export async function reloadAsync(delay?: number): Promise<void> {
```

2023-04-18 20:39 UTC, douglowder commented
> Curious how this works. Does this only work if the long-running code takes shorter than the timeout? Or does it work because it no longer awaits? Or does the await fail since it is running in the first JS instance?

@wschurman in local Detox testing, it appeared that the timeout had to be at least 500 ms -- a timeout of 1 or 10 ms was not sufficient. I will do some further testing and debugging to see if I can get any more information.

2023-04-18 21:03 UTC, douglowder commented on packages/expo-updates/src/Updates.ts
> + * (timeout) milliseconds. This is useful for cases where it is desired to allow some long-running code
```suggestion
 * @param delay If this is passed in, the reload instruction will be wrapped in a setTimeout() with a delay of
 * (delay) milliseconds. This is useful for cases where it is desired to allow some long-running code
```

2023-04-19 02:55 UTC, ide requested changes

2023-04-19 02:55 UTC, ide commented on packages/expo-updates/src/Updates.ts
> + * to allow other JS and native code to complete before the app reloads.
This guidance is too ambiguous and makes people feel they can't rely on the API. At minimum, we should describe this as a known issue we're working to resolve.

If a setTimeout call fixes this, that likely means there's something that Updates.reloadAsync() depends on that we're not waiting for. I think we need to figure out what that something is, and change the internal implementation of Updates.reloadAsync() to conceptually look like:
```
await preconditionWeDontYetKnow;
...current logic to reload
```

2023-04-19 07:48 UTC, closed without merging