[android][local-authentication] Fixed device credentials fallback when biometric sensors are unavailable
expo/expo pull request #22388
Opened 2023-05-04 23:55 UTC by hubastard

# Why

On Android when `disableDeviceFallback` is `false and the device fingerprint sensor returns a `not_available` error, the fallback to Device Credentials does not work.

# How

To fix this bug, whenever we get one of the following error with `disableDeviceFallback=false`: 
`ERROR_HW_NOT_PRESENT`, `ERROR_HW_UNAVAILABLE`,`ERROR_NO_BIOMETRICS`, `ERROR_NO_SPACE` or `ERROR_UNABLE_TO_PROCESS`
We then manually prompt the device credentials unlock screen either using `KeyguardManager` for device older than Android SDK 30 or `BiometricManager.Authenticators.DEVICE_CREDENTIAL` for newer Android SDK 30+.

# Test Plan

Since there isn't an easy way to repro this on an emulator, I tested my changes by adding the `BiometricPrompt.ERROR_USER_CANCELED` to the list of `isBiometricUnavailable()` and tested that when I manually cancel the biometric prompt the logic properly displayed the fallback to the device credentials screen.

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

2023-05-17 10:47 UTC, lukmccall requested changes
Thanks for your contribution. Looking good. Please apply my suggestions.

2023-05-17 10:47 UTC, lukmccall commented on packages/expo-local-authentication/android/src/main/java/expo/modules/localauthentication/LocalAuthenticationModule.kt
> +      )
```suggestion
      promise.resolve(
        Bundle().apply {
          putBoolean("success", false)
          putString("error", "not_available")
          putString("warning", "getCurrentActivity() returned null")
        }
      )
```

2023-05-17 10:47 UTC, lukmccall commented on packages/expo-local-authentication/android/src/main/java/expo/modules/localauthentication/LocalAuthenticationModule.kt
> +        biometricPrompt = BiometricPrompt(fragmentActivity, executor, authenticationCallback)
```suggestion
	val localBiometricPrompt = BiometricPrompt(fragmentActivity, executor, authenticationCallback)
	if (localBiometricPrompt == null) {
	  promise.reject("E_INTERNAL_ERRROR", "Canceled authentication due to an internal error")
	  return@Runnable
	}
	biometricPrompt = localBiometricPrompt
```

2023-05-17 10:47 UTC, lukmccall commented on packages/expo-local-authentication/android/src/main/java/expo/modules/localauthentication/LocalAuthenticationModule.kt
> +        }
```suggestion
        localBiometricPrompt.authenticate(promptInfo)
```

2023-05-17 10:47 UTC, lukmccall commented on packages/expo-local-authentication/android/src/main/java/expo/modules/localauthentication/LocalAuthenticationModule.kt
> +
```suggestion
```

2023-05-17 10:47 UTC, lukmccall commented on packages/expo-local-authentication/android/src/main/java/expo/modules/localauthentication/LocalAuthenticationModule.kt
> +        // On Android device older than 11, we need to use Keyguard to unlock by Device Credentials.
```suggestion
        // On Android devices older than 11, we need to use Keyguard to unlock by Device Credentials.
```

2023-05-25 14:56 UTC, lukmccall approved these changes
Please, resolve the confit ;)
After that, I'll merge your PR.

2023-05-29 13:49 UTC, hubastard commented
@lukmccall done

2023-05-30 10:41 UTC, merged