[ios][image-picker] Add preferredAssetRepresentationMode to image picker
expo/expo pull request #22456
Opened 2023-05-11 16:41 UTC by thespacemanatee

# Why

- Resolves #21707
- The issue above is not that copying to cache is low, but that some videos are transcoded into a more compatible format which is done on the fly and takes a lot of time
- `preferredAssetRepresentationMode` gives us the option to skip transcoding

# How

- Added a new enum with proper documentation
- Add this new enum as an option in `ImagePickerOptions`
- Handle this in the native side following the code style of the module

# Test Plan

- Ran the `bare-expo` app on iOS
- Imported `expo-image-picker` and launched the photo library picker with all the options
- Tested a `.hevc` video with `automatic` and `current`, `current` is much faster

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

2023-05-17 11:44 UTC, lukmccall requested changes
Looking good 🏅
Thanks for your contribution.
Please, apply my suggestions.

2023-05-17 11:44 UTC, lukmccall commented on packages/expo-image-picker/ios/ImagePickerModule.swift
> +    configuration.preferredAssetRepresentationMode = options.preferredAssetRepresentationMode.toAssetRepresentationMode()
```suggestion
    if #available(iOS 14, *) {
      configuration.preferredAssetRepresentationMode = options.preferredAssetRepresentationMode.toAssetRepresentationMode()
    }
```

2023-05-17 16:34 UTC, thespacemanatee commented on packages/expo-image-picker/ios/ImagePickerModule.swift
> +    configuration.preferredAssetRepresentationMode = options.preferredAssetRepresentationMode.toAssetRepresentationMode()
@lukmccall Thank you, I've added it!

2023-05-19 09:05 UTC, lukmccall approved these changes

2023-05-19 09:05 UTC, merged