Fix ios crop box not dragging issue
expo/expo pull request #22512
Opened 2023-05-17 06:17 UTC by ebrahimhassan121

# Why
Should fix https://github.com/expo/expo/issues/10820

# How
The solution has been mentioned here https://stackoverflow.com/a/53440254/10811237

# Test Plan

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

2023-05-17 08:53 UTC, lukmccall requested changes
Thanks for your contribution 🏅
Please, fix problems connected with swift lint and I will merge your pr.

2023-05-17 08:53 UTC, lukmccall commented on packages/expo-image-picker/ios/UIImagePickerControllerExtentsion.swift
> +//
```suggestion
// Copyright 2016-present 650 Industries. All rights reserved.
```

2023-07-20 14:17 UTC, lukmccall approved these changes

2023-07-20 14:17 UTC, merged

2024-03-13 18:16 UTC, TheNerdGuyLulu commented on packages/expo-image-picker/ios/UIImagePickerControllerExtentsion.swift
> +      let top = cropView.frame.minY + self.view.safeAreaInsets.top
Hi @ebrahimhassan121
adding the safeAreaInsets.top prevents from reaching the bottom, and overflows the top
![79758501-49ED-4661-A575-EBF0DC0A29AD_1_101_o](https://github.com/expo/expo/assets/20543676/31e108a2-038a-4c2b-a291-74c2adbe3b84)
![18FCFD88-330C-4006-BEB6-36A287F2A96E_1_101_o](https://github.com/expo/expo/assets/20543676/7e32cbff-aae2-49e6-8ee1-3a72295f7ef3)