Update expo image loader to remove Fresco and update Glide
expo/expo pull request #22542
Opened 2023-05-18 16:34 UTC by josephyanks

# Why

Attempting to update dependencies that necessitate the use of jetifier.

The expo-image-loader uses both Fresco and Glide, which both accomplish the same thing.

# How

* Updated `com.github.bumptech.glide:glide` from `4.9.0` to `4.15.1` and added a variable in `ext` to customize the glide version in the future.
* Removed `com.facebook.fresco:fresco` from the project
* Replaced `loadImageForDisplayFromURL` method body with Glide implementation
* Replaced deprecated `SimpleTarget` with `CustomTarget`
* Removed `NonNull` and `Nullable` annotations from Kotlin code, as they are lint violations (nullity is enforced by language - specifically by contract with `ImageLoaderInterface`)

# Test Plan

There are no unit tests associated with this project, so I tested the changed method `loadImageForDisplayFromURL` on my own project.

# Checklist

- [X] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [X] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [X] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

2023-05-19 19:23 UTC, josephyanks commented
@Kudo not sure why no reviewers got added but wanted to make sure someone saw this - I believe this is the last of the jetified dependencies from expo 🤞🏻

2023-05-24 14:16 UTC, Kudo commented
@lukmccall could you help to review this pr when you get a chance?

2023-05-25 12:02 UTC, lukmccall requested changes
Everything seems great! However, we need to use a different version of Glide. Kindly use Glide version `4.13.2`, as it is already being utilized in the expo-image and cannot be updated at the moment.

2023-05-29 10:48 UTC, lukmccall commented
> Updated. Out of curiosity, why can't glide be updated past 4.13.2? Wondering if there's something I should worry about in our project

We're using an external decoder for some file formats, which doesn't seem to work with the newest version.

2023-05-29 10:49 UTC, lukmccall commented on packages/expo-image-loader/CHANGELOG.md
> +-
```suggestion

```

2023-05-29 10:49 UTC, lukmccall approved these changes

2023-05-29 10:49 UTC, merged

2023-08-11 19:40 UTC, fobos531 commented
@lukmccall Recently a new version of the WebP decoder (which I assume was blocking the version upgrade) got released: https://github.com/zjupure/GlideWebpDecoder/commit/a57b21c763f8ad2325d29001ed6fab490cdb530e

That might be worth looking at.