[docs][ENG-8521] Rearrange information about VM specs
expo/expo pull request #22601
Opened 2023-05-22 12:51 UTC by khamilowicz

<img width="781" alt="image" src="https://github.com/expo/expo/assets/1774298/d11e93b2-c5ce-42d8-b67e-a16a1a00b66e">

<img width="789" alt="image" src="https://github.com/expo/expo/assets/1774298/eb382f8b-3f92-47e2-92a2-796834139e5e">

<img width="794" alt="image" src="https://github.com/expo/expo/assets/1774298/46691b39-0d5d-4599-9677-531aa46f0cb5">

<img width="799" alt="image" src="https://github.com/expo/expo/assets/1774298/5dab1568-f338-4ade-9078-eb749219ea87">

# Why

# How

# Test Plan

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

2023-05-23 08:12 UTC, szdziedzic requested changes
I think that idea behind this task was to make our infra docs easier to maintain, meaning that ideally, we wouldn't need to change hardware/resource class descriptions in multiple places.

If we are going with adding resource class/hardware descriptions to the Website https://github.com/expo/universe/pull/12408 I would just link to the pricing page from these docs, so we don't need to edit both docs and the pricing page every time we add new hardware.

2023-05-23 08:12 UTC, szdziedzic commented on docs/pages/build-reference/infrastructure.mdx
> +iOS builder VMs run on Mac Mini 8.1 hosts in an isolated environment. Every build gets its own fresh macOS VM.
```suggestion
iOS builder VMs run on Mac Mini hosts in an isolated environment. Every build gets its own fresh macOS VM.
```

I think that 8.1 is no longer true (?). Let's drop this number.

2023-05-23 08:12 UTC, szdziedzic commented on docs/pages/build-reference/infrastructure.mdx
> +  - 8 CPU, 32 GB RAM (n2-standard-8 Google Cloud machine type)
Link to pricing page descriptions from here https://github.com/expo/universe/pull/12408

2023-05-23 08:12 UTC, szdziedzic commented on docs/pages/build-reference/infrastructure.mdx
>    - M2 Pro: 3.4GHz 10-Core M2 Pro (6 performance and 4 efficiency cores), 32 GB RAM
Same as above

2023-05-23 08:12 UTC, szdziedzic commented on docs/public/static/schemas/unversioned/eas-json-build-android-schema.js
> +      '- `large` 8 CPU, 32 GB RAM (n2-standard-8 Google Cloud machine type)',
Same as above

2023-05-23 08:12 UTC, szdziedzic commented on docs/public/static/schemas/unversioned/eas-json-build-ios-schema.js
> +      '- `large` 4 cores, 12 GB RAM, 2 builder VMs per host (for builds running on M2 Pro hosts) or 4 cores, 22 GB RAM, 1 builder VM per host (for builds running on M2 hosts)',
same as above

2023-06-22 14:11 UTC, Simek commented on docs/pages/build-reference/infrastructure.mdx
> +}
Let's extract this component to separate file inside `~/ui/components`.

2023-06-22 14:12 UTC, Simek commented on docs/pages/build-reference/infrastructure.mdx
> +} = resourceSpecs.data;
Would be nice to made this object restructure during JSON generation.

2023-07-17 08:59 UTC, szdziedzic approved these changes
Seems good

2023-07-17 08:59 UTC, szdziedzic commented on docs/scripts/resource-specs-sync.mjs
> +  // TODO: is public the correct place for this?
I think this is a good question for the docs code owners 😄

2023-07-17 10:19 UTC, merged