[battery] Added hooks to expo battery
expo/expo pull request #22646
Opened 2023-05-25 14:44 UTC by Adam-Schlichtmann

# Why

Add some simple hooks to make usage of `expo-battery` easier.

# How

Use the existing listeners and types to create hooks.

# Test Plan

Import the hooks to the sandbox and use a simulator/emulator/device to verify changes to battery level, state, and power mode are reflected via the hook.

# Checklist

- [X] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [X] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [X] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

2023-06-04 11:02 UTC, tsapeta requested changes
Thanks for contribution! I left some suggestions regarding the doc comments. Also cc @amandeepmittal to review them.

Besides that, as far as I understand, all these hooks react only on some events, but what about updating the initial state to the current one? In other words, shouldn't `useBatteryLevel` also call `getBatteryLevelAsync` initially to override the initial `-1` value?

2023-06-05 06:04 UTC, amandeepmittal reviewed
Left comments to clarify each hook's definition.

2023-06-05 06:04 UTC, amandeepmittal commented on packages/expo-battery/src/Battery.ts
> + */
We don't usually explicitly call that a hook is a "React hook". I'd suggest excluding that context from all these definitions.

Also, I'd suggest using a simpler phrase like and call things for what they are for. "updates with the battery..." without explicitly mentioning React hook will be confusing.

```markdown
Gets the device's battery level, as in [`getBatteryLevelAsync`](#getbatterylevelasync).
```

2023-06-05 06:04 UTC, amandeepmittal commented on packages/expo-battery/src/Battery.ts
> + */
```markdown
Gets the device's battery state, as in [`getBatteryStateAsync`](#getbatterystateasync).
```

2023-06-05 06:04 UTC, amandeepmittal commented on packages/expo-battery/src/Battery.ts
> + */
```markdown
Boolean that indicates if the device is in low power or power saver mode, as in  [`isLowPowerModeEnabledAsync`](#islowpowermodeenabledasync).
```

2023-06-05 06:04 UTC, amandeepmittal commented on packages/expo-battery/src/Battery.ts
> + */
```markdown
Gets the device's power state information, as in [`getPowerStateAsync`](#getpowerstateasync).
```

2023-06-12 15:15 UTC, Adam-Schlichtmann commented
Thanks for the reviews @tsapeta and @amandeepmittal!

I believe everything should be updated as you requested.

2023-06-12 17:31 UTC, amandeepmittal approved these changes
Thank you for updating the type definitions 👍

2023-06-12 19:03 UTC, tsapeta approved these changes
Great, looks good to me now! Thanks for a good contribution 🤗 
I've just approved the CI jobs to run, I'll merge it later when they pass 😉

2023-06-12 21:56 UTC, merged