fix expo-print to work with web urls and data strings (again)
expo/expo pull request #22997
Opened 2023-06-20 17:03 UTC by mroswald

# Why

I may be wrong, but it seems that the current refactoring to Swift introduced a regression to the `printAsync` function. I could not simply upgrade to `expo-print` 12.3.0 without errors, so I started investigating.

Error and way to reproduce it are described in the issue: https://github.com/expo/expo/issues/22971

Disclaimer: I'm not an expert with Swift and happy for any feedback on this! Nor I am very sure this is really an issue with the code or if I simply missed something else. I used ChatGPT for coding assistance.

# How

I extended the data fetching function to also work with http(s) urls and data strings (base64 encoded).

# Test Plan

Use this snack: https://snack.expo.dev/@maki123/print-usage
It's important to note, that the current Expo Go app will not reproduce the issue, as it's bundled with the "old" EXPrint framework prior to the change that introduced the regression.
Download the snack to a local project and run it. Make sure to use `expo-print` >= 12.3.0

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

2023-06-23 15:13 UTC, behenate requested changes
Thanks for the bug report and the PR! Can you also please add a `CHANGELOG.md` entry?

2023-06-23 15:13 UTC, behenate commented on packages/expo-print/ios/ExpoPrintWithPrinter.swift
> +          self.printWithData(printingData: printingData, options: options, promise: promise)
We should use weak reference in here: 
```suggestion
      dataFromUri(uri: uri) { [weak self] data in
        if let self = self, let printingData = data {
          self.printWithData(printingData: printingData, options: options, promise: promise)
        ```

2023-06-23 15:13 UTC, behenate commented on packages/expo-print/ios/ExpoPrintWithPrinter.swift
> +      }
URL can handle the data and "file://" prefixes so we can reduce the number of ifs. Also we should use `URLSession` for http requests. In the variable declarations at the top of the file we should add:
```
  let printURLSession = URLSession(configuration: .default)
  var dataTask: URLSessionDataTask?
```
Here is an improved version of the function:
```suggestion
   private func dataFromUri(uri: String, completion: @escaping (Data?) -> Void) {
    guard var url = URL(string: uri) else {
      completion(nil)
      return
    }
    
    // Assume that URLs without a scheme eq. /home/user/file.pdf will be local file urls
    if url.scheme == nil {
      url = URL(fileURLWithPath: uri)
    }
    
    // process http and https requests asynchronously
    if url.scheme == "http" || url.scheme == "https" {
      dataTask = printURLSession.dataTask(with: URLRequest(url: url)) { [weak self] data, response, error in
        defer {
          self?.dataTask = nil
        }
        
        if error == nil, let response = response as? HTTPURLResponse, response.statusCode == 200 {
          DispatchQueue.main.async {
            completion(data)
          }
          return
        }
        completion(nil)
      };
      dataTask?.resume()
    } else {
      let data = try? Data(contentsOf: url)
      completion(data)
    }
  }
```

2023-06-25 10:47 UTC, mroswald commented
> Thanks for the bug report and the PR! Can you also please add a `CHANGELOG.md` entry?

Hey @behenate , thanks for taking the time to review this and giving suggestions! I tested your updated version and it works. Added the entry for the change log and fixed one issue the linter found

2023-06-25 19:39 UTC, mroswald commented
Rebased the main branch on my origin force-pushed to trigger a change. Not sure if it affected the tests to run on a wider scope than intended, but I didn't touch the modules that failed. Hope it works now.

2023-06-26 08:57 UTC, behenate requested changes

2023-06-26 08:57 UTC, behenate commented on packages/expo-print/ios/ExpoPrintWithPrinter.swift
> +  var dataTask: URLSessionDataTask?
Can you move these to the top of the file next to other variable declarations?

2023-06-26 15:03 UTC, behenate approved these changes

2023-06-26 17:57 UTC, tsapeta approved these changes
Looks good to me, thank you for fixing this! We'll release it soon in SDK 49 😉

2023-06-26 17:57 UTC, merged