[ENG-9064] EAS Update: a basic debugging guide, try 2
expo/expo pull request #23079
Opened 2023-06-24 04:28 UTC by quinlanj

# Why
Same idea as https://github.com/expo/expo/pull/23046 but rewrites the basic debugging guide with @kbrandwijk 's [suggestion](https://github.com/expo/expo/pull/23046#issuecomment-1603984947). 

# How

The basic debugging guide is meant to be concrete and simple. It should take users no longer than 10 minutes to go through the entire thing. It points users to the Deployments page and uses that as a starting point for all debugging solutions. 

![basic-guide](https://github.com/expo/expo/assets/6380927/cfa8f91b-a909-48f4-89f8-e6264fb95f6c)

This PR moves the current debugging guide to `debugging-advanced.mdx`.

# Test Plan

- [ ] manually tested

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

2023-06-26 16:36 UTC, wschurman requested changes
My comments are mostly to adhere to the `we` voice in the doc consistently. I personally don't like using this voice or reading this voice as a documentation consumer, but I understand why we do it and changing it it outside the scope of this PR I think.

2023-06-26 16:36 UTC, wschurman commented on docs/pages/eas-update/debug.mdx
> +The EAS website has a [Deployments page](https://expo.dev/accounts/[account]/projects/[project]/deployments) that shows the current state of our app. The term _deployment_ refers to a group of builds
```suggestion
The EAS website has a [Deployments page](https://expo.dev/accounts/[account]/projects/[project]/deployments) that shows the current state of our app. The term _deployment_ refers to a group of builds and their corresponding updates. If we've made builds and updates with EAS, we can see our project's status on the website in the Deployments tab.
```

(fwiw, I don't really like the `we` voice for docs in general, but that's outside the scope of this PR. this suggestion just adheres to a consistent voice)

2023-06-26 16:36 UTC, wschurman commented on docs/pages/eas-update/debug.mdx
> +If the deployment channel is unexpected, it means your build was not built with the correct channel. To fix this, [configure your channel](/#configure-channel).
```suggestion
If the deployment channel is unexpected, it means our build was not built with the correct channel. To fix this, [configure our channel](/#configure-channel).
```

2023-06-26 16:36 UTC, wschurman commented on docs/pages/eas-update/debug.mdx
> +If the deployment runtime version is unexpected, it means your build was not built with the correct runtime version. To fix this, [configure your runtime version](/#configure-runtime-version).
```suggestion
If the deployment runtime version is unexpected, it means our build was not built with the correct runtime version. To fix this, [configure our runtime version](/#configure-runtime-version).
```

2023-06-26 16:36 UTC, wschurman commented on docs/pages/eas-update/debug.mdx
> +If the deployment has an unexpected branch, you will need to [map your channel to the correct branch](/#map-channel-to-branch).
```suggestion
If the deployment has an unexpected branch, we will need to [map our channel to the correct branch](/#map-channel-to-branch).
```

2023-06-26 16:36 UTC, wschurman commented on docs/pages/eas-update/debug.mdx
> +The displayed deployment does not have any updates. To fix this, [publish an update to the branch](/#publish-update).
I like this voice much more than the `we` fwiw.

2023-06-26 16:36 UTC, wschurman commented on docs/pages/eas-update/debug.mdx
> +If your deployment is not displayed, this means your build is not configured properly with EAS Update. To fix this, [configure your channel](/#configure-channel) and [configure your runtime version](
```suggestion
If your deployment is not displayed, this means our build is not configured properly with EAS Update. To fix this, [configure our channel](/#configure-channel) and [configure our runtime version](/#configure-runtime-version).
```

2023-06-26 16:36 UTC, wschurman commented on docs/pages/eas-update/debug.mdx
> +To verify your runtime version, make sure your app config (**app.json**/**app.config.js**) has a `runtimeVersion` property:
```suggestion
To verify your runtime version, make sure our app config (**app.json**/**app.config.js**) has a `runtimeVersion` property:
```

2023-06-26 16:36 UTC, wschurman commented on docs/pages/eas-update/debug.mdx
> +By default, it is `{ "policy": "sdkVersion" }`, but you can change your runtime to [use a different policy or a specific version](/eas-update/runtime-versions).
```suggestion
By default, it is `{ "policy": "sdkVersion" }`, but we can change our runtime to [use a different policy or a specific version](/eas-update/runtime-versions).
```

2023-06-26 16:36 UTC, wschurman commented on docs/pages/eas-update/debug.mdx
> +If your branch is not listed, you can create a new branch with `eas branch:create`
```suggestion
If your branch is not listed, we can create a new branch with `eas branch:create`
```

2023-06-26 22:00 UTC, kbrandwijk commented on docs/pages/eas-update/debug.mdx
> +This guide shows how to verify our configuration so that we can find the source of problems like an app not showing a published update. It's important to tell the current state of our app at any give
Multiple personality 'we' in this sentence as well.

2023-06-26 22:03 UTC, kbrandwijk commented on docs/pages/eas-update/debug.mdx
> +If the deployment channel is unexpected, it means your build was not built with the correct channel. To fix this, [configure your channel](/#configure-channel).
Emphasize that a rebuild of the app is necessary after changing this (common mistake).

2023-06-26 22:04 UTC, kbrandwijk commented on docs/pages/eas-update/debug.mdx
> +  alt="Deployment has no updates"
Fix various alt texts on the different screenshots throughout.

2023-06-26 22:08 UTC, kbrandwijk commented on docs/pages/eas-update/debug.mdx
> +The displayed deployment does not have any updates. To fix this, [publish an update to the branch](/#publish-update).
Other reason is that the runtime version _of the update_ doesn't match that of the build. This is common enough to note here as well.

2023-06-26 22:11 UTC, kbrandwijk commented on docs/pages/eas-update/debug.mdx
> +If your deployment is not displayed, this means your build is not configured properly with EAS Update. To fix this, [configure your channel](/#configure-channel) and [configure your runtime version](
```suggestion
If your deployment is not displayed, this means your build is not configured properly for EAS Update. To fix this, [configure your channel](/#configure-channel) and [configure your runtime version](/#configure-runtime-version).
```

Maybe mention as well to verify the general EAS Update configuration (updates.url)?

2023-06-26 22:12 UTC, kbrandwijk commented on docs/pages/eas-update/debug.mdx
>  To verify that a build has a specific channel, make sure that in **eas.json**, there is a channel property:
```suggestion
To verify that a build has a specific channel, make sure that your build profile in **eas.json** has a channel property:
```

2023-06-26 22:13 UTC, kbrandwijk commented on docs/pages/eas-update/debug.mdx
> +If your branch is not listed, you can create a new branch with `eas branch:create`
```suggestion
If our branch is not listed, we can create a new branch with `eas branch:create`
```

2023-06-26 22:15 UTC, kbrandwijk commented on docs/pages/eas-update/debug.mdx
>  ## Mitigation steps
This is now a bit disconnected from the previous section. Any 'root cause of the issue' we might have found, was a configuration one, not an issue with the actual update up to this point.

2023-06-26 22:17 UTC, kbrandwijk commented on docs/pages/eas-update/debug.mdx
> +Read the [advanced guide](/eas-update/debug-advanced) to debug EAS Update when the basic steps don't work.
```suggestion
Read the [advanced guide](/eas-update/debug-advanced) to debug EAS Update when the basic steps don't resolve your issue.
```

2023-06-26 22:18 UTC, kbrandwijk commented on docs/pages/eas-update/debug.mdx
> +To verify your runtime version, make sure your app config (**app.json**/**app.config.js**) has a `runtimeVersion` property:
```suggestion
To verify our runtime version, we make sure our app config (**app.json**/**app.config.js**) has a `runtimeVersion` property:
```

2023-06-28 16:48 UTC, wschurman approved these changes

2023-06-28 21:31 UTC, merged