[ENG-9065][ENG-6920][2/2] Refactor the current debugging guide
expo/expo pull request #23081
Opened 2023-06-24 04:37 UTC by quinlanj

# Why

The [current debugging guide ](https://docs.expo.dev/eas-update/debug/) has mostly advanced strategies, so I've moved it to be the advanced guide with a few notable changes:

- Remove contents already covered in the basic guide https://github.com/expo/expo/pull/23079
- Restructures the doc into categories: General strategies, Configuration issues, Runtime issues and Publishing issues
- Recommend people try the General strategies first because they are the most powerful
- Order each strategy in each category by usefullness
- [Add logging entries](https://linear.app/expo/issue/ENG-6920/add-information-on) to the `in app debugging` section

# Test Plan

- [ ] manually tested

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

2023-06-26 16:39 UTC, wschurman requested changes

2023-06-26 16:39 UTC, wschurman commented on docs/pages/eas-update/debug-advanced.mdx
> +We recommend trying these strategies before using the more specific ones mentioned in this guide.
The "we" in this refers to Expo as a company versus the first paragraph referring to the developer as we. Thou shalt make this consistent.

2023-06-27 22:15 UTC, quinlanj commented on docs/pages/eas-update/debug-advanced.mdx
> +#### Verifying app configuration
Part of me wonders if this section on verifying general app configuration should go in the basic guide. wdyt @kbrandwijk

2023-06-28 16:49 UTC, wschurman approved these changes

2023-06-28 21:29 UTC, quinlanj commented on docs/pages/eas-update/debug-advanced.mdx
> +#### Verifying app configuration
actually, nm. There are people who use EAS Update but not EAS Build, as shown by this report here: https://exponent-internal.slack.com/archives/C013ZK4SA12/p1687966348035039 . And the basic guide relies on users to be making builds with EAS

2023-06-28 21:49 UTC, merged