[expo] Add uuid to @expo
expo/expo pull request #23249
Opened 2023-07-01 12:20 UTC by alanjhughes

# Why
Closes ENG-9174

# How
- Forked [uuid](https://github.com/uuidjs/uuid) @3.4.0 into @expo
- Removed the uuid from expo dependency
- Fixed all imports
- Ran tests in every package where it was being used

# Test Plan
Ran all tests and tested running bare-expo

2023-07-01 21:26 UTC, brentvatne requested changes

2023-07-01 21:26 UTC, brentvatne commented on packages/@expo/uuid/README.md
> +
```suggestion
```

2023-07-01 21:26 UTC, brentvatne commented on packages/@expo/uuid/README.md
> +Fork of UUID
```suggestion
Fork of `uuid@3.4.0` for usage without any dependency on native crypto APIs. This library is used with in several `expo` package. We do not intend for it to be used directly by developers. There may be breaking changes at any time — use `uuid` instead, if you are considering installing this.
```

2023-07-02 10:09 UTC, tsapeta requested changes
Generally I think it would be better to put this package outside the monorepo. It's not going to change, even long-term I guess.
Especially that, as I said in many threads and discussions around this problem, this is not the right solution in my opinion. It's much easier and better to expose native UUID generation from `expo-modules-core` (similarly to `expo-crypto` with its `randomUUID`) instead of unnecessarily adding all those new files to the JS bundle.

In SDK 50 there will be a "core module" ([already implemented on iOS](https://github.com/expo/expo/blob/main/packages/expo-modules-core/ios/Swift/Modules/CoreModule.swift)) that decorates the `global.expo` object and will be the place for such things.
On web we can use `crypto.randomUUID()` instead, or if we need it for server-side rendering, use only a subset of `uuid` package that we actually need.

I understand that this might be urgent to fix for SDK 49, so I'll be fine with this PR if one of the following is met:
- The package is moved outside the repo.
- v4 algorithm is included within `expo-modules-core` package, but containing only necessary functionalities (no v35, v5, md5, sha1 algorithms). This will make us closer to what we will do in SDK 50 (we'll just switch the implementation to native on Android and iOS).

2023-07-02 23:06 UTC, brentvatne commented
that sounds like a good plan @tsapeta!

2023-07-03 15:39 UTC, tsapeta commented on react-native-lab/react-native
Revert submodule update

2023-07-03 17:10 UTC, ide requested changes
The prior uuid module was deprecated because it used a weak RNG (Math.random()) to generate values, which is fine for our use cases, which are unrelated to security. However, it would be good to communicate that in the exported function names so no one uses the new uuid function for security-related use cases. Something like "weak" is maybe a good adjective to use. It should evoke light caution.

Also the function name should indicate that it generates UUID v4 values. @tsapeta pointed out places where we use UUID v5 for instance and we don't want to mix those up.

---

Separately, I'm wondering if we can both reduce the amount of JS (faster bundling times, smaller JS updates) and use a strong RNG by implementing UUID generation in Swift/C and Kotlin and just bridge a synchronous method through expo-modules-core. There are a couple of decisions we'd need to make like are we OK with adding a synchronous bridged method to e-m-c?

2023-07-03 17:43 UTC, brentvatne commented on packages/expo/src/environment/getInstallationIdAsync.ts
> +    installationId = uuid(`${bundleIdentifier}-${identifierForVendor}`);
ah good catch. yeah we should keep using v5 here to be safe, i'm not actually familiar with why we chose to use it here though 🤔

2023-07-03 17:44 UTC, brentvatne commented
lots of comments here are focused around the best thing for the future. the goal in this PR to solve an immediately problem that users often encounter when installing `uuid` alongside our copy of it in certain repo configurations, and this pr handles that without regressing behavior. i think we need to focus on what needs to be done to make this shippable and then create tasks to follow up in sdk 50 for future work.

2023-07-03 17:48 UTC, brentvatne commented
- let's keep `@expo/uuid` in this repo for SDK 49, and we can remove it once we come up with another alternative
- let's revert the change to `getInstallationIdAsync` to ensure we use uuid v5 as before

it sounds like there are a bunch of ideas here for how to make things better in the future, but we are on a short timeline and i want to make the smallest possible change here that fixes the problems we're encountering and gets us in a better state.

2023-07-03 19:55 UTC, ide commented
Deferring the possibility of native changes, I would like the new function to (1) make clear it's UUID v4 and (2) is weak and inappropriate for security ("weak"). Suggestion: `s/uuid()/weakUUIDv4()/`

2023-07-03 20:18 UTC, tsapeta commented
@ide While I generally agree with clarifying its weakness and being v4, this is not going to be a part of the public API and we'll remove it in SDK 50 anyway. Not sure if you've read my previous comments, but we've already brought up that this needs to be implemented natively and this PR aims to just fix it temporarily to unblock people using SDK 49 from using different versions of uuid.

2023-07-03 20:23 UTC, ide commented
@alanjhughes OK. I do think it is preferable to communicate the lack of safety of this function at least in a doc block explaining when and when not it is appropriate to use. In the future, it would be better for PRs like this to use the names of functions to communicate the right kind of hesitation people should have when using the functions.

2023-07-03 20:47 UTC, tsapeta commented
@ide What do you say if we already shape it in a way that we would like it to be in SDK 50, but with an additional note in the doc comment that these are weak. In SDK 50 we will switch the implementation to native and remove that note.

I imagine the API could be like this 👇 similarly to the `uuid` package
```ts
export const uuid = {
  v4() { [native code] },
  v5(name, namespace) { [native code] }
}
```

2023-07-03 20:51 UTC, ide commented
Probably better to have uuidV4() and uuidV5() instead of uuid.v4(). That way there aren't non-descriptive functions called "v4". It's much clearer to have a function named "uuidV4". Choose function names that make sense without extra context.

As for making the API change now or later, I don't think it matters that much. The important thing is to tell people not to use the function for anything where security or strong randomness is needed.

2023-07-03 22:37 UTC, ide approved these changes

2023-07-03 22:45 UTC, tsapeta approved these changes

2023-07-04 08:45 UTC, lukmccall approved these changes

2023-07-04 08:59 UTC, merged