[expo-updates] Add rollback support to useUpdates()
expo/expo pull request #24071
Opened 2023-08-22 19:27 UTC by douglowder

- New UpdateInfoType for rollbacks
- Support for rollbacks in state machine

# Test Plan

- Unit tests and E2E test coverage added

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

2023-08-23 18:06 UTC, wschurman requested changes
One round of changes to address nullability in swift. Looks great otherwise.

2023-08-23 18:06 UTC, wschurman commented on packages/expo-updates/ios/EXUpdates/AppLoader/AppLoaderTask.swift
> +                  commitTime: RollBackToEmbeddedUpdateDirective.rollbackCommitTime(updateDirective)
```suggestion
                  commitTime: RollBackToEmbeddedUpdateDirective.rollbackCommitTime(rollBackUpdateDirective)
```

2023-08-24 07:02 UTC, douglowder commented
> One round of changes to address nullability in swift. Looks great otherwise.

Thanks @wschurman! Suggested changes are now committed.

2023-08-24 16:19 UTC, wschurman approved these changes

2023-08-24 17:05 UTC, merged