[expo-segment] Add Segment.optOut feature
expo/expo pull request #2412
Opened 2018-10-12 15:20 UTC by sjchmiela

# Why

Overrides, closes https://github.com/expo/expo/pull/1004.

Also, https://expo.canny.io/feature-requests/p/add-a-closepause-method-to-segment. 

# How

- Cherry-picked @ctgardner's commit, moved the changes to `expo-analytics-admob`.
- Added setting persistence across restarts.
- Added promise rejection for trying to set enabled state in Expo Client.

# Test Plan

`test-suite` tests included, passing on iOS and Android.

2018-10-12 15:51 UTC, tsapeta requested changes

2018-10-12 15:51 UTC, tsapeta commented on packages/expo-analytics-segment/src/Segment.js
> +    return ExponentSegment.setEnabledAsync(true);
ExponentSegment.setEnabledAsync(~true~ **enabled**)?

2018-10-12 15:51 UTC, tsapeta commented on packages/expo-analytics-segment/ios/EXSegment.podspec
> +  s.dependency 'EXConstantsInterface'
Looks like there is no `peerDependency` on `expo-constants-interface`

2018-10-12 15:51 UTC, tsapeta commented on packages/expo-analytics-segment/ios/EXSegment/EXSegment.m
> +static NSString * const EXSegmentOptOutKey = @"EXSegmentOptOutKey";
I think we used to be doing `NSString *const`

2018-10-12 15:51 UTC, tsapeta commented on packages/expo-analytics-segment/ios/EXSegment/EXSegment.m
> +  resolve(optOutSetting ?: @(true));
`true` -> `YES`

2018-10-12 16:09 UTC, bbarthec commented on ios/Podfile.lock
> +  EXSegment: cfe9aed31dbd7f1455724afe89a4920e5dad0049
Well, I see these two changes in this file, but is it possible that these don't affect file final checksum? 🤔

2018-10-12 16:09 UTC, bbarthec commented on packages/expo-analytics-segment/android/src/main/java/expo/modules/analytics/segment/SegmentModule.java
> +  private static final String NAME = "ExponentSegment";
Well, `ExponentSegment` -> `ExpoSegment`?

2018-10-12 16:09 UTC, bbarthec commented on packages/expo-analytics-segment/ios/EXSegment/EXSegment.m
>  EX_EXPORT_MODULE(ExponentSegment)
`Exponent` -> `Expo`

2018-10-12 16:09 UTC, bbarthec commented on packages/expo-analytics-segment/ios/EXSegment/EXSegment.m
> +  _constants = [moduleRegistry getModuleImplementingProtocol:@protocol(EXConstantsInterface)];
I believe we should introduce some `assertions` for retrieving modules from registry. What you say?

2018-10-12 16:09 UTC, bbarthec commented on packages/expo-analytics-segment/src/Segment.js
> +  },
Would you mind transforming that into `typescript`?

2018-10-15 08:46 UTC, tsapeta approved these changes

2018-10-16 07:11 UTC, merged