[task-manager][Android] Migrated codebase to use Expo modules API
expo/expo pull request #24157
Opened 2023-08-29 13:37 UTC by lukmccall

# Why

Migrated codebase to use Expo modules API

# Test Plan

- bare-expo ✅

2023-08-29 14:02 UTC, alanjhughes requested changes

2023-08-29 14:02 UTC, alanjhughes commented on packages/expo-task-manager/android/src/main/java/expo/modules/taskManager/TaskManagerModule.kt
> +
What do you think about adding another property here?
```kotlin
private val taskService get() = ensuresTaskService()
````
 Rename the interface to something like this
```kotlin
private val taskServiceInterface: TaskServiceInterface? by lazy {
  appContext.legacyModuleRegistry.getSingletonModule("TaskService", TaskServiceInterface::class.java)
}
```
 and remove the calls to `ensuresTaskService()` in each function?

2023-09-22 14:29 UTC, alanjhughes approved these changes

2023-09-22 15:36 UTC, tsapeta approved these changes

2023-09-26 10:38 UTC, merged