[iOS][Android] Fix EXIF orientation during ImageManipulator operation…
expo/expo pull request #2432
Opened 2018-10-16 14:03 UTC by bbarthec

…s & Fix EXIF orientation info returned via ImagePicker

# Why

Resolves #2329

Removed `react-native-svg` package from `ncl` as it was causing conflicts and is provided via `expo` package anyway.

# How

ImageManipulator wasn't paying attention to EXIF information before applying any operation, so therefore with EXIF-rotated images operations, such as `crop`, `resize` and so on worked wrongly either by suddenly rotating resulting image (Android) or cropping wrong area of image (both platforms).

On iOS `EXIF.Orientation` tag was not provided alongside with other `EXIF` tags, because iOS is storing this info in separate metadata field. I injected this tag back into `EXIF` metadata returned to JS side.

# Test plan

follow scenario from app given via https://github.com/expo/expo/issues/2329#issue-365227513

2018-10-17 13:40 UTC, tsapeta requested changes

2018-10-17 13:40 UTC, tsapeta commented on ios/Exponent/Versioned/Core/Api/EXImagePicker.m
> +  };
remove `;`

2018-10-17 13:40 UTC, tsapeta commented on ios/Exponent/Versioned/Core/Api/EXImageManipulator.m
> +    case UIImageOrientationUp:
maybe use `default:` instead of list of cases?

2018-10-17 13:40 UTC, tsapeta commented on ios/Exponent/Versioned/Core/Api/EXImageManipulator.m
> +    case UIImageOrientationUpMirrored:
also, change it to `default:`

2018-10-24 11:13 UTC, sjchmiela approved these changes

2018-10-24 11:55 UTC, merged