Update devices
expo/expo pull request #24555
Opened 2023-09-21 08:23 UTC by johanholm

This adds missing iPhone 15 and iPad names.

# Why

Missing iPhone 15 devices

# How

See `/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/usr/standalone/device_traits.db`  in Xcode 15 to confirm the device names

You can open it with sqlite3 and view the `Devices` table.

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

2023-09-26 23:56 UTC, tsapeta requested changes
Looks good to me, thanks for doing that! Could you also add a changelog entry to `expo-device/CHANGELOG.md`?

2023-09-27 11:31 UTC, fobos531 commented
@tsapeta Possibly slightly offtopic, but do you think it makes sense to have `deviceYearClass` at all anymore? Or maybe to just leave it be for iOS, but remove it for Android? 

https://github.com/facebookarchive/device-year-class

The official library that is referenced by Expo and used by Android's implementation has long been abandoned and is not maintained anymore - so the `deviceYearClass` on Android is **very** misleading. Thoughts?

2023-10-03 07:25 UTC, olegatg approved these changes
LGTM!

2023-10-04 21:33 UTC, tsapeta commented
@fobos531 I agree, the device year class doesn't seem to be very useful at the moment. I think we can still merge this PR and keep it available in SDK 50, but mark as deprecated in TypeScript comments and docs. Feel free if you want to help on that!

2023-10-04 21:33 UTC, tsapeta approved these changes

2023-10-04 21:33 UTC, merged