feat(router): add router.navigate, change router.push to attempt PUSH navigation
expo/expo pull request #24600
Opened 2023-09-25 05:22 UTC by marklawlor

# Why

`router.push()` should always most history forwards, however we are currently using the NAVIGATE action which may move history backwards if the screen is in history and the closest navigator is a Stack.

Adds `router.navigate` for when users wish to opt out of this behaviour.

# How

This changes `router.push()` to a PUSH action if the lowest nested navigator is a stack and shared between the old & new routes. Otherwise it defaults back to NAVIGATE.

# Test Plan

Included test case

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

2023-09-25 21:16 UTC, marklawlor commented
Change name to `pushOrPop`

2023-09-25 21:17 UTC, EvanBacon commented on packages/expo-router/src/types.ts
> +  /** Navigate to the provided href. */
Make sure to copy these to the type generation file.

2023-09-25 21:18 UTC, EvanBacon commented on packages/expo-router/CHANGELOG.md
> +- Add `router.navigate` and `navigate` to `useRouter` ([#24600](https://github.com/expo/expo/pull/24600) by [@marklawlor](https://github.com/marklawlor))
Rename to something like `pushOrPop` to show that it's a superset of the push behavior.

2023-10-04 22:44 UTC, marklawlor commented
Add navigation event types (replace/push/pushOrPop) to `<Link />`

2023-11-02 13:53 UTC, hasanaktas commented
Is there an estimated time for release?

2023-11-27 23:18 UTC, marklawlor commented on packages/expo-router/src/__tests__/navigation.test.tsx
> +it.only('can push & replace with nested Slots', async () => {
remove only

2023-11-27 23:18 UTC, marklawlor commented on packages/expo-router/src/__tests__/smoke.test.tsx
> +it.only('deep linking nested groups', async () => {
remove only

2023-11-27 23:20 UTC, EvanBacon commented on packages/@expo/cli/src/start/server/type-generation/routes.ts
> +    /** If there's history that supports invoking the \`back\` function. */
Make sure these match the comments in source.

2023-11-27 23:20 UTC, EvanBacon commented on packages/expo-router/src/types.ts
> +  /** Navigate to the provided href. */
Make this comment more explicit, indicating that it will always push, and that `pushOrPop` may be desired.

2023-11-27 23:22 UTC, EvanBacon requested changes
Update the docs too and add a guide about differences between push / pushOrPop.

2023-12-13 00:04 UTC, marklawlor commented
Renamed back to `navigate`

Now `Link` uses `NAVIGATE` by default and `router.push` uses `PUSH`.

You can add the `push` prop to `Link` for it to use the `PUSH` behaviour
You can use `router.navigate` for it to use the `NAVIGATE` behaviour

2023-12-13 00:05 UTC, marklawlor commented
Type code I'm going to defer and add to this PR https://github.com/expo/expo/pull/25654

2023-12-13 00:41 UTC, EvanBacon commented on packages/expo-router/src/global-state/router-store.tsx
> +     * Counter intuitively - this fires AFTER both React Navigation state change and the subsequent paint.
```suggestion
     * Counter intuitively - this fires AFTER both React Navigation's state changes and the subsequent paint.
```
haha

2023-12-13 00:43 UTC, EvanBacon commented on docs/pages/router/navigating-pages.mdx
> +By default, links "push" new routes onto the navigation stack or unwind to a existing route. You can use the `push` prop to always push the route onto the stack.
```suggestion
By default, links `navigate` to the nearest route in the navigation stack, either by pushing a new route or unwinding to an existing route. You can use the `push` prop to always push the route onto the stack.
```

2023-12-13 00:44 UTC, EvanBacon approved these changes
lgtm, pending docs pass

2023-12-13 05:54 UTC, amandeepmittal approved these changes
Minor suggestions but lgtm 👍

2023-12-13 05:54 UTC, amandeepmittal commented on docs/pages/router/navigating-pages.mdx
> +Expo Router employs a stack-based navigation approach. This means that each new route you navigate to is added to a stack. If you navigate to a route that's already in the stack, the stack is unwound
```suggestion
Expo Router uses a stack-based navigation approach. Each new route you navigate to gets added to a stack. If you navigate a route already in the stack, the stack unwinds back to that existing route.
```

- Let's keep this in present tense for clairty
- Also, let's be a bit concise

2023-12-13 05:54 UTC, amandeepmittal commented on docs/pages/router/navigating-pages.mdx
> +For example, if you navigate from `/feed` to `/profile`, the stack will contain `/feed` and `/profile`. If you then navigate to `/settings`, the stack will contain `/feed`, `/profile`, and `/settings
```suggestion
For example, when you navigate from `/feed` to `/profile`, the stack contains `/feed` and `/profile`. If you then navigate to `/settings`, the stack contains `/feed`, `/profile`, and `/settings`. If you then navigate back to `/feed`, the stack unwinds back to `/feed`.
```

2023-12-13 05:54 UTC, amandeepmittal commented on docs/pages/router/navigating-pages.mdx
> +If you wish to navigate to a route without the stack unwinding, you can use the `push` prop on the `<Link>` component. This will always push the route onto the stack, even if it already exists.
```suggestion
To navigate to a route without the stack unwinding, you can use the `push` prop on the `<Link>` component. This alwayss pushes the route onto the stack, even if it already exists.
```

2023-12-13 05:54 UTC, amandeepmittal commented on docs/pages/router/navigating-pages.mdx
> +
```suggestion
```

2023-12-13 05:54 UTC, amandeepmittal commented on docs/pages/router/navigating-pages.mdx
> +- **naviate**: `(href: Href) => void` Navigate to a route using the default behaviour. You can provide a full path like **/profile/settings** or a relative path like **../settings**. Navigate to dyna
```suggestion
- **navigate**: `(href: Href) => void` Navigate to a route using the default behavior. You can provide a full path like **/profile/settings** or a relative path like **../settings**. Navigate to dynamic routes by passing an object like `{ pathname: 'profile', params: { id: '123' } }`.
```

- Typo and we prefer American English for spellings

2023-12-13 10:10 UTC, Simek commented on docs/pages/router/navigating-pages.mdx
> +```js app/index.js
```suggestion
```jsx app/index.js
```

Syntax highlight nit.

2023-12-15 03:21 UTC, merged

2023-12-18 19:07 UTC, kennethstarkrl commented
@marklawlor The push issue still exists for me after this change in v3.
Doing a `router.push()` to the same route with different params changes the url with the new params, but the page doesn't change.

I commented out the following from `/expo-router/build/global-state/routing.js` `getNavigateAction()` and now push is working and navigates as I expected to.
```js
if (route.state && routesAreEqual && currentRoute.state) {
    return getNavigateAction(route.state, currentRoute.state, type);
}
```

My guess is that since only the route params changed, all the routes and states are equal. Might need an additional check to see if the params are equal as well. 

I modified it adding a params are equal check  and it seems to be working
_(not entirely sure if this is optimal or correct)_
```js
function getNavigateAction(state, parentState, type = 'NAVIGATE') {

    const route = state.routes[state.routes.length - 1];

    const currentRoute = parentState.routes.find((parentRoute) => parentRoute.name === route.name);
    const routesAreEqual = parentState.routes[parentState.index] === currentRoute;
    const paramsAreEqual = rewriteNavigationStateToParams(parentState).params === rewriteNavigationStateToParams(state).params;
    // If there is nested state and the routes are equal, we should keep going down the tree
    if (route.state && routesAreEqual && currentRoute.state && paramsAreEqual) {
        return getNavigateAction(route.state, currentRoute.state, type);
    }
    // Either we reached the bottom of the state or the point where the routes diverged
    const { screen, params } = rewriteNavigationStateToParams(state);
    if (type === 'PUSH' && parentState.type !== 'stack') {
        type = 'NAVIGATE';
    }
    else if (type === 'REPLACE' && parentState.type === 'tab') {
        type = 'JUMP_TO';
    }
    return {
        type,
        target: parentState.key,
        payload: {
            name: screen,
            params,
        },
    };
}
```