feat(babel): rewrite babel preset for web
expo/expo pull request #24725
Opened 2023-10-04 00:25 UTC by EvanBacon

# Why

We've used `metro-react-native-babel-preset` for web to get the closest behavior between platforms, but this doesn't make the most sense because the target JS engines between web, native, and server are pretty different. This PR aims to improve the correctness per-platform, by introducing an entirely new preset for web/server which uses more mainstream settings. The aim is keep things mostly working the same, but without the spaghetti code in `metro-react-native-babel-preset`.

# How

- Add new web-only preset with `@babel/preset-env`, `react`, and `typescript`.
- The new web-only preset uses a custom flow preset to support enums.
- `plugin-transform-runtime`, `babel-plugin-react-native-web`, `@babel/plugin-syntax-export-default-from` are also added on web.
- The lazy option isn't currently supported, unclear if we want to add this since web should be using esm more often than not.

# Test Plan

- Existing tests should pass.
- We may want to add more tests, but I'm not sure yet.

2023-10-17 07:09 UTC, ide requested changes

2023-10-17 07:09 UTC, ide commented on packages/babel-preset-expo/src/web.ts
> +      },
Are these plugins omittable when `disableFlowStripTypesTransform` is set to true? Intuitively that is what I would expect to happen

2023-10-31 23:53 UTC, EvanBacon commented on packages/babel-preset-expo/src/native.ts
> +          useTransformReactJSXExperimental: true,
We resolved this in the rewrite to use `babel/preset-react`.

2023-11-01 00:15 UTC, EvanBacon commented on packages/babel-preset-expo/src/web.ts
> +        regenerator: true,
Dropping it because hermes doesn't use it and it would seem like the adoption is generally wide enough for us not to need it.

2023-11-01 00:16 UTC, EvanBacon commented on packages/babel-preset-expo/src/web.ts
> +          modules: platformOptions.disableImportExportTransform ? false : 'commonjs',
```
- 'false' to indicate no module processing
```

2023-11-01 04:16 UTC, ide approved these changes

2024-03-28 06:27 UTC, EvanBacon commented
Closing in favor of the simpler PR https://github.com/expo/expo/pull/27907

2024-03-28 06:27 UTC, closed without merging