[docs] [ENG-8973] Update docs re submit profiles
expo/expo pull request #25142
Opened 2023-10-31 11:21 UTC by radoslawkrzemien

# Why

https://linear.app/expo/issue/ENG-8973/eas-submit-doesnt-use-asc-configuration-from-selected-build-profile

# How

Updated docs under https://docs.expo.dev/submit/eas-json/ to include the description of new changes regarding how the submission profile is resolved when the user does not provide the profile name

# Test Plan

Checked manually
<img width="868" alt="Screenshot 2023-10-31 at 12 13 18" src="https://github.com/expo/expo/assets/2974455/69f675dc-ab82-43cb-8a50-9536a20d8de5">

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

2023-10-31 11:42 UTC, amandeepmittal approved these changes
One tine suggestion but LGTM 👍 Thank you for updating this!

2023-10-31 11:42 UTC, amandeepmittal commented on docs/pages/submit/eas-json.mdx
> +When you select a build for submission, then a profile matching the build profile used for the selected build will be chosen. If it does not exist, it will default to `production` profile.
```suggestion
When you select a build for submission, it chooses the profile that is used for the selected build. If the profile does not exist, it selects the default `production` profile.
```

Let's use active voice here for better readability.

2023-10-31 12:39 UTC, szdziedzic approved these changes

2023-10-31 12:39 UTC, szdziedzic commented on docs/pages/submit/eas-json.mdx
> +You can also use EAS CLI to pick up another `submit` profile by specifying it with a parameter. For example, `eas submit --platform iOS --profile submit-profile-name`.
```suggestion
You can also use EAS CLI to pick up another `submit` profile by specifying it with a parameter. For example, `eas submit --platform ios --profile submit-profile-name`.
```

2023-11-07 09:39 UTC, Simek requested changes
Can you revert the lock changes? Looks like you have used newer version of Yarn than the docs uses by default.

2023-11-07 09:46 UTC, Simek approved these changes

2023-11-07 09:57 UTC, merged