[expo-updates] Remove unused method storedUpdateIdsWithConfiguration
expo/expo pull request #25194
Opened 2023-11-02 21:29 UTC by wschurman

# Why

The `storedUpdateIdsWithConfiguration` isn't called from anywhere.

# How

Remove.

# Test Plan

Inspect.

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

2023-11-03 17:47 UTC, wschurman commented
lol wtf github

2023-11-03 18:32 UTC, douglowder commented
I thought that this was called from dev launcher when viewing updates already in the DB.

2023-11-03 18:35 UTC, wschurman commented
https://github.com/search?q=repo%3Aexpo%2Fexpo%20storedUpdateIds&type=code

no results that I see.

Though I need to change this PR to also remove it from swift.

2023-11-03 21:22 UTC, douglowder commented
@wschurman you are right, the dev launcher code that used it must have been removed.

2023-11-03 21:23 UTC, douglowder approved these changes

2023-11-04 04:15 UTC, ide requested changes
PR is OK and mergeable but it looks like there is more closely related cleanup that can be done. lmk if you prefer to do that in a separate PR, though.

2023-11-04 04:15 UTC, ide commented on packages/expo-updates/android/src/main/java/expo/modules/updates/UpdatesController.kt
> -      val readyUpdateIds = launcher.getReadyUpdateIds(databaseHolder.database)
getReadyUpdateIds is now only used in tests

2023-11-04 16:51 UTC, wschurman commented
Addressed comments, going to land to land the first part of the stack (2 more on top of this) to keep momentum. Any post-commit audits are welcome.

2023-11-04 16:52 UTC, merged