CI-related cleanup
expo/expo pull request #2528
Opened 2018-10-27 17:55 UTC by nicknovitski

Splitting out unrelated changes from expo/expo#2506.

`--frozen-lockfile` is pretty important for CI, the whole point of yarn.lock files are that we don't want to install different versions of things willy-nilly. 

The gradle cache was just a typo.

[With circleci config 2.1, `workflows` don't have their own version](https://github.com/CircleCI-Public/config-preview-sdk/blob/master/docs/whats-new.md#whats-new-in-21-configuration)

I don't currently plan to make our own docker images for ci, especially with rocker, but the files will be in git history if it turns out we need to restore or refer back to them.

2018-10-28 21:53 UTC, ide approved these changes

2018-10-28 21:53 UTC, ide commented on .circleci/config.yml
> +      - run: echo '--frozen-lockfile true' >> ~/.yarnrc
Nice way to apply this as a universal default

2018-10-28 21:55 UTC, ide requested changes
Actually it looks like the Android CI build is failing due to a change in permissions of a `.gradle` directory:

```
Cached paths:
  * /root/.gradle

Downloading cache archive...
Unarchiving cache...
tar: root/.gradle: Cannot mkdir: Permission denied
tar: root/.gradle/caches: Cannot mkdir: Permission denied
tar: root/.gradle/caches/4.4: Cannot mkdir: Permission denied
```

2018-10-28 22:20 UTC, nicknovitski commented
Yeah, it's silly.

I first made that change in a branch that was mostly about using a nix
docker images instead of circle's android one, and one difference between
them is users. So now this branch is trying to reuse a cache made by uid 0.

I think I know how to fix it.

On Sun, Oct 28, 2018, 14:55 James Ide <notifications@github.com> wrote:

> *@ide* requested changes on this pull request.
>
> Actually it looks like the Android CI build is failing due to a change in
> permissions of a .gradle directory:
>
> Cached paths:
>   * /root/.gradle
>
> Downloading cache archive...
> Unarchiving cache...
> tar: root/.gradle: Cannot mkdir: Permission denied
> tar: root/.gradle/caches: Cannot mkdir: Permission denied
> tar: root/.gradle/caches/4.4: Cannot mkdir: Permission denied
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/expo/expo/pull/2528#pullrequestreview-169111471>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAJPKRtb1QiH_lyZrZMAhL3jUuKQESr4ks5upifEgaJpZM4X9jzY>
> .
>

2018-10-28 23:02 UTC, nicknovitski commented
Yeah, that fixed it.

2018-10-29 06:45 UTC, ide approved these changes

2018-10-29 21:54 UTC, merged