Update installing-updates.mdx
expo/expo pull request #25559
Opened 2023-11-23 16:49 UTC by italocoura87

# Why
Missing step for installation and testing locally

# How
Adding this step to te android configuration

# Test Plan
Removing the tag and trying to update.

# Checklist
- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [X] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

2023-11-27 17:13 UTC, wschurman requested changes
I think this might make the most sense to be a part of https://github.com/expo/expo/blob/main/docs/pages/eas-update/debug-advanced.mdx#L150 to not accidentally suggest that this setting is needed for normal operation of expo-updates (it's only needed for debugging and shouldn't be included in a production build).

2023-11-27 17:13 UTC, wschurman commented on docs/pages/bare/installing-updates.mdx
> +Add to **android/app/src/main/AndroidManifest.xml** so you can test ir locally:
```suggestion
Add to **android/app/src/main/AndroidManifest.xml** so you can test it locally:
```

2023-11-30 17:15 UTC, douglowder approved these changes

2023-11-30 17:16 UTC, wschurman requested changes
See my previous PR comment about where this should live.

2023-11-30 17:29 UTC, douglowder commented on docs/pages/bare/installing-updates.mdx
> +Add to **android/app/src/main/AndroidManifest.xml** so you can test it locally:
```suggestion
If using the updates server URL shown above (a custom non-HTTPS update server running on the same machine), you will need to modify **android/app/src/main/AndroidManifest.xml** as follows:
```

2023-11-30 17:31 UTC, douglowder commented
@wschurman after review, I believe the additional text is in the right place, but needed clarification, so I added that.

2023-11-30 17:53 UTC, merged