Add ios option to disable notification entitlement
expo/expo pull request #25808
Opened 2023-12-07 23:14 UTC by alexbrazier

# Why

Adding the `aps-environment` iOS entitlement is unnecessary when your app doesn't have push notifications

- fixes https://github.com/expo/expo/issues/18951
- fixes https://github.com/expo/eas-cli/issues/987

# How

Use a new config field `ios.disableNotifications` to remove the `aps-environment` generation. Setting it to `undefined` causes the value to be removed.

If you just don't set it, it will leave any existing value in your `App.entitlements` file so setting to `undefined` as I think the desired behaviour would be to remove the value when `disableNotifications=true`

- An alternative would be using something like `notifications.disableIosNotifications: true`

# Test Plan

Tested by changes the config and running `npx expo prebuild`

1. Set `ios.disableNotifications` to `true` and see that the `aps-environment` key is removed (or not added)
2. Set `ios.disableNotifications` to `false` or omit and see that it is set to `aps-environment:development` as before

*Changes to `App.entitlements` when setting to `true`:*
<img width="342" alt="image" src="https://github.com/expo/expo/assets/5689874/ce83ce12-1907-4134-97e7-fd94c2319989">

The default behaviour - i.e. when there is no value set is the same as before so this won't cause any breaking changes.

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

2023-12-08 16:43 UTC, EvanBacon requested changes
Setting the apns by default is an artifact of the legacy build system that we've since deprecated. I'd rather we just remove setting it by default.

As a temporary workaround, you can create a config plugin to delete the apns entitlement:

```js
const { withEntitlementsPlist } = require("expo/config-plugins");

module.exports = (config) => {

  withEntitlementsPlist(config, (config) => {
    delete config.modResults["aps-environment"];
    return config;
  });

  return config;
};
```

2023-12-12 14:20 UTC, onizam95 commented
Hi @alexbrazier how can i test this?
I tried giving your branch link to expo: in package.json but it gives me error.

2023-12-13 08:15 UTC, alexbrazier commented
> Setting the apns by default is an artifact of the legacy build system that we've since deprecated. I'd rather we just remove setting it by default.
> 
> As a temporary workaround, you can create a config plugin to delete the apns entitlement:
> 
> ```js
> const { withEntitlementsPlist } = require("expo/config-plugins");
> 
> module.exports = (config) => {
> 
>   withEntitlementsPlist(config, (config) => {
>     delete config.modResults["aps-environment"];
>     return config;
>   });
> 
>   return config;
> };
> ```

Hi @EvanBacon, thanks for the review. That's fair, happy to try that method or just keep my current method using `patch-package`. Just thought I would share back the changes I made.

2023-12-13 08:15 UTC, closed without merging

2023-12-13 08:16 UTC, alexbrazier commented
> Hi @alexbrazier how can i test this? I tried giving your branch link to expo: in package.json but it gives me error.

@onizam95 I would suggest either using [patch-package](https://www.npmjs.com/package/patch-package) with the changes in this PR or using the method @EvanBacon suggested above rather than trying to install this branch.