fix(metro-config): use explicit `@expo/metro-config` dependency with resolved module paths
expo/expo pull request #25804
Opened 2023-12-07 15:47 UTC by byCedric

# Why

Unfortunately, `metro-config` does not always return the fully resolved path of dependencies within the default metro config. This causes issues when using isolated modules (pnpm or npm).

# How

- Added explicit `@expo/metro-config` dependency to `expo`
  → This solves the same issue as https://github.com/expo/expo/pull/23580, but simplified.
- Resolve `transformer.asyncRequireModulePath` to either `@expo/metro-runtime` or `metro-runtime/src/modules/asyncRequire` (with prio for `@expo/metro-runtime` when installed)

# Test Plan

TBD, will provide a repo to test.

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

2023-12-07 19:23 UTC, ide approved these changes

2023-12-08 16:32 UTC, EvanBacon commented on packages/@expo/metro-config/src/ExpoMetroConfig.ts
> +        ? require.resolve('@expo/metro-runtime/async-require')
These could resolve to two different copies, resolve once and use the results of `resolveFrom`.

2023-12-09 18:33 UTC, ide requested changes

2023-12-09 18:33 UTC, ide commented on packages/@expo/metro-config/src/ExpoMetroConfig.ts
> +        expoMetroRuntimeModulePath ??
Doesn't this need to be the path to the async require module?

2023-12-11 17:57 UTC, ide approved these changes

2023-12-11 19:11 UTC, merged