Allow skipping InstalledDependencyVersionCheck with env var
expo/expo pull request #25822
Opened 2023-12-08 18:43 UTC by floatplane

# Why

Adding ability to disable one particular check (`InstalledDependencyVersionCheck`). See https://github.com/expo/expo/discussions/25698 for background.

# How

Extract the list of checks into a method, make the addition of this particular check dynamic.

# Test Plan

Wrote tests for the new `getChecks` method. Also tested manually - sample output without the variable:
```
$  npx ../expo/packages/expo-doctor                                     
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✖ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

Some dependencies are incompatible with the installed expo version:
  @sentry/react-native@5.5.0 - expected version: 5.10.0
  expo-file-system@15.4.4 - expected version: ~15.4.5
  sentry-expo@7.0.1 - expected version: ~7.1.0
Your project may not work correctly until you install the correct versions of the packages.
Fix with: npx expo install --fix
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.

One or more checks failed, indicating possible issues with the project.
```

and sample output with:

```
$ EXPO_DOCTOR_SKIP_DEPENDENCY_VERSION_CHECK=1 npx ../expo/packages/expo-doctor
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!
```

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

2023-12-08 19:28 UTC, floatplane commented
cc @keith-kurak @kadikraman PR to close the loop on #25698

2023-12-08 20:15 UTC, kadikraman reviewed
This is great, thanks so much for adding it! @keith-kurak might have some comments, but it LGTM!

Just one small thing: could you please also add a [changelog](https://github.com/expo/expo/blob/main/packages/expo-doctor/CHANGELOG.md) entry for this here?

2023-12-12 15:44 UTC, keith-kurak requested changes
Working well on my end! Thanks for doing this. Got a couple of comments in-line.

2023-12-12 17:54 UTC, floatplane commented
Had to rebase and force push to deal with upstream conflicts. Now printing a warning:

<img width="703" alt="image" src="https://github.com/expo/expo/assets/101196/3929f198-60de-4583-8f68-8d42b8a80a85">

PTAL @keith-kurak

2023-12-15 17:06 UTC, keith-kurak approved these changes
Looks great, thanks for submitting this!

2023-12-15 17:21 UTC, merged