[cli][config-plugins] introduce patch based config-plugin
expo/expo pull request #26199
Opened 2024-01-02 10:20 UTC by Kudo

# Why

close ENG-9909

# How

- [cli] introduce `npx expo uneject` that will convert bare projects to CNG projects and generate **cng-patches/ios.patch** or **cng-patches/android.patch**
  - it uses `git diff` to generate patches, so git is required. (patch-package also requires git to generate patches)
  - it moves existing android / ios directories to temporary paths and runs prebuild again. then we can diff between the two project states.
- [config-plugins][prebuild-config] introduce withPatchMod that will apply patches from **cng-patches/ios.patch** or **cng-patches/android.patch**
  - the mod will only run once and being the last mod to execute
  - it uses `git apply` to apply the patches, so git is also required in prebuild process if cng-patches files are there. (unlike patch-package that implements patch appliers by their own)

# Test Plan

- added unit tests
- added e2e tests 

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

2024-01-08 23:14 UTC, brentvatne requested changes

2024-01-08 23:14 UTC, brentvatne commented on packages/@expo/cli/bin/cli.ts
> +  uneject: () => import('../src/uneject/index.js').then((i) => i.expoUneject),
as discussed on slack, let's rename to `prebuild:patch`

2024-01-08 23:14 UTC, brentvatne commented on packages/@expo/cli/src/uneject/index.ts
> +      `Convert native iOS and Android project files into CNG patch files`,
```suggestion
       `(Experimental) Generate patch files for iOS and Android native projects to persist changes made manually after prebuild`
```

2024-01-09 17:59 UTC, Kudo commented
some key updates
- change `uneject` to `prebuild:patch` and will keep android/ios folders by default. having a `prebuild:patch --clean` to clean up the folders
- will use prebuild template tarball's md5 checksum as patch version, e.g. `/app/cng-patches/ios+86fb269d190d2c85f6e0468ceca42a20.patch`
  - will show a warning if there are multiple patches
  - will show a warning if patch does not match the prebuild template version. in this case we use the first patch as best effor
- will show a warning if the patch added/deleted lines exceeds 300

now it's good and ready for another round of review

2024-01-12 22:28 UTC, EvanBacon commented on packages/@expo/config-plugins/src/plugins/mod-compiler.ts
> +    patch: -1,
Change this to something like `finalize` or `post` to indicate that it runs last. Split this feature out of this PR and land it as a new dangerous modifier that runs after all other modifiers.

```suggestion
    finalize: -1,
```

2024-01-12 22:39 UTC, EvanBacon requested changes
The parts of this PR related to adding the new dangerous mod that runs last should be easily mergable in a different PR. The rest of this is a bit shaky.

For the patches that relate to serializable modifiers, I think these should mostly be implemented in some other capacity. Perhaps with a helper plugin that merges static contents in an opinionated way with a simple API.

The pbxproj modifier, which works very different to the other "patches", seems like an entirely different feature. 

I think it's fine if the results of three or four distinct features result in a "patching" system, but we should safely land the more stable concepts first.

2024-01-15 19:48 UTC, Kudo commented
i'm closing this pr and split changes to #26413, #26414 and #26429. since the feature is experimental, i'm introducing a new `@expo/prebuild-patch` package to run the `prebuild-patch` command and the config-plugin to apply the patches.
the downside is that requires to `require()` for expo-cli's internal code.

2024-01-15 19:48 UTC, closed without merging