[doc] add 3rd party libs integrations for expo-sqlite/next
expo/expo pull request #26205
Opened 2024-01-02 15:12 UTC by Kudo

# Why

add 3rd party integrations like Drizzle ORM

# How

add a section for 3rd party libs integrations and add Drizzle ORM and Knex.js

# Test Plan

ci passed

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

2024-01-08 22:55 UTC, brentvatne requested changes

2024-01-08 22:55 UTC, brentvatne commented on docs/pages/versions/unversioned/sdk/sqlite-next.mdx
> +## Third-party libraries integrations
```suggestion
## Third-party library integrations
```

2024-01-08 22:55 UTC, brentvatne commented on docs/pages/versions/unversioned/sdk/sqlite-next.mdx
> +The `expo-sqlite` library is designed to be a solid SQLite foundation. It enables broader integrations with third-party libraries for more advanced features. Here are some of the libraries that you c
```suggestion
The `expo-sqlite` library is designed to be a solid SQLite foundation. It enables broader integrations with third-party libraries for more advanced higher-level features. Here are some of the libraries that you can use with `expo-sqlite`.
```

2024-01-08 22:55 UTC, brentvatne commented on docs/pages/versions/unversioned/sdk/sqlite-next.mdx
> +[Drizzle](https://orm.drizzle.team/) is a headless TypeScript ORM with a head. Runs on Node, Bun and Deno. Lives on the Edge and yes, it's a JavaScript ORM too! It comes with a [drizzle-kit](https://
```suggestion
[Drizzle](https://orm.drizzle.team/) is a ["headless TypeScript ORM with a head"](https://orm.drizzle.team/docs/overview). It runs on Node, Bun, Deno, and React Native. It also comes with a [CLI compansion called drizzle-kit](https://orm.drizzle.team/kit-docs/overview) for generating SQL migrations.
```

2024-01-08 22:55 UTC, brentvatne commented on docs/pages/versions/unversioned/sdk/sqlite-next.mdx
> +[Knex.js](https://knexjs.org/) is a SQL query builder that is flexible, portable, and fun to use!
```suggestion
[Knex.js](https://knexjs.org/) is a SQL query builder that is ["flexible, portable, and fun to use!"](https://github.com/knex/knex)
```

2024-01-09 11:54 UTC, amandeepmittal commented on docs/pages/versions/unversioned/sdk/sqlite-next.mdx
> +[Drizzle](https://orm.drizzle.team/) is a ["headless TypeScript ORM with a head"](https://orm.drizzle.team/docs/overview). It runs on Node, Bun, Deno, and React Native. It also comes with a [CLI comp
```suggestion
[Drizzle](https://orm.drizzle.team/) is a ["headless TypeScript ORM with a head"](https://orm.drizzle.team/docs/overview). It runs on Node.js, Bun, Deno, and React Native. It also has a CLI compansion called [`drizzle-kit`](https://orm.drizzle.team/kit-docs/overview) for generating SQL migrations.
```

Let's highlight the CLI tool/package name with inline code highlight and for link, only highlight the library name as well.

2024-01-11 17:59 UTC, amandeepmittal approved these changes

2024-01-15 19:32 UTC, merged