[NCL][web] Adding web target to test shims
expo/expo pull request #2677
Opened 2018-11-09 21:53 UTC by EvanBacon

# Why

Making the Expo SDK usable in RNWeb.

# How

* [NCL] added a webpack config
* [NCL] added some web specific files `public/`, `src/`

# Test Plan

run `yarn web` in `apps/native-component-list/` the web app should open and run without errors.

2018-11-13 02:16 UTC, ide requested changes

2018-11-13 02:16 UTC, ide commented on apps/native-component-list/webpack.config.js
> +const moduleDirectory = path.resolve(__dirname, '../../node_modules/');
This seems kind of fragile and coupled to our repo structure. Let's do some more research on how to get webpack projects working with monorepos / Yarn workspaces / Lerna repos.

2018-11-28 04:37 UTC, EvanBacon commented on packages/expo-yarn-workspaces/bin/AppEntry.template.js
> +import registerRootComponent from 'expo/build/launch/registerRootComponent';
importing all of expo will throw errors on web because a lack of support

2018-12-05 04:12 UTC, ide commented on packages/expo/src/web/Performance/Systrace.ts
> +
Do we need this whole module? What functions are called and can we get away with stubbing them minimally?

2018-12-05 04:12 UTC, ide commented on packages/expo/src/launch/registerRootComponent.web.tsx
> +export default function registerRootComponent(component) {
Match / copy the type signature from the non-.web version of this file.

2018-12-10 18:30 UTC, ide approved these changes

2018-12-13 22:24 UTC, ide approved these changes

2018-12-14 01:05 UTC, merged