[android] Run Android Studio code formatter for all .gradle files
expo/expo pull request #2681
Opened 2018-11-10 11:36 UTC by sjchmiela

# Why

To make https://github.com/expo/expo/pull/2446 easier to review and cause it's nice to have files formatted properly.

# How

Iterated manually through every Gradle file visible in the left pane of Android Studio and for each ran <kbd>Reformat Code</kbd> command.

# Test Plan

Project synced without problems.

2018-11-12 09:19 UTC, tsapeta approved these changes

2018-11-12 09:19 UTC, tsapeta commented on android/versioned-abis/expoview-abi25_0_0/build.gradle
> +  // Be careful when upgrading! Upgrading might break experience scoping. Check with Jesse. See Analytics.resetAmplitudeDatabaseHelper
move this comment above `api 'com.amplitude:android-sdk:2.9.2'`

2018-11-12 09:19 UTC, tsapeta commented on android/versioned-abis/expoview-abi26_0_0/build.gradle
> +  // Be careful when upgrading! Upgrading might break experience scoping. Check with Jesse. See Analytics.resetAmplitudeDatabaseHelper
move this comment

2018-11-12 09:19 UTC, tsapeta commented on android/versioned-abis/expoview-abi27_0_0/build.gradle
> +  // Be careful when upgrading! Upgrading might break experience scoping. Check with Jesse. See Analytics.resetAmplitudeDatabaseHelper
move this comment

2018-11-12 09:19 UTC, tsapeta commented on android/versioned-abis/expoview-abi28_0_0/build.gradle
> +  // Be careful when upgrading! Upgrading might break experience scoping. Check with Jesse. See Analytics.resetAmplitudeDatabaseHelper
move this comment

2018-11-12 09:19 UTC, tsapeta commented on android/versioned-abis/expoview-abi29_0_0/build.gradle
> +  // Be careful when upgrading! Upgrading might break experience scoping. Check with Jesse. See Analytics.resetAmplitudeDatabaseHelper
move this comment

2018-11-12 09:19 UTC, tsapeta commented on android/versioned-abis/expoview-abi30_0_0/build.gradle
> +  // Be careful when upgrading! Upgrading might break experience scoping. Check with Jesse. See Analytics.resetAmplitudeDatabaseHelper
move this comment

2018-11-12 09:19 UTC, tsapeta commented on android/versioned-abis/expoview-abi31_0_0/build.gradle
> +  // Be careful when upgrading! Upgrading might break experience scoping. Check with Jesse. See Analytics.resetAmplitudeDatabaseHelper
move this comment

2018-11-13 10:18 UTC, bbarthec requested changes
What about `packages/expo-module-template/android/build.gradle`?

2018-11-13 11:49 UTC, bbarthec approved these changes

2018-11-13 11:50 UTC, merged