[android][camera] Fix barcode scanning by setting higher resolution scan
expo/expo pull request #26886
Opened 2024-02-02 15:55 UTC by byudaniel

# Why

Higher resolution barcodes such as PDF417 cannot be scanned at the default resolution. Without this fix the scan is sending a 640x480 image to ML Kit to analyze. iOS is able to scan the barcode without a patch.

# How

I needed to scan a PDF417 barcode and it was not working. After debugging it I realized it was because the source image was too low resolution to properly scan. See the ML Kit docs under ["Input image guidelines."](https://developers.google.com/ml-kit/vision/barcode-scanning/android#input-image-guidelines)

# Test Plan

I tested manually by scanning the back of a driver's license with an Galaxy S21 and a Galaxy S22 Ultra.

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

2024-02-02 16:47 UTC, alanjhughes requested changes

2024-02-02 16:47 UTC, alanjhughes commented on packages/expo-camera/android/src/main/java/expo/modules/camera/next/ExpoCameraView.kt
> +      .setTargetResolution(Size(1920, 1080))
```suggestion
  ImageAnalysis.Builder()
      .setResolutionSelector(
        ResolutionSelector.Builder()
          .setResolutionStrategy(ResolutionStrategy.HIGHEST_AVAILABLE_STRATEGY)
          .build()
      )
```
We shouldn't hardcode the resolution and this method is deprecated. We should do this

2024-02-02 17:04 UTC, alanjhughes commented
@byudaniel - you'll need to run spotless to fix CI. cd into the android directory in `bare-expo` and run `./gradlew :expo-camera:spotlessApply`

2024-02-02 18:04 UTC, byudaniel commented
@alanjhughes Formatting is fixed.

2024-02-02 18:06 UTC, alanjhughes commented
@byudaniel - Great, thanks! Can you fix the conflict and I'll merge?

2024-02-02 18:21 UTC, byudaniel commented
@alanjhughes Fixed conflict.

2024-02-02 19:24 UTC, alanjhughes commented
@byudaniel Looks like it's missing an import

2024-02-02 20:01 UTC, byudaniel commented
@alanjhughes Import fixed, hopefully it is good to go this time.

2024-02-05 09:06 UTC, alanjhughes commented
@byudaniel another conflict 😅

2024-02-05 13:57 UTC, lukmccall approved these changes
I think we can merge it for now, but in the long run, it would be nice if the user could specify that option.

2024-02-05 13:58 UTC, merged