[expo-linear-gradient][android] feat: Paint dithering ability to fix color banding on Android
expo/expo pull request #27153
Opened 2024-02-18 16:00 UTC by alexandrius

# Why
Gradients on Android have color banding issue. When gradient used as a screen background it becomes very obvious and doesn't look nice. It looks worse everytime after you noticing for the first time. This PR adds option to enable paint dithering for smooth gradients.

# How
Researched `Paint` class on Android. Found and tested the dithering. 

# Test Plan
Unfortunately due to compression it's not well noticeable in screenshots. Must be tested on real device to make it obvious.
These colors work for me: `['rgb(6,25,49)', 'rgb(14,64,110)', 'rgb(152,165,193)']`

Just in case I'm attaching the screenshot. Both screenshots have banding issues due to compression. Screenshots do not reflect how it will look on real hardware unfortunately. 

| Dither | No Dither |
| --- | ----------- |
| ![dither](https://github.com/expo/expo/assets/5978212/9b409af7-6e0d-4f1d-a139-90549d3c0c46) | ![nodither](https://github.com/expo/expo/assets/5978212/f7fab7c9-c011-4220-847b-3f9d65eab62a) |

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

2024-02-18 16:18 UTC, alexandrius commented
BTW how to avoid getting this changed?

![Screenshot 2024-02-18 at 20 13 22](https://github.com/expo/expo/assets/5978212/87fab100-6635-4dcc-b6a3-636be29ac829)

2024-02-19 21:05 UTC, BLOCKMATERIAL commented
upd

2024-02-20 06:58 UTC, ide reviewed
Some feedback:

- Dithering is the part that's relevant to the developer while the "paint" part isn't relevant and is an implementation detail of the Android API. So I'd suggest calling this prop `ditherAndroid`.
- Should dithering be on by default? In the context of a linear gradient, I can't imagine banding ever being desirable. Should (disabling) dithering even be an option?

@alanjhughes Could you review this one please?

2024-02-20 07:03 UTC, alexandrius commented
> Dithering is the part that's relevant to the developer while the "paint" part isn't relevant and is an implementation detail of the Android API. So I'd suggest calling this prop ditherAndroid.

👍

> Should dithering be on by default? In the context of a linear gradient, I can't imagine banding ever being desirable. Should (disabling) dithering even be an option?

I have 2 points why we shouldn't enable it by default for now
- Color banding isn't obvious for smaller (non background) Gradients
- According to [docs](https://developer.android.com/reference/android/graphics/Paint#setDither(boolean)) enabling dithering is slower. We don't want people to suddenly experience slowdown. SDK 52 can include this by default after people are aware of change.

2024-02-20 09:14 UTC, ide commented
What is the actual (measured) difference in performance?

2024-02-20 10:32 UTC, Simek commented on packages/expo-linear-gradient/src/LinearGradient.tsx
> +  ditherPaintAndroid?: boolean | false;
```suggestion

  /**
   * Enables or disables paint dithering on Android. Paint dithering can fix color banding issue.
   * @default false
   * @platform android
   */
  ditherPaint?: boolean;
```

Typing, naming and JSDoc nit. We usually do not include the platform name in platform specific props..

2024-02-20 10:40 UTC, Simek commented
Would be nice if you can also add an example/test case using this prop to the NCL screen for the package:
* https://github.com/expo/expo/blob/main/apps/native-component-list/src/screens/LinearGradientScreen.tsx

2024-02-20 11:53 UTC, alanjhughes requested changes
I'd also be in favour of this being the default. This has been made default in other frameworks and is easy to opt of. The gradient should look good using the defaults, if performance is a concern then just disable it. I don't see any strong performance warnings related to enabling it.

2024-02-20 11:53 UTC, alanjhughes commented on packages/expo-linear-gradient/src/LinearGradient.tsx
> +  ditherPaintAndroid?: boolean | false;
```suggestion
  dither?: boolean;
```

2024-02-20 11:53 UTC, alanjhughes commented on packages/expo-linear-gradient/android/src/main/java/expo/modules/lineargradient/LinearGradientModule.kt
> +      }
```suggestion
      Prop("dither") { view, shouldDither: Boolean? ->
        view.setDitherPaint(shouldDither ?: false)
      }
```
Removing the prop will cause null to be passed here. I see you are always passing something on the JS side but it's still better to handle this in native.

2024-02-24 13:20 UTC, alexandrius commented
Addressed comments. 
- Enabled dithering by default with a flag
- Improved docs
- Changed from `ditherPaintAndroid` to `dither`

2024-02-24 18:47 UTC, alanjhughes approved these changes

2024-02-24 18:48 UTC, alanjhughes commented
Thanks @alexandrius!

2024-02-25 20:14 UTC, merged