[expo-updates] Add cli to resolve runtime version
expo/expo pull request #27263
Opened 2024-02-23 19:33 UTC by wschurman

# Why

In the same way that https://github.com/expo/expo/pull/27119 was added to resolve the fingerprint using the current version of fingerprint in the project's expo-updates dependencies (rather than `eas-cli`'s dependencies), we need to do the same thing for general runtime version resolution since that can differ from version to version of `expo-updates` and `@expo/config-plugins`, ...

I noticed this because all of the `Updates.getRuntimeVersionNullableAsync` calls within eas-cli didn't resolve the correct runtime version (during builds for example: https://github.com/expo/eas-cli/blob/main/packages/eas-cli/src/build/metadata.ts#L41).

# How

Add new command, `npx expo-updates runtimeversion:resolve --platform <ios | android>` that gets the final runtime version that will be used by the build/update.

# Test Plan

In a project, run the command, see it works:
```
$ yarn expo-updates runtimeversion:resolve --platform android
yarn run v1.22.19
$ /Users/wschurman/expo/expo/bare-apps/testwat47/node_modules/.bin/expo-updates runtimeversion:resolve --platform android
"264f7759f8d8d1afe60f07244c2f563418d8ba78"
✨  Done in 9.56s.
```

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

2024-02-23 21:34 UTC, douglowder approved these changes

2024-02-23 21:36 UTC, douglowder requested changes
`Updates-test` seems to be failing and causing `check-packages` CLI to fail....

Does the new `resolveRuntimeVersion.ts` need any unit tests of its own?

2024-02-24 23:01 UTC, wschurman commented
> Does the new `resolveRuntimeVersion.ts` need any unit tests of its own?

For sure. I'll add some tests.

In general, we need tests for the CLI and `createManifest` too now that they're in more testable packages.

2024-02-26 17:53 UTC, quinlanj approved these changes

2024-02-27 16:34 UTC, merged