[docs] Adding Calendly OAuth2 Guide
expo/expo pull request #27326
Opened 2024-02-27 17:34 UTC by imtiendat0311

# Why

Adding guide for Calendly API OAuth2 using expo auth session package

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

2024-03-03 17:46 UTC, imtiendat0311 commented
Sorry for bother both of you guy ,@Simek @amandeepmittal. I'm wondering if there is any particular reason why this PR has not been approved yet

2024-03-04 17:17 UTC, amandeepmittal commented
Hey @imtiendat0311, apologies for the delay in not taking a look at this. I'll go through it soon.

2024-03-06 14:17 UTC, amandeepmittal requested changes
Thanks for adding this example! I've left some feedback to improve this as per our [writing style guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md) and for concistency.

2024-03-06 14:17 UTC, amandeepmittal commented on docs/pages/guides/authentication.mdx
> +  href ="/guides/google-authentication/"
```suggestion
    protocol={['OAuth 2', 'OpenID']}
    href="/guides/google-authentication/"
```

As per our Prettier configuration, this formatting is incorrect. Let's revert it.

2024-03-06 14:17 UTC, amandeepmittal commented on docs/pages/guides/authentication.mdx
> +  <GridItem title="Calendly" protocol={['OAuth 2']} image={ASSETS.calendly} />
Let's not add this at the end of this Grid. On this page, we follow alphabetical order so let' stick to that. Please remove this line from here and add it before "Cognito".

2024-03-06 14:17 UTC, amandeepmittal commented on docs/pages/guides/authentication.mdx
> +{/* Start Calendly*/}
Same as above. On this page, we follow alphabetical order so let' stick to that. Please remove this line from here and add it before "Cognito".

2024-03-06 14:17 UTC, amandeepmittal commented on docs/pages/guides/authentication.mdx
> +{/* prettier-ignore */}
```suggestion
<Tab>

{/* prettier-ignore */}
```

Let's add the space so that Prettier does not auto-format the code snippet below.

2024-03-06 14:17 UTC, amandeepmittal commented on docs/pages/guides/authentication.mdx
> +```tsx
````suggestion
```jsx Calendly Example
````

Add the example snippet title. Also, I don't see any TypeScript in the snippet below, so let's stick to using `.jsx`.

2024-03-06 14:17 UTC, amandeepmittal commented on docs/pages/guides/authentication.mdx
> +/* @info <strong>Web only:</strong> This method should be invoked on the page that the auth popup gets redirected to on web, it'll ensure that authentication is completed properly. On native this doe
```suggestion
/* @info <strong>Web only:</strong> This method should be invoked on the page that the auth popup gets redirected to on web, it'll ensure that authentication is completed properly. On native, this does nothing. */
```

Missing comma.

2024-03-06 14:17 UTC, amandeepmittal commented on docs/pages/guides/authentication.mdx
> +        native: /* @info Set up scheme property in your app.json or app.config.js. EX app.json {scheme: "myapp"} */ "myapp://" /* @end */,
```suggestion
        native: /* @info Set up scheme property in your app.json or app.config.js. For example, app.json {scheme: "myapp"} */ "myapp://" /* @end */, 
```

2024-03-06 14:17 UTC, amandeepmittal commented on docs/pages/guides/authentication.mdx
> +          title="Connect to calendly"
```suggestion
          title="Connect to Calendly"
```

Branding title.

2024-03-06 14:17 UTC, amandeepmittal commented on docs/ui/components/Authentication/index.ts
> +  calendly: ASSETS_PATH + 'calendly.svg',
Same as above. On this page, we follow alphabetical order so let' stick to that. Please remove this line from here and add it before "Cognito".

2024-03-06 14:17 UTC, amandeepmittal commented on docs/pages/guides/authentication.mdx
> +            code: /* @info Recieved Code from firs request*/ exchangeTokenReq /* @end */,
```suggestion
            code: /* @info Received code from first request*/ exchangeTokenReq /* @end */,
```

Let's fix these typos.

2024-03-06 14:17 UTC, amandeepmittal commented on docs/pages/guides/authentication.mdx
> +      clientId: /* @info Your client id, can hardcode or put it in .env file */ process.env.EXPO_PUBLIC_Client_ID /* @end */,
```suggestion
      clientId: /* @info Your client id. Can be hardcoded or put it in .env file */ process.env.EXPO_PUBLIC_Client_ID /* @end */,
```

2024-03-06 17:11 UTC, amandeepmittal approved these changes
Thank you for incorporating those changes and for adding this!

Welcome to the community 🎉

2024-03-06 18:02 UTC, merged