[cli] detect missing `adb`, add fix suggestion and docs hint
expo/expo pull request #27419
Opened 2024-03-04 09:13 UTC by Simek

# Why

Hopefully fixes ENG-10014

# How

Add `AndroidPrerequisite` check for ADB, and provide basic information and hints how to solve the problem.

Any wording tweaks are appreciated! 😉 

# Test Plan

All lint checks and tests are passing. Local CLI after the changes behaves as expected. 

# Preview

https://github.com/expo/expo/assets/719641/f0f9fb46-c265-4c1a-ad31-1684ca5213a2

2025-04-29 11:44 UTC, kadikraman approved these changes
I merged `main` into this before testing locally - looks good to me!

<img width="1579" alt="Screenshot 2025-04-29 at 12 40 05" src="https://github.com/user-attachments/assets/717da835-165e-4c7e-b874-7704b65eaa67" />

2025-04-29 11:44 UTC, kadikraman commented on packages/@expo/cli/src/start/doctor/android/AndroidPrerequisite.ts
> +    console.error(chalk.red`Cannot find {bold adb} hooked into PATH on this machine!`);
```suggestion
    console.error(chalk.red`Cannot find {bold adb} setup on this machine.`);
```

2025-04-29 11:44 UTC, kadikraman commented on packages/@expo/cli/src/start/doctor/android/AndroidPrerequisite.ts
> +      message: chalk`{bold Android SDK} needs to be installed, ANDROID_HOME set and correctly hooked up to PATH. Would you like to open Expo docs to learn more?`,
```suggestion
      message: chalk`The {bold Android SDK} needs to be installed before you can continue. Would you like to open Expo docs to learn more?`,
```

2025-04-29 13:48 UTC, byCedric requested changes

2025-04-29 13:48 UTC, byCedric commented on packages/@expo/cli/src/start/startAsync.ts
> +    await getXcodeVersionAsync({ silent: true });
Not awaiting this was intentional, see the logs above.

```suggestion
    getXcodeVersionAsync({ silent: true });
```

2025-04-29 13:48 UTC, byCedric commented on packages/@expo/cli/src/start/startAsync.ts
> +  }
I don't think we should assert `adb` is installed on `expo start`. I think `expo run android` definitely requires `adb`, but I think you don't actually need `adb` to start the app using Expo Go, right?

Have you tested the performance too? Might be good to understand if this adds 1s to the startup time, or if it's 100ms 😄

2026-05-12 16:57 UTC, brentvatne commented
Hi! This PR is being closed automatically as part of a cleanup of pull requests that are older than 6 months and haven't had any activity in the past 3 months. This isn't a reflection on the quality of the contribution — we just want to keep the open PR list focused on work that's actively moving forward.

If you're still interested in landing this, please feel free to reopen it (or open a fresh PR against the latest `main`) and ping me so we can take another look. Expo team members: same applies — reopen if you'd like to pick this back up.

Thanks for contributing to Expo!

2026-05-12 16:57 UTC, closed without merging