Replace android run.sh, build.sh, and make-release.sh with fastlane
expo/expo pull request #2759
Opened 2018-11-21 00:34 UTC by nicknovitski

2018-11-21 05:27 UTC, ide requested changes
See comments about whether the prod_release lane should build an APK or not.

2018-11-21 19:49 UTC, nicknovitski commented on android/shell.nix
> +  ANDROID_SDK_ROOT=builtins.getEnv("HOME") + (if stdenv.isDarwin then "/Library/Android/sdk" else "/Android/Sdk");
Yeah.  Weird, isn't it?  I'll add a comment.

2018-11-22 00:07 UTC, nicknovitski commented on .circleci/config.yml
>        - restore_cache:
I mistakenly thought that the restored apk would act as a build cache, and the prod_release step would mostly skip over the build, but I just determined locally that is not the case, so never mind.

We do want to keep a build job for building release builds and one releasing release builds.  Given that, there's no reason not to reuse the output of one as the input to the other.  I just erroneously believed I was still doing that.

2018-11-22 00:17 UTC, nicknovitski commented on fastlane/Fastfile
> +    build(build_type: "Release")
I've backed out this line.

2018-11-22 01:23 UTC, ide approved these changes

2018-11-22 02:12 UTC, merged