[expo-video] Enable transparency on Android
expo/expo pull request #27627
Opened 2024-03-13 14:20 UTC by kowczarz

# Why

# How

# Test Plan

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

2024-03-13 18:20 UTC, kowczarz commented
Cc. @behenate @lukmccall

2024-03-18 11:32 UTC, lukmccall requested changes

2024-03-18 11:32 UTC, lukmccall commented on packages/expo-video/android/src/main/java/expo/modules/video/transparent/TransparentVideoModule.kt
> +}
```suggestion
```

2024-03-18 11:32 UTC, lukmccall commented on packages/expo-video/android/src/main/java/expo/modules/video/transparent/TransparentVideoView.kt
> +  private val coroutineScope = CoroutineScope(Dispatchers.Main)
`coroutineScope` is too broad in my opinion, especially since it's linked to the UI thread.

2024-03-18 11:32 UTC, lukmccall commented on packages/expo-video/android/src/main/java/expo/modules/video/transparent/TransparentVideoView.kt
> +  }
```suggestion
  private val textureView = TextureView(context).apply {
    surfaceTexture?.let {
      onSurfaceTextureCreated(it)
    }
    surfaceTextureListener = GLTextureViewListener(coroutineScope, renderer, onFrameAvailable)
    isOpaque = false
    layoutParams = RelativeLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT)
  }
```

2024-03-18 11:32 UTC, lukmccall commented on packages/expo-video/android/src/main/java/expo/modules/video/transparent/TransparentVideoModule.kt
> +      return@Function TransparentVideoView.isPictureInPictureSupported()
```suggestion
      false
```

2024-03-18 11:32 UTC, lukmccall commented on packages/expo-video/android/src/main/java/expo/modules/video/transparent/TransparentVideoView.kt
> +  }
```suggestion
```

2024-03-18 11:32 UTC, lukmccall commented on packages/expo-video/android/src/main/java/expo/modules/video/transparent/glTexture/GLTextureViewListener.kt
> +    if (currentEGLHandler != null) return@execute
```suggestion
    if (currentEGLHandler != null) {
      return@execute
    }
```

2024-03-18 11:32 UTC, lukmccall commented on packages/expo-video/android/src/main/java/expo/modules/video/transparent/glTexture/GLTextureViewListener.kt
> +  }
```suggestion
  override fun onSurfaceTextureUpdated(surface: SurfaceTexture) = Unit
```

2024-10-31 15:28 UTC, closed without merging