@bbarthec/ar core
expo/expo pull request #2780
Opened 2018-11-23 15:09 UTC by bbarthec

# Why

Resolves https://github.com/expo/universe/issues/2927

# How

- [x] Added ARCore as Android AR library
- [x] Moved AR to module
- [x] Added `expo-three` as package (probably to be moved out)
- [x] Moved whole JS code to TS
- [x] Merged `expo-graphics` with `expo-ar` module. `expo-graphics` would not be needed anymore

# Test Plan

NCL has AR section for AR specific screens.

# Things to still be done:

- [ ] `expo-three` should possibly be not included in this repo
- [ ] iOS refactor & moving camera texture rendering to separate `shared GL Context` (as it's currently done on Android)
- [ ] iOS features that needs to be adapted on Android
- [ ] documentation
- [ ] `expo-three#AR.{MagneticObjects, Light, ShadowFloor, CubeTexture}, loaders & other functions` are not adapted nor tested
- [ ] missing ARKit features 
- [ ] missing ARCore features

2018-12-04 14:32 UTC, bbarthec commented
@tsapeta @sjchmiela @EvanBacon 
Please review this part of whole Android AR introduction.
The rest of functionalities that would came to your mind or are listed above would be made in separate PRs as this one's growing too much. Review with this fought in mind please 😉

2018-12-27 16:35 UTC, tsapeta requested changes
Left some comments about changes in `expo-gl` part. Looks good 💯, but generally I think the classes for main and shared contexts should be reduced to only what distinguishes them. Does it make sense?

2018-12-27 16:35 UTC, tsapeta commented on packages/expo-gl/android/src/main/java/expo/modules/gl/thread/GLSharedThread.java
> +    if (mEGLSurface == null || mEGLSurface == EGL10.EGL_NO_SURFACE) {
Is it possible that `mEGLSurface` would be `null` here? I'd recommend to use `EGL_NO_*` flags in all those functions that create EGL objects.

2018-12-27 16:35 UTC, tsapeta commented on packages/expo-gl/android/src/main/java/expo/modules/gl/thread/GLSharedThread.java
> +  private EGLSurface createEGLSurface(EGLDisplay eglDisplay, EGLConfig eglConfig) {
This code already exists in `GLThread.createSurface`. Maybe it should sit in `GLBaseThread` too? Imho everything that is not related to the `shared context` concept shouldn't be here.

2018-12-27 16:35 UTC, tsapeta commented on packages/expo-gl/android/src/main/java/expo/modules/gl/thread/GLSharedThread.java
> +    if (mEGLContext == null || mEGLContext == EGL10.EGL_NO_CONTEXT) {
As above, checking for `null` is probably unnecessary

2018-12-27 16:35 UTC, tsapeta commented on packages/expo-gl/android/src/main/java/expo/modules/gl/thread/GLSharedThread.java
> +  void deinitEGL() {
Could you try to merge this with `GLThread.deinitEGL`? 
I guess this should be the default implementation (`GLBaseThread`) and then the thread for the main context should call its superclass method and then call `eglTerminate`.

2019-01-02 22:33 UTC, EvanBacon commented on apps/native-component-list/package.json
> +    "three": "^0.98.0",
Make sure that this works with android. If I remember correctly there was some arithmetic error.

2019-01-02 22:39 UTC, EvanBacon commented on packages/expo-ar/src/lifecycle/index.ts
> +import { findNodeHandle } from 'react-native';
Is there a way to access this without `react-native`?

2019-05-20 21:14 UTC, tsapeta commented
Closing due to inactivity 🤷‍♂

2019-05-20 21:14 UTC, closed without merging