[WIP] Test module for validating expo-modules exception serialization
expo/expo pull request #27960
Opened 2024-03-31 18:14 UTC by cltnschlosser

# Why

https://github.com/expo/expo/issues/27959

# How

Created a new expo module with functions that return hardcoded exception from several different function implementations. Then writes a test that the exception matches expectations on the javascript side.

# Test Plan

Includes tests using `apps/test-suite`

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

2024-04-12 07:50 UTC, tsapeta requested changes
The changes for error codes looks good to me, however I'm a bit concerned about adding another standalone package just for these tests. I think I'll need to set up a better environment to add native modules to test-suite just for testing. Probably best if they are local modules.

That being said, can you remove the `expo-modules-exception-test` package from this PR and keep just the changes that are needed for error codes?

If you do want to provide some tests, you could add a simple test for `FunctionCallException` here: https://github.com/expo/expo/blob/main/packages/expo-modules-core/ios/Tests/ExceptionsSpec.swift (without going through the native module). Might be a good idea to add it inside `describe("FunctionCallException") {}`.

For a test that goes through different layers (DSL, native module, runtime, JS), take a look at these tests: https://github.com/expo/expo/blob/31f646a5fe93f36d62b262fab5f3edd1e5287feb/packages/expo-modules-core/ios/Tests/FunctionSpec.swift#L245
There is a mocked native module already. Sadly, we don't have an easy way to test AsyncFunction from unit tests yet – we'll need to write some helpers to conveniently work with promises, so that will be enough if you add a test only for a sync function.

These tests can be run from Xcode in bare-expo project. See below:
<img width="467" alt="Screenshot 2024-04-12 at 09 47 43" src="https://github.com/expo/expo/assets/1714764/58bf8595-cff7-44b2-b700-9bc4e91845f7">

Let me know if you need any more assistance on this!

2024-04-13 01:41 UTC, cltnschlosser commented
Okay, @tsapeta this should be ready for review, let me know what you think.

2024-04-14 07:14 UTC, tsapeta approved these changes
Looks good, thanks for taking care of that! Just apply my suggestion in the changelog and it's ready to go 👍

2024-04-14 07:14 UTC, tsapeta commented on packages/expo-modules-core/CHANGELOG.md
> +- [iOS] Provide Exception.code to javascript (as Error.code) for all types of functions. ([#27960](https://github.com/expo/expo/pull/27960) by [@cltnschlosser](https://github.com/cltnschlosser))
```suggestion
- [iOS] Provide Exception.code to JavaScript (as Error.code) for all types of functions. ([#27960](https://github.com/expo/expo/pull/27960) by [@cltnschlosser](https://github.com/cltnschlosser))
```

2024-04-14 07:14 UTC, tsapeta commented on packages/expo-modules-core/ios/JSI/EXJavaScriptRuntime.mm
> +        // instead of using the CodedError subclass.
I'll take a look what was wrong 👍 For now that's fine.

2024-04-14 08:28 UTC, cltnschlosser commented
> Looks good, thanks for taking care of that! Just apply my suggestion in the changelog and it's ready to go 👍

Not that I expect you to remember my preferences against everyone else’s, but I don’t mind if you accept the change yourself :)

2024-04-14 18:28 UTC, merged

2024-04-14 20:30 UTC, tsapeta commented
Would you mind if it comes out in SDK 51 (in less than a month, beta release pretty soon)? In other words, do you need this to be backported to SDK 50?

2024-04-14 20:36 UTC, cltnschlosser commented
SDK 51 is okay