[android][image-picker] fix getting filename and filesize from cropped images
expo/expo pull request #28352
Opened 2024-04-21 16:47 UTC by fobos531

# Why

Fixes https://github.com/expo/expo/issues/27554

# How

It seems like the current method for fetching filename and file size via contentResolver method results in null values. However, it seems like accessing the File object directly that is acquired via outputFile produces the desired result both with cropped images and original images.

# Test Plan

Tested on Pixel 8 Pro simulator with API 33. Untested on other API levels, but I believe this method should work on other API levels as well. Please let me know if that is not the case.

Note the filename and filesize values for both images with allowsEditing: false and allowsEditing: true

Before

https://github.com/expo/expo/assets/19533289/ca22ab26-1090-4198-9584-268903148d34

After

https://github.com/expo/expo/assets/19533289/0182fc8b-4b6a-49f2-9ed1-67dfb3e37b08

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [X] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

2024-04-21 19:13 UTC, alanjhughes requested changes
Hi @fobos531 - This solution is not correct. What you are returning for the filename is actually just a UUID appended to the file extension that we create when we create the output file, not the actual name of the file. 

The cause of the problem is the cropped image does not exist in the content resolver so the solution is to fallback to using the file as you have as this cropped image will only exist where we wrote it too.

2024-04-21 19:13 UTC, alanjhughes commented on packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/MediaHandler.kt
> +      fileSize = outputFile.length(),
```suggestion
      fileName = fileData?.fileName ?: outputFile.name,
      fileSize = fileData?.fileSize ?: outputFile.length(),
```

2024-04-21 19:13 UTC, alanjhughes commented on packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/MediaHandler.kt
> -    val fileData = getAdditionalFileData(sourceUri)
Restore this

2024-04-22 06:59 UTC, fobos531 commented
Hello @alanjhughes 

That makes sense! Feedback applied.

2024-04-22 07:03 UTC, alanjhughes approved these changes
Great! Thanks for the fix @fobos531

2024-04-22 08:59 UTC, lukmccall approved these changes
Looks good! Thanks for your contribution🥇

2024-04-22 08:59 UTC, merged