Fix ExpoAsset.web.ts
expo/expo pull request #28405
Opened 2024-04-23 22:57 UTC by jamiees2

# Why

This function doesn't match the declaration in ExpoAsset.ts, since the resulting object is `{ default: { downloadAsync: ... }}` instead of `{ downloadAsync: ... }` like ExpoAsset. 

This causes the error `(0, _ExpoAsset.downloadAsync) is not a function` when trying to develop with Expo web.

# How

By updating the signature of ExpoAsset.web to match the definition of ExpoAsset

# Test Plan

After running `Asset.loadAsync([require("image.png"])` on Expo web, this previously failed with the aforementioned error, after this patch, it succeeds.

# Checklist

- [ x ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ x ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ x ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

2024-04-23 23:05 UTC, tsapeta requested changes
Thanks for fixing this! Could you also run `yarn build` in the package folder to rebuild JS files?

2024-04-23 23:05 UTC, tsapeta commented on packages/expo-asset/CHANGELOG.md
> +- Fix `TypeError: (0, _ExpoAsset.downloadAsync) is not a function` when loading assets using Expo Web. ([#28405](https://github.com/expo/expo/pull/28405) by [@jamiees2](https://github.com/jamiees2))
```suggestion

- Fix `TypeError: (0, _ExpoAsset.downloadAsync) is not a function` when loading assets using Expo Web. ([#28405](https://github.com/expo/expo/pull/28405) by [@jamiees2](https://github.com/jamiees2))
```

2024-04-23 23:12 UTC, jamiees2 commented
Done :)

2024-04-23 23:13 UTC, tsapeta approved these changes
Great, thank you!

2024-04-23 23:21 UTC, tsapeta commented
Looks like the formatting also needs to be fixed, see the CI job that failed: https://github.com/expo/expo/actions/runs/8808424372/job/24177500392?pr=28405

2024-04-24 00:20 UTC, jamiees2 commented
ah, that's been fixed now :)

2024-04-24 16:45 UTC, wschurman approved these changes

2024-04-24 16:47 UTC, wschurman commented
Looks like the `check-packages` test is still having issues. Running `et cp expo-asset` and then committing the result should fix it. I'll merge once that check is passing. Don't worry about the other checks (Updates e2e) since those need to be run by a expo employee.

2024-04-24 20:45 UTC, merged