[dev-launcher][updates] fix loading error when no runtimeVersion specified
expo/expo pull request #28662
Opened 2024-05-07 19:38 UTC by Kudo

# Why

fix loading error with expo-dev-client and expo-updates installed but no runtimeVersion configured

# How

add a `validateUpdate(withConfiguration)` function to validate updates configuration beforehand. if failed, just using dev-launcher's local loader to load the app.

# Test Plan

```sh
$ yarn create expo -t blank@sdk-51 sdk51
$ cd sdk51
$ npx expo install expo-dev-client expo-updates
$ npx expo run:ios
$ npx expo run:android
```

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

2024-05-07 20:45 UTC, lukmccall approved these changes

2024-05-07 20:50 UTC, gabrieldonadel approved these changes

2024-05-07 23:54 UTC, wschurman requested changes
Main comment is about the change in error semantics on android.

2024-05-07 23:54 UTC, wschurman commented on packages/expo-updates/android/src/main/java/expo/modules/updates/UpdatesDevLauncherController.kt
> +    val newUpdatesConfiguration = validateConfig(configuration, context)
Previously this would call the callback with the exception? It throws now. I just want to make sure that that's expected?

2024-05-07 23:54 UTC, wschurman commented on packages/expo-updates-interface/android/src/main/java/expo/modules/updatesinterface/UpdatesInterface.kt
> +  fun validateUpdateWithConfiguration(configuration: HashMap<String, Any>, context: Context): Boolean
```suggestion
  fun isValidUpdatesConfiguration(configuration: HashMap<String, Any>, context: Context): Boolean
```

2024-05-07 23:54 UTC, wschurman commented on packages/expo-updates-interface/ios/EXUpdatesInterface/UpdatesExternalInterface.swift
> +  @objc func validateUpdate(withConfiguration configuration: [String: Any]) -> Bool
```suggestion
  @objc func isUpdatesConfigurationValid(_ configuration: [String: Any]) -> Bool
```

2024-05-07 23:54 UTC, wschurman commented on packages/expo-updates/android/src/main/java/expo/modules/updates/UpdatesDevLauncherController.kt
> +  private fun validateConfig(configuration: HashMap<String, Any>, context: Context): UpdatesConfiguration {
```suggestion
  private fun createUpdatesConfiguration(configuration: HashMap<String, Any>, context: Context): UpdatesConfiguration {
```

2024-05-07 23:54 UTC, wschurman commented on packages/expo-updates/ios/EXUpdates/DevLauncherAppController.swift
> +  private func validateConfig(_ configuration: [String: Any]) throws -> UpdatesConfig {
```suggestion
  private func createUpdatesConfig(_ configuration: [String: Any]) throws -> UpdatesConfig {
```

2024-05-07 23:54 UTC, wschurman commented on packages/expo-dev-launcher/android/src/debug/java/expo/modules/devlauncher/launcher/loaders/DevLauncherAppLoaderFactory.kt
> +      if (updatesInterface == null || updatesInterface?.validateUpdateWithConfiguration(configuration, context) == false) {
I don't remember if kotlin allows this, but if so:

```suggestion
      if (updatesInterface == null || !updatesInterface.isValidUpdatesConfiguration(configuration, context)) {
```

2024-05-08 04:44 UTC, Kudo commented
> Main comment is about the change in error semantics on android.

good catch for the missing exception catcher and also great naming recommendation. updated the pr accordingly and add log from isValidUpdatesConfiguration

2024-05-08 15:55 UTC, wschurman approved these changes

2024-05-08 16:33 UTC, merged