[fingerprint] skip version from app config
expo/expo pull request #28712
Opened 2024-05-09 10:57 UTC by Kudo

# Why

i've heard different feedback that they would like to ignore fingerprinting `version` from app.json. in their workflow they would bump version in app.json for simply for updates.
references:
- https://discord.com/channels/695411232856997968/1214250595641466940/1234569102631108661
- https://discord.com/channels/695411232856997968/1232785567352225902/1237380679935721513

# How

- introducing the `sourceSkips` bitwise flags that would potentially support more aggresive fingerprint for app repacking.
- currently by default the sourceSkips is `const DEFAULT_SOURCE_SKIPS = SourceSkips.AppConfigVersion | SourceSkips.AppConfigRuntimeVersion;`

# Test Plan

add some unit tests and ci passed

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

2024-05-10 17:47 UTC, wschurman requested changes
Notes:
- Need to think through how people will configure this who don't have access to the JS API (a file similar to `.fingerprintignore` maybe? how will the two interact?)
- If we do go with the skips pattern, I think some of the items should probably be separated into their own skip enum option.

2024-05-14 01:43 UTC, brentvatne commented on packages/@expo/fingerprint/src/Options.ts
> +const DEFAULT_SOURCE_SKIPS = SourceSkips.AppConfigVersion | SourceSkips.AppConfigRuntimeVersion;
i generally agree with @wschurman that we probably want to keep this list pretty small - although, i think we could get away with using the app version by default here, and i wouldn't be opposed to shipping that as-is.

for anything beyond that, an approach for controlling ignores via something like **.fingerprintignore** (such as **fingerprint.config.js**) would be great - @Kudo brought this up on our sync today and i think we're on the same page. we could express our defaults in a version of that file that we create for people when they init fingerprint in their project.

2024-05-15 18:38 UTC, Kudo commented on packages/@expo/fingerprint/src/Fingerprint.types.ts
> +  None = 1 << 0,
good catch! that makes 100% sense.

2024-05-15 18:39 UTC, Kudo commented on packages/@expo/fingerprint/src/Fingerprint.types.ts
> +  AppConfigName = 1 << 3,
this would be basically used for app repacking and i don't want to introduce too many options. let's use `ExpoConfigNames` for that.

2024-05-15 18:40 UTC, Kudo commented on packages/@expo/fingerprint/src/sourcer/Expo.ts
> +    normalizedConfig.slug = '';
during prebuild we will actually generate an implicit scheme based on slug.

2024-05-15 18:50 UTC, Kudo commented
update the pr based on the feedback
- default to `SourceSkips.None` and people could configure through fingerprint.config.js
- refactor the config tests a little bit to use true config contents for testing. there's now a test to indicate the config test
  ```ts
    it('should support sourceSkips from config', async () => {
      await jest.isolateModulesAsync(async () => {
        vol.fromJSON(require('./fixtures/ExpoManaged47Project.json'));
        vol.writeFileSync(
          '/app/app.config.js',
          `\
  export default ({ config }) => {
    config.android = { versionCode: 1, package: 'com.example.app' };
    config.ios = { buildNumber: '1', bundleIdentifier: 'com.example.app' };
    return config;
  };`
        );
  
        const configContents = `\
  const { SourceSkips } = require('@expo/fingerprint');
  /** @type {import('@expo/fingerprint').Config} */
  const config = {
    sourceSkips: SourceSkips.ExpoConfigAndroidPackage | SourceSkips.ExpoConfigIosBundleIdentifier | SourceSkips.ExpoConfigVersions,
  };
  module.exports = config;
  `;
        vol.writeFileSync('/app/fingerprint.config.js', configContents);
        jest.doMock('/app/fingerprint.config.js', () => requireString(configContents), {
          virtual: true,
        });
  
        const sources = await getExpoConfigSourcesAsync('/app', await normalizeOptionsAsync('/app'));
        const expoConfigSource = sources.find<HashSourceContents>(
          (source): source is HashSourceContents =>
            source.type === 'contents' && source.id === 'expoConfig'
        );
        const expoConfig = JSON.parse(expoConfigSource?.contents?.toString() ?? 'null');
        expect(expoConfig).not.toBeNull();
        expect(expoConfig.version).toBeUndefined();
        expect(expoConfig.android.versionCode).toBeUndefined();
        expect(expoConfig.android.package).toBeUndefined();
        expect(expoConfig.ios.buildNumber).toBeUndefined();
        expect(expoConfig.ios.bundleIdentifier).toBeUndefined();
      });
    });
  ```

2024-05-16 22:11 UTC, wschurman approved these changes

2024-05-17 05:37 UTC, merged