[clipboard] fixed href in type definitions
expo/expo pull request #29011
Opened 2024-05-21 08:03 UTC by mrakesh0608

# Why

Hyperlinks are working in type definitions.

https://github.com/expo/expo/assets/101246871/9080d449-b6e6-4557-abb6-01dd83f98b48

# How

Changed to absolute hyperlinks.

# Test Plan

Tested Locally.

2024-05-21 09:09 UTC, Simek requested changes
So far we prefer docs correctness ove IDE annotations due to some technical limitations on TypeDoc side, but lately I have introduced back the JSDoc standard notation (`@link`), which should be used for internal links onwards. 

Using the full URL will lead to unwanted full page reload on the docs side, since we use JSDoc to generate docs data.

See:
* https://github.com/expo/expo/pull/28516
* https://jsdoc.app/tags-inline-link

2024-05-21 19:23 UTC, mrakesh0608 commented
@Simek  I tried every combination of @link tag, but none of them worked.

In each of the following cases, the `href` of the `setStringAsync` method in `setString`'s type definition is always `#setstringasynctext-options` in the docs (when running the docs locally).

![A](https://github.com/expo/expo/assets/101246871/4443af58-fb57-4b93-bb5b-e884c77de4ba)

![B](https://github.com/expo/expo/assets/101246871/e4954acb-fee0-4f36-b07a-5121d16d05ef)

![C](https://github.com/expo/expo/assets/101246871/16ee048c-b2df-4364-880d-97c4cad799a0)

![D](https://github.com/expo/expo/assets/101246871/85a0c26f-e155-4063-b681-f4957c9cbac6)

2024-05-22 09:58 UTC, Simek commented
@mrakesh0608 Thank you so much for the investigation and posting a full report of it. I really appreciate it, it's awesome! 🙏 

The work you have done started to remind me about more quirks and incompatibilities between JSDoc standard and TypeDoc implementation. Look like the one JSDoc notation which should actually work for us (i.e. `MyClass's foo property]{@link MyClass#foo}`) is not supported by TypeDoc for some reason (we are missing the link between the actual link and it's display value):
* https://typedoc.org/tags/link/

ATM, I think that there is no easy solution to achieve what we want without altering the TypeDoc comments tokenization or adding an another custom `@link` notation (which is out of spec). I have some other topics on my plate currently, but I can look at this more deeply soon, sorry that it has been a trial of errors for you and there is no straightforward way to generate useful links for both docs and IDEs. Hopefully, we can change it in near future.

2024-05-22 11:31 UTC, mrakesh0608 commented
@Simek I think I have some idea, see if this works. 

If we use absolute URLs in type definitions, it will work with IDEs without any problem.

After generating the docs API JSON data using this [https://github.com/expo/expo/blob/main/tools/src/commands/GenerateDocsAPIData.ts](https://github.com/expo/expo/blob/main/tools/src/commands/GenerateDocsAPIData.ts). 

In that JSON file, if we replace every absolute URL related to that package with the part after `#`.

For example, generated docs API as following content.

```json
{
    "blockTags": [
        {
            "tag": "@deprecated",
            "content": [
                {
                    "kind": "text",
                    "text": "Use [setStringAsync()](https://docs.expo.dev/versions/latest/sdk/clipboard/#setstringasynctext-options) instead."
                }
            ]
        },
        {
            "tag": "@returns",
            "content": [
                {
                    "kind": "text",
                    "text": "On web, this returns a boolean value indicating whether or not the string was saved to\nthe user's clipboard. On iOS and Android, nothing is returned."
                }
            ]
        }
    ]
}
```

Package Name : `expo-clipboard`
Absolute URL Prefix : `https://docs.expo.dev/versions/latest/sdk/clipboard/`

So, here we will match every text property using [includes()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes) method with absolute URL Prefix, if matches will replace it by section id of that absolute URL.

After : 

```json
{
    "blockTags": [
        {
            "tag": "@deprecated",
            "content": [
                {
                    "kind": "text",
                    "text": "Use [setStringAsync()](#setstringasynctext-options) instead."
                }
            ]
        },
        {
            "tag": "@returns",
            "content": [
                {
                    "kind": "text",
                    "text": "On web, this returns a boolean value indicating whether or not the string was saved to\nthe user's clipboard. On iOS and Android, nothing is returned."
                }
            ]
        }
    ]
}
```

But, it will need to change almost every package which is quite tedious task 😅.

2024-05-22 12:17 UTC, Simek commented
That's a great idea! Let me explore it and make sure that it also also cover some known edge-cases we already have.

> But, it will need to change almost every package which is quite tedious task 😅.

No worries, if this solves the issue and improves a DX we will plough through needed changes.

2026-05-12 21:19 UTC, brentvatne commented
Hi! This PR is being closed automatically as part of a cleanup of pull requests that are older than 6 months and haven't had any activity in the past 3 months. This isn't a reflection on the quality of the contribution — we just want to keep the open PR list focused on work that's actively moving forward.

If you're still interested in landing this, please feel free to reopen it (or open a fresh PR against the latest `main`) and ping me so we can take another look. Expo team members: same applies — reopen if you'd like to pick this back up.

Thanks for contributing to Expo!

2026-05-12 21:19 UTC, closed without merging