fix: compile getFreeDiskStorage on tvOS
expo/expo pull request #29891
Opened 2024-06-20 09:34 UTC by vonovak

# Why

well, I was being sloppy and merged https://github.com/expo/expo/pull/29873 prematurely

# How

use only symbols available on the platform

# Test Plan

I did get the tvOS simulator but somehow can't get bare expo to build 🤔 

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

2024-06-20 14:01 UTC, tsapeta reviewed
I think the code is now a bit more complicated. Can't we add another `#if #else` around the guard?

2024-06-20 14:23 UTC, vonovak commented
It'll be a little more repetitive but I'll add it 👍.

2024-06-20 14:29 UTC, tsapeta commented
In that case I think it's better to repeat some code rather than complicating it for all platforms. Especially now that Xcode dims the code within compiler directives that will not be used in the currently used target/schema – it's just easier to read.

2024-06-20 16:52 UTC, douglowder requested changes
See inline

2024-06-20 16:52 UTC, douglowder commented on packages/expo-file-system/ios/FileSystemModule.swift
> +      let resourceValues = try getResourceValues(from: documentDirectory, forKeys: [.volumeAvailableCapacityKey])
In tvOS, `.documentDirectory` is not available for writing. You should probably be checking `.cachesDirectory` instead.

2024-06-21 00:49 UTC, douglowder approved these changes

2024-06-21 00:50 UTC, merged