Fixed creation of a contact with a birthday on Android
expo/expo pull request #30132
Opened 2024-07-02 14:08 UTC by Eric013

# Why

Fix #30131 

# How

I use expo-contacts to create contacts with birthday dates and I've noticed that when I specify a date in my Contact it doesn't work (not taken into account or the contact isn't created).

# Test Plan

By using addContactAsync with a contact of type Contact with and without a date property attached to the contact

```
import type { Contact} from 'expo-contacts';
import {
  addContactAsync,
} from 'expo-contacts';
...
const contact: Contact = {
    id: "ID",
    contactType: 'person',
    firstName: firstName ?? '',
    lastName: lastName ?? '',
    ...
    name: `${firstName ?? ''} ${lastName ?? ''}`,
    dates: birthdayDate
      ? [
          {
            label: 'birthday',
            year: birthdayDate?.getFullYear(),
            month: birthdayDate?.getMonth(),
            day: birthdayDate?.getDate(),
            id: `${profileId}-birthday`,
          },
        ]
      : [],
    urlAddresses: (userName
      ? [
          {
            label: 'azzapp',
            url: buildUserUrl(userName),
            id: `${profileId}-azzapp`,
          },
        ]
      : []
    )
  };
...
await addContactAsync(contact);
```

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

2024-07-03 14:20 UTC, vonovak requested changes
Thank you for the PR.

With this change, the code does more work than necessary:

In `fromMap` it takes individual map entries to convert them into string in `parseDateFromMap`.
Then it takes the string and parses it back into the individual numbers using `SimpleDateFormat.parse`. It can just take the input directly, no?

Also, note that looking at the code, it seems that `year` is optional. Maybe other fields are as well. Let's try to make the code work without the `year` field being provided.

Finally, would you mind creating a [test case here](https://github.com/expo/expo/blob/main/apps/test-suite/tests/Contacts.js)?

Thank you!

2024-08-30 19:30 UTC, mlecoq commented
> Thank you for the PR.
> 
> With this change, the code does more work than necessary afaict:
> 
> In `fromMap` it takes individual map entries to convert them into string in `parseDateFromMap`. Then it takes the string and parses it back into the individual numbers using `SimpleDateFormat.parse`. It can just take the input directly, no?
> 
> Also, note that looking at the code, it seems that `year` is optional. Maybe other fields are as well. Let's try to make the code work without the `year` field being provided.
> 
> Finally, would you mind creating a [test case here](https://github.com/expo/expo/blob/main/apps/test-suite/tests/Contacts.js)?
> 
> Thank you!

Hi @vonovak, following your suggestions I have made some updates. 

Thanks,
Mickael

2024-10-01 06:37 UTC, vonovak commented on packages/expo-contacts/android/src/main/java/expo/modules/contacts/Contact.kt
> +            val datePattern = SimpleDateFormat("yyyy-MM-dd", Locale.US)
nothing wrong with `Locale.getDefault()` in this case, but I pinned it to `Locale.US` to make it "raise no questions" if that makes sense.

2024-10-01 06:37 UTC, vonovak approved these changes

2024-10-01 08:01 UTC, lukmccall approved these changes
LGTM

2024-10-01 10:20 UTC, merged

2024-10-01 10:21 UTC, vonovak commented
@Eric013 thank you for contributing and thank you for your patience with review! 👍