[apps] initial theming support
expo/expo pull request #30292
Opened 2024-07-09 14:35 UTC by Simek

# Why

Experiment introducing theming support in the workspace apps (Bare Expo, NCL and Test Suite).

# How

TBD

# Test Plan

TBD

2024-07-09 22:23 UTC, tsapeta reviewed
Looks great so far! 👏

2024-08-07 21:31 UTC, tsapeta requested changes

2024-08-07 21:31 UTC, tsapeta commented on apps/common/ThemeProvider.tsx
Not sure if making a `common` directory here is a good idea (it's not an app). Can you temporarily copy these two files to both test-suite and NCL?

2024-08-07 21:31 UTC, tsapeta commented on apps/common/ThemeToggler.tsx
> +export function ThemeToggle() {
ThemeToggle or ThemeToggler (as the file name)? Maybe it should be a default export?

2024-08-08 07:17 UTC, Simek commented on apps/common/ThemeProvider.tsx
The extraction was needed to properly sync the themes between various navigators, is separated,, there was multiple different theme context, and toggling one did not affect other IIRC. Will retest this later today.

2024-08-09 08:34 UTC, tsapeta approved these changes

2024-08-12 09:14 UTC, merged