@bbarthec/splash screen standalone app
expo/expo pull request #3029
Opened 2018-12-20 07:42 UTC by bbarthec

# Why

Resolves expo/expo#2533
Corresponding docs for https://github.com/expo/expo-cli/pull/268

2018-12-20 07:44 UTC, bbarthec commented on docs/versions/unversioned/sdk/splash-screen.md
> +## Example without any flickering between SplashScreen and it's later continuation
This is only explicit change I've made, all the rest is just auto-behaviour of my IDE

2018-12-20 07:45 UTC, bbarthec commented on docs/versions/unversioned/workflow/configuration.md
> +        Determines how the "image" will be displayed in the splash loading screen.
My explicit changes are here, the rest is just out-fixing made by my IDE

2018-12-20 08:52 UTC, tsapeta requested changes
Added suggestions about some typos 😉

2018-12-20 08:52 UTC, tsapeta commented on docs/versions/unversioned/guides/splash-screens.md
> +- **cover** - In this mode Expo is leveraging Android possibility to present static bitmap at the very beginning of the application start. Unfortunately Android (unlike iOS) is not supporting provide
```suggestion
- **cover** - In this mode Expo is leveraging Android possibility to present static bitmap at the very beginning of the application start. Unfortunately Android (unlike iOS) is not supporting provided image stretching, so Expo will just present given image centered on the screen.
```

2018-12-20 08:52 UTC, tsapeta commented on docs/versions/unversioned/guides/splash-screens.md
> +By default `splash.image` would be used as `mdpi` resource. It's up to you to provide graphics that meet your expectations and fits the screen dimension. To achieve this use different resolutions for
```suggestion
By default `splash.image` would be used as `mdpi` resource. It's up to you to provide graphics that meet your expectations and fit the screen dimension. To achieve this, use different resolutions for [different device DPIs](configuration.html#mdpi), from `mdpi` to `xxxhdpi`.
```

2018-12-20 08:52 UTC, tsapeta commented on docs/versions/unversioned/guides/splash-screens.md
> +- **contain** - As described in _cover_ mode we're unable to dynamicly adjust image to screen size at the very beginning of the application start. Therefore in this mode only background color will be
```suggestion
- **contain** - As described in _cover_ mode we're unable to dynamically adjust image to screen size at the very beginning of the application start. Therefore in this mode only background color will be presented and a while later when some view hierarchy is mounted we'll show provided `splash.image`.
```

2019-01-02 22:44 UTC, esamelson reviewed
Looks good, can you make sure to add a CHANGELOG entry as well since this may be a breaking change for people (they may need to switch from "contain" to "cover" or vice versa)?

2019-01-08 15:02 UTC, sjchmiela reviewed
Nice one, I don't know if all my suggestions make sense. Nice job! 💯

2019-02-06 13:46 UTC, merged