[Web] Updated Location module for TestSuite
expo/expo pull request #3075
Opened 2018-12-28 02:54 UTC by EvanBacon

* made `setApiKey` accessible
* made the geocoding errors clearer on web/android
* added `hasServicesEnabledAsync` to the `ExpoLocation` module

2018-12-29 13:07 UTC, tsapeta requested changes

2018-12-29 13:07 UTC, tsapeta commented on packages/expo-location/src/ExpoLocation.web.ts
> +    return false;
`return 'geolocation' in navigator;` will be better here. See https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API#The_geolocation_object
It's the same value as returned by `(await getProviderStatusAsync()).locationServicesEnabled` - I just wanted to make more convenient API for checking this thing 😉

2019-01-01 20:22 UTC, tsapeta approved these changes

2019-01-02 19:56 UTC, ide approved these changes

2019-01-02 22:44 UTC, EvanBacon commented on packages/expo-location/src/Location.ts
> +    // TODO: This is missing a lot of props
[expo-location] Geocoding with Google Maps API is incomplete
#3089

2019-01-04 05:02 UTC, merged