Convert SpeechModule into universal module
expo/expo pull request #3091
Opened 2019-01-02 11:24 UTC by Szymon20000

# Why

resolves https://github.com/expo/expo/issues/3077

# How

- https://github.com/expo/expo/blob/master/guides/Creating%20Universal%20Modules.md

# Test Plan

Run TextToSpeechScreen in NCL

2019-01-08 13:08 UTC, sjchmiela reviewed
Thanks! 👏

2019-01-08 13:08 UTC, sjchmiela commented on packages/expo-speech/android/src/main/java/expo/modules/speech/SpeechPackage.java
> +}
Again, I think there should be a new line at the end of file

2019-01-08 13:08 UTC, sjchmiela commented on packages/expo-speech/ios/EXSpeechModule.podspec
> +  s.name           = 'EXSpeechModule'
Hm… Shouldn't this be `EXSpeech`?

2019-01-08 13:08 UTC, sjchmiela commented on packages/expo-speech/ios/EXSpeechModule.xcodeproj/project.pbxproj
> +// !$*UTF8*$!
Remove `xcodeproj`

2019-01-08 13:08 UTC, sjchmiela commented on packages/expo-speech/ios/EXSpeechModule/EXSpeech.h
> +#import <EXCore/EXExportedModule.h>
```suggestion
// Copyright 2015-present 650 Industries. All rights reserved.

#import <EXCore/EXExportedModule.h>
```

2019-01-08 13:08 UTC, sjchmiela commented on packages/expo/src/Expo.ts
> +export { Speech } from 'expo-speech';
I think we would like to keep the `import *, export` notation to let dead-code eliminators do their job

2019-01-08 13:08 UTC, sjchmiela commented on packages/expo-speech/src/index.ts
> +import * as Speech from './Speech/Speech';
Remove this file and point `main` to `Speech/Speech` 🙂

2019-01-08 13:08 UTC, sjchmiela commented on packages/expo-speech/src/index.ts
> +import * as Speech from './Speech/Speech';
For explanation see discussion at https://github.com/expo/expo/pull/2920/files/7ea7e9f76e0a1f1c0b3d321493ac8d607293d049#diff-4b06aa1fcb81c39457d7f817740f39ab

2019-01-08 13:08 UTC, sjchmiela commented on packages/expo-speech/ios/EXSpeechModule/EXSpeech.m
> +  id<EXEventEmitterService> emiter = [_moduleRegistry getModuleImplementingProtocol:@protocol(EXEventEmitterService)];
```suggestion
  id<EXEventEmitterService> emitter = [_moduleRegistry getModuleImplementingProtocol:@protocol(EXEventEmitterService)];
```

2019-01-08 13:08 UTC, sjchmiela commented on packages/expo-speech/ios/EXSpeechModule/EXSpeech.m
> +  if (emiter != nil) {
In ObjC calling methods on `nil` is _safe_, so we don't need to `if` this, but it's ok to leave it as far as I'm concerned

2019-01-08 13:08 UTC, sjchmiela commented on packages/expo-speech/ios/EXSpeechModule/EXSpeech.m
> +  id<EXEventEmitterService> emiter = [_moduleRegistry getModuleImplementingProtocol:@protocol(EXEventEmitterService)];
```suggestion
  id<EXEventEmitterService> emitter = [_moduleRegistry getModuleImplementingProtocol:@protocol(EXEventEmitterService)];
```

2019-01-08 13:08 UTC, sjchmiela commented on packages/expo-speech/ios/EXSpeechModule/EXSpeech.m
> +  id<EXEventEmitterService> emiter = [_moduleRegistry getModuleImplementingProtocol:@protocol(EXEventEmitterService)];
```suggestion
  id<EXEventEmitterService> emitter = [_moduleRegistry getModuleImplementingProtocol:@protocol(EXEventEmitterService)];
```

2019-01-15 15:23 UTC, tsapeta requested changes
Left some comments, but looks good 💯 

Could you also rename `stop`, `pause` and `resume` methods by adding `Async` suffix to them as they return promises? The old names should still work for at least one SDK version, but calling these functions should warn that they might be removed soon.

Also, please make sure they all have `async` keyword so `UnavailabilityError` is not thrown synchronously.

2019-01-21 16:13 UTC, tsapeta approved these changes
Looks good to me! 💯 
After some discussions, we will be fixing some other comments in a separate PR. This one is ready to go anyway 😉

2019-01-22 13:05 UTC, merged