[sdk] screen orientation js
expo/expo pull request #3103
Opened 2019-01-04 11:23 UTC by quinlanj

# Why

ScreenOrientation JS portion

Related PRS:

2019-01-15 04:00 UTC, ide requested changes
I would really like to see Jest tests for this module, especially where there is meaningful logic or tricky edge cases.

2019-01-26 02:03 UTC, esamelson requested changes
agree with @ide's comments and adding a few more, but most of this looks great 🙏

2019-01-29 19:19 UTC, ide requested changes

2019-01-29 19:38 UTC, quinlanj commented on packages/expo/src/ScreenOrientation/ScreenOrientation.ts
> +  verticalSizeClass?: iOSSizeClass;
you are correct -- good catch! the iOSSizeClasses are meant to be REGULAR/COMPACT, and each iOS device has a sizeClass for the vertical and horizontal axis

2019-01-31 00:19 UTC, merged