[core] Removed all `NativeModulesProxy` occurrences
expo/expo pull request #31496
Opened 2024-09-16 13:02 UTC by reichhartd

# Why

In order to remove `NativeModulesProxy` from `expo-modules-core` in the future, I have replaced the use of it in all other packages.

# How

I have replaced all occurrences of the deprecated `NativeModulesProxy`.

I have left the export of `NativeModulesProxy` in the `index.ts` of `expo-modules-core`, but can remove it if it is not too early.

# Test Plan

Test cases run.

# Checklist

- [X] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [X] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [X] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

2024-09-16 14:13 UTC, tsapeta requested changes
Great, thank you so much! 🙏 I left some changelog suggestions, but in general it looks good.
Recently I had some troubles to move off of `NativeModulesProxy` in `expo-font` tests, but looks like they are passing now – which is great 👍

2024-09-16 14:13 UTC, tsapeta commented on packages/expo-modules-core/CHANGELOG.md
> +- Removed all `NativeModulesProxy occurrences. ([#31496](https://github.com/expo/expo/pull/31496) by [@reichhartd](https://github.com/reichhartd))
```suggestion
- Removed all `NativeModulesProxy` occurrences. ([#31496](https://github.com/expo/expo/pull/31496) by [@reichhartd](https://github.com/reichhartd))
```

2024-09-16 14:13 UTC, tsapeta commented on packages/expo-screen-orientation/CHANGELOG.md
> +- Removed all `NativeModulesProxy occurrences. ([#31496](https://github.com/expo/expo/pull/31496) by [@reichhartd](https://github.com/reichhartd))
```suggestion
- Removed all `NativeModulesProxy` occurrences. ([#31496](https://github.com/expo/expo/pull/31496) by [@reichhartd](https://github.com/reichhartd))
```

2024-09-16 14:13 UTC, tsapeta commented on packages/expo-secure-store/CHANGELOG.md
> +- Removed all `NativeModulesProxy occurrences. ([#31496](https://github.com/expo/expo/pull/31496) by [@reichhartd](https://github.com/reichhartd))
```suggestion
- Removed all `NativeModulesProxy` occurrences. ([#31496](https://github.com/expo/expo/pull/31496) by [@reichhartd](https://github.com/reichhartd))
```

2024-09-16 14:13 UTC, tsapeta commented on packages/expo-sms/CHANGELOG.md
> +- Removed all `NativeModulesProxy occurrences. ([#31496](https://github.com/expo/expo/pull/31496) by [@reichhartd](https://github.com/reichhartd))
```suggestion
- Removed all `NativeModulesProxy` occurrences. ([#31496](https://github.com/expo/expo/pull/31496) by [@reichhartd](https://github.com/reichhartd))
```

2024-09-16 14:13 UTC, tsapeta commented on packages/expo-constants/CHANGELOG.md
> +- Removed all `NativeModulesProxy occurrences. ([#31496](https://github.com/expo/expo/pull/31496) by [@reichhartd](https://github.com/reichhartd))
```suggestion
- Removed all `NativeModulesProxy` occurrences. ([#31496](https://github.com/expo/expo/pull/31496) by [@reichhartd](https://github.com/reichhartd))
```

2024-09-16 14:13 UTC, tsapeta commented on packages/expo-font/CHANGELOG.md
> +- Removed all `NativeModulesProxy occurrences. ([#31496](https://github.com/expo/expo/pull/31496) by [@reichhartd](https://github.com/reichhartd))
```suggestion
- Removed all `NativeModulesProxy` occurrences. ([#31496](https://github.com/expo/expo/pull/31496) by [@reichhartd](https://github.com/reichhartd))
```

2024-09-16 14:13 UTC, tsapeta commented on packages/expo-maps/CHANGELOG.md
> +- Removed all `NativeModulesProxy occurrences. ([#31496](https://github.com/expo/expo/pull/31496) by [@reichhartd](https://github.com/reichhartd))
```suggestion
- Removed all `NativeModulesProxy` occurrences. ([#31496](https://github.com/expo/expo/pull/31496) by [@reichhartd](https://github.com/reichhartd))
```

2024-09-17 00:02 UTC, reichhartd commented
You're welcome 🙏
Is it too early to remove the export of `NativeModulesProxy` in the `index.ts` of `expo-modules-core`? Since it would be a breaking change.

2024-09-17 10:57 UTC, tsapeta commented
Yeah, I think it's too early. We'll probably need to search over GitHub to see if there are any popular libraries importing it and help them migrate. I would keep it until we entirely remove the legacy modules from the native code.

One more thing we could do is to make it a `Proxy` object and log a warning in its getter, so it's easier to identify places where the deprecated API is used.

2024-09-17 10:58 UTC, tsapeta approved these changes

2024-09-17 10:59 UTC, merged