[expo-notifications][iOS] Plugin should not overwrite existing aps-entitlement
expo/expo pull request #31892
Opened 2024-10-06 22:31 UTC by douglowder

# Why

# How

# Test Plan

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

2024-10-06 22:31 UTC, douglowder commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/expo/expo/31892?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#31892** <a href="https://app.graphite.dev/github/pr/expo/expo/31892?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#31856** <a href="https://app.graphite.dev/github/pr/expo/expo/31856?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @douglowder and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-10-07 06:03 UTC, vonovak approved these changes

2024-10-07 06:04 UTC, vonovak requested changes
@douglowder lets open this as a ~separate PR on top of main~ (only if the downstack PR isn't ready), with changelog entry?

2024-10-07 07:23 UTC, douglowder commented
The downstack PR is ready, actually

2024-10-07 07:27 UTC, douglowder commented
Restacked to main

2024-10-07 07:29 UTC, vonovak commented
> Restacked to main

Thanks, I believe that's better. Let's just add a changelog entry please 🙏

2024-10-07 07:55 UTC, vonovak approved these changes

2024-10-07 19:11 UTC, douglowder commented
### Merge activity

* **Oct 7, 3:11 PM EDT**: @douglowder started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/expo/expo/31892).

2024-10-07 19:11 UTC, merged