[audio] Add initial docs for alpha release
expo/expo pull request #32278
Opened 2024-10-23 15:38 UTC by alanjhughes

# Why
Adds the initial version of the `expo-audio` docs for the alpha release. 

# How
Same approach as what we did for expo-video. The Expo AV audio doc now appear in the sidebar as `Audio (expo-av)` and `Audio` directs to the doc for the new library.

# Test Plan

2024-10-23 17:16 UTC, amandeepmittal requested changes

2024-10-23 17:16 UTC, amandeepmittal commented on docs/pages/versions/unversioned/sdk/audio.mdx
> +> **Info** This page documents an upcoming version of the Audio library. **Expo audio is currently in alpha and subject to breking changes.**
```suggestion
> **warning** This page documents an upcoming version of the Audio library. **Expo audio is currently in alpha and subject to breaking changes.**
```

Warning is an appropriate callout here.

2024-10-23 17:16 UTC, amandeepmittal commented on docs/pages/versions/unversioned/sdk/audio-av.mdx
> +<APISection packageName="expo-audio" apiName="Audio" />
```suggestion
<APISection packageName="expo-audio-av" apiName="Audio" />
```

To fetch the correct reference as per the change in `GenerateDocsAPIData.ts`, lets update the package name here.

2024-10-23 17:16 UTC, amandeepmittal commented on docs/pages/versions/unversioned/sdk/audio-av.mdx
> +`Audio` from `expo-av` allows you to implement audio playback and recording in your app.
```suggestion
> **info** The `Audio` component from `expo-av` documented on this page will be replaced by an improved version in `expo-audio` in an upcoming release when the new library is stable. [Learn about `expo-audio`](https://docs.expo.dev/versions/unversioned/sdk/audio/).

`Audio` from `expo-av` allows you to implement audio playback and recording in your app.
```

Maybe we should add a callout here about the upcoming Audio library, just like we do for Video [(reference)](http://localhost:3002/versions/unversioned/sdk/audio/).

![CleanShot 2024-10-23 at 22 40 29](https://github.com/user-attachments/assets/4e3234a9-d1ca-404e-811c-413b08b8e626)

2024-10-23 18:05 UTC, tsapeta commented on docs/pages/versions/unversioned/sdk/audio.mdx
>  title: Audio
One thing that I found annoying in Video is the lack of the package name here. Of course we'll remove it once `expo-av` docs are removed.
```suggestion
title: Audio (expo-audio)
```

2024-10-24 00:29 UTC, merged

2024-11-16 16:54 UTC, clarkg commented
@alanjhughes et. al any chance you guys could pls provide an example of recording a sound and then playing back the same recording with the new API?

the documentation has examples for recording and playing separately, not together

When I tried it:
- when the recording ends, recording.uri is reset
- and there's no method to load new URI into AudioPlayer after your instantiate it the first time

2024-11-16 16:57 UTC, alanjhughes commented
@clarkg our example screen does exactly that https://github.com/expo/expo/blob/main/apps/native-component-list/src/screens/Audio/expo-audio/RecordingScreen.tsx

2024-11-16 16:59 UTC, clarkg commented
ah doh ty @alanjhughes

2024-11-16 17:03 UTC, alanjhughes commented
@clarkg no worries! The library is in early beta so I didn't want to fill the docs with examples that could go out of date quickly, things will likely change as we get feedback from users but to will add more examples for the stable release in sdk 53. Any feedback you have is welcome. Feel free to ping me on discord etc.