[docs] refactor and simplify global styles
expo/expo pull request #32376
Opened 2024-10-26 18:19 UTC by Simek

# Why

Probably second to last part of Emotion styling removal efforts. This time the global styles has been a target.

# How

Replace Emotion based global styles with single CSS file utilizing already existing Tailwind classes.

There should be no visual differences* between currently deployed site and this PR.

> *There were also few small tweaks and fixes for the existing styles, which might appear when testing on mobile, but nothing major to mention.

# Test Plan

The changes have been reviewed by running docs app locally. All lint checks and tests are passing.

# Preview

![Screenshot 2024-10-26 at 20 13 12](https://github.com/user-attachments/assets/bcf81aae-8e8e-4b3c-a1a2-b37f1bb1e810)
![Screenshot 2024-10-26 at 20 14 00](https://github.com/user-attachments/assets/405176ad-ac6a-4ab6-9a11-e02cd45f49b1)
![Screenshot 2024-10-26 at 20 14 38](https://github.com/user-attachments/assets/d0949e60-bf83-4326-b2ca-815abf2719b8)

2024-10-28 20:13 UTC, amandeepmittal requested changes
It seems the tooltip for light theme is not showing up:

![CleanShot 2024-10-29 at 01 40 54@2x](https://github.com/user-attachments/assets/0f653289-75ed-4924-8476-b5a004ce71b2)

vs.

![CleanShot 2024-10-29 at 01 41 02@2x](https://github.com/user-attachments/assets/30688893-20df-4b34-b39b-daad4ca9ef26)

2024-10-28 20:13 UTC, amandeepmittal commented on docs/styles/global.css
> +img[src*="https://placehold.it/15"] {
Is this placeholder value required?

2024-10-29 10:16 UTC, Simek commented
Thanks for catching that! Fix is up:

![Screenshot 2024-10-29 at 11 14 12](https://github.com/user-attachments/assets/95a0b3bc-633f-49dc-a1bb-450956391b37)

2024-10-29 10:18 UTC, Simek commented on docs/styles/global.css
> +img[src*="https://placehold.it/15"] {
It looks like it's unused, removing!

2024-10-29 10:49 UTC, amandeepmittal approved these changes
Thank you!

2024-10-29 10:51 UTC, merged