improve type definition of iOS entitlements
expo/expo pull request #32392
Opened 2024-10-28 05:23 UTC by Spice-Z

# Why

I found some libraries mistakenly add the value in iOS entitlements.
I want to prevent it by adding type definition.

# How

According to [Apple Developer's Entitlements](https://developer.apple.com/documentation/bundleresources/entitlements), added specific type definitions.
This change includes only iOS entitlement values.

# Test Plan

I thought this change doesn't need any tests because it's only about type 🤔 

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

2024-10-28 09:42 UTC, vonovak requested changes
Hello and thanks for the PR,
this looks potentially useful!

However, the correct place to make these edits is [here](https://github.com/expo/expo/blob/86c59c44eac10698d703a6a82f6e5984d9d214a0/packages/%40expo/config-types/src/ExpoConfig.ts#L418). The file you edited is produced from the `.ts` files and your changes would get overwritten by the build process.

I'm wondering: because the 

```
    [k: string]: any;
```

entry has [remained in your change](https://github.com/expo/expo/pull/32392/files#diff-6671c9773aa1c778937b22f6f846ae974313ddf0d1be660e97a4c0e7c947757fR679), arbitrary entries can still be added - and that's fine - but then how does the change help with type checking? Is there some intellisense improvement? (can you add a screenshot from your IDE?)

As an alternative, [this approach](https://medium.com/@florian.schindler_47749/typescript-hacks-1-string-suggestions-58806363afeb#:~:text=Append%20string%20%26%20%7B%7D%20to%20your,you%20some%20values%20as%20suggestions.) could provide good intellisense support but still allow arbitrary entries - we don't want to be super strict with type checking this. But if we can provide some guidance, then that's great.

2024-10-29 04:37 UTC, Spice-Z commented
Hi @vonovak !

Thank you for checking!
I moved changes to `ExpoConfig.ts`.

About your concern, I think the problem is only about String type.
Even with `[k: string]: any;`, we can get suggestion in object.
I confirmed it in my editor.

![Screenshot 2024-10-28 at 9 23 55 PM](https://github.com/user-attachments/assets/a51e60e3-ca6c-41d6-8635-9b680f367aa8)

Also, I checked simplified one in TS Playground, and it seems work.

![Screenshot 2024-10-28 at 9 16 39 PM](https://github.com/user-attachments/assets/7b0f50f6-2f91-4835-a816-3358075fd36e)

You can easily confirm the suggestion behavior on this [Playground](https://www.typescriptlang.org/play/?#code/C4TwDgpgBA8gRgKwgY2AFXNAvFA3gKCiKgCIBDEgfgC4oBnYAJwEsA7AcwBpDjy4raDFhwDaAXW7EoIgNaCmbdmNplWIANz4AvvnzIA9qwZR9teElQZIUHASnbdu0NYDKCjleykKUAD7f+P3p3dl0DI2B6Wjdhdk8bUhIgA).

Thanks!

2024-10-29 08:11 UTC, vonovak commented
Thanks! @Spice-Z can you run `yarn build` in `packages/@expo/config-types` and commit the result as well? Thank you

2024-10-29 15:42 UTC, Spice-Z commented
@vonovak 

Committed a build result!

2024-10-30 17:27 UTC, vonovak commented
Hi @Spice-Z,
thank you for making that change! I have learned that this file is, in fact, generated using some internal tooling and then exported in here. Therefore changes merged here won't have a lasting impact, and merging directly isn't what we want to do.

I will follow up on this later; allow some time for this to happen as I deal with other things too.

Thank you!

2024-10-31 06:44 UTC, Spice-Z commented
@vonovak 
I didn't know this file is created by generating script, good to know!
I look forward to further updates, thanks!

2026-05-12 21:19 UTC, brentvatne commented
Hi! This PR is being closed automatically as part of a cleanup of pull requests that are older than 6 months and haven't had any activity in the past 3 months. This isn't a reflection on the quality of the contribution — we just want to keep the open PR list focused on work that's actively moving forward.

If you're still interested in landing this, please feel free to reopen it (or open a fresh PR against the latest `main`) and ping me so we can take another look. Expo team members: same applies — reopen if you'd like to pick this back up.

Thanks for contributing to Expo!

2026-05-12 21:19 UTC, closed without merging