[docs] remove duplicated note on Audio pages, change note theme
expo/expo pull request #32410
Opened 2024-10-28 13:30 UTC by Simek

# Why

Spotted that Audio page for legacy `expo-av` module have duplicated note:

![Screenshot 2024-10-28 at 14 28 22](https://github.com/user-attachments/assets/d4762f87-719d-4b9b-974b-3f9b4e62f6cb)

# How

Remove duplicated note, change note theme.

# Test Plan

The changes have been reviewed by running docs app locally.

# Preview

![Screenshot 2024-10-28 at 14 26 41](https://github.com/user-attachments/assets/447c982a-d05b-49c5-b39b-85ea91e090e9)

2024-10-28 21:06 UTC, amandeepmittal requested changes

2024-10-28 21:06 UTC, amandeepmittal commented on docs/pages/versions/v52.0.0/sdk/audio-av.mdx
> +> **warning** The `Audio` component from `expo-av` documented on this page will be replaced by an improved version in `expo-audio` in an upcoming release when the new library is stable. [Learn about
Let's fix the link also.

2024-10-29 09:27 UTC, Simek commented on docs/pages/versions/unversioned/sdk/audio-av.mdx
> +> **warning** The `Audio` component from `expo-av` documented on this page will be replaced by an improved version in `expo-audio` in an upcoming release when the new library is stable. [Learn about
```suggestion
> **warning** The `Audio` component from `expo-av` documented on this page will be replaced by an improved version in `expo-audio` in an upcoming release when the new library is stable. [Learn about `expo-audio`](/versions/unversioned/sdk/audio/).
```

2024-10-29 09:27 UTC, Simek commented on docs/pages/versions/v52.0.0/sdk/audio-av.mdx
> +> **warning** The `Audio` component from `expo-av` documented on this page will be replaced by an improved version in `expo-audio` in an upcoming release when the new library is stable. [Learn about
```suggestion
> **warning** The `Audio` component from `expo-av` documented on this page will be replaced by an improved version in `expo-audio` in an upcoming release when the new library is stable. [Learn about `expo-audio`](/versions/v52.0.0/sdk/audio/).
```

2024-10-29 09:28 UTC, amandeepmittal approved these changes

2024-10-29 09:52 UTC, merged