[expo][expo-updates]  re-export fingerprint in expo package instead of updates
expo/expo pull request #32494
Opened 2024-10-31 08:47 UTC by quinlanj

# Why

We want `eas-cli` to call the fingerprint library through the expo package. This would be done by adding fingerprint to a dependency of the expo package and reexporting it as expo/fingerprint like [expo/config-plugins](https://github.com/expo/expo/blob/main/packages/expo/config-plugins.js).

This PR re-exports the fingerprint package in expo/expo instead of expo-updates. Since fingerprint was last re-exported after SDK 51, no one would currently depend on it yet (?) https://github.com/expo/expo/pull/30757

# How

- Re-exported fingerprint library through expo package
- ran `yarn prepare` in `expo-updates`

# Test Plan

- [ ] current tests still pass

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

2024-10-31 10:13 UTC, tsapeta approved these changes

2024-10-31 10:13 UTC, tsapeta commented on packages/expo/package.json
> +    "@expo/fingerprint": "0.11.0",
This version must match the version that is used in the monorepo. It should fix CI failures 😉 
```suggestion
    "@expo/fingerprint": "0.11.1",
```

2024-10-31 12:05 UTC, Kudo requested changes
please help to update the doc at
https://github.com/expo/expo/blob/63b63942d42519e7914199010549cf08ff6c6b2a/packages/%40expo/fingerprint/README.md?plain=1#L217-L220

2024-10-31 18:07 UTC, wschurman approved these changes

2024-10-31 22:40 UTC, tsapeta approved these changes

2024-11-01 06:32 UTC, Kudo approved these changes

2024-11-01 19:05 UTC, merged