[expo-notifications][iOS] Swift conversion 2: push token module
expo/expo pull request #32612
Opened 2024-11-05 03:22 UTC by douglowder

# Why

# How

# Test Plan

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

2024-11-05 03:23 UTC, douglowder commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/expo/expo/32612?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#32612** <a href="https://app.graphite.dev/github/pr/expo/expo/32612?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#32069** <a href="https://app.graphite.dev/github/pr/expo/expo/32069?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @douglowder and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-11-05 11:14 UTC, vonovak requested changes
👏👏 👏 <img width="164" alt="Screenshot 2024-11-05 at 12 14 16" src="https://github.com/user-attachments/assets/79049dd0-a824-4589-a35c-b86218e49dfe">


Left some stylistic comments, and also I believe there are 2 bugs to be resolved :)

2024-11-06 21:14 UTC, douglowder commented on packages/expo-notifications/ios/EXNotifications/PushToken/PushTokenModule.swift
> +      promiseNotYetResolved.reject(error)
This function should have been removed, everything is handled in `onNotificationResult` now.

2024-11-06 21:27 UTC, douglowder commented on packages/expo-notifications/ios/EXNotifications/PushToken/PushTokenModule.swift
> +  public func onNotificationResult(notification: Notification) {
I'll come up with a better name...

2024-11-07 17:24 UTC, vonovak requested changes
just one more suggestion :)

2024-11-07 17:24 UTC, vonovak commented on packages/expo-notifications/ios/EXNotifications/PushToken/PushTokenModule.swift
> +          promise.reject("E_AWAIT_PROMISE", "Another async call to this method is in progress. Await the first Promise.")
```suggestion
          promise.reject("E_AWAIT_PROMISE", "Another async call to 'getDevicePushTokenAsync' method is in progress. Await the first Promise.")
```

2024-11-08 06:59 UTC, vonovak approved these changes

2024-11-14 13:39 UTC, tsapeta requested changes

2024-11-14 13:39 UTC, tsapeta commented on packages/expo-notifications/ios/EXNotifications/PushToken/PushTokenModule.swift
> +    OnStartObserving {
Let's use the new approach for `OnStartObserving`/`OnStopObserving`, where we provide the event name.
```suggestion
    OnStartObserving(onDevicePushTokenEventName) {
```

2024-11-14 13:39 UTC, tsapeta commented on packages/expo-notifications/ios/EXNotifications/PushToken/PushTokenModule.swift
> +    OnStopObserving {
```suggestion
    OnStopObserving(onDevicePushTokenEventName) {
```

2024-11-14 13:39 UTC, tsapeta commented on packages/expo-notifications/ios/EXNotifications/PushToken/PushTokenModule.swift
> +    }
If you're using the Promise, switching to the async context makes no sense and becomes much slower. Just use `.runOnQueue(.main)` modifier to run it on the main queue.

```suggestion
    AsyncFunction("getDevicePushTokenAsync") { (promise: Promise) in
      if promiseNotYetResolved != nil {
        promise.reject("E_AWAIT_PROMISE", "Another async call to this method is in progress. Await the first Promise.")
      }
      promiseNotYetResolved = promise
      UIApplication.shared.registerForRemoteNotifications()
    }
    .runOnQueue(.main)
```

2024-11-14 23:51 UTC, tsapeta approved these changes

2024-12-06 21:37 UTC, merged