[expo-sensors] Fixed parity issues, added more information on functionality
expo/expo pull request #3277
Opened 2019-01-22 00:58 UTC by EvanBacon

# Why

iOS & Android function differently. This fixes those issues and makes it easier to test the Accelerometer going forward. 

#3117 

# How

* Inversed iOS values on Accelerometer
* Inversed Gravity on iOS & Web to match DeviceMotion across all platforms
* Updated docs with information about functionality regarding Gyroscope.

# Test Plan

Added a screen to NCL

2019-01-22 03:17 UTC, ide requested changes

2019-01-22 03:17 UTC, ide commented on ios/Exponent/Kernel/Services/EXSensorManager.m
> +        // Inverse values to match Android
```suggestion
        // Invert values to match Android
```

2019-01-22 03:17 UTC, ide commented on packages/expo-sensors/ios/EXSensors/EXSensorsManager.m
> +          // Inverse values to match Android
```suggestion
          // Invert values to match Android
```

2019-01-22 03:17 UTC, ide commented on packages/expo-sensors/ios/EXSensors/EXSensorsManager.m
> +                    @"x": [NSNumber numberWithDouble:x],
```suggestion
                    @"x": @(x),
```

2019-01-23 03:59 UTC, EvanBacon commented on docs/versions/unversioned/sdk/accelerometer.md
> +Access the device accelerometer sensor(s) to respond to changes in rotation in 3d space. Data is measured in _`m/s^2`_.
lmao unless something gets swapped on our side I think they're wrong

2019-01-23 04:17 UTC, EvanBacon commented on docs/versions/unversioned/sdk/accelerometer.md
> +> As of v33 values have been inverted on iOS to match Android.
So I actually built the gyro wrong on web I'm seeing. I built it like a gyroscope. Should I rename the native modules on the API side or change the web module functionality?

2019-02-28 00:52 UTC, closed without merging