[expo-updates] fix detox debug build
expo/expo pull request #32951
Opened 2024-11-15 16:06 UTC by matejkriz

# Why

fixes https://github.com/expo/expo/issues/28918

Debug build is using Dev Client and `launchAssetFile` [can't be called from Dev Client](https://github.com/expo/expo/blob/c1ab8d0551cf2f1b0604316a18daa563fd24c495/packages/expo-updates/android/src/main/java/expo/modules/updates/UpdatesDevLauncherController.kt#L82), so it's not possible to run Detox E2E tests in debug mode, which makes the development of tests harder. 

# How

Simply do not try to preload updates if Dev Client is used.

# Test Plan

There is no user facing change. It only affects E2E tests development.

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

2024-11-15 16:08 UTC, matejkriz commented
cc @Kudo this is a followup for https://github.com/expo/expo/commit/bf03ebf9900da9a5cf63cbc7aa858d6305b8790c

2024-11-19 14:14 UTC, Kudo requested changes
thanks for digging the issue and having the fix. i'm kind of afraid using `BuildConfig.USE_DEV_CLIENT` here because it may also have ANR when testing with dev client.

how about just loose the controller.launchAssetFile limit with softer warning?

```patch
diff --git a/packages/expo-updates/android/src/main/java/expo/modules/updates/UpdatesDevLauncherController.kt b/packages/expo-updates/android/src/main/java/expo/modules/updates/UpdatesDevLauncherController.kt
index ca034f32e5..48804a830f 100644
--- a/packages/expo-updates/android/src/main/java/expo/modules/updates/UpdatesDevLauncherController.kt
+++ b/packages/expo-updates/android/src/main/java/expo/modules/updates/UpdatesDevLauncherController.kt
@@ -78,8 +78,11 @@ class UpdatesDevLauncherController(
   }

   @get:Synchronized
-  override val launchAssetFile: String
-    get() = throw Exception("IUpdatesController.launchAssetFile should not be called in dev client")
+  override val launchAssetFile: String?
+    get() {
+      logger.warn("IUpdatesController.launchAssetFile should not be called in dev client, except during Detox testing")
+      return null
+    }

   override val bundleAssetName: String
     get() = throw Exception("IUpdatesController.bundleAssetName should not be called in dev client")
```

2024-11-22 00:22 UTC, wschurman requested changes
Agree with @Kudo.

2025-01-22 21:03 UTC, Kudo reviewed
thanks for updating the stuff. having some last minute changes and good to go

2025-01-22 21:03 UTC, Kudo commented on packages/expo-updates/android/src/main/java/expo/modules/updates/UpdatesDevLauncherController.kt
> +      logger.warn("IUpdatesController.launchAssetFile should not be called in dev client, except during Detox testing")
```suggestion
      logger.warn("launchAssetFile should not be called from expo-dev-client build, except for Detox testing")
```

nit: little fine tune of the message.

2025-01-22 21:03 UTC, Kudo commented on packages/expo-updates/CHANGELOG.md
> +
```suggestion
```

2025-01-22 21:03 UTC, Kudo commented on packages/expo-updates/CHANGELOG.md
> +
```suggestion
- fix E2E tests in Detox debug build ([#32951](https://github.com/expo/expo/pull/32951) by [@matejkriz](https://github.com/matejkriz))
```

2025-01-22 21:05 UTC, Kudo commented
> thanks for updating the stuff. having some last minute changes and good to go

cool since the pr is available for maintainers to edit. i just edit in-place.

2025-01-23 00:13 UTC, Kudo approved these changes

2025-01-23 01:27 UTC, wschurman approved these changes

2025-01-23 01:28 UTC, merged