[docs] various updates
expo/expo pull request #3296
Opened 2019-01-23 00:09 UTC by EvanBacon

2019-01-23 00:26 UTC, aghahuseynov approved these changes

2019-01-24 08:18 UTC, ide requested changes
I have some more notes at the office but these are most of them. One of the main things I think we need to hash out is the wording around frontend, backend, API layer, and native layer.

2019-01-25 01:39 UTC, ide requested changes

2019-01-25 01:39 UTC, ide commented on guides/Creating Web Platform Modules.md
> +```js
Include the filename here to make it clear this is in the API layer

2019-01-25 01:39 UTC, ide commented on guides/Deploying Expo Web Apps.md
> +Run the `surge` command, then promptly log-in or create a new account.
```suggestion
Run the `surge` command, then promptly log in or create a new account.
```

2019-01-25 01:39 UTC, ide commented on guides/Deploying Expo Web Apps.md
> +1. [Start a new netlify project](https://app.netlify.com/signup)
```suggestion
1. [Start a new Netlify project](https://app.netlify.com/signup)
```

2019-01-29 22:06 UTC, EvanBacon commented on guides/Enabling the Expo Web Target.md
> +    // To test secure features like iOS permissions, you need to add: --https --host <YOUR_IP>
otherwise permissions are automatically rejected.

2019-03-07 19:39 UTC, ide commented on guides/Enabling the Expo Web Target.md
> +[native-directory]: http://native.directory
```suggestion
[native-directory]: https://native.directory
```

2019-04-08 22:55 UTC, closed without merging