fix (config-plugins): ManifestServiceAttributes missing foregroundServiceType
expo/expo pull request #33166
Opened 2024-11-22 03:43 UTC by micaelomota

# Why

I'm using expo module-api to create an android foreground service and, Android 10 introduced the `android:foregroundServiceType` attribute within the [`service`](https://developer.android.com/guide/topics/manifest/service-element) element in `AndroidManifest.xml`

 https://developer.android.com/about/versions/14/changes/fgs-types-required

I'm having this typescript error message:

<img width="752" alt="Screenshot 2024-11-21 at 10 35 49 PM" src="https://github.com/user-attachments/assets/f3062223-089a-45e0-bf85-f7e42bc8c204">

And I noticed this attribute type was missing in the definition:

<img width="679" alt="Screenshot 2024-11-21 at 10 38 04 PM" src="https://github.com/user-attachments/assets/99912585-de52-41a9-9fae-22a4e6124413">

# How

I just changed the type definition to include `android:foregroundServiceType`

```typescript

type ManifestServiceAttributes = AndroidManifestAttributes & {
    'android:enabled'?: StringBoolean;
    'android:exported'?: StringBoolean;
    'android:foregroundServiceType'?: string;
    'android:permission'?: string;
};
```

# Test Plan

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

2024-11-22 13:08 UTC, vonovak requested changes
Hello and thanks for this PR!

Please make your change in [this file](https://github.com/expo/expo/blob/197cfb33893732c9898feeaa70cabf1bcb6ee6fb/packages/%40expo/config-plugins/src/android/Manifest.ts#L38C6-L38C22)

and then run `yarn build` in the `packages/@expo/config-plugins` directory. Then commit all changes from there. 

Additionally, please add a changelog entry in the `CHANGELOG.md` file in the package.

Thank you!

2024-11-24 02:30 UTC, micaelomota commented
Thanks for the review @vonovak  I just pushed the changes

2024-11-24 08:50 UTC, vonovak requested changes
Let's please add a changelog entry too.

2024-11-24 19:17 UTC, micaelomota commented
@vonovak done! thank you!

2024-11-24 22:23 UTC, vonovak commented on packages/@expo/config-plugins/CHANGELOG.md
> +- Add foregroundServiceType property to Android ManifestServiceAttributes by [@micaelomota](https://github.com/micaelomota)) ([#33166](https://github.com/expo/expo/pull/33166) by [@micaelomota](https
```suggestion
- Add foregroundServiceType property to Android ManifestServiceAttributes by [@micaelomota](https://github.com/micaelomota)) ([#33166](https://github.com/expo/expo/pull/33166)
```

2024-11-24 22:24 UTC, vonovak commented on packages/@expo/config-plugins/CHANGELOG.md
> +- Add foregroundServiceType property to Android ManifestServiceAttributes by [@micaelomota](https://github.com/micaelomota)) ([#33166](https://github.com/expo/expo/pull/33166)
```suggestion
- Add foregroundServiceType property to Android ManifestServiceAttributes by [@micaelomota](https://github.com/micaelomota)) ([#33166](https://github.com/expo/expo/pull/33166))
```

2024-11-24 22:26 UTC, vonovak commented on packages/@expo/config-plugins/CHANGELOG.md
> +- Add foregroundServiceType property to Android ManifestServiceAttributes by [@micaelomota](https://github.com/micaelomota)) ([#33166](https://github.com/expo/expo/pull/33166))
```suggestion
- Add foregroundServiceType property to Android ManifestServiceAttributes ([#33166](https://github.com/expo/expo/pull/33166) by [@micaelomota](https://github.com/micaelomota))
```

2024-11-25 08:02 UTC, vonovak approved these changes

2024-11-25 08:03 UTC, merged