Update Payments docs with missing information
expo/expo pull request #3318
Opened 2019-01-24 14:52 UTC by eliasturbay

# Why

The docs to integrate the Stripe SDK on Android are outdated.

# How

Added just a couple of missing steps in the process.

# Test Plan

N/A

2019-01-25 05:04 UTC, brentvatne requested changes
left some suggested changes, thanks!

2019-01-25 05:04 UTC, brentvatne commented on docs/versions/unversioned/sdk/payments.md
> +// add this two lines
I don't think this comment is necessary

```suggestion
```

2019-01-25 05:04 UTC, brentvatne commented on docs/versions/unversioned/sdk/payments.md
> +// make sure this two lines are there
I don't think this comment is necessary

```suggestion
```

2019-01-25 05:04 UTC, brentvatne commented on docs/versions/unversioned/sdk/payments.md
> +6.  Add `StripePackage` to the list of Expo Packages in `your-project/android/app/src/main/java/host/exp/exponent/MainApplication.java`.
```suggestion
6.  Add `StripePackage` to the list of Expo Packages in `android/app/src/main/java/host/exp/exponent/MainApplication.java`.
```

2019-01-25 05:04 UTC, brentvatne commented on docs/versions/unversioned/sdk/payments.md
> +        ...
```suggestion
        // other packages here
```

2019-01-25 05:04 UTC, brentvatne commented on docs/versions/unversioned/sdk/payments.md
> +        new BackgroundFetchPackage(),
```suggestion
```

2019-02-05 15:54 UTC, nicknovitski commented
The docs pages have moved from `docs/versions` to `docs/pages/versions`.  Rebasing should resolve the conflicts and fix the client build.

2019-02-05 16:00 UTC, eliasturbay commented
Excuse me @nicknovitski, rebasing against which branch? Thx!

2019-02-13 02:07 UTC, esamelson commented
Hi @eliasturbay - apologies for the slow followup here, if you could rebase again current expo master that would be great 😄

2019-10-31 15:09 UTC, springcoil commented
@eliasturbay https://stackoverflow.com/questions/7929369/how-to-rebase-local-branch-with-remote-master/7929499 if you're having any difficulty with your rebasing. (I know I've had a lot of trouble in the past with OSS work :) so I hope this helps.)

2019-11-20 09:51 UTC, sjchmiela commented
These instructions are outdated now since we introduced autolinking of unimodules. Sorry it took us so long to look into this PR and thank you for your contribution! ❤️

2019-11-20 09:51 UTC, closed without merging