feat: Allow Nullable dates for reminders
expo/expo pull request #33264
Opened 2024-11-26 11:04 UTC by TomAtterton

# Why

I want to allow the ability to fetch all reminders but just passing an id

# How

I've updated the code to allow null values to the dates and updated the types. So it will work both ways so shouldn't have an impact on previous implementations.

# Test Plan

You can now fetch all reminders like below. 

``` 
import {
  getRemindersAsync,
} from 'expo-calendar';

const reminders = await getRemindersAsync([id]);
```

# Checklist

The documentation is ambigous with if the dates are defined so I don't believe we need to update it. 

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).

- [x ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

2024-11-29 15:12 UTC, vonovak requested changes
Hello, this looks good in principle, but please add a test case for this in here https://github.com/expo/expo/blob/main/apps/test-suite/tests/CalendarReminders.js

Does the change work on iOS?

2024-12-06 08:13 UTC, TomAtterton commented
@vonovak Added a test and synced with main.

2024-12-11 11:22 UTC, vonovak requested changes
Thank you, can you please run `yarn build` in the package directory and commit the results? (see https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)

Thank you!

2024-12-11 11:22 UTC, vonovak commented on packages/expo-calendar/CHANGELOG.md
> +- feat: Allow nullable dates for getRemindersAsync ([#33264](https://github.com/expo/expo/pull/33264) by [@TomAtterton](https://github.com/TomAtterton))
```suggestion
- Allow nullable dates for getRemindersAsync ([#33264](https://github.com/expo/expo/pull/33264) by [@TomAtterton](https://github.com/TomAtterton))
```

2024-12-12 14:52 UTC, alanjhughes approved these changes

2025-01-21 23:47 UTC, lukmccall approved these changes
I'll merge it, and rebuilt it after

2025-01-21 23:48 UTC, merged