Added types to Constants
expo/expo pull request #3341
Opened 2019-01-27 02:22 UTC by EvanBacon

* Updated UIWebView to WKWebView
* Added missing web props

2019-01-28 22:26 UTC, ide requested changes
Thank you for going through the constants and writing a type definition for it - think this will be helpful.

2019-01-28 23:44 UTC, EvanBacon commented on packages/expo-constants/ios/EXConstants/EXConstants.m
> +        strongSelf->webView = [[WKWebView alloc] init];
nah if you use a local reference it throws an error in the returned value.

2019-01-28 23:46 UTC, EvanBacon commented on packages/expo-constants/src/Constants.types.ts
> +export interface PlatformInterface {
lol .. It's like the part of constants that you interface with tho. Will change it though

2019-01-28 23:47 UTC, EvanBacon commented on packages/expo-constants/ios/EXConstants/EXConstants.m
> +  WKWebView *webView;
can't, maybe I should leave a comment so no one tries to remove it.

2019-01-29 04:19 UTC, ide approved these changes

2019-01-29 18:21 UTC, ide commented
LGTM

2019-01-29 18:45 UTC, merged