[core] Declare specific interface for ExpoProcess's env
expo/expo pull request #33567
Opened 2024-12-10 11:47 UTC by noelblaschke

# Why
Typescript offers module augmentation. Augmenting Expo's globally declared ExpoProcess (process.env) with e.g. additional environment variables (ExpoProcess["env"]) wont work because already declared members must be the same type.

**Before:**
```
e.g. types/your-types.ts

export {};

declare module "expo-modules-core" {
  interface ExpoProcess {
    env: { <--- #Subsequent property declarations must have the same type....
      EXPO_PUBLIC_API_URL?: string;
    }
  }
}
```

# How
I extracted the ExpoProcess["env"] to a dedicated interface. Now its possible to augment the module's interface with additional members.

**After:**

```
export {};

declare module "expo-modules-core" {
  interface ExpoProcessEnv {
    EXPO_PUBLIC_API_URL?: string;
  }
}

```

# Test Plan
Checks are passing and process.env is properly typed, i.e. expo-specific and user configured variables are available.

2024-12-10 15:19 UTC, Kudo commented
hi there! thanks for having the pr. though the code change looks good to me, i'm not quite clear how the type error happens. could you share some repro for the problem you indicated?

```
e.g. types/your-types.ts

export {};

declare module "expo-modules-core" {
  interface ExpoProcess {
    env: { <--- #Subsequent property declarations must have the same type....
      EXPO_PUBLIC_API_URL?: string;
    }
  }
```

2024-12-16 08:54 UTC, LeunensMichiel commented
We've had our linting breaking because ExpoProcess overrides the NodeEnv typings. (throwing many `any` errors), and module augmentation doesn't seem to work.

Hope this PR solves that, thank you for your contribution 💪

2024-12-16 12:35 UTC, Kudo commented
@noelblaschke thanks much for the proof of concept. i'm now fully understand the intention and it makes 100% sense.
please help to revert the [change](https://github.com/noelblaschke/expo/commit/d30b639f3ee9bf8a5b20a4829a57a05be248c942) for the pr and resolve CHANGELOG.md conflict. and we are ready to merge.

2024-12-16 21:56 UTC, noelblaschke commented
@Kudo Thanks for your review.

I think the [change](https://github.com/noelblaschke/expo/commit/d30b639f3ee9bf8a5b20a4829a57a05be248c942) should stay in the test apps as it proofs that the module augmentation works. Do you agree?

2024-12-17 07:19 UTC, dennzimm commented
This looks great 🚀 I'm looking forward to seeing this merged 👌😎

2025-01-07 10:40 UTC, lukmccall approved these changes
Looks good!

2025-01-12 09:18 UTC, Kudo requested changes
sorry for late review.

i want to further write a test to ensure the custom var types would be correctly inferred. i propose #34112 as a replacement for this pr. also trying to wrap the process.env type as `NodeJS.ProcessEnv` so that people can use node's common way to add custom env types.

will add you as co-author for the pr. thanks for initiating the good pr.

2025-01-13 11:06 UTC, noelblaschke commented
@Kudo Thanks for your reply. I subscribed to the #34112

2025-01-13 11:06 UTC, closed without merging