Expo video upgrade
expo/expo pull request #33639
Opened 2024-12-12 17:54 UTC by HADeveloper

# Why

This PR is to add the ability to customize the video player metadata (especially on tvos).

# How

I added the metadata types and followed the docs here: https://developer.apple.com/documentation/avkit/customizing-the-tvos-playback-experience

# Test Plan

Since this is for TVOS, to test this, you play a video using expo-video and set the metadata parameters and you should see them show up when the player is playing the video, especially when paused.
![Screenshot 2024-12-12 at 11 44 17 AM](https://github.com/user-attachments/assets/ae0764e7-20d2-4d46-bc66-cb4e5770960a)

# Checklist

- [*] I added a `changelog.md` entry and rebuilt the package sources according to [this short guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [*] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).
- [*] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)

2024-12-18 23:52 UTC, behenate requested changes
Hi before I proceed with an actual review, it seems like your fork is incorrectly rebased from main (there is a lot of additional changes from other PRs), also please fix all of the SwiftLint violations instead of marking them as resolved, the code has to be compliant with our SwiftLint rules 😄

2024-12-19 01:04 UTC, douglowder commented
> Hi before I proceed with an actual review, it seems like your fork is incorrectly rebased from main (there is a lot of additional changes from other PRs), also please fix all of the SwiftLint violations instead of marking them as resolved, the code has to be compliant with our SwiftLint rules 😄

I concur with @behenate 's comment above. When checking SwiftLint, you should use [this config file](https://github.com/expo/expo/blob/main/.swiftlint.yml) at the top of our monorepo. You can reach out to me on the Expo Discord `building-for-tv` channel if you have any issues with the rebase or with SwiftLint.

2024-12-19 16:51 UTC, HADeveloper commented
I think I have it working now.
Please check @behenate @douglowder 

Thanks!
(I'm still learning the process and any guidance is greatly appreciated)

2024-12-20 22:40 UTC, douglowder commented
> I think I have it working now. Please check @behenate @douglowder
> 
> Thanks! (I'm still learning the process and any guidance is greatly appreciated)

@HADeveloper there are merge conflicts and SwiftLint errors still in the PR.

To unblock you, I created a new branch from main, cherry-picked your changes, and resolved conflicts and fixed SwiftLint issues (including two that I found that actually were not part of your PR 😄 )

Please take a look at https://github.com/expo/expo/tree/doug/pr-33639 -- if you are happy with those changes, please sync your PR branch to that, and merge issues should be resolved. @behenate

2024-12-26 14:53 UTC, Simek commented on packages/expo-video/CHANGELOG.md
> -## 2.0.2 - 2024-11-29
Looks like rebase artifact, probably should be restored.

2024-12-26 14:54 UTC, Simek commented on packages/expo-video/src/VideoPlayer.types.ts
> +>>>>>>> main
Unresolved merge conflict.

2024-12-26 14:54 UTC, Simek commented on packages/expo-video/src/VideoPlayer.types.ts
> +>>>>>>> main
Unresolved merge conflict.

2025-01-02 17:30 UTC, HADeveloper commented
I think I have everything right now. @douglowder

2025-01-02 21:55 UTC, behenate commented
@HADeveloper 
Please notice that in @douglowder branch there is only [11 changed files with 128 additions and 11 deletions](https://github.com/expo/expo/compare/main...doug/pr-33639#:~:text=with%20128%20additions%20and%2011%20deletions.)
Whereas if you look in the top right of this PR there is over 17 thousand lines changed in 38 files
<img width="801" alt="image" src="https://github.com/user-attachments/assets/0c5cbafc-4ee4-4ba0-9302-b7d877feef48" />
This means that most likely at one point something went wrong when merging the main branch into your branch (you should prefer rebasing over merging, because when merging stuff like this sometimes happens). You will likely solve those issues by fetching the newest version of `expo:main` and rebasing your branch onto it.

If you can't get it to work you can always try creating a fresh branch from the current `expo:main` version, pasting the appropriate changes and opening a new PR 😄 (I'd lie if I said I never did that when things got FUBAR'd 😅 )

2025-01-06 15:46 UTC, HADeveloper commented
I think it is getting worse

2025-01-06 16:22 UTC, closed without merging