[expo-updates] Fix expo-updates breaking filesystem on API24-25
expo/expo pull request #33694
Opened 2024-12-16 17:42 UTC by aleqsio

# Why

Closes https://github.com/expo/expo/issues/33520

# How

expo-file-system relies on `commons-io:commons-io:1.4` for the `copyFile` path.
expo-updates uses `commons-io:commons-io:2.16.1`.

To fix this issue in the least invasive way IMO I would just downgrade the version in expo-updates to the latest one that correctly supports `copyFile` on API24 and 25.

# Test Plan

Tested the original repro. Let's see if updates tests pass correctly.

# Checklist

- [ ] I added a `changelog.md` entry and rebuilt the package sources according to [this short guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
…DK24

2024-12-16 18:11 UTC, wschurman reviewed
I think downgrading this only solves a very specific instance of this problem but the more general problem would still exist: there exist native libraries that use the current `commons-io` and therefore are incompatible with `expo-file-system`. If we can fix this in a future-proof way that improves compatibility with other libraries, IMO that's the preferable path. That being said, I'm not as deep into the issue as you are.

What's the aversion to update the dependency in `expo-file-system`? Is there an API version requirement that is preventing us from doing so? Or is it just the existence of the `copyFile` function? Does the current version of `copyFile` not work on API24/25?

2024-12-16 18:15 UTC, aleqsio commented
My understanding is that the latest versions of commons-io will try and use java.nio dependencies that are not available on the API levels we aim to support.

We can probably just use a different copy function not coming from commons-io and drop that dependency in file-system – let me try that.

2024-12-17 10:25 UTC, aleqsio commented
I think you're not using those exact functions so it may work, but It's also likely it doesn't. I think we should assume the latest version of commons-io is not 100% compatible with API24-25.

I'm not sure what is the best way to test updates e2e – can I run one of the CI flows locally on emulator or how best to go about it?

2024-12-18 19:29 UTC, wschurman requested changes
Back to your queue. If changing `expo-file-system` to a different mechanism ends up being complex, then feel free re-request review on this downgrade and we can go with this in the meantime.

2025-01-07 12:19 UTC, aleqsio commented
@wschurman Instead of downgrading the dependency I added two separate code paths for 24 and 25 that do not rely on `FileUtils`. You're right that this is quite cleaner.

2025-01-07 18:16 UTC, wschurman approved these changes

2025-01-08 10:49 UTC, merged