[ios][video] Background mode playback
expo/expo pull request #33706
Opened 2024-12-17 11:18 UTC by hromovp

# Why

When using background mode in iOS, app behavior not necessary logical. e.g

1. When using `player.staysActiveInBackground = true` and `allowsPictureInPicture={false}` for `VideoView`:
    - upon locking screen with app open **videoplayback stops**;
    - upon moving app to the background **videoplaback stops**;
2. When using `player.staysActiveInBackground = true` and `allowsPictureInPicture={true}` for `VideoView`:
    - upon moving app to the background PiP mode turns on and **video is playing**;
    - when locking screen while PiP mode is on - **video is playing**;
    - upon locking screen with app open **videoplayback stops**;

Considering there is more elegant way to handle background audio playback, configuration could be updated.

# How

- If using `player.staysActiveInBackground = true` set `audiovisualBackgroundPlaybackPolicy = .continuesIfPossible`
- Remove setTracksEnabled function

# Test Plan
1. In example video app, when using `player.staysActiveInBackground = true`  and `allowsPictureInPicture={false}` for `VideoView`:
    - upon locking screen with app open **video is playing** without PiP;
    - upon moving app to the background **video is playing** without PiP;
2. When using `player.staysActiveInBackground = true` and `allowsPictureInPicture={true}` for `VideoView`:
    - upon moving app to the background PiP mode turns on and **video is playing**;
    - when locking screen while PiP mode is on - **video is playing**;
    - upon locking screen with app open **video is playing**;

# Checklist

- [ ] I added a `changelog.md` entry and rebuilt the package sources according to [this short guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)

2024-12-18 23:45 UTC, behenate commented
Hi! 
I'd like to ask you some more questions about this part 
>```
>When using player.staysActiveInBackground = true and allowsPictureInPicture={false} for VideoView:
>. upon locking screen with app in foreground video stops;
>. upon moving app to the background video stops;
>When using player.staysActiveInBackground = true and allowsPictureInPicture={true} for VideoView:
>. upon moving app to the background PiP mode turns on and video is playing;
>. when locking screen while PiP mode is on - audio is playing;
>. upon locking screen with app in foreground video stops;
>```

I couldn't reproduce this behaviour at all. Behaviour in my testing was following:

1. When using `player.staysActiveInBackground = true` and `allowsPictureInPicture={false}` for VideoView:
    - upon locking screen with app in foreground video  **keeps playing**;
    - upon moving app to the background video **keeps playing**;
2. When using player.staysActiveInBackground = true and allowsPictureInPicture={true} for VideoView:
    - upon moving app to the background PiP mode turns on and video is playing;
    - when locking screen while PiP mode is on - audio is playing;
    - upon locking screen with app in foreground video **keeps playing**;

So basically i observed a correct behaviour.

2024-12-18 23:53 UTC, hromovp commented
> Hi! I'd like to ask you some more questions about this part
> 
> > ```
> > When using player.staysActiveInBackground = true and allowsPictureInPicture={false} for VideoView:
> > . upon locking screen with app in foreground video stops;
> > . upon moving app to the background video stops;
> > When using player.staysActiveInBackground = true and allowsPictureInPicture={true} for VideoView:
> > . upon moving app to the background PiP mode turns on and video is playing;
> > . when locking screen while PiP mode is on - audio is playing;
> > . upon locking screen with app in foreground video stops;
> > ```
> 
> I couldn't reproduce this behaviour at all. Behaviour in my testing was following:
> 
> 1. When using `player.staysActiveInBackground = true` and `allowsPictureInPicture={false}` for VideoView:
>    
>    * upon locking screen with app in foreground video  **keeps playing**;
>    * upon moving app to the background video **keeps playing**;
> 2. When using player.staysActiveInBackground = true and allowsPictureInPicture={true} for VideoView:
>    
>    * upon moving app to the background PiP mode turns on and video is playing;
>    * when locking screen while PiP mode is on - audio is playing;
>    * upon locking screen with app in foreground video **keeps playing**;
> 
> So basically i observed a correct behaviour. How did you do your testing?

Oh, sorry. I am not using new architecture so that must be the reason.
Also the other reason might be that I am running HLS stream

2024-12-19 00:32 UTC, behenate commented
The old architecture shouldn't be the problem. Expo-video was initially created and tested on old architecture and the background playback functionality was working.
Is the config plugin configured in your project? https://docs.expo.dev/versions/latest/sdk/video/#configurable-properties

2024-12-19 06:56 UTC, hromovp commented
> The old architecture shouldn't be the problem. Expo-video was initially created and tested on old architecture and the background playback functionality was working. Is the config plugin configured in your project? https://docs.expo.dev/versions/latest/sdk/video/#configurable-properties

I use bare RN project, so it is not configured per se, but as far as  I understood the only thing that is needed is to add `UIBackgroundModes` - `audio`, and I did that.

My setup:
"react-native": "0.76.5",
"expo": "52.0.19",
"expo-video": "2.0.2",

Tested on: Iphone 12 mini, iOS 18.1.1

2025-01-02 21:56 UTC, behenate commented
@hromovp Interesting. I'll do some more testing in a fresh project to reproduce this

2025-01-16 00:18 UTC, joeporpeglia commented
@behenate I started experiencing this issue when switching from MP4 to HLS video. I created a corresponding MRE and issue here https://github.com/expo/expo/issues/34170

2025-02-19 23:00 UTC, henrikkoivisto commented
Having same issue! @behenate @joeporpeglia .

2025-04-17 17:11 UTC, epzee commented
@behenate fyi we're having the same issue. HLS video stops playing when app enters background mode on ios
```
    "expo": "~52.0.46",
    "expo-video": "~2.0.6",
    "react-native": "0.76.9",
```

2025-08-21 15:02 UTC, behenate requested changes
@hromovp Hi, I'm really sorry for such a late review. Do you have the time to rebase the PR to remove the conflicts and apply my suggestion, or would you prefer me to take over? I'd like to have this merged by monday 😄

2025-08-21 15:02 UTC, behenate commented on packages/expo-video/ios/VideoManager.swift
>          player.pointer.pause()
Let's set the audiovisualBackgroundPlaybackPolicy to `.pauses` when we don't need it. I assume keeping it in continuesIfPossible may have a negative effect on battery life.
```suggestion
        player.pointer.audiovisualBackgroundPlaybackPolicy = .continuesIfPossible
      } else if !videoView.isInPictureInPicture {
        player.ref.audiovisualBackgroundPlaybackPolicy = .pauses
        player.pointer.pause()
```

2025-08-21 16:30 UTC, hromovp commented on packages/expo-video/ios/VideoManager.swift
>          player.pointer.pause()
Hi @behenate, could you please check if this will work?

2025-08-22 10:29 UTC, behenate approved these changes
I tested it and it looks like it works well!

2025-08-22 10:30 UTC, merged