feat(bun): add support for text-based lockfile format
expo/expo pull request #33825
Opened 2024-12-24 00:04 UTC by tharakadesilva

# Why

Bun v1.1.39 introduced a new text-based lockfile format (bun.lock) as an alternative to the binary format (bun.lockb). This change adds support for detecting and using both formats.

https://bun.sh/blog/bun-lock-text-lockfile

Closes https://github.com/expo/eas-cli/issues/2782.

# How

# Test Plan

# Checklist

- [ ] I added a `changelog.md` entry and rebuilt the package sources according to [this short guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)

2024-12-31 21:04 UTC, smaccoun commented
Hope this gets merged soon. This creates a lot of unexpected error when building/running if you don't realize what's happening, especially if you are working in a monorepo with bun

2024-12-31 22:04 UTC, tharakadesilva commented
I have a feeling that this will only solve expo cli, not eas.

If we are not doing already, we should add a command to expo cli that we can then use in eas.

I'll try to check on this tomorrow.

2025-01-03 16:25 UTC, tharakadesilva commented
Someone from EAS might have better information than what I can find from the existing code base.. I will wait for someone to reply.

2025-01-03 17:31 UTC, Kudo commented
sorry that most people were off during the holiday season and would back from next week. i can check how eas support bun under the hood on the weekend.

2025-01-03 18:08 UTC, Kudo requested changes
please remove the unrelated `using-bun.mdx` and `expo-cli.mdx` file changes. also fix the lint error from package-manager.

```
🏃‍♀️ Running yarn clean
🏃‍♀️ Running yarn build
🏃‍♀️ Running yarn test --watch false --passWithNoTests --maxWorkers 1
🏃‍♀️ Running yarn lint --max-warnings 0
lint script failed, see process output:
stdout > yarn run v1.22.22
stdout > $ expo-module lint --max-warnings 0
stdout > 
stdout > /home/runner/work/expo/expo/packages/@expo/package-manager/src/utils/nodeManagers.ts
stdout >   49:45  warning  Replace `file` with `(file)`  prettier/prettier
stdout >   55:37  warning  Replace `file` with `(file)`  prettier/prettier
stdout > 
stdout > ✖ 2 problems (0 errors, 2 warnings)
stdout >   0 errors and 2 warnings potentially fixable with the `--fix` option.
stdout > 
stdout > info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
stderr > ESLint found too many warnings (maximum: 0).
stderr > error Command failed with exit code 1.
```

2025-01-03 18:08 UTC, Kudo commented on docs/pages/versions/unversioned/guides/using-bun.mdx
this new changes is unrelated and could be removed from this pr.

2025-01-03 18:08 UTC, Kudo commented on docs/pages/versions/unversioned/more/expo-cli.mdx
this new changes is unrelated and could be removed from this pr.

2025-01-03 18:17 UTC, Kudo commented
> i can check how eas support bun under the hood on the weekend.

for what i can tell, eas will just use `bun install` to install dependencies. as long as `bun.lock` were there in the project with newer bun binary, it should be fine to run `bun install`. after this pr landed and `@expo/package-manger` can resolve the  correct package manager and fix the https://github.com/expo/eas-cli/issues/2782 issue. we don't need to do any other changes from eas side.

2025-01-05 18:17 UTC, tharakadesilva commented
> please remove the unrelated `using-bun.mdx`

Removed the `using-bun.mdx` file as that is not related to this change and is in EAS.

> we don't need to do any other changes from eas side.

If this is the case, should we still keep the doc change?

2025-01-05 18:18 UTC, tharakadesilva commented on docs/pages/versions/unversioned/more/expo-cli.mdx
Feel like this is still relevant since we are making a change to this repository. Or am I missing something?

2025-01-05 19:44 UTC, amandeepmittal commented on docs/pages/versions/unversioned/more/expo-cli.mdx
Hi @tharakadesilva, the Expo CLI docs file is located under `docs/pages/more/expo-cli.mdx`. We do not keep a versioned document for Expo CLI.

The changes you've made and included in this diff https://github.com/expo/expo/pull/33825/files#diff-8c2b6f8e985e42676c1d874b0750a60dba9562499a1728eaea950dfa73e29c4e will apply to Expo CLI reference page.

2025-01-05 19:48 UTC, amandeepmittal approved these changes
The docs change lg! Thank you for updating Expo CLI reference to mention the new lock file extension.

2025-01-05 19:49 UTC, tharakadesilva commented on docs/pages/versions/unversioned/more/expo-cli.mdx
Ah, that makes sense, thanks Amandeep! Removed the unversioned doc.

2025-01-06 13:33 UTC, Kudo approved these changes

2025-01-06 13:39 UTC, byCedric approved these changes
Wow, I'm impressed. You not only added support for `bun.lock`, you also went the extra mile of updating the docs, `--help` output, and tests (fixtures). Thanks for that ❤️

Only left 2 suggestions for the changelogs, but these are optional.

2025-01-06 13:39 UTC, byCedric commented on packages/@expo/cli/CHANGELOG.md
> +- feat(bun): add support for text-based lockfile format ([#33825](https://github.com/expo/expo/pull/33825) by [@tharakadesilva](https://github.com/tharakadesilva))
```suggestion
- Add support for Bun's text-based lock file format `bun.lock` ([#33825](https://github.com/expo/expo/pull/33825) by [@tharakadesilva](https://github.com/tharakadesilva))
```

2025-01-06 13:39 UTC, byCedric commented on packages/@expo/package-manager/CHANGELOG.md
> +- feat(bun): add support for text-based lockfile format ([#33825](https://github.com/expo/expo/pull/33825) by [@tharakadesilva](https://github.com/tharakadesilva))
```suggestion
- Add support for Bun's text-based lock file format `bun.lock` ([#33825](https://github.com/expo/expo/pull/33825) by [@tharakadesilva](https://github.com/tharakadesilva))
```

2025-01-06 13:42 UTC, byCedric commented
I think the `--help` snapshots also needs to be updated. You can do this locally through:
- `cd ./packages/@expo/cli`
- `yarn test:e2e -u install-test`

Or modify the snapshot manually at https://github.com/expo/expo/blob/main/packages/%40expo/cli/e2e/__tests__/install-test.ts#L50.

Let me know if you need help with that.

2025-01-06 14:16 UTC, merged