[bare-expo] fix search navigation
expo/expo pull request #33858
Opened 2024-12-27 18:07 UTC by mateoguzmana

# Why

The navigation via the search screen of the `bare-expo` app is not working. Seems like a regression from #31992 during upgrading `@react-navigation`.

# How

Was setting up the local development environment to get familiar with the internals and noticed this when trying to navigate through the components and APIs.

# Test Plan

<details>
<summary>Recording before the fix</summary>

https://github.com/user-attachments/assets/1665c222-d8fa-402c-ad10-96a90a6b9a27

</details>

<details>
<summary>Recording after the fix</summary>

https://github.com/user-attachments/assets/0374c16a-495f-44c9-a1fe-f4285502c258

</details>

I've also verified the normal navigation still works as expected.

# Checklist

- [ ] I added a `changelog.md` entry and rebuilt the package sources according to [this short guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)

2024-12-29 15:30 UTC, vonovak requested changes
Hello and thank you for the PR!
There's one thing that needs clarification, see my comment.

Thanks!

2024-12-29 22:06 UTC, mateoguzmana commented on apps/native-component-list/src/screens/ComponentListScreen.tsx
>    screenName?: string;
Good one, it is indeed not needed anymore. I've cleaned it up in 54ea9e1debe2d80a4c75fb1a6a74720ead883ae3

2025-01-07 10:01 UTC, vonovak approved these changes

2025-01-07 10:05 UTC, merged

2025-01-07 10:06 UTC, vonovak commented
Thank you! :)