[TypeScript] Migrated expo-gl
expo/expo pull request #3401
Opened 2019-02-02 02:40 UTC by EvanBacon

# How

* Added snapshot tests
* Added tests to CI

# Test Plan

* CI should run tests

2019-02-02 03:38 UTC, ide requested changes

2019-02-02 03:38 UTC, ide commented on packages/expo-gl/src/GLView.tsx
> +  async destroyObjectAsync(glObject: WebGLObject): Promise<any> {
figure out these return types

2019-02-02 03:38 UTC, ide commented on packages/expo-gl/src/GLView.tsx
> +  async startARSessionAsync(): Promise<any> {
fix up return type (maybe void?)

2019-02-02 03:38 UTC, ide commented on packages/expo-gl/src/GLView.tsx
> +export { SurfaceCreateEvent, ExpoWebGLRenderingContext, SnapshotOptions, GLViewProps }
```suggestion
export { SurfaceCreateEvent, ExpoWebGLRenderingContext, SnapshotOptions, GLViewProps };
```

2019-02-02 03:38 UTC, ide commented on packages/expo-gl/src/GLView.tsx
> +import { SurfaceCreateEvent, ExpoWebGLRenderingContext, SnapshotOptions, GLViewProps } from './GLView.types';
order the imports and the modules alphabetically

2019-02-02 03:38 UTC, ide commented on packages/expo-gl/src/GLView.tsx
> +  static NativeView: any;
Do we need to expose this? It doesn't seem very useful, and is possibly misleading since "native views" from RN are strings at runtime.

2019-02-04 09:42 UTC, tsapeta requested changes
Looks great, thanks bro! 💪 left some minor comments

2019-02-04 09:42 UTC, tsapeta commented on packages/expo-gl/package.json
> +    "react-test-renderer": "^16.7.0"
I guess `expo-module-scripts` must be added here as a devDependency

2019-02-04 09:42 UTC, tsapeta commented on packages/expo-gl/src/GLView.tsx
> +  async destroyObjectAsync(glObject: WebGLObject): Promise<any> {
```suggestion
  async destroyObjectAsync(glObject: WebGLObject): Promise<boolean> {
```

2019-02-04 09:42 UTC, tsapeta commented on packages/expo-gl/src/GLView.tsx
> +  async takeSnapshotAsync(options: SnapshotOptions = {}): Promise<any> {
Might be worth to add a type for snapshots 🤔

2019-02-23 00:44 UTC, ide approved these changes

2019-02-23 00:44 UTC, ide commented on packages/expo-gl/src/GLView.tsx
> +  // React.ElementRef<typeof GLView.NativeView>
?

2019-02-23 00:44 UTC, ide commented on packages/expo-gl/src/index.ts
> +export default GLView;
Thinking we maybe should remove this so that it's consistently imported as `import { GLView } from 'expo-gl'`. Right now it's exported twice.

2019-02-23 00:44 UTC, ide commented on packages/expo-gl/src/__tests__/GLView-test.tsx
> +it(`renders correctly on Web`, () => {
```suggestion
it(`renders correctly on web`, () => {
```

2019-02-26 20:43 UTC, merged