[docs] Info about how app signing on android works
expo/expo pull request #3448
Opened 2019-02-07 11:01 UTC by wkozyra95

# Why

Update documentation about app signing process for android.

# How

# Test Plan

2019-02-07 16:24 UTC, dsokal requested changes

2019-02-07 16:24 UTC, dsokal commented on docs/pages/versions/unversioned/distribution/app-signing.md
> +Process is automated for iOS and Android, but in both cases you can choose to provide your own overrides. Both `build:ios` and
```suggestion
Process is automated for iOS and Android, but in both cases you can choose to provide your own overrides. Both `expo build:ios` and
```

2019-02-07 16:24 UTC, dsokal commented on docs/pages/versions/unversioned/distribution/app-signing.md
> +`build:android` generates signed applications ready to be uploaded into respective stores.
```suggestion
`expo build:android` commands generate signed applications ready to be uploaded into respective stores.
```

2019-02-07 16:24 UTC, dsokal commented on docs/pages/versions/unversioned/distribution/app-signing.md
> +Android requires that all APKs be digitally signed with a certificate before they are installed on a device or updated. Usually
```suggestion
Google requires all Android apps to be digitally signed with a certificate before they are installed on a device or updated. Usually
```

2019-02-07 16:24 UTC, dsokal commented on docs/pages/versions/unversioned/distribution/app-signing.md
> +a private key and its public certificate is stored in a keystore. In the past APKs uploaded to the store were requiered to be signed with
```suggestion
a private key and its public certificate is stored in a keystore. In the past, APKs uploaded to the store were required to be signed with
```

2019-02-07 16:24 UTC, dsokal commented on docs/pages/versions/unversioned/distribution/app-signing.md
> +the **app signing certificate**(certificate that will be attached to app in store), if that keystore were lost there is no way to
```suggestion
the **app signing certificate** (certificate that will be attached to the app in store), if the keystore was lost there is no way to
```

2019-02-07 16:24 UTC, dsokal commented on docs/pages/versions/unversioned/distribution/app-signing.md
> +recover or reset it. If you opt in to App Signing by Google Play you need to upload an apk signed with **upload certificate**, store will
```suggestion
recover or reset it. If you opt in to App Signing by Google Play you need to upload an APK signed with **upload certificate**, store will
```

2019-02-07 16:24 UTC, dsokal commented on docs/pages/versions/unversioned/distribution/app-signing.md
> +**app signing key** are essentially the same mechanism, but if your upload keystore is lost or compromised you can contact
```suggestion
**app signing key** are essentially the same mechanism, but if your upload keystore is lost or compromised, you can contact
```

2019-02-07 16:24 UTC, dsokal commented on docs/pages/versions/unversioned/distribution/app-signing.md
> +From build process perspective there is no difrence whether app is signed with **upload certificate** or **app signing certificate**, command `expo build:android` will generate apk signed using keyst
```suggestion
From build process perspective, there is no difrence whether an app is signed with an **upload certificate** or an **app signing certificate**, `expo build:android` will generate an APK signed with the keystore currently assigned to your application. If you want to generate an upload keystore manually, you can do
```

2019-02-07 16:24 UTC, dsokal commented on docs/pages/versions/unversioned/distribution/app-signing.md
> +You can find more informations about this proces [here](https://developer.android.com/studio/publish/app-signing).
```suggestion
See [here](https://developer.android.com/studio/publish/app-signing to find more information about this process.
```

2019-02-07 16:24 UTC, dsokal commented on docs/pages/versions/unversioned/distribution/app-signing.md
> +Create a new application and allow Google Play to handle your **app signing key**. Certificate used to sign first apk uploaded to the store
```suggestion
Create a new application and allow Google Play to handle your **app signing key**. A certificate used to sign the first APK uploaded to the store
```

2019-02-07 16:24 UTC, dsokal commented on docs/pages/versions/unversioned/distribution/app-signing.md
> +If you want to use App Signing in an already existing app, you can call `expo opt-in-google-play-signing` and follow it's instructions. After
```suggestion
If you want to use App Signing in an already existing app, you can call `expo opt-in-google-play-signing` and follow its instructions. After
```

2019-02-07 16:24 UTC, dsokal commented on docs/pages/versions/unversioned/distribution/app-signing.md
> +this process original keystore will be backed up to your current working directory and credentials for that keystore will be printed on screen,
```suggestion
this process, the original keystore will be backed up to your current working directory and credentials for that keystore will be printed on the screen,
```

2019-02-07 16:24 UTC, dsokal commented on docs/pages/versions/unversioned/distribution/app-signing.md
> +Remove that keystore only when you are sure that everything works.
```suggestion
Remove that keystore only when you are sure that everything works correctly.
```

2019-02-07 16:24 UTC, dsokal commented on docs/pages/versions/unversioned/distribution/app-signing.md
> +In case you lose your upload keystore(or it's compromised), you can ask google support team to reset your upload key.
```suggestion
In case you lose your upload keystore (or it's compromised), you can ask Google Support Team to reset your upload key.
```

2019-02-07 16:24 UTC, dsokal commented on docs/pages/versions/unversioned/distribution/app-signing.md
> +  - `expo fetch:android:upload-cert` extracts public certificat from keystor into `.pem` file
```suggestion
  - `expo fetch:android:upload-cert` extracts public certificate from the keystore into `.pem` file
```

2019-02-07 16:24 UTC, dsokal commented on docs/pages/versions/unversioned/distribution/app-signing.md
> +  - add upload cert in Google Play console
```suggestion
  - add the upload certificate in Google Play console
```

2019-02-07 16:24 UTC, dsokal commented on docs/pages/versions/unversioned/distribution/app-signing.md
> +  - Generate new keystore
```suggestion
  - Generate a new keystore
```

2019-02-07 16:24 UTC, dsokal commented on docs/pages/versions/unversioned/distribution/app-signing.md
> +  - Extract upload certificate with
```suggestion
  - Extract the upload certificate with
```

2019-02-07 16:24 UTC, dsokal commented on docs/pages/versions/unversioned/distribution/app-signing.md
> +  - add upload certificate in Google Play console
```suggestion
  - Add the upload certificate in Google Play console
```

2019-02-07 16:24 UTC, dsokal commented on docs/pages/versions/unversioned/distribution/app-signing.md
> +First time you call `expo build:android` you can allow expo to generate keystore or pass it manually along with all necessary credentials,
```suggestion
First time you call `expo build:android` you can allow expo to generate a keystore or pass it manually along with all necessary credentials,
```

2019-02-12 03:52 UTC, ide requested changes

2019-02-12 03:52 UTC, ide commented on docs/pages/versions/unversioned/distribution/app-signing.md
> +  - `expo android:build --clear-credentials` and select option `Let Expo handle the process!`, this will generate a new keystore and sign new APK with it
```suggestion
  - `expo android:build --clear-credentials` and select the option `Let Expo handle the process!`, which generates a new keystore and signs a new APK with it
```

2019-02-12 03:52 UTC, ide commented on docs/pages/versions/unversioned/distribution/app-signing.md
> +  - add the upload certificate in Google Play console
```suggestion
  - add the upload certificate to the Google Play console
```

2019-02-12 03:52 UTC, ide commented on docs/pages/versions/unversioned/distribution/app-signing.md
> +- If you want to handle it yourself
```suggestion
- If you want to handle it create the upload certificate yourself:
```

2019-02-12 03:52 UTC, ide commented on docs/pages/versions/unversioned/distribution/app-signing.md
> +  - Add the upload certificate in Google Play console
```suggestion
  - Add the upload certificate to the Google Play console
```
```suggestion
  - Add the upload certificate in Google Play console
```

2019-02-12 03:52 UTC, ide commented on docs/pages/versions/unversioned/distribution/app-signing.md
> +### 2. Signing APKs with **app signing key** (deprecated)
```suggestion
### 2. Signing APKs with an **app signing key** (deprecated)
```

2019-02-12 03:52 UTC, ide commented on docs/pages/versions/unversioned/distribution/app-signing.md
> +First time you call `expo build:android` you can allow expo to generate a keystore or pass it manually along with all necessary credentials,
```suggestion
The first time you run `expo build:android`, you can choose for Expo to generate a keystore or manually specify all of the required credentials. These credentials are used to sign APKs created by Expo services.
```

2019-02-12 09:59 UTC, merged