[wip][ncl] Standalone, vanilla React Native NCL
expo/expo pull request #3450
Opened 2019-02-07 14:39 UTC by sjchmiela

2019-02-08 00:41 UTC, brentvatne commented
neat, this approach looks good for now

2019-02-08 00:42 UTC, brentvatne approved these changes

2019-02-08 03:40 UTC, ide requested changes
Please revert the changes to handle missing native modules -- it makes the TS types nullable for this one edge case and adds extra if-statements that should normally never fail as long as the native code is properly installed. It's also too easy to break by introducing code that assumes the corresponding native code is installed.

Projects using bare RN should use the unimodules directly instead of the `expo` package (until the `expo` package is just the core).

2019-02-11 18:50 UTC, ide commented on packages/expo-localization/src/ExpoLocalization.ts
> +export default NativeModulesProxy.ExpoLocalization || {};
Still needed?

2019-02-19 21:53 UTC, EvanBacon approved these changes

2019-02-21 12:29 UTC, sjchmiela commented on packages/expo-localization/src/ExpoLocalization.ts
> +export default NativeModulesProxy.ExpoLocalization || {};
Removed ✅

2019-02-21 12:47 UTC, merged