Remove usages of `props.exp.notification` discussing push notifications.
expo/expo pull request #3526
Opened 2019-02-17 07:15 UTC by AndrewSouthpaw

# Why

Closes #3047, and performs action requested in #843 and #1691.

# What

- Removes references to `props.exp.notification`
- Clarifies language to show what `Exponent.notification` is referring to.

# How

Tweaked docs, ran for v28+.

2019-02-17 20:25 UTC, AndrewSouthpaw commented
I'm new to contributing to expo, I'm not sure what's wrong with the build. Any guidance would be much appreciated! 🙇

2019-02-22 01:54 UTC, esamelson approved these changes
Hey @AndrewSouthpaw - thanks very much for taking care of this!! This has been needed for quite a while now 🙈 I have a few comments for how to improve this just a bit more.

Also, no need to worry about the CI failure (aside from the `docs` job) -- some of our jobs are red on master right now but it has nothing to do with your PR!

2019-02-22 01:54 UTC, esamelson commented on docs/pages/versions/unversioned/guides/push-notifications.md
> +It's not entirely clear from the above when your app will be able to handle the notification depending on it's state at the time the notification is received. For clarification, see the table below.
I don't think there's any reason for this to be called `Exponent.notification` anymore -- this is a really old relic 😮 Could we just change this wording to something like "Listener called with notification: origin: ..." instead?

2019-02-22 01:54 UTC, esamelson commented on docs/pages/versions/unversioned/guides/push-notifications.md
>  | Push was received when...                       | Android           | iOS               |
Since the iOS and Android columns are no different anymore can we remove the extra column?

2019-02-22 01:55 UTC, esamelson requested changes
(whoops sorry, meant to request changes rather than approving!)

2019-02-22 23:53 UTC, AndrewSouthpaw commented
Added new changes based on PR feedback, let me know if that reads better to you!

2019-02-23 00:06 UTC, esamelson requested changes
thanks @AndrewSouthpaw - this is a huge improvement 🙏  just one small nit with link formatting but otherwise looks great!

2019-02-23 00:06 UTC, esamelson commented on docs/pages/versions/unversioned/guides/push-notifications.md
> +Event listeners added using `Notifications.addListener` will receive an object when a notification is received ((docs)[https://docs.expo.io/versions/latest/sdk/notifications/#eventsubscription]). The
`(docs)[https://docs.expo.io/versions/latest/sdk/notifications/#eventsubscription]` -> `[docs](../../sdk/notifications/#eventsubscription)`

2019-02-23 00:10 UTC, AndrewSouthpaw commented on docs/pages/versions/unversioned/guides/push-notifications.md
> +Event listeners added using `Notifications.addListener` will receive an object when a notification is received ((docs)[https://docs.expo.io/versions/latest/sdk/notifications/#eventsubscription]). The
Nice catch, thanks! Fixed.

2019-02-23 00:10 UTC, AndrewSouthpaw commented
Updated

2019-02-23 00:13 UTC, esamelson approved these changes
this is awesome, thanks so much!

2019-02-23 00:14 UTC, merged

2019-02-26 06:35 UTC, AndrewSouthpaw commented
Thanks for all your help with the feedback! Happy to contribute to an excellent project. 🙏