Get rid of exploit_v1 prefix from UNVERSIONED. Prefix ExoPlayer in versioned sdk. Bump ExoPlayer in UNVERSIONED.
expo/expo pull request #3539
Opened 2019-02-20 10:01 UTC by Szymon20000

# Why

WIP

This pr Should fix (https://github.com/expo/expo/issues/2941) in UNVERSIONED.
I've played 30 videos and everything was right.

# How

WIP

# Test Plan

Clone from branch [example/android-video-bug] and run https://github.com/natterstefan/playlist-example. Please run also in our sandbox [unversioned].

2019-02-22 09:42 UTC, sjchmiela requested changes
AWESOME! Soo looking forward to landing it 💪

2019-02-22 09:42 UTC, sjchmiela commented on android/ReactAndroid/build.gradle
> +    api 'com.facebook.infer.annotation:infer-annotation:0.11.2'
We could also move this `expolibbed` JAR to `versiond-abis/abi32/maven`, right?

2019-02-22 09:42 UTC, sjchmiela commented on android/ReactAndroid/build.gradle
> +    implementation 'com.squareup.okhttp3:okhttp:3.6.0'
Let's bump it to 3.10.0, which current RN uses 👍 https://github.com/facebook/react-native/blame/833954a669a980ad574b69d8d4aa4c07627171c5/ReactAndroid/gradle.properties#L15

2019-02-22 09:42 UTC, sjchmiela commented on android/ReactAndroid/src/main/java/com/facebook/react/modules/network/OkHttpClientProvider.java
> +            return (OkHttpClient) Class.forName("host.exp.exponent.ReactNativeStaticHelpers").getMethod("getOkHttpUnprefixedClient", Class.class).invoke(null, OkHttpClientProvider.class);
```suggestion
            return (OkHttpClient) Class.forName("host.exp.exponent.ReactNativeStaticHelpers").getMethod("getOkHttpClient", Class.class).invoke(null, OkHttpClientProvider.class);
```

Let's add name modifications to these extra functions and treat unprefixed client as the normal one

2019-02-22 09:42 UTC, sjchmiela commented on android/app/src/main/java/host/exp/exponent/MainApplication.java
> +import okhttp3.OkHttpClient;
Add a breaking change to CHANGELOG that people we removed use of `expolib_v1.okhttp` in favor of `okhttp` (this means people will need to edit their `MainApplication` on their own when upgrading)

2019-02-22 09:42 UTC, sjchmiela commented on android/app/src/main/java/host/exp/exponent/MainApplication.java
> +  public static expolib_v1.okhttp3.OkHttpClient.Builder okHttpPrefixedClientBuilder(expolib_v1.okhttp3.OkHttpClient.Builder builder) {
We can remove this, as `MainApplication` class is only used in ejected apps and ejected app won't ever use `expolib_v1` from now on. 🙂

2019-02-22 09:42 UTC, sjchmiela commented on android/expoview/build.gradle
> +  api 'expolib_v1.com.squareup.okhttp3:okhttp:3.6.0'
These can be `provided` as we don't want to include them in ejected apps (we want to include them only in Expo Client and it's the old ABIs which will depend on them strongly).

2019-02-22 09:42 UTC, sjchmiela commented on android/expoview/build.gradle
> +  api 'com.squareup.okhttp3:okhttp:3.6.0'
We could upgrade okhttp to 3.10.0, right?

2019-02-22 09:42 UTC, sjchmiela commented on android/expoview/src/main/java/host/exp/exponent/ReactNativeStaticHelpers.java
> +  public static OkHttpClient getOkHttpUnprefixedClient(Class callingClass) {
```suggestion
  public static Object getOkHttpClient(Class callingClass) {
```

How about we return an `Object` from this function and depending on `RNObject.versionForClassname` of the `callingClass` we could return either `expolib_v1.okhttp` the way you implemented it in `getOkHttpClient` below or a regular `okhttp` if the calling class is of version 33 or newer?

2019-02-22 09:42 UTC, sjchmiela commented on android/expoview/src/main/java/versioned/host/exp/exponent/modules/universal/av/CustomHeadersOkHttpDataSourceFactory.java
> +import okhttp3.CacheControl;
I think we could remove this file altogether (`expo-av` and `expoview` will use the same `okhttp` now) 🤔

2019-02-22 09:42 UTC, sjchmiela commented on packages/expo-av/android/build.gradle
> +  provided 'com.google.android.exoplayer:extension-okhttp:2.9.2'
I think the comment above could also be removed and `extension-okhttp` promoted to `api` (instead of `provided`)

2019-02-22 09:42 UTC, sjchmiela commented on android/expoview/src/main/java/host/exp/exponent/network/ExponentNetwork.java
> +  public expolib_v1.okhttp3.Cache getCacheForPrefixedClient() {
```suggestion
  public expolib_v1.okhttp3.Cache getExpolibOkhttpCacheForClient() {
```

2019-02-22 09:42 UTC, sjchmiela commented on android/expoview/src/main/java/host/exp/exponent/network/ExponentNetwork.java
> +  // This method should be removed when sdk 32 is dropped
```suggestion
  // TODO: Remove this method once SDK32 is phased out
```

2019-02-22 09:44 UTC, sjchmiela commented
This PR should also fix https://github.com/expo/expo/issues/2298 and I'm curious whether it will fix https://github.com/expo/expo/issues/3488 too 🤔

2019-02-22 11:15 UTC, sjchmiela commented on android/expoview/src/main/java/host/exp/exponent/ReactNativeStaticHelpers.java
> +    int versionNumber = RNObject.getVersionFromClassname(callingClass.getName());
How about using `ABIVersion.toNumber(version)`?

2019-02-22 11:15 UTC, sjchmiela commented on android/ReactAndroid/build.gradle
> +    implementation 'com.squareup.okhttp3:okhttp:3.6.0'
Dismissed to another PR

2019-02-22 11:15 UTC, sjchmiela commented on CHANGELOG.md
> +- From now on, we use regular OkHttp3, so please update your MainApplication.getOkHttpBuilder method. [@Szymon20000](https://github.com/Szymon20000) ([#3539](https://github.com/expo/expo/pull/3539))
```suggestion
- removed use of `expolib_v1.okhttp` in favor of regular `okhttp` dependency by [@Szymon20000](https://github.com/Szymon20000) ([#3539](https://github.com/expo/expo/pull/3539)) (an update to `MainApplication.getOkHttpBuilder` may be required when upgrading)
```

You could also add a note about bugs fixed by this PR in bug fixes section 😅

2019-02-22 23:52 UTC, esamelson reviewed
agree with @sjchmiela 's comments but otherwise think this looks good! thanks for taking care of this 🙂

2019-02-22 23:52 UTC, esamelson commented on android/expoview/src/main/java/host/exp/exponent/network/ExponentNetwork.java
> +    // when sdk24 is no longer supported.
let's open a separate ticket for removing this

2019-02-22 23:52 UTC, esamelson commented on android/expoview/build.gradle
> +  compileOnly 'expolib_v1.com.squareup.okhttp3:okhttp:3.6.0'
can we put these inside of the `// WHEN_PREPARING_SHELL_REMOVE_FROM_HERE` tags?

2019-02-25 15:25 UTC, merged

2019-03-02 11:28 UTC, christtrc commented
When will this merge can be available for the next release?

2019-03-04 17:30 UTC, esamelson commented
Hi @christtrc - we currently don't have a date set for the next SDK release. The best way to find out is to watch our [blog](https://blog.expo.io/), as we will post an announcement there as soon as it's ready.

2019-03-07 13:54 UTC, christtrc commented
@esamelson We just need this fix to compile our android project which has several third party native modules affected by `exploit_v1` package name. Can you release an `expokit` module which may be with micro version change such as `32.0.8` that we can pull to go on?

2019-03-07 20:30 UTC, esamelson commented
@christtrc - unfortunately, no. We'll need to do a thorough QA on this before we release it and I hope you understand that as we are a small team, we simply don't have the bandwidth to do that with every bugfix/feature that lands between SDK releases. You're welcome to clone this repo and build a custom version of the `expokit` packages yourself, though -- just keep in mind that ymmv.

2019-03-09 14:44 UTC, christtrc commented
@esamelson Thanks for your answer! How can i build my own `expokit` package? Is there some docs to describe it?

2019-03-09 16:39 UTC, sjchmiela commented
You can find the instructions in this (and following comments): 
https://github.com/expo/expo/issues/2657#issuecomment-442730588 (note you’ll probably be using `32` instead of `31` when it comes to SDK, branch names etc. 🙂

2019-03-11 18:28 UTC, esamelson commented
Also, please go ahead and post on our [forums](https://forums.expo.io/) if you have any other questions or run into issues! I'm going to go ahead and lock this thread since this PR has been merged and I think there's enough information here now 🙂