WIP Make expo-file-system work in an app with bare RN
expo/expo pull request #3569
Opened 2019-02-25 12:12 UTC by Szymon20000

# Why

closes https://github.com/expo/expo/issues/3096

# How

WIP

# Test Plan

WIP

2019-02-25 12:35 UTC, sjchmiela reviewed
How about:…

2019-02-25 12:35 UTC, sjchmiela commented on android/expoview/src/main/java/host/exp/exponent/utils/ScopedContext.java
> +      Boolean inExpoClient = bundle.getBoolean("host.exp.exponent.InExpoClient");
For `if expoClient` you could use `Constants.isStandaloneApp()`

2019-02-25 12:35 UTC, sjchmiela commented on packages/expo-file-system/ios/EXFileSystem/EXFileSystem.m
> ++ (NSString *)documentDirectoryForExperienceId:(NSString *)experienceId
How about moving those methods to instance methods of `EXFileSystemService` so we can just override them in `EXFileSystemBinding` and not override `EXFileSystem` at all? 🤔

2019-02-25 12:35 UTC, sjchmiela commented on template-files/android/AndroidManifest.xml
> +    <meta-data android:name="host.exp.exponent.InExpoClient" android:value="true"/>
This file defines both Expo Client manifest and apps built in Turtle, so this value would always be `true`

2019-02-25 12:35 UTC, sjchmiela commented on packages/expo-file-system/ios/EXFileSystem/EXFileSystem.h
> +#import <EXCore/EXExportedModule.h>
Unnecessary import changes

2019-02-25 12:35 UTC, sjchmiela commented on packages/expo-file-system/ios/EXFileSystem/EXFileSystem.h
> +@property (nonatomic, retain) EXModuleRegistry *moduleRegistry;
```suggestion
@property (nonatomic, weak) EXModuleRegistry *moduleRegistry;
```

2019-02-25 12:35 UTC, sjchmiela commented on android/app/src/main/java/host/exp/exponent/generated/DetachBuildConstants.java
> +  public static final String DEVELOPMENT_URL = "exp://192.168.1.29:80";
Revert this change

2019-02-25 12:35 UTC, sjchmiela commented on packages/expo-file-system/ios/EXFileSystem/EXFileSystem.h
> +  EXModuleRegistry *_moduleRegistry;
Why define this property like this? If it's defined in the public header isn't it accessible and inheritable already? 🤔

2019-02-25 12:35 UTC, sjchmiela commented on packages/expo-file-system/ios/EXFileSystem/EXFileSystem.m
> +@synthesize moduleRegistry = _moduleRegistry;
Why do you synthesize this property?

2019-02-25 12:35 UTC, sjchmiela commented on packages/expo-file-system/ios/EXFileSystem/EXFileSystem.m
> +  NSArray *paths = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES);
Always annotate collection types with `<type>`

2019-02-27 12:18 UTC, sjchmiela requested changes

2019-02-27 12:18 UTC, sjchmiela commented on packages/expo-file-system/ios/EXFileSystem/EXFileSystem.h
> +@interface EXFileSystem : EXExportedModule <EXEventEmitter, EXModuleRegistryConsumer, EXFileSystemInterface>
Unnecessary change

2019-02-27 12:18 UTC, sjchmiela commented on packages/expo-file-system/ios/EXFileSystem/EXFileSystem.m
> +@property (nonatomic, weak) EXModuleRegistry *moduleRegistry;
Unnecessary change

2019-02-27 12:18 UTC, sjchmiela commented on ios/Exponent/Versioned/Core/UniversalModules/EXScopedFileSystemModule.m
> ++ (NSString *)documentDirectoryForExperienceId:(NSString *)experienceId isDetached:(BOOL)isDetached {
This method doesn't need to have this argument, it can just always use `[EXEnvironment sharedEnvironment].isDetached`

2019-02-27 12:18 UTC, sjchmiela commented on ios/Exponent/Versioned/Core/UniversalModules/EXScopedFileSystemModule.m
> +  return [_appOwnership isEqualToString:@"expo"];
In `ExpoKit` we can use `EXEnvironment` to know whether the app is detached or not

2019-02-27 12:18 UTC, sjchmiela commented on android/expoview/src/main/java/host/exp/exponent/utils/ScopedContext.java
> +    if (Constants.isStandaloneApp()) {
bump

2019-02-28 11:06 UTC, sjchmiela approved these changes
Thanks! 💯

2019-02-28 15:29 UTC, sjchmiela commented
Hey, @ide, I've added you as a reviewer to start a discussion about data migration—how do you think we should approach it? On one hand the only safe way of handling this would be to synchronously move all the files from `/ExponentExperienceData/${experienceId}` to `/` when the app starts, on the other hand this increases startup time by a call to the file system… On the other hand it's _only one FS call_… Maybe it is something we can live with and remove when we phase SDK32 out? Maybe we should save information about migration in some faster storage, like `NSUserDefaults`?

2019-03-03 06:15 UTC, ide commented
Synchronously moving everything on the first launch seems like the best approach:

- It's simple and likely to have the fewest bugs as long as we run the migration as an atomic operation. Correctness is more important than performance here (though I think we can achieve excellent performance too).
- I like the idea of migrating all files at once instead of on-demand so that file paths are more consistent and operations like listing all of the files in the directory are simpler to implement.
- We aren't copying any file contents. Regardless of file size, we're just creating new inodes. We should benchmark it, but I expect moving even 1000 files to run in a few milliseconds. This seems like an acceptable one-time cost.
- I don't think it's necessary to store migration information in NSUserDefaults. Let the file system be the source of truth unless we find the performance to be too slow (for example, > 1 millisecond to check if the migration has happened).
- Sometimes people stay on an old SDK even after the Expo client has dropped it. We could keep this auto-migration logic even after the client no longer includes SDK 32, but perhaps make it be opt-in (ex: `Filesystem.runMigrationAsync()`) so that most apps don't run it at all.

2019-03-06 15:06 UTC, merged