[web] Linear Gradient web color bug fix
expo/expo pull request #3671
Opened 2019-03-07 09:25 UTC by EvanBacon

# Why

Fixed bug where certain _valid_ web colors were not being converted properly.

# How

Added a method to parse alpha colors better than RN(W) `parseAsync` method.

2019-03-07 19:05 UTC, brentvatne commented
can we upstream color parsing fixes to RNW?

2019-03-07 19:37 UTC, ide commented on packages/expo-linear-gradient/src/processColor.web.ts
> +const defaultColor = [0, 0, 0, 0];
Is this code from somewhere else?

2019-03-07 23:22 UTC, ide commented
What are some of the examples that don't work? Would like to make sure we have the right fix for those here (or change NativeLinearGradient.web.tsx if needed).

2019-03-08 01:26 UTC, ide requested changes

2019-03-08 01:26 UTC, ide commented on packages/expo-linear-gradient/src/NativeLinearGradient.web.tsx
> +function hexStringFromProcessedColor(color: number) {
```suggestion
function hexStringFromProcessedColor(argbColor: number): string {
```

2019-03-08 01:26 UTC, ide commented on packages/expo-linear-gradient/src/NativeLinearGradient.web.tsx
> +  const colorStr = `${color.toString(16)}`;
```suggestion
  const hexColorString = color.toString(16);
```

2019-03-08 01:26 UTC, ide commented on packages/expo-linear-gradient/src/NativeLinearGradient.web.tsx
> +  const withoutAlpha = colorStr.substring(2, colorStr.length);
```suggestion
  const withoutAlpha = colorStr.substring(2);
```

2019-03-08 01:26 UTC, ide commented on packages/expo-linear-gradient/src/NativeLinearGradient.web.tsx
> +function hexStringFromProcessedColor(color: number) {
Move this function below the class so that the more salient code comes first in the file.

2019-03-08 01:27 UTC, ide commented
This approach looks good & correct.

2019-03-08 02:18 UTC, merged