Update expo-cli docs
expo/expo pull request #3752
Opened 2019-03-15 18:47 UTC by AdamJNavarro

Purpose: Make the expo-cli docs a bit more beginner-friendly by painting a clearer picture of what it can be used for.

Changes:
- Create a bulleted list of the main features
- In-lined the installation steps so users don't have to navigate away from the page

# Why

Please describe the motivation for this PR, and link to relevant GitHub issues, forums posts, or feature requests.

# How

How did you build this feature or fix this bug and why?

# Test Plan

Please describe how you tested this change and how a reviewer could reproduce your test, especially if this PR does not include automated tests! If possible, please also provide terminal output and/or screenshots demonstrating your test/reproduction.

2019-03-15 21:19 UTC, cruzach reviewed
Looks good to me! Only thoughts I have would be to change “enhances your workflow” to something more concrete like “makes development faster and easier” just bc people reading these docs are most likely beginners so I think the more obvious what it does is, the better. Also for the same reason, linking to the publishing/building docs pages in those specific bullet points, so that they can easily find what we mean when we say something like “Publishing your JS and assets,” which is now second-nature to us but isn’t if you’re new to Expo.

2019-03-20 18:41 UTC, brentvatne requested changes

2019-03-20 18:41 UTC, brentvatne commented on docs/pages/versions/unversioned/workflow/expo-cli.md
> +Expo CLI is a command line interface that enhances your workflow by empowering developers to perform actions such as:
```suggestion
Expo CLI is a command line app that is the main interface between a developer and Expo tools. You'll use it for a variety of tasks, such as:
```

2019-03-20 18:41 UTC, brentvatne commented on docs/pages/versions/unversioned/workflow/expo-cli.md
> +- Serving your app so you can begin development
```suggestion
- Developing your app: running the project server, viewing logs, opening your app in a simulator 
```

2019-03-20 18:41 UTC, brentvatne commented on docs/pages/versions/unversioned/workflow/expo-cli.md
> +- Creating a new Expo project
```suggestion
- Creating new projects
```

2019-03-20 18:41 UTC, brentvatne commented on docs/pages/versions/unversioned/workflow/expo-cli.md
> +- Publishing your JS and assets
```suggestion
- Publishing your app JavaScript and other assets and managing releasing them over the air
```

2019-03-20 18:41 UTC, brentvatne commented on docs/pages/versions/unversioned/workflow/expo-cli.md
> +- Building `apk` and `ipa` files to be uploaded to the App Store and Play Store
```suggestion
- Building binaries (`apk` and `ipa` files) to be uploaded to the App Store and Play Store
```

2019-03-20 18:41 UTC, brentvatne commented on docs/pages/versions/unversioned/workflow/expo-cli.md
> +- Uploading Apple Credentials and Google Keystores
```suggestion
- Managing Apple Credentials and Google Keystores
```

2019-03-20 18:41 UTC, brentvatne commented on docs/pages/versions/unversioned/workflow/expo-cli.md
> +It also includes a web-based interface, named Expo Dev Tools, which enables you to use some of the most often used features from a quick-to-use graphical interface. We’ve only scratched the surface o
You may use the CLI in your terminal or use the web based interface (it opens automatically by default, or you can press `d` from the CLI to open it on demand). The web interface enables you to use some of the most often used features from a quick-to-use graphical interface. We’ve only scratched the surface of what expo-cli can do so far. Be sure to check out all the possible commands below!

2019-03-27 15:24 UTC, merged