[expo-camera][Android] Fix adding/removing children from CameraPreview
expo/expo pull request #3904
Opened 2019-04-01 07:50 UTC by bbarthec

# Why

Resolves #3495

# How

Previously upon react child added to camera component, preview (Android TextureView) was re-added as a first child to container, but that was causing texture destruction or something similar and newly added preview was not showing actual preview anymore.
Solution is not to remove preview view but to rearrange all children order in camera container.
Side thought: IMO camera should be leaf component and not container.

# Test Plan

You can dynamically add/remove children from `CameraPreview`.
https://snack.expo.io/@barthec/ZXhwby

2019-04-01 07:57 UTC, sjchmiela commented
Have you considered removing ability to add native children to `CameraView` in favor of doing in JS:
```jsx
  render() {
    return (
      <View style={[styles.container, this.props.style]}>
        <ExpoCameraView style={StyleSheet.absoluteFill} />
        {this.props.children}
      </View>
    );
  }
```

2019-04-01 08:54 UTC, mczernek approved these changes

2019-04-01 12:07 UTC, bbarthec commented
@sjchmiela please see this PR description. I wish that camera becomes leaf component, but that would cause breaking change and I would rather do that in #3612 .

2019-04-01 13:06 UTC, tsapeta requested changes

2019-04-01 13:06 UTC, tsapeta commented on packages/expo-camera/android/src/main/java/expo/modules/camera/ExpoCameraView.java
> +    for (View childView: childrenToBeReordered) {
```suggestion
    for (View childView : childrenToBeReordered) {
```

2019-04-01 13:06 UTC, tsapeta commented on packages/expo-camera/android/src/main/java/expo/modules/camera/ExpoCameraView.java
> +      this.bringChildToFront(childView);
```suggestion
      bringChildToFront(childView);
```

2019-04-01 13:06 UTC, tsapeta commented on packages/expo-camera/android/src/main/java/expo/modules/camera/ExpoCameraView.java
> +import android.view.TextureView;
```suggestion
```

2019-04-02 07:53 UTC, sjchmiela commented
Why would it be a breaking change? Is there a noticable difference between putting children inside and next to `<ExpoCameraView />`?

2019-04-05 11:33 UTC, bbarthec commented
@sjchmiela it's matter of discussion whether stopping supporting this (examples and community goes this way now):
```javascript
(
  <ExpoCameraView style={[styles.container, this.props.style]}>
    {this.props.children}
  </ExpoCameraView>
);
```
in favour of this:
```javascript
(
  <View style={[styles.container, this.props.style]}>
    <ExpoCameraView style={StyleSheet.absoluteFill}/>
    {this.props.children}
  </View>
);
```
is a breaking change, but for now I will leave it as is.

2019-04-05 11:35 UTC, merged