@dsokal/updates reanimated
expo/expo pull request #4023
Opened 2019-04-18 10:06 UTC by dsokal

# Why

Closes https://github.com/expo/expo/issues/3969

# How

- I upgraded native code using `update-react-native-reanimated` gulp task.
- I upgraded `react-native-reanimated` to `1.0.1` in `expo` npm package.
- I added a new screen in NCL using Transitioning API (it proves the upgrade succeeded).

# Test Plan

Tested on iPhone and LG (with Android) using the new example screen in NCL.

2019-04-23 10:08 UTC, sjchmiela approved these changes
LGTM! Thanks! 👏

2019-04-23 10:14 UTC, sjchmiela requested changes
Whoops, could you please fix the CI? https://circleci.com/gh/expo/expo/39590 It looks like you'll need to update native modules mocks — run Expo Client, start `apps/jest-expo-mock-generator`, run it in latest Expo Client and follow instructions there

2019-04-23 16:09 UTC, dsokal commented
@sjchmiela should be fixed now

2019-04-24 13:19 UTC, sjchmiela approved these changes

2019-04-24 13:21 UTC, merged