[web] Added local version of parseErrorStack to expo Logger
expo/expo pull request #4063
Opened 2019-04-24 21:41 UTC by EvanBacon

# Why

Removes dependence on React Native internals that aren't supported on web.

2019-04-24 21:46 UTC, ide requested changes
I left some comments but am also wondering if this is the right approach at all. Do we ever show web logs in Expo CLI at all? If not -- and tbh I think the browser console is great -- it might be better not to override console on web in the first place.

2019-04-24 21:46 UTC, ide commented on packages/expo/package.json
> +    "stacktrace-parser": "^0.1.5",
```suggestion
    "stacktrace-parser": "0.1.4",
```
Lock it, 0.1.5 is busted on iOS.

2019-04-24 21:46 UTC, ide commented on packages/expo/src/logs/parseErrorStack.ts
> + * @flow
Clean this up

2019-04-24 21:46 UTC, ide commented on packages/expo/src/logs/parseErrorStack.ts
> + * LICENSE file in the root directory of this source tree.
```suggestion
 * LICENSE file in the root directory of React Native's source tree.
```

2019-04-24 21:46 UTC, ide commented on packages/expo/src/logs/parseErrorStack.ts
> +export type StackFrame = {
Don't need to export the types I think

2019-04-25 01:06 UTC, ide requested changes

2019-04-25 01:06 UTC, ide commented on packages/expo/src/logs/parseErrorStack.ts
> +/**
Delete this file

2019-04-25 01:06 UTC, ide commented on yarn.lock
> -"@expo/react-native-navigator@0.5.2":
Something weird is going on here. I deleted this in a prior commit, check your Git state.

2019-04-25 01:31 UTC, ide commented
Looks like web tests are failing, too -> fix those as well.

2019-04-29 19:19 UTC, EvanBacon commented
Closing in favor of removing altogether: #4066

2019-04-29 19:19 UTC, closed without merging