[web] Added contribution guide for expo web.
expo/expo pull request #4365
Opened 2019-06-02 02:24 UTC by EvanBacon

# Why

Moved from https://github.com/expo/web-examples

2019-06-05 05:55 UTC, amandeepmittal commented
@EvanBacon there are a couple of typos, would you mind if I amend them? 😄

2019-06-05 15:57 UTC, ide commented on docs/pages/versions/unversioned/guides/contributing-to-web.md
> +To work on modules like `expo-camera` or even community libraries, I like to work in the expo monorepo, this is because it's a yarn workspace which links the packages really well.
Let's change the tone from casual & first-person to more second-person like the rest of our docs.

2019-06-06 05:15 UTC, amandeepmittal requested changes
@EvanBacon I could not edit the file directory, so I am submitting some changes I think to fix the typos and improve the overall tone, as suggestions.

2019-06-06 05:15 UTC, amandeepmittal commented on docs/pages/versions/unversioned/guides/contributing-to-web.md
> +There are a couple different things you could work on in regards to Expo for web. Here we'll cover how you can setup your environment to easily contribute.
There are a couple of different things you could work on in regards to Expo for web. Here we'll cover how you can setup your environment to easily contribute.

2019-06-06 05:15 UTC, amandeepmittal commented on docs/pages/versions/unversioned/guides/contributing-to-web.md
> +To work on modules like `expo-camera` or even community libraries, I like to work in the expo monorepo, this is because it's a yarn workspace which links the packages really well.
To work on modules like `expo-camera` or community libraries, consider working in the expo monorepo. The reason for this is that the monorepo is a yarn workspace which links the packages really well.

2019-06-06 05:15 UTC, amandeepmittal commented on docs/pages/versions/unversioned/guides/contributing-to-web.md
> +For example if you want to work on `react-navigation`, clone it to `expo/packages/react-navigation` and run `yarn`, now projects like `expo/apps/native-component-list` will use your local copy of nav
For example, if you want to work on `react-navigation`, clone it to `expo/packages/react-navigation` and run `yarn`. Now projects like `expo/apps/native-component-list` will use your local copy of navigation and update when you make changes.

2019-06-06 05:15 UTC, amandeepmittal commented on docs/pages/versions/unversioned/guides/contributing-to-web.md
> +For absolute best practices, I use the `expo-module-scripts` which unify the TypeScript configuration and make testing really easy. The setup looks something like this:
For absolute best practices, use the `expo-module-scripts` that unifies the TypeScript configuration and makes testing really easy. The setup looks something like this:

2019-06-06 05:15 UTC, amandeepmittal commented on docs/pages/versions/unversioned/guides/contributing-to-web.md
> +Currently we are temporarily adding documentations to this repo (`web-examples`). In the future we will move this to [Expo Docs](https://docs.expo.io). Until then, you can open issues or pull request
Currently, we are temporarily adding documentation to this repo (`web-examples`). In the future, we will move this to [Expo Docs](https://docs.expo.io). Until then, you can open issues or pull requests with new documentation, ideas, or questions here! 😁

2019-10-09 00:52 UTC, closed without merging