Modify the console.log function to truncate large files during logging
expo/expo pull request #4419
Opened 2019-06-04 22:24 UTC by vivianzzhu91

# Why

Modified the console.log function to truncate large files when doing console.log() 
Resolve the issue: https://github.com/expo/expo/issues/4340

# How

Try to change the return results in the packages/expo/src/logs to find where the data are sent to Expo Cli and check for the string length to truncate it.

# Test Plan

I tried to load a local json file with 22 MB and it worked to print 10000 characters (around 10kb) instead of giving a PayloadTooLargeError.

2019-06-04 22:52 UTC, ide requested changes

2019-06-04 22:52 UTC, ide commented on ios/Exponent.xcodeproj/project.pbxproj
> +						DevelopmentTeam = 74633SH798;
Revert all changes to the iOS project.

2019-06-04 22:52 UTC, ide commented on apps/sandbox/app.json
> +}
Revert

2019-06-04 22:52 UTC, ide commented on apps/sandbox/package.json
> +}
Revert

2019-06-04 22:52 UTC, ide commented on packages/expo/src/logs/LogSerialization.ts
> +      if(result.length > 10000){
Set up your editor to run Prettier and run it over this file

2019-06-04 22:52 UTC, ide commented on packages/expo/src/logs/LogSerialization.ts
> +        let newResult = result.substring(0,10000);
```suggestion
        let truncatedResult = result.substring(0,10000);
```

2019-06-04 22:52 UTC, ide commented on packages/expo/src/logs/LogSerialization.ts
> +        newResult += '...';
Communicate clearly what is happening with the truncation when people see this in their logs:
```suggestion
        newResult += `...(truncated to the first ${LOG_MESSAGE_MAX_LENGTH} characters)`;
```

2019-06-04 22:52 UTC, ide commented on packages/expo/src/logs/LogSerialization.ts
> +      //check the size of string returned
style: space between `//` and comment

```suggestion
      // check the size of string returned
```

2019-06-04 22:52 UTC, ide commented on packages/expo/src/logs/LogSerialization.ts
> +        //truncate the result to 10kb
```suggestion
        // truncate the result to 10kb
```

2019-06-04 22:52 UTC, ide commented on ios/Exponent.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
> +<?xml version="1.0" encoding="UTF-8"?>
Revert

2019-06-04 22:52 UTC, ide commented on ios/Exponent/Supporting/Info.plist
> +		<string>81130e95ea13cd7ed9a4f455e96214902c721c99</string>
Revert

2019-06-05 00:37 UTC, ide requested changes
It looks like several file permissions changed as part of your commit (644 -> 755) -- please revert these.

2019-06-05 00:37 UTC, ide commented on packages/expo/src/logs/LogSerialization.ts
> +        truncatedResult += '...';
add the message explaining what is going on: https://github.com/expo/expo/pull/4419#discussion_r290526911

2019-06-10 17:23 UTC, esamelson reviewed
looks great -- thanks for fixing this!! could you add an entry to CHANGELOG.md in the repo root? then will be good to go ahead and merge.

2019-06-10 21:54 UTC, merged