[home] Added image banner for Expo home.
expo/expo pull request #4424
Opened 2019-06-05 05:31 UTC by EvanBacon

# Why

Utilize the Camera, MediaLibrary, and associated permissions in the home app. 

# How

Added a banner image to the user profile which is stored in local state. Then using the MediaLibrary, and Cameraja code from NCL, integrated a system for choosing images.

# Test Plan

Should be able to run home in home with expo start. Go to your user profile and add a banner image by pressing the "Change Banner" button. If you reset the app, the banner should persist. Other profiles will show a default image until actually integrating with a server sometime in the future.

![IMG_0365](https://user-images.githubusercontent.com/9664363/58932272-00915480-8718-11e9-95e6-754f8512cdb7.PNG)
![IMG_0363](https://user-images.githubusercontent.com/9664363/58932274-00915480-8718-11e9-925a-02a48a88e53e.PNG)
![IMG_0362](https://user-images.githubusercontent.com/9664363/58932277-0129eb00-8718-11e9-8fa7-25025a3f73e0.PNG)
![IMG_0361](https://user-images.githubusercontent.com/9664363/58932280-01c28180-8718-11e9-91b3-fb9854c15c20.PNG)

2019-06-06 17:54 UTC, brentvatne commented on home/screens/MediaLibrary/MediaDetailsScreen.tsx
> +      case MediaLibrary.MediaType.video: // TODO: render Expo.Video component
what happens in the current form if someone chooses a videO?

2019-06-07 04:57 UTC, ide requested changes
Rebase after your kernel and options buttons commits, and also clean up unused cruft.

2019-06-07 04:57 UTC, ide commented on home/screens/MediaLibrary/MediaAlbumsScreen.tsx
> +// import MonoText from '../../components/MonoText';
fix whatever is going on here

2019-06-07 04:57 UTC, ide commented on home/screens/MediaLibrary/MediaDetailsScreen.tsx
> +import * as MediaLibrary from 'expo-media-library';
This whole screen looks irrelevant

2019-06-07 04:57 UTC, ide commented on home/screens/MediaLibrary/MediaLibraryScreen.tsx
> +      // headerRight: (
remove

2019-06-07 04:57 UTC, ide commented on home/screens/MediaLibrary/MediaLibraryScreen.tsx
> +    // this.props.navigation.navigate('MediaDetails', {
remove

2019-06-07 04:57 UTC, ide commented on home/screens/MediaLibrary/MediaLibraryScreen.tsx
> +    console.log('chosen: ', asset);
remove

2019-06-11 04:07 UTC, ide commented on home/screens/MediaLibrary/MediaAlbumsScreen.tsx
> +    title: 'MediaLibrary Albums',
This doesn't look right..

2019-06-11 05:52 UTC, merged