babel-plugin-expo-vector-icons
expo/expo pull request #4530
Opened 2019-06-11 03:06 UTC by EvanBacon

# How

Removed the re-export of vector-icons. You will now have to import your fonts like so

```diff
- import { Icons } from 'expo';

+ import { Ionicons } from '@expo/vector-icons';
```

Which will then become a direct import after bundling:

```diff
- import { Ionicons } from '@expo/vector-icons';

+ import Ionicons from '@expo/vector-icons/build/Ionicons';
```

> This applies to native as well.

# Test Plan

In the future, running `expo build:web` will generate a project with only the font files you use and none of the extra fonts. Currently you get all of these bundled even if you never use fonts:

```
AntDesign.ttf
Entypo.ttf
Feather.ttf
FontAwesome.ttf
FontAwesome5_Brands.ttf
FontAwesome5_Solid.ttf
Foundation.ttf
Ionicons.ttf
MaterialCommunityIcons.ttf
MaterialIcons.ttf
SimpleLineIcons.ttf
```

2019-11-20 11:02 UTC, sjchmiela approved these changes
Apart from these two comments I would say it looks good to me. Are we looking to merge it?

Isn't importing icons from `expo` deprecated for a while now so we could remove it altogether and remove the root need for this package?

2019-11-20 18:12 UTC, brentvatne commented
> Isn't importing icons from `expo` deprecated for a while now so we could remove it altogether and remove the root need for this package?

since it was removed we have added it back as a global because it's still depended on in the ecosystem: https://github.com/expo/expo/blob/master/packages/expo/src/globals.ts

2019-11-20 18:15 UTC, brentvatne commented
i think we should add this to the vector-icons repo so it's clear that changes to @expo/vector-icons may require updating this plugin

i like this pr though!

2019-11-20 18:15 UTC, brentvatne approved these changes

2019-11-24 20:01 UTC, ide requested changes
Looks good except for the Babel 6 usage. Also we need to have a smooth transition plan for deprecating `import { Icons } from 'expo';`.

2019-11-24 20:01 UTC, ide commented on packages/babel-plugin-expo-vector-icons/package.json
> +    "babel-core": "^6.26.3",
Having two versions of Babel in the repo is more likely to cause issues somewhere down the line. Update this to use Babel 7.

2020-04-07 22:20 UTC, EvanBacon commented
stale, closing. We may investigate using SVG icons on web instead.

2020-04-07 22:20 UTC, closed without merging