@bbarthec/native splash screen
expo/expo pull request #4567
Opened 2019-06-12 13:44 UTC by bbarthec

# Why

`Picassa` was not preventing from loading too big images into `ImageView` what is causing error like this: Max size of Bitmap that can be set to ImageView is 4096*4096 px. ([link for reference](https://medium.com/@v.danylo/android-16-e56c27173ef4)).

`Glide` is by default downscaling loaded images to `2048*2048 px` or so.

# How

Replaced `Picassa` lib with `Glide`. `Glide` is also used by `unimodules-react-native-adapter`

2019-06-12 14:04 UTC, tsapeta requested changes

2019-06-12 14:04 UTC, tsapeta commented on docs/pages/versions/unversioned/guides/splash-screens.md
> +- **contain** - Android SplshScreen API is unable to stretch/scale splash image (see **native** mode). This mode would instruct device to show only background color first and then, when some view hie
```suggestion
- **contain** - Android SplashScreen API is unable to stretch/scale splash image (see **native** mode). This mode would instruct device to show only background color first and then, when some view hierarchy is mounted, `splash.image` will be shown as contained image.
```

2019-06-12 14:04 UTC, tsapeta commented on docs/pages/versions/unversioned/guides/splash-screens.md
> +- **cover** - Same behaviour as in **contain** mode in terms of firstly showing background color and than mounting some view hierarchy presenting splash image that covers whole screen.
```suggestion
- **cover** - Same behaviour as in **contain** mode in terms of firstly showing background color and then mounting some view hierarchy presenting splash image that covers whole screen.
```

2019-06-12 14:04 UTC, tsapeta commented on docs/pages/versions/v33.0.0/guides/splash-screens.md
> +- **contain** - Android SplshScreen API is unable to stretch/scale splash image (see **native** mode). This mode would instruct device to show only background color first and then, when some view hie
```suggestion
- **contain** - Android SplashScreen API is unable to stretch/scale splash image (see **native** mode). This mode would instruct device to show only background color first and then, when some view hierarchy is mounted, `splash.image` will be shown as contained image.
```

2019-06-12 14:04 UTC, tsapeta commented on docs/pages/versions/v33.0.0/guides/splash-screens.md
> +- **cover** - Same behaviour as in **contain** mode in terms of firstly showing background color and than mounting some view hierarchy presenting splash image that covers whole screen.
```suggestion
- **cover** - Same behaviour as in **contain** mode in terms of firstly showing background color and then mounting some view hierarchy presenting splash image that covers whole screen.
```

2019-06-12 14:04 UTC, tsapeta commented on android/expoview/src/main/java/host/exp/exponent/LoadingView.java
> +            public boolean onLoadFailed(@Nullable GlideException e, Object model, Target<Drawable> target, boolean isFirstResource) {
Can we make one function that loads Glide so we don't have duplicated code here?

2019-06-17 13:30 UTC, sjchmiela approved these changes
Looks more or less good to me, could you ask some better English-speaking reviewer to also take a look at the copy?

2019-06-18 17:24 UTC, brentvatne requested changes
left some suggestions for wording changes in the documentation, they will need to be backported to the sdk33 file too

2019-06-18 17:24 UTC, brentvatne commented on docs/pages/versions/unversioned/guides/splash-screens.md
> +- **contain** - Android SplashScreen API is unable to stretch/scale splash image (see **native** mode). This mode would instruct device to show only background color at first and then, when some view
```suggestion
- **contain** - on Android, the splash screen API is unable to stretch/scale the splash image (see the **native** mode). As a result, the `contain` mode will initially display only the background color, and when the initial view hierarchy is mounted then `splash.image` will be displayed.
```

2019-06-18 17:24 UTC, brentvatne commented on docs/pages/versions/unversioned/guides/splash-screens.md
> +- **cover** - Same behaviour as in **contain** mode in terms of firstly showing background color and then mounting some view hierarchy presenting splash image that covers whole screen.
```suggestion
- **cover** - this mode has the limitations as **contain** for the same reasons.
```

2019-06-18 17:24 UTC, brentvatne commented on docs/pages/versions/unversioned/guides/splash-screens.md
> +- **native** - In this mode your app will be leveraging Android's ability to present a static bitmap at the very beginning of the application start. Unfortunately, Android (unlike iOS) is not support
```suggestion
- **native** - in this mode your app will be leveraging Android's ability to present a static bitmap while the application is starting up. Android (unlike iOS) does not support stretching the provided image, so the application will  present the given image centered on the screen. By default `splash.image` would be used as the `xxxdpi` resource. It's up to you to provide graphics that meet your expectations and fit the screen dimension. To achieve this, use different resolutions for [different device DPIs](../../workflow/configuration/#android), from `mdpi` to `xxxhdpi`.
```

2019-06-18 17:26 UTC, brentvatne commented
we should also rename "Differences between environments - Android" to "Splash screen API limitations on Android"

2019-06-24 15:53 UTC, merged