fix(react-native-adapter): Bare React Native app _reactNative.UIManager.getViewManagerConfig is not a function close #4737
expo/expo pull request #4819
Opened 2019-07-04 03:48 UTC by Pines-Cheng

# Why

Accessing view manager configs directly off UIManager via UIManager[ ] is no longer supported from React Native 0.58. Use UIManager.getViewManagerConfig() instead.

Which cause Bare React Native app _reactNative.UIManager.getViewManagerConfig is not a function  #4737 

# How

add a line of compatible code

# Test Plan

use expo-av under React Native@0.55.4 , It's fine.

2019-07-04 08:25 UTC, tsapeta requested changes
Hey @Pines-Cheng, thanks for contributing! 💪 
This looks good to me, but could you please apply this one formatting change, run `yarn build` in `react-native-adapter` package and commit changes it made? JavaScript files in `build` folder will be updated as well after that 🙂

2019-07-04 08:25 UTC, tsapeta commented on packages/@unimodules/react-native-adapter/src/NativeViewManagerAdapter.tsx
> +  const reactNativeUIConfiguration = (UIManager.getViewManagerConfig ? UIManager.getViewManagerConfig(reactNativeViewName):UIManager[reactNativeViewName]) || {
```suggestion
  const reactNativeUIConfiguration = (UIManager.getViewManagerConfig ? UIManager.getViewManagerConfig(reactNativeViewName) : UIManager[reactNativeViewName]) || {
```

2019-07-04 11:38 UTC, Pines-Cheng commented
have formatting code and run yarn build in react-native-adapter~

2019-07-04 14:16 UTC, tsapeta requested changes

2019-07-04 14:16 UTC, tsapeta commented on packages/@unimodules/react-native-adapter/build/index.d.ts
> +    OS: import("react-native").PlatformOSType;
I don't think we want this change 🤔

```suggestion
    OS: "ios" | "android" | "windows" | "macos" | "web";
```

2019-07-05 05:42 UTC, Pines-Cheng commented
thank you for review~

2019-07-05 11:07 UTC, tsapeta approved these changes
Thank you so much for your work 🙂

2019-07-05 11:09 UTC, merged