[Calendar] Fix Calendar.getEventsAsync and remove Calendar.DEFAULT
expo/expo pull request #4836
Opened 2019-07-05 12:19 UTC by lukmccall

# Why

Resolves #4760.

# How

Wrapping calendarId with ''.

# Test Plan

If calendarId is sqlite keyword it will not longer crash app.
You can check it https://snack.expo.io/@lukaszkosmaty/healthy-crackers.

2019-07-08 07:10 UTC, bbarthec requested changes
Nice job 💯 👍 💪 Please refer to my comments and add entry in [CHANGELOG.md](https://github.com/expo/expo/blob/master/CHANGELOG.md)

2019-07-08 07:10 UTC, bbarthec commented on packages/expo-calendar/ios/EXCalendar/EXCalendar.m
> +             nil);
Two things:
1) proper indentation
2.a) in general if method invocation isn't too long, we keep it as oneliner (`reject(@"E_INVALID_CALENDAR_ID", @"CalendarId is required.", nil);`)
2.b) another thing is to keep an eye on parameters alignment when method invocation is multiliner - keep all arguments aligned to the first one
```obj-c
       |
reject(@"E_INVALID_CALENDAR_ID",
       @"CalendarId is required.",
       nil);
       |
       ^
       aligning line 
```

2019-07-08 07:10 UTC, bbarthec commented on packages/expo-calendar/src/Calendar.ts
> +export async function createEventAsync(calendarId: string, { id, ...details }: OptionalKeys<Event> = {}): Promise<string> {
I have a quest for you 😂 Please, in separate commit, remove type `OptionalKeys` and replace it with TypeScript default `Partial` built-in type 😜

2019-07-08 07:10 UTC, bbarthec commented on packages/expo-calendar/src/Calendar.ts
> +  calendarIds: (string | null)[],
Interesting way, but convention is to use `Array<firstTypeInUnionType | secondTypeInUnionType | ... and so on>`

2019-07-08 07:10 UTC, bbarthec commented on packages/expo-calendar/src/Calendar.ts
> +  {id, ...details}: Reminder = {}
proper indentation is:
`{ id, ...details }: Reminder = {}`

2019-07-09 08:23 UTC, tsapeta approved these changes
Nice one, good work! 💪 Let @bbarthec do the final review and feel free to merge once he approves 😉

2019-07-09 08:38 UTC, bbarthec approved these changes

2019-07-09 08:38 UTC, merged