[sqlite][iOS] Fix bool variable representation
expo/expo pull request #4862
Opened 2019-07-08 12:03 UTC by lukmccall

# Why

Resolve #4656

# How

BOOL variable in objective-c can be represent as `bool` or `signed char` (according to [objc.h](https://opensource.apple.com/source/objc4/objc4-706/runtime/objc.h.auto.html)). 
We only check if BOOL variables are represent as a `bool`.  

# Test Plan

[Should work now](https://snack.expo.io/@lukaszkosmaty/[sqlite]-ios-fails-to-execute-%22create-table%22)

2019-07-08 15:42 UTC, ide requested changes
Can you please provide a more robust test plan that shows the code working?

2019-07-08 15:42 UTC, ide commented on packages/@unimodules/core/ios/UMCore/UMExportedModule.m
> +      char value = [obj charValue];
```suggestion
      BOOL value = [obj charValue];
```

2019-07-09 08:35 UTC, tsapeta approved these changes
Looks good to me 👍

2019-07-09 08:35 UTC, tsapeta commented on packages/@unimodules/core/ios/UMCore/UMExportedModule.m
> +    if([methodSignature getArgumentTypeAtIndex:(2 + idx)][0] == _C_CHR){
```suggestion
    if ([methodSignature getArgumentTypeAtIndex:(2 + idx)][0] == _C_CHR) {
```

2019-07-09 08:51 UTC, lukmccall commented
On older devices (with 32 bit iOS) BOOL type is represented by `signed char` so I tested SQL module on iPhone 5 (simulator and physical device)

2019-07-09 09:17 UTC, tsapeta commented
@lukmccall Could you also add changelog entry for that? Maybe not specifically for SQLite as I can imagine there are some more issues that might have been solved by this.

2019-07-09 12:19 UTC, merged

2019-07-17 09:45 UTC, giautm commented
Hi @tsapeta , Is it released in SDK-33 as a fix? I facing with this issues on production right now.

2019-07-19 16:29 UTC, ide commented
This will go out with SDK 34.