[camera] ability to modify video bitrate on android
expo/expo pull request #4878
Opened 2019-07-09 10:44 UTC by xHeinrich

# Why
To allow for more fine grained control over the size of video files generated on android. This is especially useful for apps being used for video services to reduce the amount of data transfer required when uploading video.
https://github.com/react-native-community/react-native-camera/issues/687

# How

Most of the code is taken from the below PR on react-native-camera
https://github.com/react-native-community/react-native-camera/pull/2055

# Test Plan

I dont currently have a mac so am unable to test the changes. I will try get my hands on one to compile the changes and ensure its functioning. The code attached should be sufficient to test the changes.

```this.camera.recordAsync({
        quality: Camera.Constants.VideoQuality['720p'],
        videoBitrate: 1000
    })```

2019-07-15 13:45 UTC, bbarthec requested changes
You need to build `expo-camera` and provide newer `build` directory with your changes (our idea is to have transpilled code ready to be used after user install each unimodule):
```
yarn build
```

Good job 💯 overall, but we need to test your changes when ready, so please adjust PR and I will take of it further.

2019-07-15 13:45 UTC, bbarthec commented on CHANGELOG.md
> +- added `videoBitrate` option for camera component on android
```suggestion
- Added `videoBitrate` option for camera on Android by [@xHeinrich] ([#4878])
```

2019-07-15 13:45 UTC, bbarthec commented on docs/pages/versions/v33.0.0/sdk/camera.md
> +  - **videoBitrate (_number_)** -- Android Only. (int greater than 0) This option specifies a desired video bitrate.  For example, 5\*1000\*1000 would be 5Mbps.
Please move these changes to https://github.com/expo/expo/blob/master/docs/pages/versions/unversioned/sdk/camera.md

2019-07-15 13:45 UTC, bbarthec commented on packages/expo-camera/android/src/main/java/expo/modules/camera/ExpoCameraView.java
> +        profile.videoBitRate = (int) options.get(VIDEO_BITRATE_KEY);
```suggestion
        profile.videoBitRate = ((Double) options.get(VIDEO_BITRATE_KEY)).intValue();
```

2019-07-15 13:45 UTC, bbarthec commented on packages/expo-camera/src/Camera.tsx
> +    console.warn('Video Bitrate should be a positive integer');
Remove that checking. `Typescript` is ensuring proper typings, we do not want to duplicate its work in runtime.

2019-07-16 02:53 UTC, xHeinrich commented
Thanks! I've updated all of the requested items and run yarn build however for some reason the sdk test is still failing, is there something specific I should do to resolve that?

2019-11-08 16:40 UTC, bbarthec commented
@xHeinrich, I need to apologise to you - I've lost track of this PR and it fell behind master so terribly 🙇 I'd like to merge your PR, but I need to ask you to refresh it a little by resolving conflicts 🙏

2020-01-19 18:28 UTC, wolverineks commented
@xHeinrich any plans to fix the merge conflicts?
i could give it a try if you're too busy. im working on a project right now that might benefit from this

2020-01-20 12:14 UTC, bbarthec commented
@wolverineks please do, as @xHeinrich seems unreachable for a while now 😢

2020-01-30 13:51 UTC, xHeinrich commented
@wolverineks @bbarthec please feel free to update this, last time i tried running yarn build the tests were still failing and couldnt figure out why. You might have better luck.

2020-03-05 02:51 UTC, wolverineks commented
ive made the changes, and ive written a simple test in test-suite/tests/Camera.js
but which commands should i run to get the changes?

ive tried
`yarn build` in expo-camera
`expo start` in test-suite

am i heading in the right direction?

2020-03-05 03:57 UTC, wolverineks commented
ok, i think i got it now

2020-03-09 16:47 UTC, wolverineks commented
dang, i finally got bare-expo to run, but Camera and GL test options are greyed out
any ideas?

2020-03-10 01:52 UTC, wolverineks commented
it looks like this commit wrapped the import so that the Camera.js tests never run if there is an error thrown.
the error thrown is:
`TypeError: undefined is not an object (evaluating 'CameraManager.Type)`
im running on my device (Pixel 3), so do i have to start the app differently to get it to import the camera without throwing?

https://github.com/expo/expo/commit/dc814a6b86b23bc80c8ca78b6579f2e3c6b42abc#diff-225580c4eddce6fbc51d58127b6e3219

2020-03-11 16:41 UTC, bbarthec commented
@wolverineks, please don't bother about writing tests for this small change as there's hardly any way to actually test in on JS level.
Please take care of conflicts, by running `yarn build` in `packages/expo-camera` and manual adjustments and I'll take care of the rest 💪

2020-03-11 20:05 UTC, wolverineks commented
@bbarthec any value to a test like...
```typescript
t.it('records with selected bitrate', async () => {
        const videoBitRate = 8000000; // 8 Mbps
        const duration = 1; // 1 second
        await mountAndWaitFor(<Camera ref={refSetter} style={style} />);
        const { uri } = await instance.recordAsync({
          maxDuration: duration,
          videoBitRate,
        });
        const fileInfo = await FileSystem.getInfoAsync(uri);
        const actualBitRate = (fileInfo.size * 8) / duration;

        t.expect(actualBitRate).toBeLessThan(videoBitRate * 1.25);
        t.expect(actualBitRate).toBeGreaterThan(videoBitRate * 0.75);
      });
```

@xHeinrich did you ever get around to testing this, on a device or otherwise?

2020-03-11 22:40 UTC, xHeinrich commented
@wolverineks i manually tested on device

2020-03-12 09:25 UTC, bbarthec commented
@wolverineks, I see a value in the test you are suggesting, but if you're having this amount of problems running them correctly I prefer you not to worry about them and ship the feature 😉
Unfortunately I cannot assure you that I would be of any help in this testing matter right now 😞😭

2020-03-13 16:39 UTC, wolverineks commented
if you can confirm that `test-suite/tests/Camera.js` runs on `bare-expo`, ill keep chugging away

2020-03-13 18:06 UTC, bbarthec commented
@wolverineks, unfortunately at this moment `camera` test are not working in `bare-expo`, so please don't worry about them 😉
However, as you've already prepared test for this new option, please comment them out and provide them in your PR 😃

2020-03-13 18:44 UTC, wolverineks commented
thats too bad. oh well, let us know when the tests are running again. thanks

2021-01-17 14:49 UTC, limiaspasdaniel commented
@wolverineks any news on this?

2021-01-17 21:29 UTC, wolverineks commented
> @wolverineks any news on this?

i stopped working on this when the test suite wouldn't run
i tried again today, but i couldn't get it to run on android or ios

2021-02-11 23:51 UTC, makzee commented
I'm trying to get it working. I have hand picked the changes from xHeinrich repo into my repo, now trying to test it. I don't use Mac but have an old Mac machine and setting up the environment there so that I could test it.

2021-02-12 18:54 UTC, makzee commented
@bbarthec I have fixed the conflicts and created a new PR (https://github.com/expo/expo/pull/11932).

2021-02-18 11:59 UTC, xHeinrich commented
Thanks for the work getting this into master @makzee

2021-02-18 11:59 UTC, closed without merging