[Localization] Change Localization.country
expo/expo pull request #4921
Opened 2019-07-11 14:42 UTC by lukmccall

# Why

Resolve #4540.

# How

Country variable on Android came from currently selected language, however on devices with iOS country was got from `Region` in `Language & Region`. 
Not all android phone provide `Region` setting, so I suggest renaming Localization.country to Localization.region and make it available only on iOS.

# Test Plan

You can check it on https://snack.expo.io/@lukaszkosmaty/9e807b.
I also updated test-suits.

2019-07-15 22:12 UTC, EvanBacon commented on docs/pages/versions/unversioned/sdk/localization.md
> +**Available on iOS only.**  Region code for your device which came from `Region` setting in `Language & Region`. Ex: `US`, `NZ`.
Seems like web has support as well

2019-07-17 09:05 UTC, bbarthec reviewed
LGTM 💯 Please add entry in `CHANGELOG.md` under `breaking changes` section 😃

2019-08-02 16:20 UTC, sjchmiela approved these changes

2019-08-05 12:07 UTC, bbarthec approved these changes

2019-08-06 08:53 UTC, tsapeta requested changes
Looks good, but could you add changelog entry and fix issues found by CI in `expo_sdk` job?

2019-08-23 18:24 UTC, tsapeta approved these changes

2019-08-23 18:27 UTC, merged

2020-04-10 21:43 UTC, tobiascornille commented
So it's not possible to guess the country on Android without asking for the user's location?

2021-09-02 16:48 UTC, Stevemoretz commented
Weird though how does Whatsapp know your phone-number prefix then?