[MediaLibrary][Android] Fix media's width and height are sometimes 0
expo/expo pull request #4935
Opened 2019-07-12 09:33 UTC by lukmccall

# Why

Resolve #4326.

# How

For some images (for example from Instagram) dimensions got from `query` don't have value, so i get them from `BitmapFactory.Options`

# Test Plan

You can check it on https://snack.expo.io/@kakarn/medialibrarybug.

2019-07-12 11:57 UTC, tsapeta requested changes
Looks good except one typo 😉 
Would you like to add some tests to `test-suite` checking whether returned sizes are correct? I guess it is not possible to reproduce an issue in our tests, but simple checks on our test assets would be great and enough 🙂

2019-07-12 11:57 UTC, tsapeta commented on packages/expo-media-library/android/src/main/java/expo/modules/medialibrary/MediaLibraryUtils.java
> +  static int[] getSizeFromCoursor(Cursor cursor, int mediaType, int localUriIndex){
```suggestion
  static int[] getSizeFromCursor(Cursor cursor, int mediaType, int localUriIndex) {
```

2019-07-12 11:57 UTC, tsapeta commented on packages/expo-media-library/android/src/main/java/expo/modules/medialibrary/MediaLibraryUtils.java
> +      int[] size = getSizeFromCoursor(cursor, mediaType, localUriIndex);
```suggestion
      int[] size = getSizeFromCursor(cursor, mediaType, localUriIndex);
```

2019-07-12 13:28 UTC, tsapeta approved these changes

2019-07-17 09:12 UTC, bbarthec approved these changes
LGTM 💯 Only one small suggestion.

2019-07-17 09:12 UTC, bbarthec commented on packages/expo-media-library/android/src/main/java/expo/modules/medialibrary/MediaLibraryUtils.java
> +        cursor.getType(heightIndex) == Cursor.FIELD_TYPE_NULL &&
I believe if any of `cursor.getType({widthIndex, heightIndex})` equals `Cursor.FIELD_TYPE_NULL` we should check for actual size using this different flow. 
```suggestion
if ((cursor.getType(widthIndex) == Cursor.FIELD_TYPE_NULL ||
    cursor.getType(heightIndex) == Cursor.FIELD_TYPE_NULL) &&
    mediaType == Files.FileColumns.MEDIA_TYPE_IMAGE)
```

2019-08-06 08:15 UTC, tsapeta commented on apps/test-suite/tests/MediaLibrary.js
> +      t.it('check size - vide', async () => {
```suggestion
      t.it('check size - video', async () => {
```

2019-08-06 08:42 UTC, tsapeta approved these changes

2019-08-06 09:04 UTC, merged