Update up-and-running.md
expo/expo pull request #5031
Opened 2019-07-21 23:43 UTC by peterennis

language and typo

# Why

Please describe the motivation for this PR, and link to relevant GitHub issues, forums posts, or feature requests.

# How

How did you build this feature or fix this bug and why?

# Test Plan

Please describe how you tested this change and how a reviewer could reproduce your test, especially if this PR does not include automated tests! If possible, please also provide terminal output and/or screenshots demonstrating your test/reproduction.

2019-07-22 18:35 UTC, cruzach commented
Great! Could you make the same changes to [SDK 33 docs page](https://github.com/expo/expo/blob/master/docs/pages/versions/v33.0.0/workflow/up-and-running.md) and [SDK 34 docs page](https://github.com/expo/expo/blob/master/docs/pages/versions/v34.0.0/workflow/up-and-running.md)?

2019-07-23 01:26 UTC, peterennis commented
@cruzach 

Done here: https://github.com/expo/expo/pull/5043

2019-07-23 13:12 UTC, cruzach requested changes
no need to change this, I think. On the other linked PR you kept the wording the same, so let's do the same here.

2019-07-23 13:12 UTC, cruzach commented on docs/pages/versions/unversioned/workflow/up-and-running.md
> +- If you've followed the above steps and live reload **still** doesn't work, [post to Expo Forums](https://forums.expo.io/c/help) to send us a support request. Until we resolve your reported issue, y
```suggestion
- If you've followed the above steps and live reload **still** doesn't work, [post to Expo Forums](https://forums.expo.io/c/help) to send us a support request. Until we resolve the issue for you, you can either shake the device and press `Reload`, or use one of the following tools which work both with and without development mode.
```

2019-08-06 18:17 UTC, closed without merging