Fix expo check
expo/expo pull request #5053
Opened 2019-07-23 15:53 UTC by n-sviridenko

# Why

There is no `expo` folder inside this package. And expo webpack config doesn't resolve this path.

2019-07-23 18:27 UTC, ide requested changes
This doesn't look robust -- expo-constants cannot assume that the expo package is installed at `../../expo`, which is why it looks for `expo` instead.

Not sure what the correct fix is, but we need it to be robust.

2019-07-24 09:34 UTC, n-sviridenko commented
Maybe it can be solved on a project level? We tried NODE_PATH, webpack
resolve options, but this didn’t help

вт, 23 июля 2019 г. в 20:27, James Ide <notifications@github.com>:

> *@ide* requested changes on this pull request.
>
> This doesn't look robust -- expo-constants cannot assume that the expo
> package is installed at ../../expo, which is why it looks for expo
> instead.
>
> Not sure what the correct fix is, but we need it to be robust.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/expo/expo/pull/5053?email_source=notifications&email_token=ACHHE7XGHELZFVPQQBNSI7DQA5ES5A5CNFSM4IGGAR3KYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOB7KKWYQ#pullrequestreview-265595746>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ACHHE7TOZMZXP4375C4YGWTQA5ES5ANCNFSM4IGGAR3A>
> .
>

2019-07-24 19:09 UTC, ide commented
@bacon is expo-constants supposed to be able to load the manifest on web when `expo` is installed? (Or is that not supposed to work at all?)

2019-11-20 17:29 UTC, sjchmiela commented
There's no such function anymore, so this shouldn't be a problem! 😅

2019-11-20 17:29 UTC, closed without merging