Created babel-plugin-universal-platforms
expo/expo pull request #5158
Opened 2019-08-02 03:12 UTC by EvanBacon

# Why

Transform projects for the platform they're built to run on.

The following examples show what the output of a lexical block looks like after it's been transpiled with `expo build:web` (`babel-plugin-universal-platforms` & Webpack's Terser).

## If Statements

Application code

```js
import { Platform } from '@unimodules/core';
let value;
if (Platform.OS === 'ios') {
  value = 'ios';
} else if (Platform.OS == 'android') {
  value = 'android';
} else if (Platform.OS === 'web') {
  value = 'web';
} else {
  value = 'default';
}
console.log('Output', value);
```

### Before

```js
var value,
  Platform = {
    OS: 'web',
    select(e) {
      return 'web' in e ? e.web : e.default;
    },
  };
(value =
  Platform.OS === 'ios'
    ? 'ios'
    : Platform.OS == 'android'
    ? 'android'
    : Platform.OS === 'web'
    ? 'web'
    : 'default'),
  console.log('Output', value);
```

### After

```js
console.log('Output', 'web');
```

## `Platform.select`

### Input

```js
import { Platform } from 'react-native';
const value = Platform.select({
  ios: 'ios',
  android: 'android',
  web: 'web',
  default: 'default',
});
console.log('Output', value);
```

### Before

```js
var value = {
  OS: 'web',
  select(e) {
    return 'web' in e ? e.web : e.default;
  },
}.select({ ios: 'ios', android: 'android', web: 'web', default: 'default' });
console.log('Output', value);
```

### After

```js
console.log('Output', 'web');
```

## Switch Statements

### Input

```js
import { Platform } from 'react-native';
switch (Platform.OS) {
  case 'ios':
    console.log('iOS');
    break;
  case 'android':
    console.log('Android');
    break;
  case 'web':
    console.log('web');
    break;
  default:
    console.log('default');
    break;
}
```

### Before

```js
switch (
  {
    OS: 'web',
    select(e) {
      return 'web' in e ? e.web : e.default;
    },
  }.OS
) {
  case 'ios':
    console.log('iOS');
    break;
  case 'android':
    console.log('Android');
    break;
  case 'web':
    console.log('web');
    break;
  default:
    console.log('default');
}
```

### After

```js
console.log('web');
```

# How

Created `babel-plugin-universal-platforms`

# Test Plan

CI should pass

2019-08-09 22:58 UTC, ide requested changes

2019-08-09 22:58 UTC, ide commented on packages/babel-plugin-universal-platforms/src/__tests__/index-test.ts
> +// Terser should shake it during the bundling.
```suggestion
// Terser should remove it during the bundling.
```

2019-08-09 22:58 UTC, ide commented on packages/babel-plugin-universal-platforms/src/__tests__/index-test.ts
> +// Terser should shake it during the bundling.
```suggestion
// Terser should remove it during the bundling.
```

2019-08-09 22:58 UTC, ide commented on packages/babel-plugin-universal-platforms/src/__tests__/index-test.ts
> +it(`switch statement is converted for Terser`, () => {
```suggestion
it(`converts switch-statement predicates for Terser`, () => {
```

2019-08-09 22:58 UTC, ide commented on packages/babel-plugin-universal-platforms/src/__tests__/index-test.ts
> +describe('if Statements', () => {
```suggestion
describe('if statements', () => {
```

2019-08-09 22:58 UTC, ide commented on packages/babel-plugin-universal-platforms/src/__tests__/index-test.ts
> +  it('should replace Platform.select with value for default case if there is no matching platform', () => {
```suggestion
  it(`replaces Platform.select with the default value if no platform matches`, () => {
```

2019-08-09 22:58 UTC, ide commented on packages/babel-plugin-universal-platforms/src/__tests__/index-test.ts
> +  it('should replace Platform.select with value for matching platform', () => {
```suggestion
  it(`replaces Platform.select with the value for the matching platform`, () => {
```

2019-08-09 22:58 UTC, ide commented on packages/babel-plugin-universal-platforms/src/__tests__/index-test.ts
> +  it('should remove non-matching platforms but leave Platform.select', () => {
```suggestion
  it(`removes non-matching platforms but leaves Platform.select if other platforms may match at runtime`, () => {
```

2019-08-09 22:58 UTC, ide commented on packages/babel-plugin-universal-platforms/src/__tests__/index-test.ts
> +  it('should replace Platform.select with undefined if no cases are matching', () => {
```suggestion
  it('replaces Platform.select with "undefined" if no platforms match`, () => {
```

2019-08-09 22:58 UTC, ide commented on packages/babel-plugin-universal-platforms/src/__tests__/index-test.ts
> +  it('should remove non-matching platforms but leave Platform.select with unknown cases 1', () => {
```suggestion
  it(`removes non-matching platforms but leaves Platform.select with indeterminate platforms`, () => {
```

2019-08-09 22:58 UTC, ide commented on packages/babel-plugin-universal-platforms/src/__tests__/index-test.ts
> +  it('should remove non-matching platforms but leave Platform.select with unknown cases and default case', () => {
```suggestion
  it(`removes non-matching platforms but leaves Platform.select with indeterminate platforms and the default case`, () => {
```

2019-08-09 22:58 UTC, ide commented on packages/babel-plugin-universal-platforms/src/__tests__/index-test.ts
> +  it('should remove non-matching platforms but leave Platform.select with method', () => {
I think we can do better here:
```
const value = Platform.select({ android() {} });
```
could become
```
const value = function() {};
```

2019-08-09 22:58 UTC, ide commented on packages/babel-plugin-universal-platforms/src/__tests__/index-test.ts
> +  it('should remove non-matching platforms but leave Platform.select with method', () => {
```suggestion
  it(`leaves Platform.select if the matching platform's value is a method`, () => {
```

2019-08-09 22:58 UTC, ide commented on packages/babel-plugin-universal-platforms/src/index.ts
> +// /Literal$/.test(node.type) || (node.type === 'Identifier' && node.name === 'undefined');
```suggestion
```

2019-08-09 22:58 UTC, ide commented on packages/babel-plugin-universal-platforms/src/index.ts
> +    throw new Error('babel-plugin-universal-platforms: platform option must be defined');
```suggestion
    throw new Error('babel-plugin-universal-platforms: "platform" option must be defined');
```

2019-08-09 22:58 UTC, ide commented on packages/babel-plugin-universal-platforms/src/index.ts
> +     * Transforms static ID values for Terser to shake
```suggestion
     * Transforms static ID values for Terser to analyze
```

2019-08-09 22:58 UTC, ide commented on packages/babel-plugin-universal-platforms/src/index.ts
> +     * Transforms member expressions for Terser to shake
```suggestion
     * Transforms member expressions for Terser to analyze
```

2019-08-09 22:58 UTC, ide commented on packages/babel-plugin-universal-platforms/src/index.ts
> +       * Transforms redundant boolean expressions
do we need to do this? shouldn't terser take care of this?

2019-08-09 22:58 UTC, ide commented on packages/babel-plugin-universal-platforms/src/index.ts
> +        // If we got exact mach, we can strip the rest
```suggestion
        // If we got an exact match, we can strip the rest
```

2019-08-09 22:58 UTC, ide commented on packages/babel-plugin-universal-platforms/src/index.ts
> +    'BinaryExpression|LogicalExpression': {
shouldn't terser take care of this as well?

2020-08-08 03:47 UTC, EvanBacon commented
Closing for now

2021-05-10 09:16 UTC, closed without merging