[expo-wallet] Supports adding passes to Apple Wallet unimodule
expo/expo pull request #5365
Opened 2019-08-16 22:53 UTC by vivianzzhu91

# Why

Due to this [feature request](https://expo.canny.io/feature-requests/p/apple-wallet), we decided to add `expo-wallet` module to add passes to Apple Wallet with different functionalities and UI component (the Add to Apple Wallet button) and web implementations.

# How

With reference to Apple official [docs](https://developer.apple.com/documentation/passkit/wallet?language=objc) and `react-native-wallet`, I created this module.

# Test Plan

Tested on real devices and got all expected behaviors and event emitters working.
![IMG_6852](https://user-images.githubusercontent.com/35270434/63202298-eb04a900-c03d-11e9-9673-cdbc30566bda.PNG)

2019-08-16 22:56 UTC, hesyifei commented
Todo:

- [ ] Add [PKAddPassButton](https://developer.apple.com/documentation/passkit/pkaddpassbutton)

- [ ] Web support (`Wallet.addPassFromUrlAsync(url)` should open the URL. Probably add a `alert` if the user is not using Safari to say that they have to open the downloaded .pkpass file manually.)

2019-09-11 11:47 UTC, sheepsteak commented
This is great! Will this make it into [Expo SDK 35?](https://github.com/expo/expo/issues/5564)

2019-09-11 17:55 UTC, esamelson commented
@sheepsteak - no, it will not; we have a pretty hard deadline for SDK 35 due to iOS 13, and this PR has not gone through review yet. However, this is going to be a bare-workflow-only module for the time being (just like `expo-in-app-payments`) and so at the time it does land, we will not need to wait for the next SDK version to release it.

2019-11-28 17:25 UTC, dbbk commented
Any news on this? This would be very useful for us.

2019-12-17 18:37 UTC, amsimoes commented
Any news? I need this very urgently on my project, otherwise I'll have to eject :'(

2020-02-08 16:32 UTC, AngSin commented
Can we get an update about this please?

2020-02-10 19:10 UTC, esamelson commented
Hi all - we are not actively working on this right now. You are welcome to check out this branch and try installing the module yourself but ymmv.

2020-02-19 07:10 UTC, EvanBacon commented on packages/expo-wallet/android/src/main/java/expo/modules/wallet/WalletViewManager.java
> +    return Arrays.asList("onSomethingHappened");
...

2020-02-19 07:11 UTC, EvanBacon commented on packages/expo-wallet/package.json
> +,"_resolved": ""
remove

2020-02-19 07:12 UTC, EvanBacon commented on packages/expo-wallet/src/ExpoWallet.web.ts
> +    window.open(url);
nice

2020-02-19 07:12 UTC, EvanBacon requested changes
Android shims need to be resolved

2020-03-09 18:57 UTC, amsimoes commented
Guys, any news? @vivianzzhu91 @EvanBacon how can I help here?

2020-06-26 13:32 UTC, sjchmiela commented
In an effort to keep all the Expo libraries high quality and well maintained we sometimes have to trim the branches of different libraries we would like to support, but don't really have the bandwidth to.

Expo bare workflow and `react-native-wallet` will be the best way to go if you need this feature. 🙂

2020-06-26 13:32 UTC, closed without merging

2020-10-01 21:39 UTC, HughBerriez commented
@sjchmiela  This feature is the one feature in the next 3 months or so that I forsee causing us to have to eject to the bare workflow. It looks like so much work was done on the PR for the adding card to wallets feature. 

Is this really closed for the foreseeable future? Definitely a bit of a bummer if so

2020-10-01 21:58 UTC, sjchmiela commented
It does indeed look like a good work, unfortunately I'm afraid we wouldn't feel comfortable taking on yet another module's maintaining burden. Once we tidy up what we have already we may revisit this PR.

FWIW even if this was implemented there's no 100% chance that this would be available in the managed workflow — I haven't checked, but Wallet stuff seems like it may cause apps to undergo a more thorough Apple Review process and not all Expo-built apps would be able to explain why do they need to do something with the Apple Wallet API.

Moreover, bare workflow has undergone some pretty serious changes since the middle of 2019 and ejecting to bare workflow no longer means "having to spend a week configuring some strange native stuff" nor "not being able to use all the Expo goodness" — we've removed ExpoKit so now you eject to bare-bare-React-Native with unimodules preconfigured and we've moved last of our best features to bare-compatible packages, i.e. `expo-updates`, `expo-splash-screen` and `expo-notifications`.

2020-10-01 22:34 UTC, HughBerriez commented
@sjchmiela thanks for the quick and detailed reply. That makes a lot of sense - I'll take a deeper look into the updated bare workflow - sounds much less daunting that a few years ago. Really do appreciate the insights above - expo is incredible.