[docs] discard the '/#__next' suffix when navigating to GH edit page
expo/expo pull request #5387
Opened 2019-08-19 20:23 UTC by cruzach

# Why

When you navigate to a page via the Algolia search results, the url has `/#__next` appended to it. This will throw off the "Edit this Page" link at the bottom of each docs page, so the regex will not match either the trailing slash **or `/#__next`**, and replace it with `.md`

# Test Plan

tested locally

2019-08-20 00:54 UTC, ide requested changes
See comment

2019-08-20 00:54 UTC, ide commented on docs/components/DocumentationFooter.js
> +  let pathAsMarkdown = path.replace(/\/$|\/#__next$/, '') + '.md';
This looks overly precise -- our intent is to get the pathname without any query strings or fragments, not just `#__next`. I think we may want to figure out why `path` has a fragment in the first place and fix the issue at the source (i.e. an assertion that `path` doesn't have `?` or `#` always should pass).

2019-08-21 16:17 UTC, cruzach commented
@ide new commit discards the extraneous anchor by transforming docsearch's returned hits (if they contain it). 

Apparently, this is happening because of a lack of anchor id/name for the header element? Might instead be able to avoid this by giving those headers an anchor, haven't tried that yet though

2019-08-21 17:27 UTC, ide approved these changes

2019-08-21 17:27 UTC, ide commented on docs/components/plugins/AlgoliaSearch.js
> +          hit.url = hit.url.replace(/#__next/, '');
```suggestion
          hit.url = hit.url.replace(/#__next$/, '');
```

2019-08-21 17:27 UTC, ide commented on docs/components/plugins/AlgoliaSearch.js
> +          hit.anchor = hit.anchor.replace(/__next/, '');
```suggestion
          hit.anchor = hit.anchor.replace(/^__next$/, '');
```

2019-08-21 18:57 UTC, merged