[ios][image-picker] Copy video file instead of moving
expo/expo pull request #5434
Opened 2019-08-24 00:29 UTC by tsapeta

# Why

Fixes #5321 

# How

Simply replaced `moveItemAtURL:toURL:error` with `copyItemAtURL:toURL:error`, as the first one throws an error due to missing permissions 🤷‍♂ Probably the temporary directory to which the compressed videos are saved is now protected in iOS 13.

# Test Plan

Snack https://snack.expo.io/@tsapeta/imagepicker-from-camera-roll works as expected on iOS 13.

2019-08-26 23:57 UTC, esamelson requested changes
Do we need to delete the file, or will the OS take care of this for us? We've had issues in the past with ImagePicker creating multiple copies of files in temp locations and taking up a bunch of space. Just want to make sure we aren't creating that problem again, inadvertently.

Also would advocate for **not** backporting this to older SDK versions unless we are planning to cherry-pick to old release branches and create new shell app bases. Otherwise this creates more confusing behavior differences between the client and shell apps (i.e. ImagePicker works on my SDK 33 project in the Expo Client, why is it suddenly failing in my standalone app?). Better to leave it alone in the Expo Client so it's clear you need to upgrade to 35 in order to fix this.

2019-08-27 23:39 UTC, merged

2019-09-23 09:16 UTC, mvjansen commented
Hi, there still appears to be an issue in ImagePicker.launchImageLibraryAsync.  I get the following error when I select a video: "The callback callMethod() exists in module NativeUnimoduleProxy, but only one callback may be registered to a function in a native module"

2019-09-23 09:34 UTC, sjchmiela commented
Hey @mvjansen! Could you please create a new issue with all the details provided? This sounds like a completely different problem than the one fixed by this PR. Thanks!

2019-09-23 14:59 UTC, Nnoerregaard commented
@mvjansen I experienced the exact same issue on iOS 13 before upgrading to expo SDK 35 (I was on SDK 33 previously).
After updating, the issue has disappeared

2019-09-23 17:04 UTC, tomelsner commented
@mvjansen I had the same issue, it disappeared when updating to SDK 35. Make sure you also update "expo-image-picker": "^7.0.0" and you also have "sdkVersion": "35.0.0" set in your app.json.

2019-09-24 06:31 UTC, mvjansen commented
Thanks for your help everyone - I'd missed updating the sdkVersion in app.json! @Nnoerregaard @tomelsner

2021-04-23 04:22 UTC, mikeRChambers610 commented
I am using Expo SDK 40 and "expo-image-picker": "~9.2.0", but still getting the issue.

When I try to pick a video, my error message is shown as below:

Possible Unhandled Promise Rejection (id: 0): Error: Could not get the image promiseMethodWrapper@http.......

2021-04-23 04:44 UTC, mikeRChambers610 commented
Upgraded to Expo SDK 41 and now using "expo-image-picker": "~10.1.4", still getting the same issue.