[expo-ads-admob] Upgrade underlying native SDKs
expo/expo pull request #5447
Opened 2019-08-26 23:14 UTC by sjchmiela

# Why

Fixes https://github.com/expo/expo/issues/5242 and closes https://github.com/expo/expo/issues/5330.

# How

Upgraded underlying native SDKs on both iOS and Android. Added required app IDs to `AndroidManifest` and `Info.plist`. Added support for `googleMobileAdsAppId` to XDL and Universe. Added documentation around `googleMobileAdsAppId`.

x-refs: https://github.com/expo/expo-cli/pull/961, https://github.com/expo/universe/pull/3660

# Test Plan

Expo client builds with these changes on both platforms.

2019-08-27 01:24 UTC, ide requested changes

2019-08-27 01:25 UTC, sjchmiela commented on template-files/android/AndroidManifest.xml
> +      android:value="ca-app-pub-3940256099942544~3347511713"/>
Those are sample IDs from AdMob setup instructions

> Note: If you haven't created an AdMob account and registered an app yet, now's a great time to do so. In a real app, it is important that you use your actual AdMob app ID, not the one listed above. If you're just looking to experiment with the SDK in a Hello World app, though, you can use the sample App ID shown above. ([Source](https://developers.google.com/admob/ios/quick-start#update_your_infoplist))

2019-08-27 01:54 UTC, ide approved these changes

2019-08-28 17:25 UTC, merged

2019-09-13 13:25 UTC, changLiuUNSW commented
@sjchmiela @ide 
When is this change going to release ? 
We only have 7 days left for the IOS 13. Is that possible to release this one as soon as possible. Otherwise my app will get blocked due to https://github.com/expo/expo/issues/5242

2019-09-13 16:21 UTC, ide commented
We are looking to release SDK 35 before the iOS 13 public release (Sept 19).

2019-11-24 09:24 UTC, MehmetKaplan commented
Hi,

First pardon me for the below dump question but I need a comment to decide if I really need to modify the code or not...

According to the SDK 35 release blog ( https://blog.expo.io/expo-sdk-35-is-now-available-beee0dfafbf4 ), this change seems as a breaking change **for all** Admob related codes. But when I test existing application without the app.json addition it seems fine.

> Admob: all Admob ads now require a new configuration value in app.json, expo.[platform].config.googleMobileAdsAppId. The value can be found by following the guide in this Google Support answer. (Related PR.)

So the question is, is it really required for all Admob ads or is it related with firebase only (#5242 and #5330)

2019-11-26 21:52 UTC, ide commented
You need this for standalone apps. I would follow the instructions because even if things happen to work without changes, accidental side effects like that are not part of the public interface and might break whenever.