migrate to androidx
expo/expo pull request #5521
Opened 2019-09-02 10:19 UTC by Szymon20000

# Why

Please describe the motivation for this PR, and link to relevant GitHub issues, forums posts, or feature requests.

# How

How did you build this feature or fix this bug and why?

# Test Plan

Please describe how you tested this change and how a reviewer could reproduce your test, especially if this PR does not include automated tests! If possible, please also provide terminal output and/or screenshots demonstrating your test/reproduction.

2019-09-03 17:05 UTC, mczernek approved these changes

2019-09-04 19:27 UTC, ide requested changes
This is a great start and will make it so much smoother for Expo developers on Android when we add RN 0.61 to the Expo client.

Do we need to recompile any AARs, such as ReactAndroid for SDK 33 and 34?

**Release timing:** I think the best time to land this commit will be after the SDK 35 branch has been cut for a few reasons. SDK 35 uses RN 0.59.8, which does not have AndroidX support outside of our changes. So if someone uses ExpoKit v35 and looks for a module that is compatible with RN 0.59.8 (no AndroidX), we want their app to compile.

Additionally, this is a complex PR and the longer we have to test it, the better. By merging it after the SDK 35 branch has been created, this maximizes the amount of time we can internally test this PR on master before creating the SDK 36 branch.

**Testing:** We need a thorough test plan as part of this PR, especially because it has to be so large in several ways unfortunately. Some of the activity screens like the OAuth webview activity seem important to test since they reference class names from XML. We also need to test loading projects that use older SDK versions.

**Vendored libraries:** what should people who are updating vendored libraries like Maps be aware of? When @brentvatne or @sjchmiela updates GestureHandler, for example, will the new versions have AndroidX support or will they need to make manual changes, in which case what should they do? Do we need to reach out to library authors to have a sustainable path forward?

2019-09-05 09:26 UTC, bbarthec commented on android/app/build.gradle
> +  implementation 'androidx.appcompat:appcompat:1.0.0'
Take a look here: https://developer.android.com/jetpack/androidx/versions
Version of each package seems to be diverged 🤔

2019-09-24 15:18 UTC, Szymon20000 commented on android/app/src/main/res/layout/error_activity_new.xml
> +<androidx.viewpager.widget.ViewPager
I checked this activity and it works.

2019-09-24 15:23 UTC, Szymon20000 commented on android/cameraview/cameraview/src/main/api14/com/google/android/cameraview/Camera1.java
> +import androidx.collection.SparseArrayCompat;
I think so. However, @bbarthec is more familiar with this topic.

2019-09-24 18:30 UTC, ide approved these changes

2019-09-25 07:15 UTC, merged