[react-native-adapter] Update build.gradle for react-native@>0.60 support
expo/expo pull request #5648
Opened 2019-09-14 02:23 UTC by brentvatne

# Why

It's important to support the latest stable version of React Native.

# How

https://github.com/unimodules/react-native-unimodules/issues/67#issuecomment-529892115

# Test Plan

This change worked as expected in a bare project with 0.59 and 0.60. Let's let CI do the rest.

2019-09-14 09:11 UTC, sjchmiela requested changes
If only we could get away with it in Expo client too… CI failed since the builder now tries to load both `android/ReactAndroid` and `com.facebook.react:react-native:+`

```
Warning: Exception while processing task java.io.IOException: Can't write [/root/expo/android/app/build/intermediates/transforms/proguard/release/0.jar] (Can't read [/root/expo/android/ReactAndroid/build/intermediates/intermediate-jars/release/classes.jar(;;;;;;;**.class)] (Duplicate jar entry [com/facebook/debug/debugoverlay/model/DebugOverlayTag.class]))
```

2019-09-18 18:23 UTC, brentvatne commented
😢 any ideas @sjchmiela @tsapeta? we need to update rn-adapter for 0.60 support asap

2019-09-19 05:19 UTC, sjchmiela commented
The easiest, but maybe not the prettiest way of fixing this would be to introduce some kind of `ext` variable that would decide whether the adapter should include dependencies as if `ReactAndroid` was there (`compileOnly`?) or as if used in bare workflow (`implementation`). I don't have any better idea as of yet.

Do we know if the problem comes from some change in React Native itself, or from upgrading Android Studio / Gradle version in RN 0.60?

If it's the former, I would be ok with getting away with a solution like this (API-like change).

If it's the latter, we will need to look into proper Gradle setup nevertheless (there are numerous reports stating there are problems with ejected projects on newer versions of AS/Gradle), so fixing that would actually fix this bug too.

2019-09-19 12:42 UTC, sjchmiela commented
Interestingly, here Expo client compiled https://github.com/expo/expo/pull/5695 with this change!

2019-10-15 08:58 UTC, sjchmiela commented
Closed in https://github.com/expo/expo/pull/5695

2019-10-15 08:58 UTC, closed without merging