[docs] Explain how to correctly map Expo published source maps to Sentry Issues
expo/expo pull request #5659
Opened 2019-09-16 13:44 UTC by aldegoeij

# Why

Clarification of Sentry documentation, how to map Sentry Issues to the correct Sentry Release source maps as published by Expo

# How

doc update

# Test Plan

n.a.

2019-09-16 22:07 UTC, ide requested changes

2019-09-16 22:07 UTC, ide commented on docs/pages/versions/unversioned/guides/using-sentry.md
> +import Constants from "expo-constants"
```suggestion
import Constants from 'expo-constants';
```

2019-09-16 22:07 UTC, ide commented on docs/pages/versions/unversioned/guides/using-sentry.md
> +Sentry.setRelease(Constants.manifest.revisionId)
```suggestion
Sentry.setRelease(Constants.manifest.revisionId);
```

2019-09-16 22:07 UTC, ide commented on docs/pages/versions/unversioned/guides/using-sentry.md
> +In order to use the published release sourcemaps with Issues in Sentry, you'll have to set your Expo `revisionId` as Sentry release identifier, like so:
```suggestion
In order to use the published release source maps with Issues in Sentry, you'll have to set your Expo `revisionId` as the Sentry release identifier, like so:
```

2019-09-17 08:01 UTC, aldegoeij commented
All accepted!

2019-09-17 08:37 UTC, ide commented
Please push the changes so that we can land them.

2019-09-17 19:04 UTC, merged