Update Appearance Module Documenation
expo/expo pull request #5743
Opened 2019-09-23 13:45 UTC by AEJester

# Why

The current documentation on the expo website does not show the full documentation for the module, this Pull Request fixed that.

# How

I used the help that u/brentvatne gave to me on reddit, and added them into the documentation page. I also added a full example of an app that supports Light/Dark system themes.

# Test Plan

I tested this change by looking at the markdown and concluding that it looks like official documentation. I also tested the example app and it works as intended on my iDevice.

2019-09-23 19:50 UTC, ide commented
@cruzach could you please do a pass over this when you get back (rewrite as necessary) so that this is consistent with the other docs?

2019-09-23 20:08 UTC, brentvatne commented
hi there! I just noticed this PR, I have updated the documentation already to clarify the app.json key: https://docs.expo.io/versions/v35.0.0/sdk/appearance/#configuration

do you think this is sufficient?

2019-09-23 20:14 UTC, AEJester commented
> hi there! I just noticed this PR, I have updated the documentation already to clarify the app.json key: https://docs.expo.io/versions/v35.0.0/sdk/appearance/#configuration
> 
> do you think this is sufficient?

I do think what you have added is satisfactory, but having an example in the documentation until you can update snack to support ios13 (has it already?) would be even better. Please change what you need in my PR (or just don't merge it lol, it's up to you guys), and thanks for all the help you've given me!

2019-09-25 14:05 UTC, EvanBacon commented on docs/pages/versions/v35.0.0/sdk/appearance.md
> +import react, {Component} from 'react';
```suggestion
import React, {Component} from 'react';
```

2019-09-25 14:05 UTC, EvanBacon commented on docs/pages/versions/v35.0.0/sdk/appearance.md
> +export default class App extends Component {
Rewrite with hooks plx

2019-09-25 22:49 UTC, brentvatne commented
an example could be useful! as @EvanBacon's advice here would be good to follow if you're interested in updating it

2019-09-26 17:54 UTC, cruzach requested changes
along with Evan's requested changes, just copy/paste this into https://snack.expo.io/ and hit `Prettier {}` so the formatting fits the rest of our examples/snacks

2019-09-26 17:54 UTC, cruzach commented on docs/pages/versions/v35.0.0/sdk/appearance.md
> +        <View stle={{
```suggestion
        <View style={{
```

2020-02-19 07:08 UTC, EvanBacon approved these changes
LGTM thanks for the hooks :D

2020-02-19 07:08 UTC, merged