Add Cli Command documentation
expo/expo pull request #5786
Opened 2019-09-26 20:05 UTC by AdamJNavarro

# Why

Provides an added resource for users to gain knowledge of the commands offered by the CLI and what their options do.

# How

Each command is now documented to indicate if an alias is available, the possible options as well as descriptions for the command itself and its options.

Will add changes to other versions upon feedback and approval.

2019-09-26 22:53 UTC, brentvatne commented
<img width="897" alt="Screen Shot 2019-09-26 at 15 50 56" src="https://user-images.githubusercontent.com/90494/65730106-8a717e80-e075-11e9-8928-639e8ee8a441.png">

we should improve spacing here - there should be less spacing between the header and its related paragraph and more between the header and the previous section.

<hr />

another concern i have is that this is a lot of information and it's hard to parse. i think we might want to make the commands appear at the top level but have all of the information under the commands collapsed, so you have to click on the command to see the full info. probably want to add an arrow next to it to indicate its expandable. if we don't have any tools for building this into the docs right now we should create them.

<hr />

not sure what the process for creating these docs is like but once we settle on the exact format (the above two points) we should create a script that will generate these docs from `expo-cli` automatically so we don't have to manually update all the time

2019-09-26 22:54 UTC, brentvatne requested changes
☝️

2019-11-21 11:50 UTC, sjchmiela approved these changes
LGTM apart from that one small comment. BTW is this docs easily updatable? (Does it require manual labor to keep it up to date?)

2019-11-21 11:50 UTC, sjchmiela commented on docs/pages/versions/unversioned/workflow/expo-cli.md
> +## Universal Options
I think this should come above the specific commands, otherwise it gets lost

2019-11-21 12:03 UTC, sjchmiela commented
Oh, I see this should have gotten closed by https://github.com/expo/expo/commit/1247cefb5b8a2ce32d5f70daf164c7a78506f958.

2019-11-21 12:03 UTC, closed without merging