[views] "expo-views" - a module for common views like View, ScrollView, Text, etc...
expo/expo pull request #5848
Opened 2019-10-03 05:10 UTC by ide

This provides a common interface across more than just Android and iOS and also sets up the API to more easily add in a more optimized image implementation, for example. This is intentionally a very thin module that should not change the behavior of any apps and helps restructure the code to be more universal.

2019-10-03 07:03 UTC, tsapeta approved these changes

2019-10-03 07:03 UTC, tsapeta commented on packages/expo-views/README.md
> +- Image
What about StyleSheet?

2019-10-03 07:08 UTC, ide commented on packages/expo-views/README.md
> +- Image
😱

2019-10-15 22:49 UTC, brentvatne requested changes
the world is not ready yet

2021-02-17 08:15 UTC, ide commented
I have a better approach in mind that is more modular and simpler to name.

2021-02-17 08:15 UTC, closed without merging