Disable font face observer on MS Edge
expo/expo pull request #5961
Opened 2019-10-14 01:16 UTC by EvanBacon

# Why

fix #5935

# How

- Disable font face observer on MS Edge
- Disable entire module in node

# Test Plan

- should run on edge
- shouldn't throw in SSR envs

2019-10-14 10:17 UTC, ide requested changes
Edge is moving to Chromium, in which case I'd expect this API to start working. Need to figure out how to distinguish between old and new Edge.

2019-10-14 10:17 UTC, ide commented on packages/expo-font/src/ExpoFontLoader.web.ts
> +    if (!('document' in global)) {
seems like you should use the canUseDOM check

2019-10-15 00:45 UTC, EvanBacon commented
Should be fine. You detect new Edge by finding `edg` https://social.msdn.microsoft.com/Forums/en-US/edde0150-9478-4ca6-ba0f-9e084b5a4719/how-to-detect-microsoft-edge-chromium-chrome-ie-browser-using-javascript?forum=iewebdevelopment

2019-10-15 01:11 UTC, EvanBacon commented
Saving unrelated ios_build failure: https://app.circleci.com/jobs/github/expo/expo/98499/parallel-runs/0/steps/0-117

2019-10-15 02:36 UTC, ide approved these changes
OK, good to know

2019-10-23 01:31 UTC, merged

2019-12-24 09:51 UTC, lucasfronza commented
Had the same issue with Firefox and Safari.

```
if (navigator.userAgent.includes('Firefox')) {
    return;
}
if (navigator.userAgent.includes('Safari')) {
    return;
}
```
seems to fix it.

2020-04-09 11:57 UTC, jjg77 commented
I'm seeing the same issue in Firefox and Safari.  Is there a fix?