[BarcodeScanner][iOS] Fix scanning PDF417 with \0 (null) characters
expo/expo pull request #5976
Opened 2019-10-15 15:28 UTC by bbarthec

# Why

Resolves #4817
iOS SDK does not properly scan `PDF417` barcodes containing `u'\0'` (null) characters, what trims substring after `u'\0'` character occurrence.

_Update:_
Added support for scanning `Code39` by `ZXing` as it scans correctly images [like 
this](https://github.com/expo/expo/pull/5976#issuecomment-545001008) while built-in iOS scanner does not recognise barcode at all.

# How

I've added `zxing` library for scanning only `PDF417` barcode type.

# Test Plan

`ncl#BarcodeScannerScreen`

2019-10-16 11:09 UTC, tsapeta requested changes
This whole ZXing pod looks really big, can we use just `PDF417` subspec instead?

2019-10-22 14:51 UTC, xiCO2k commented
Hey @bbarthec also detected that code39 is not working well for example with car VIN codes like this:
![image](https://user-images.githubusercontent.com/823088/67298826-b3a1f500-f4e3-11e9-9c32-ab2fe63dda7f.png)

Do you think the ZXing library can also help with that?

Thanks

2019-10-24 11:33 UTC, xiCO2k commented
@bbarthec thats awesome, thanks ;)

2019-10-28 12:23 UTC, bbarthec commented
@xiCO2k, it looks that `ZXing` can handle your scenario and produce some useful result 🎉 I've added support for scanning `Code39` for ZXing flow. Meanwhile you can try [`ZXing demo app`](https://github.com/zxingify/zxingify-objc/tree/master/examples/BarcodeScanner).

2019-10-28 12:30 UTC, tsapeta approved these changes

2019-10-28 12:30 UTC, tsapeta commented on CHANGELOG.md
> +- Fixed scanning `PDF417` in `BarCodeScanner` on iOS. ([#5976](https://github.com/expo/expo/pull/5531) by [@bbarthec](https://github.com/bbarthec))
```suggestion
- Fixed scanning `PDF417` and `Code39` in `BarCodeScanner` on iOS. ([#5976](https://github.com/expo/expo/pull/5531) by [@bbarthec](https://github.com/bbarthec))
```

2019-10-28 12:54 UTC, xiCO2k commented
@bbarthec @tsapeta That is great, thanks a lot.

2019-10-28 23:15 UTC, esamelson reviewed
thanks for looking into this @bbarthec . Code changes look good to me, but could we get a sense of the filesize diff of a release-mode build with and without these three ZXing pods included?

2019-11-06 18:21 UTC, gabzim commented
Will this make SDK 36?

2019-11-06 18:57 UTC, xiCO2k commented
Hopping that will be on the SDK 36, the Code39 fix for iOS would be awesome to have it no SDK 36 :)

2019-11-08 13:32 UTC, bbarthec commented
@esamelson, I've prepared two simulator builds (based off master & based off this branch) using `et client-build -p ios` command and these are the results:
```bash
150M	ExponentWithoutZXING.app
152M	ExponentWithZXING.app
231M	ExponentWithoutZXING.app.dSYM
233M	ExponentWithZXING.app.dSYM
```

2019-11-08 23:03 UTC, esamelson approved these changes
OK, that diff doesn't seem too bad, let's go ahead and land this. Thanks for investigating!

2019-11-12 14:57 UTC, merged