[contacts] Add note to generated entitlements file
expo/expo pull request #5977
Opened 2019-10-15 16:15 UTC by lukmccall

# Why

Resolve #5949.

# How

Now, users can set `com.apple.developer.contacts.notes` entitlement (It's connected to https://github.com/expo/expo/commit/882d80bf97b50d7cade84bf4a3f09d2af702bdfc).

# Test Plan

N/D

2019-10-16 10:59 UTC, tsapeta requested changes

2019-10-16 10:59 UTC, tsapeta commented on docs/pages/versions/unversioned/workflow/configuration.md
> +    "note": BOOLEAN,
name of this configuration should be self-descriptive, `note` tells nothing to the users

2019-10-28 09:29 UTC, sjchmiela approved these changes
LGTM! Has the Universe PR been merged?

2019-11-04 12:31 UTC, sjchmiela approved these changes
Just one suggestion and then 👍

2019-11-04 12:31 UTC, sjchmiela commented on docs/pages/versions/unversioned/sdk/contacts.md
> +| Note                    | `'note'`                     | ⚠️  | ✅      | On iOS 13 and above, your app must have the `com.apple.developer.contacts.notes` entitlement. You must contact Apple and rece
```suggestion
| Note                    | `'note'`                     | ⚠️  | ✅      | On iOS 13 and above, your app must have the `com.apple.developer.contacts.notes` entitlement. You must contact Apple and receive approval for this entitlement. Read [the Apple docs](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_contacts_notes) to learn more. Expo client doesn't have this entitlement. However, you can add this to a standalone app. To do this you need to set the `accessesContactNotes` key to true in your app.json file as specified [here](https://docs.expo.io/versions/latest/workflow/configuration/#ios). |
```

2019-11-04 15:17 UTC, merged