[ios][expo-battery] isSupported false in simulator
expo/expo pull request #6067
Opened 2019-10-23 16:55 UTC by bradbumbalough

# Why

Resolves #5584.

# How

In the native iOS `EXBattery.m` module's constants method I check if the target is a simulator and then return `FALSE`. 

# Test Plan

I updated the test suite to check if `Battery.isSupported` (in addition to testing that it is `TRUE` for iOS devices and Android. It doesn't seem that the Battery test is called for simulators, and I wasn't sure if it qualified to be added to the `global.DETOX` group of tests. 

Otherwise it can be verified by checking for `Battery.isSupported` on an iOS simulator. The actual device tests for Battery should still pass since it would be `TRUE` in that case.

2019-10-25 21:58 UTC, brentvatne commented
hi @bradbumbalough! we'll need to discuss this one a bit as we want to make sure that similar types of functionality has similar naming across modules. we use `Module.isAvailableAsync()` in a handful of places currently and `Module.isSupported()` in one place, but this would be the first instance of `Module.isSupported`

2019-10-25 22:01 UTC, bradbumbalough commented
Hey @brentvatne, that makes sense! I initially just wanted to keep the existing constant but I think it would be good to have the same method of checking if it's available. We could do `Module.isSupported()` since we wouldn't need to wait on the bridge to get the value. In fact, this could probably move to pure JS function since we have the apis to know the platform and `Device.isDevice`. Let me know how you'd like it to go and I'll update.

2019-10-30 13:27 UTC, EvanBacon commented
Could you convert it to `isAvailableAsync` -- we probably want to ensure every module has a `isAvailableAsync(): Promise<boolean>` method.

2019-11-06 00:53 UTC, ide requested changes

2019-11-06 00:53 UTC, ide commented on docs/pages/versions/v35.0.0/sdk/battery.md
> +Note: On iOS simulators, battery monitoring is not possible. You can confirm by checking [`Battery.isSupported`](#batteryissupported).
revert SDK 35 doc changes

2019-11-25 14:33 UTC, closed without merging