[android][Linking] allow Linking.openUrl while app is foregrounded
expo/expo pull request #6077
Opened 2019-10-24 20:22 UTC by cruzach

# Why

Closes #6058 
When a standalone app was already foregrounded, the incorrect key (the `scheme` rather than the published url) was being searched for in the `mManifestUrlToOptions` hashmap.
# How

Search for the appropriate URL in the hashmap

# Test Plan

Tested locally

2019-10-24 21:00 UTC, esamelson commented
@cruzach thanks so much for digging into this 🙏  Have you verified that this doesn't break anything in the Expo client case? IIRC `Constants.INITIAL_URL` is null or `""` in the Expo client so I think this might break `openURI` in the client. We may need to check `Constants.isStandaloneApp()` here.

I would recommend testing a few common linking cases in both the client and a standalone app before landing this -- probably some list like
- Expo client: test `exp://<your app manifest url>` with app in foreground, in background, and closed
- Expo client: test `exp://<some other app manifest url>` with your app open in the foreground
- Standalone app: test `<scheme>://deep/link` with app in foreground, in background, and closed
- Both: test opening some other url (`tel://` maybe?) from your app

and make sure the initial URL is set correctly and the listener fires when expected in all cases. This code is pretty tough to modify without accidentally breaking something else so it's good to err on the side of testing more things.

2019-10-25 17:09 UTC, cruzach commented
Good point, I had tested standalone but not in the Expo Client. Turns out this completely broke behavior in the client 😬 

- standalone app: test `<scheme>://deep/link` with app in foreground, in background, and closed, and multiple different links to different screens in the same app. The `Linking.addEventListener` listener doesn't fire in the case of a closed app, but that's due to the listener not being added yet, so that's expected
- Expo client: test exp://<some other app manifest url> with your app open in the foreground
- Both: test opening some other url (tel:// ) from app
- opening exp://exp.host/<your app manifest url> from another published experience opens the expo experience, not the standalone app
- Opening exp://exp.host/<your app manifest url> via Firefox with Expo Client closed opens up the expo experience
-

2019-10-25 17:26 UTC, cruzach commented
Good point, I had tested standalone but not in the Expo Client. Turns out this completely broke behavior in the client 😬 With the new changes, you observe the following:

- standalone app: test `<scheme>://deep/link` with app in foreground, in background, and closed, and multiple different links to different screens in the same app. The `Linking.addEventListener` listener doesn't fire in the case of a closed app, but that's due to the listener not being added yet, so that's expected ✅
- Expo client: test `exp://<some other app manifest url>` with your app open in the foreground ✅
- Both: test opening some other url (`tel://` ) from app ✅
- opening `exp://exp.host/<your app manifest url>` from another published experience opens the expo experience, not the standalone app ✅
- Opening `exp://exp.host/<your app manifest url>` via Firefox with Expo Client closed opens up the expo experience ✅

The only iffy behavior is:
- if standalone app is in foreground and you open `exp://exp.host/<your app manifest url>`, the expo experience doesn't open and the standalone app will stay in the foreground
Although, how often is someone going to want to open their Expo experience from the standalone version of that same experience?

2019-10-25 23:33 UTC, esamelson requested changes
Thanks for testing this so thoroughly! In a PR like this testing is definitely more than half the work. I agree that one iffy case is not a big deal because the use case is so weird. That said, just looking at this file I bet the problem is coming from `canOpenURI` and is probably a simple fix 😄 just need to check `Constants.isStandaloneApp()` before returning `true` with exp/exps scheme. Up to you if you want to do that in this PR or not.

I have one small code suggestion, but otherwise looks good to me 👍

2019-10-25 23:33 UTC, esamelson commented on android/expoview/src/main/java/host/exp/exponent/kernel/services/linking/LinkingKernelService.java
> +    String manifestUrl = (Constants.INITIAL_URL != null && !Constants.INITIAL_URL.isEmpty()
```suggestion
    String manifestUrl = (Constants.isStandaloneApp()
```
Both options would achieve the same thing but I think this is more meaningfully correct, & would not break in the future if for example we start including an `INITIAL_URL` in the client 🤷‍♂

2019-10-28 18:41 UTC, esamelson approved these changes

2019-10-28 21:07 UTC, cruzach commented
So now just merge and cherry-pick to the `sdk-35` branch?

2019-10-28 22:41 UTC, esamelson commented
yep!

2019-10-29 13:41 UTC, merged