[Permissions] Add unit test to Permissions module
expo/expo pull request #6285
Opened 2019-11-15 15:20 UTC by lukmccall

2019-11-18 12:00 UTC, mczernek requested changes
Generally, very good refactoring for testability, but I think that tests need some cleanup. Solid work, though and definitely a step in a very good direction - I hope unit testing and kotlin will be a new standard in android modules :)

2019-11-27 11:08 UTC, mczernek approved these changes

2019-11-27 11:08 UTC, mczernek commented on packages/expo-permissions/android/src/test/java/expo/modules/permissions/PermissionsServiceTest.kt
> +    every { mActivityDelegate.askForPermissions(any(), any()) } answers {
I generally like the concept and approve it, but maybe you would consider one more improvement?

Tests are often written in `given->when-then` convention. Each part is seperated from the other, given might be ommited.
Separation comes either by formatting and comment between each part, or putting each part into seperate function. Hence, example test might look like that:
```kt
fun test(){
  givenPermission(name = "permissionName", isDenied = true, canAskAgain = false)
  whenAskingForPermission()

  //then
  verify { thatSomethingHappened }
}
```

This is just suggestion :)

2020-06-26 13:40 UTC, sjchmiela commented
Now that `unimodules-test-core` landed, would we want to update this PR and land it on `master`?

2020-08-12 06:59 UTC, closed without merging