[ImagePicker] Improve picking photos with unchanged quality
expo/expo pull request #6303
Opened 2019-11-18 10:19 UTC by lukmccall

# Why

When the user doesn't change image quality, `ImagePicker` should only copy file. Not load it to the memory and then copy the original file.

# How

I've extracted from`loadImageForManipulationFromURL`, logic which doesn't need to have access to the bitmap object. 

Also, I've free every `closeable` resource. Some user complains about memory leaks.

# Test Plan

- https://snack.expo.io/@lukaszkosmaty/github---imagepicker---improve-picking-photos-with-unchanged-quality- <- I've used this demo to test ImagePicker with different options and media types.

2019-11-18 10:48 UTC, bbarthec approved these changes
LGTM 💯🎉

2019-11-18 10:49 UTC, mczernek approved these changes

2019-11-18 16:03 UTC, tsapeta requested changes
Could you add a changelog entry for this fix?

2019-11-22 09:18 UTC, sjchmiela approved these changes
LGTM, thank you! 👌

2019-11-22 09:18 UTC, sjchmiela commented on packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.java
> +              if (quality == null || quality == DEFAULT_QUALITY) {
Let's hardcode `100` here, in case someone changes `DEFAULT_QUALITY` to something like `80`.

2019-11-22 09:18 UTC, sjchmiela commented on packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerModule.java
> +                  options.inJustDecodeBounds = true;
💙

2019-11-22 17:22 UTC, tsapeta approved these changes

2019-11-22 17:23 UTC, merged

2019-11-26 22:44 UTC, esamelson commented
Reverted this because it caused some of the NCL examples (the ones with cropping) to crash the app. Let's fix and land the fix on master and plan to have it go out with the SDK 37 release.