[Documentation] Add unimodules-* to jest transformIgnorePatterns
expo/expo pull request #6602
Opened 2019-12-22 05:46 UTC by hyochan

# Why
Some of unimodule that should be transpiled in jest is not in `@unimodules/.*` and rather it stays in `unimodules-*`. Hope this `doc` can help other users for better jest setup.

# How

Add `unimodules-*` to `transformIgnorePatterns`.

# Test Plan
Try to use `expo-permissions` for testing without the above option.
![image](https://user-images.githubusercontent.com/27461460/71317762-c2982a00-24c9-11ea-9268-c51d4aba15fc.png)

With the above option, it resolves.
![image](https://user-images.githubusercontent.com/27461460/71317765-c926a180-24c9-11ea-8d12-4574221f069f.png)

2019-12-30 20:23 UTC, EvanBacon commented
The exact string should be `'node_modules/(?!(jest-)?react-native|@react-native-community|expo(nent)?|@expo(nent)?/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|react-native-svg)',`. Extra points if you add a comment in the file `packages/jest-expo/jest-preset.js` that says to keep this line up to date.

2019-12-30 20:24 UTC, EvanBacon requested changes
The exact string should be `'node_modules/(?!(jest-)?react-native|@react-native-community|expo(nent)?|@expo(nent)?/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|react-native-svg)',`. Extra points if you add a comment in the file `packages/jest-expo/jest-preset.js` that says to keep this line up to date.

2019-12-30 23:55 UTC, brentvatne commented
thanks @hyochan! whoever wants to update accordingly first (you or @EvanBacon) go ahead :)

2019-12-31 01:01 UTC, hyochan commented
@EvanBacon @brentvatne Made changes~! 😃

2019-12-31 22:20 UTC, EvanBacon approved these changes
Great work!

2019-12-31 22:21 UTC, merged

2020-03-26 06:10 UTC, vitalbone commented
The current `transformIgnorePatterns` regex found in the current `testing-with-jest.md` does not work for `expo-permissions`. Still seeing:

```sh
Details:

/Users/vbz/Projects/picket/fpa/mmp/planner-client/MMPPlanner/node_modules/expo-permissions/build/Permissions.js:1
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { Platform } from 'react-native';
                                                                                                ^

SyntaxError: Unexpected token {
> 2 | import * as Permissions from 'expo-permissions';
```

System details:
```sh
Expo CLI 3.15.5 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.19.0 - ~/.nvm/versions/node/v10.19.0/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v10.19.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5977832
      Xcode: 11.4/11E146 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^36.0.0 => 36.0.2
      react: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4
      react-navigation: ^3.11.0 => 3.13.0
```