Fix library name from expo-three to expo-three-ar
expo/expo pull request #6659
Opened 2020-01-02 20:09 UTC by Gatreek92

- Change library name to expo-three-ar.
- Fix links.

# Why

The API reference documentation for AR still reference to expo-three.

# How

Change library name to expo-three-ar and fix the links

# Test Plan

Read the API reference documentation for AR.

2020-01-02 21:54 UTC, cruzach commented
Thanks! Could you make the same changes to the other versions of the docs? most importantly v36

2020-01-04 19:02 UTC, Gatreek92 commented
@cruzach done :)

2020-01-06 15:06 UTC, cruzach requested changes
the example url in the pages (except `unversioned`) are 404s

2020-01-06 15:06 UTC, cruzach commented on docs/pages/versions/v36.0.0/sdk/AR.md
> +> [Examples can be found here](https://github.com/expo/expo-three-ar/tree/master/example/screens/AR)
page not found

2020-01-06 15:17 UTC, Gatreek92 commented on docs/pages/versions/v36.0.0/sdk/AR.md
> +> [Examples can be found here](https://github.com/expo/expo-three-ar/tree/master/example/screens/AR)
Ah I see, i will fix it later today.

2020-01-09 14:40 UTC, cruzach approved these changes

2020-01-09 14:40 UTC, merged