[expo-application] Add methods for app release type and APNs environment
expo/expo pull request #6724
Opened 2020-01-09 17:03 UTC by sjchmiela

# Why

APNs environment will be useful for `expo-notifications` module. App release type could be useful for users' analytics. 

# How

In the gist of things, I copied already present `EXProvisioningProfile` from `ExpoKit` to `EXApplication`, renaming the original to `EXExpoKitProvisioningProfile`.

# Test Plan

Added tests to `test-suite`, verified in `bare-expo` that they pass.

2020-01-10 03:38 UTC, ide requested changes
I don't think we should copy and paste a whole class like this. Also, as you mentioned, the notifications module will also need this code. It might make sense to publish a small npm package that contains only iOS code that can be shared between modules that need to parse provisioning profiles.

2020-01-10 03:38 UTC, ide commented on packages/expo-application/src/Application.ts
> +  Unknown = 0,
```suggestion
  UNKNOWN = 0,
```

etc...

2020-01-10 08:00 UTC, sjchmiela commented on apps/test-suite/tests/Application.js
> +        try {
I was surprised to see that pattern in that file, but assumed something between _that's the convention in this file 🤷‍♂_ and _maybe there's something to it I don't know about_ and decided to stick with it..

2020-01-10 09:32 UTC, sjchmiela commented
I agree copy-pasting the class wasn't in this case the best idea — yesterday I realized we could just use `EXProvisioningProfile` from `EXApplication` wherever we would use `EXExpoKitProvisioningProfile`, since in important situations we know the module will be available and otherwise we know what to use as a fallback. I've updated this PR accordingly, let me know if this looks better.

When it comes to using this code by `expo-notifications` — it will use `getIosPushNotificationServiceEnvironmentAsync` in the `getExpoPushTokenAsync` method to know whether to set the `development` property in `body` to `true`. I think making `expo-notifications` depend on `expo-application` should suffice in this case (we use some other properties from `expo-application` in `expo-notifications` anyway, so dependency is in order [with fallbacks to `expo-constants` and overriding possibilities]).

2020-01-10 16:06 UTC, sjchmiela commented
How `expo-notifications` will use `expo-application` can be found [here](https://github.com/expo/expo/pull/6733/files/f7f286947ac9dcd4f3aa117485837ca2fa109908..ceda1e9de08c26f3bf1595f6ad31bb7b0844efa4#diff-cc7d4344d60a9118e71fd6274b53de0aR123-R151)

2020-01-10 19:25 UTC, ide commented on apps/test-suite/tests/Application.js
> +        try {
OK, I see your reasoning. (I don't think this file sets a good example.) Generally I think consistency is good, but setting more of an undesirable example might lead more people to copy+paste this in the future. Could you remove this pattern in your new tests for now, and we'll clean up the rest of this file later?

2020-01-11 09:17 UTC, sjchmiela commented on apps/test-suite/tests/Application.js
> +        try {
Sure sure, already done!

2020-01-16 03:07 UTC, ide requested changes

2020-01-21 04:30 UTC, ide approved these changes

2020-01-21 07:56 UTC, merged