[expo-notifications] Add getExpoPushTokenAsync()
expo/expo pull request #6733
Opened 2020-01-10 16:04 UTC by sjchmiela

# Why

We will want to still allow developers to use Expo backend for sending push notifications.

# How

Implemented fetching of the token in JS.

# Test Plan

- ✅ added test to `test-suite` that checks whether fetching of the token renders proper, stringy result passes. It is run on iOS and Android (backend doesn't support Web push notifications).

- ✅ notification sent via Expo server to the token received reaches the device.

To be able to test whether the notification does reach the device I had to manually call `Permissions.askAsync(Permissions.USER_FACING_NOTIFICATIONS)` since it seems that our server can't send silent notifications (the device was receiving them only when sent via device push token).

Moreover, I added one of the Exponent push tokens to `@exponent` account and assigned the push token to `(@exponent/bare-expo, dev.expo.Payments)` app/experience.

2020-02-03 14:27 UTC, mczernek approved these changes

2020-02-04 00:26 UTC, esamelson requested changes
a few small changes to request but otherwise this looks great. Thanks for adding test coverage 🙏

2020-02-04 00:26 UTC, esamelson commented on packages/expo-notifications/src/getExpoPushTokenAsync.ts
> +    (Constants.manifest && `@${Constants.manifest.owner}/${Constants.manifest.slug}`);
```suggestion
    (Constants.manifest && Constants.manifest.id);
```
we actually want to move away from the `@owner/slug` construction of experienceId so let's not add another dependency on it here 😅

2020-02-04 00:26 UTC, esamelson commented on packages/expo-notifications/src/getExpoPushTokenAsync.ts
> +  const appId = options.appId || Application.applicationId || experienceId;
I'm not sure that falling back to `experienceId` is the right approach here 🤔 do you know if we're set up to handle that on the server? Looking at both the iOS and Android native implementations of this we only ever send the bundle/package name. I think we might want to instead throw if we can't get the `applicationId`.

2020-02-10 12:25 UTC, merged