[android][web-browser] Fix WebBrowser sending 'dismiss' before opening
expo/expo pull request #6743
Opened 2020-01-12 12:24 UTC by LucaColonnello

# Why
Fixes #6679

# How

https://github.com/expo/expo/issues/6679#issuecomment-570963717

**TL;DR**
A wrong usage of AppState causes WebBrowser to resolve with
`{ type: 'dismiss' }` before opening the view.

This is related to AppState being not initialised yet,
triggering a change before the user leaves the app view
to focus on the browser view.

# Test Plan

As this can be tested only in production (the bug does not happen in development), testing is hard to achieve.
I tested it in the app I'm building, other people (see comments in the issue) did the same, linking their forked package with the patch applied to their apps, and it seems to work fine.

2020-01-12 12:26 UTC, LucaColonnello commented
I'm looking for ways to test this in E2E 🤞
Open to suggestions!

2020-01-12 13:55 UTC, LucaColonnello commented
![image](https://user-images.githubusercontent.com/536973/72219907-1df68e80-3543-11ea-97b4-edaafdb8bac0.png)
Tests are having issues in CI...

2020-02-01 14:47 UTC, LucaColonnello commented
@mczernek I'm unfortunately blocked on this one.
Could I get some support? I don't know how to unlock this CI error.
I read the contributor guidelines document but I can't find anything relevant...

2020-02-20 09:53 UTC, lukmccall commented
Hi @LucaColonnello, to fix the problem with SDK, you need to run `yarn build` in the `expo-web-browser` folder. 

An issue with the client is strange. Maybe rebase help.  

Moreover, please add an entry to [`CHANGELOG.md`](https://github.com/expo/expo/blob/master/CHANGELOG.md).

2020-03-17 22:52 UTC, LucaColonnello commented
@lukmccall @mczernek @sjchmiela Can I ask for a re review here please? :)
I added the `CHANGELOG.md` and managed to do get the CI passing (all but the client 🤷‍♂)

Thanks in advance!

2020-03-18 09:00 UTC, lukmccall requested changes
Please don't bother about failing CI job - this particular job always fails to people from community.  

I'm not sure why you have changes in `yarn.lock`. Did you rebase your branch?

2020-03-18 09:00 UTC, lukmccall commented on packages/expo-web-browser/src/WebBrowser.ts
> +let _previousAppState: null | string = AppState.currentState;
It'll be better if we change it to `bool` and rename it. We don't have to remember the previous app state. We need information if it the first call or not.

2020-03-23 09:53 UTC, lukmccall approved these changes
LGTM 🥇I'll merge when you fix one more thing ;)

2020-03-23 09:53 UTC, lukmccall commented on packages/expo-web-browser/CHANGELOG.md
> +- Fix WebBrowser sending `dismiss` before opening ([#6743](https://github.com/expo/expo/pull/6743) by [@LucaColonnello](https://github.com/LucaColonnello))
```suggestion
- Fix `WebBrowser` sending `dismiss` before opening. ([#6743](https://github.com/expo/expo/pull/6743) by [@LucaColonnello](https://github.com/LucaColonnello))
```

2020-03-23 22:40 UTC, LucaColonnello commented
🎉
Can someone help testing this in an Android machine?
Unfortunately my machine has some issues with Android VM.

2020-03-25 13:28 UTC, LucaColonnello commented
Hey @cruzach can you please explain your point better? Unfortunately I do not understand why it would result in dismiss.

Only thing I’m tackling here is that there’s no guarantee to have an initial event from AppState triggered ONLY when you do change focus.

The AppState could trigger the first time is currentState is called even if no change occurred.

How is this change impacting the current feature as you say?

Thanks in advance :)

2020-03-25 13:34 UTC, cruzach commented
Sorry, I didn't mean to indicate this PR was negatively impacting the feature at all. 

Since, with a Chrome custom tab, we have no way of knowing whether the web browser was closed, or backgrounded, we [state in the docs](https://docs.expo.io/versions/latest/sdk/webbrowser/) that:
> On Android promise resolves with {type: 'opened'} if we were able to open browser.

I think we should revert back to this behavior, since resolving to `{type: 'dismiss'}` indicates that the web browser was successfully closed, which is the behavior on the iOS side:
> On iOS: if the browser is closed using `dismissBrowser` , the Promise resolves with { type: 'dismiss' }.


The best option would be to tell whether the chrome custom tab was closed or not, but I'm not sure it's possible

2020-03-25 22:56 UTC, brentvatne commented
I can't reproduce the issue described here on SDK36 on Android.

```
import React from "react";
import { AppState, Button, StyleSheet, Text, View } from "react-native";
import * as WebBrowser from "expo-web-browser";

export default function App() {
  return (
    <View style={styles.container}>
      <Text>{AppState.currentState}</Text>
      <Button
        title="Press me"
        onPress={() => {
          WebBrowser.openAuthSessionAsync(
            "https://expo.io",
            "exp://127.0.0.1:19000"
          );
        }}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center"
  }
});
```

1) the `AppState.currentState` text is initialized to `active`, which is what is to be expected for React Native 0.61 (the docs appear to be outdated and incorrect - see https://github.com/facebook/react-native/blob/master/Libraries/AppState/AppState.js#L42
2) I added logs to the app state change function that you modified and it fired with the values I expected: first `background` and then `active` when I return to the app.

I tried this inside of Expo client and in a standalone app ([download apk here](https://exp-shell-app-assets.s3.us-west-1.amazonaws.com/android/%40notbrent/testing-focus-stuff-6bdc91ca684243ae89e727d344a9d2e6-signed.apk))

Can you explain how I can reproduce this problem on SDK36?

2020-03-26 05:24 UTC, thisBrian commented
@brentvatne 

The reason is because you call `AppState.current` explicitly before opening the browser.
The problem will occur were you to start the auth flow directly and see if it resolves.

2020-03-28 10:43 UTC, LucaColonnello commented
Are we ok to merge this @lukmccall? :)

2020-03-28 20:04 UTC, brentvatne commented
@thisBrian - that doesn't make any sense -- accessing the property does not initialize it. it is initialized in the AppState constructor as i linked to. i would need more information on exactly what the problem is and how i can reproduce this before i'm comfortable merging

2020-03-29 04:26 UTC, thisBrian commented
@brentvatne 

Apologies if it didn't make sense, let me clarify: your _code block_ where you read from AppState prior to launching the auth session has side effects that won't reproduce the bug.

[To demonstrate I forked your helloworld repo](https://github.com/nullables/hello-world-jest-expo-universal) and quickly added a simple auth flow using reddit as an example.

- [Here is the bug](https://i.imgur.com/eUdaJ8j.mp4) where the first attempt silently fails, yet subsequent attempts succeed
- [Here is the same code](https://i.imgur.com/1XklccM.mp4) but with the side effect of having read `AppState.currentState` prior to launching the browser.

The same holds true for any helper classes that use WebBrowser (such as AuthSession).

I hope that clears it up enough to merge the fix by @LucaColonnello, cheers!

----
Here's an excerpt from the aformentioned fork

```tsx
import { AuthSession } from 'expo';
import React from 'react';
import { Button, StyleSheet, View } from 'react-native';
import { getAuthorizeUrl } from './helpers';

export default function App() {
  return (
    <View style={styles.container}>
      <Button
        title="Press me"
        onPress={async () => {
          const returnUrl = 'helloworld://any';
          const authUrl = getAuthorizeUrl(
            {
              client_id: 'INSERT_YOUR_CLIENT_ID', // https://www.reddit.com/prefs/apps/ + match redirect Url with aformentioned returnUrl
              duration: 'temporary',
              redirect_uri: returnUrl,
              response_type: 'code',
              scope: ['identity'],
            },
            '.compact'
          );
          const result = await AuthSession.startAsync({
            authUrl,
            returnUrl,
          }).catch(alert);
          alert(JSON.stringify(result));
        }}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

2020-03-29 18:13 UTC, LucaColonnello commented
@brentvatne I understand where you're coming from, it is misleading.
I'll try make it clearer.

The ReactContext `LifecycleEventListener`, used by AppState, triggers an `onHostResume` event when you add the _first ever_ listener, according to this [code](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/bridge/ReactContext.java#L200).

(read  my comment here for details of why this is important in the context of `AuthSession` https://github.com/expo/expo/issues/6679#issuecomment-570963717, although lines have changed since then in ReactNative)

You're right to say that if that is the case it should not matter as AppState constructor creates a listener as soon as an instance is created, but there's a detail you're missing.

**In the context of ReactNative, all modules are exported as getter of the `module.exports` object, requiring such modules only when and if required (most probably for performance reasons).**
Here's the [code responsible for that](https://github.com/facebook/react-native/blob/master/index.js#L294), you can see AppState being exported in such way at line 294.

Based on this, when you import AppState in your app before using `AuthSession`, you're triggering the constructor earlier.

2020-03-30 00:03 UTC, LucaColonnello commented
@thisBrian could you tell me how to reproduce this in a virtual machine if you did this in a VM to take the videos?
I was only able to debug this in a real device (old Android), but unfortunately I don't have it with me anymore...

Thanks :)

2020-03-30 03:32 UTC, thisBrian commented
@LucaColonnello 

Oh I had used a screen recorder for those particular videos; [however Expo has some good docs on setting up a virtual device](https://docs.expo.io/versions/latest/workflow/android-studio-emulator/).

Alternatively if you want a quick and dirty virtual Android device to run the apk, you could use [BlueStacks](https://www.bluestacks.com/) too. I have tested it with both virtual variations and they could reproduce the bug.

Apologies, if I was able to get to the office I would upload my docker image that has it all set up.

2020-04-14 10:52 UTC, lukmccall commented
@LucaColonnello, I'm sorry it took so long. However, I think all doubts were resolved. So, we almost ready to merge it 🎉Please, just resolve conflicts and it will be good to go.

2020-04-15 11:50 UTC, vernondegoede commented
Hey guys,

We ran into the same issue with `expo-web-browser`. When running `openAuthSessionAsync` from `expo-web-browser`, we always get returned with `{"type": "dismiss"}`. This only happens on Android.

I applied the changes from this PR using `patch-package`, but without any luck.

Just to be sure, this is what `patches/expo-web-browser+8.1.0.patch` looks like:

```
diff --git a/node_modules/expo-web-browser/build/WebBrowser.js b/node_modules/expo-web-browser/build/WebBrowser.js
index 91daac4..d0d56dc 100644
--- a/node_modules/expo-web-browser/build/WebBrowser.js
+++ b/node_modules/expo-web-browser/build/WebBrowser.js
@@ -106,7 +106,16 @@ let _redirectHandler = null;
 // Store the `resolve` function from a Promise to fire when the AppState
 // returns to active
 let _onWebBrowserCloseAndroid = null;
+// If the initial AppState.currentState is null, we assume that the first call to
+// AppState#change event is not actually triggered by a real change,
+// is triggered instead by the bridge capturing the current state
+// (https://facebook.github.io/react-native/docs/appstate#basic-usage)
+let _isAppStateAvailable = AppState.currentState !== null;
 function _onAppStateChangeAndroid(state) {
+    if (!_isAppStateAvailable) {
+        _isAppStateAvailable = true;
+        return;
+    }
     if (state === 'active' && _onWebBrowserCloseAndroid) {
         _onWebBrowserCloseAndroid();
     }
diff --git a/node_modules/expo-web-browser/src/WebBrowser.ts b/node_modules/expo-web-browser/src/WebBrowser.ts
index 37ee736..0391591 100644
--- a/node_modules/expo-web-browser/src/WebBrowser.ts
+++ b/node_modules/expo-web-browser/src/WebBrowser.ts
@@ -149,7 +149,17 @@ let _redirectHandler: ((event: RedirectEvent) => void) | null = null;
 // returns to active
 let _onWebBrowserCloseAndroid: null | (() => void) = null;
 
+// If the initial AppState.currentState is null, we assume that the first call to
+// AppState#change event is not actually triggered by a real change,
+// is triggered instead by the bridge capturing the current state
+// (https://facebook.github.io/react-native/docs/appstate#basic-usage)
+let _isAppStateAvailable: boolean = AppState.currentState !== null;
 function _onAppStateChangeAndroid(state: AppStateStatus) {
+  if (!_isAppStateAvailable) {
+    _isAppStateAvailable = true;
+    return;
+  }
+
   if (state === 'active' && _onWebBrowserCloseAndroid) {
     _onWebBrowserCloseAndroid();
   }
```

2020-04-16 23:10 UTC, brentvatne approved these changes
still not totally sure why this is happening but was able to repro it in a prod build of the app and not in development. thanks for the patience!

2020-04-16 23:12 UTC, merged

2020-04-17 00:09 UTC, brentvatne commented
this is available in `expo-web-browser@8.1.1`

2020-04-17 02:58 UTC, Rohansi commented
> this is available in `expo-web-browser@8.1.1`

Any way to use that in an SDK 37 app? I tried pulling it but it wasn't fixed, and `expo install`ing it only gives 8.1.0. Maybe I need to build standalone again?

2020-04-17 03:21 UTC, brentvatne commented
if you already have expo-web-browser in your app 8.1.0 matches ~8.1.0 which is what is installed by expo install. if you remove it and then install it again you will get the latest version, or just run yarn add expo-web-browser@8.1.1

2020-04-17 03:41 UTC, Rohansi commented
Yeah, I installed expo-web-browser@8.1.1 and rebuilt the standalone app. Still immediately get a dismiss the first time around.

Expo CLI also said `There were no new changes from the last build, you can download that build from here` which makes me think these dependencies are bundled separately from my app's code?

2020-06-01 17:36 UTC, simplesthing commented
I am getting this issue with expo-web-browser 8.2.1

2020-06-02 07:10 UTC, thisBrian commented
@simplesthing It seems you got your issue [resolved](https://github.com/expo/expo/issues/6679#issuecomment-637040641). btw the `./helpers` and `getAuthorizeUrl` were reddit-specific implementations for the demo to reproduce the bug.