@lukmccall/screen orientation update documentation
expo/expo pull request #6838
Opened 2020-01-23 15:46 UTC by lukmccall

# Why

Follow up to https://github.com/expo/expo/pull/6760

2020-02-03 20:53 UTC, brentvatne commented
it's not touched in this pr but it would be good to fix while we're here - under Object Types and Function Types there are bullet points are indented within a heading, eg:

### `ScreenOrientation.PlatformOrientationInfo`

    - screenOrientationConstantAndroid (_integer_): A constant to set using the Android native [API](https://developer.android.com/reference/android/R.attr.html#screenOrientation). For example, in order to set the lock policy to [unspecified](https://developer.android.com/reference/android/content/pm/ActivityInfo.html#SCREEN_ORIENTATION_UNSPECIFIED), -1 should be passed in. (Android only)

on the github markdown parser this strangely results in the bullet points being marked as codeblocks, as you can see above. this makes it difficult to read the full description. we should remove the indentation.

2020-02-03 20:53 UTC, brentvatne requested changes

2020-02-03 20:53 UTC, brentvatne commented on packages/expo-screen-orientation/ios/EXScreenOrientation/EXScreenOrientationModule.m
> +    return reject(@"ERR_SCREEN_ORIENTATION_UNSUPPORTED_ORIENTATION_LOCK", @"This device does not support this orientation.", nil);
```suggestion
    return reject(@"ERR_SCREEN_ORIENTATION_UNSUPPORTED_ORIENTATION_LOCK", @"This device does not support the requested orientation.", nil);
```

2020-02-04 17:54 UTC, brentvatne approved these changes

2020-02-19 14:15 UTC, sjchmiela reviewed
👍

2020-02-19 14:15 UTC, sjchmiela commented on docs/pages/versions/unversioned/sdk/screen-orientation.md
> +This module needs additional configuration to work properly on iPads. Unfortunately, it will disable support for the split view.
Could you elaborate a bit on what does it mean to _work properly on iPads_, why doesn't this module _work properly_ by default, what are the advantages and disadvantages of adding `requireFullScreen: true` property?

2020-02-19 14:15 UTC, sjchmiela commented on docs/pages/versions/unversioned/sdk/screen-orientation.md
> +Tick the `Requires Full Screen` checkbox in XCode. It should be located under `Project Target > General > Deployment Info`.
```suggestion
Tick the `Requires Full Screen` checkbox in Xcode. It should be located under `Project Target > General > Deployment Info`.
```

2020-02-19 14:15 UTC, sjchmiela commented on docs/pages/versions/unversioned/sdk/screen-orientation.md
> +Open your app.json and add the following inside of the "expo" field:
```suggestion
Open your `app.json` and add the following inside of the `"expo"` field:
```

2020-02-20 13:41 UTC, sjchmiela commented on docs/pages/versions/unversioned/sdk/screen-orientation.md
> +The Apple added support for the `split view` mode to iPads in iOS 9. This changed how the screen orientation is handled by the system. Briefly, for the iOS, your iPad is always in the landscape mode
```suggestion
Apple added support for _split view_ mode to iPads in iOS 9. This changed how the screen orientation is handled by the system. To put the matter shortly, for the iOS, your iPad is always in the landscape mode unless you open two applications side by side. In order to be able to lock screen orientation using this module you will need to disable support for this feature. For more information about the _split view_ mode, check out [the official Apple documentation](https://support.apple.com/en-us/HT207582).
```

2020-02-20 13:41 UTC, sjchmiela commented on docs/pages/versions/unversioned/sdk/screen-orientation.md
> +Open your `app.json` and add the following inside of the `"expo"` field:
How about putting the `expo` to inside the json? so it looks kinda like:

```
{
  expo: {
    ...
    ios: {
      ...
      requireFullScreen: true
```

2020-02-20 13:41 UTC, sjchmiela commented on docs/pages/versions/unversioned/sdk/screen-orientation.md
> +- `ERR_SCREEN_ORIENTATION_INVALID_ORIENTATION_LOCK` - an invalid [`OrientationLock`](#screenorientationorientationlock) was passed in (**isOnly**).
```suggestion
- `ERR_SCREEN_ORIENTATION_INVALID_ORIENTATION_LOCK` - an invalid [`OrientationLock`](#screenorientationorientationlock) was passed in (**iOS only**).
```

I guess

2020-02-20 13:41 UTC, sjchmiela commented on docs/pages/versions/unversioned/sdk/screen-orientation.md
> +> **Note** `OrientationLock.ALL` and `OrientationLock.PORTRAIT` are invalid on devices which not support `OrientationLock.PORTRAIT_DOWN`.
```suggestion
> **Note** `OrientationLock.ALL` and `OrientationLock.PORTRAIT` are invalid on devices which do not support `OrientationLock.PORTRAIT_DOWN`.
```

2020-02-20 13:41 UTC, sjchmiela commented on packages/expo-screen-orientation/README.md
> +   UIViewController *rootViewController = [[EXScreenOrientationViewController alloc] initWithDefaultScreenOrientationMask:UIInterfaceOrientationMaskPortrait]; // through parameter you can specify you
Can we default to using `init]`(less decisions for the developer) and note that people can also set a default orientation mask with a parameter?

2020-02-20 13:41 UTC, sjchmiela commented on packages/expo-screen-orientation/README.md
> +> **Note** if you are using the custom view controller, this controller needs to extend the `EXScreenOrientationViewController`.
```suggestion
> **Note** if you are using a custom view controller, the controller will need to extend the `EXScreenOrientationViewController`.
```

2020-02-20 13:41 UTC, sjchmiela commented on packages/expo-screen-orientation/README.md
> +   To get more information about available orientation masks, please check out [UIInterfaceOrientationMask](https://developer.apple.com/documentation/uikit/uiinterfaceorientationmask?language=objc)
```suggestion
   For more information about available orientation masks check out [UIInterfaceOrientationMask](https://developer.apple.com/documentation/uikit/uiinterfaceorientationmask?language=objc)
```

2020-02-21 15:01 UTC, sjchmiela approved these changes

2020-02-21 15:01 UTC, sjchmiela commented on packages/expo-screen-orientation/ios/EXScreenOrientation/EXScreenOrientationViewController.m
> +  if (self = [super init]) {
Let's delegate to another initializer:

`return [self initWithDefaultScreenOrientationMask:UIInterfaceOrientationMaskPortrait]`

2020-02-21 16:09 UTC, merged