[expo-notifications] Badge count module
expo/expo pull request #6869
Opened 2020-01-27 16:46 UTC by sjchmiela

# Why

We want to let people set badge counter on demand.

# How

- on Android we use `ShortcutBadger`
- on iOS we use `applicationIconBadgeNumber`
- on web we use `badgin`

### API

```ts
getBadgeCountAsync(): Promise<number>;
```

```ts
setBadgeCountAsync(badgeCount: number, undefined | {
  web?: badgin.Options
}): Promise<void>;
```

# Test Plan

Tested the module on iOS 13 (worked ✅), Android 7.1 (Samsung, 👎), Android 9 (Nokia, 👎), web (worked ✅). I guess those Android launchers weren't supported by `ShortcutBadger` — I added a simple infrastructure inside `NewNotifications.js` test suite to handle similar cases.

2020-02-26 00:11 UTC, esamelson requested changes
My only comment here is instead of rejecting/throwing when we're unable to set the badge count, I wonder if we should just resolve the promise with `false` (and with `true` when we are successful). In general I think rejecting should be reserved for actual errors and exceptions, and here we expect a fair amount of devices in production to have this failure -- which developers have no control over. Also, there's not really any alternative to this behavior so I think most developers would just catch the error and then do nothing. (or have an unhandled promise rejection) --> resolving with `false` is better and people can handle it if they want to.

This would also take care of the weird test case -- we can just expect either true or false and the test will only fail if an actual exception occurs.

2020-02-26 14:13 UTC, sjchmiela commented
Following your suggestion I have changed the `setBadgeCountAsync` signature to return `Promise<boolean>`. The value returned is:
- on Android: whether `ShortcutBadger` reports it succeeded
- on iOS: whether current notification settings allow access to icon badge number
  > In iOS 8.0 and later, your application must register for user notifications using `-[UIApplication registerUserNotificationSettings:]` before being able to set the icon badge.
- on Web: always `true`, since `badgin` itself implements some fallbacks, one of which is changing `window.title` which rarely fails

2020-03-05 00:44 UTC, esamelson approved these changes

2020-03-05 08:25 UTC, merged

2021-06-17 04:14 UTC, mikeRChambers610 commented
This does not work on Android, but returns a promise with "true":