[expo-updates] add TS implementation and web shim
expo/expo pull request #6923
Opened 2020-01-31 01:33 UTC by esamelson

# Why

partial step of #6517

# How

- Brought package.json & rest of module up-to-date with other unimodules, including bumping `expo-module-scripts` version
- copied the meat of the TS implementation from the current `Updates.ts` code as it's very similar, and made changes where necessary

# Test Plan

- [ ] Manual testing
- [ ] Maybe add a few jest tests

2020-02-06 04:03 UTC, ide requested changes
Just some small changes.

2020-02-06 04:03 UTC, ide commented on packages/expo-updates/src/__tests__/Updates-test.native.ts
> +  ExpoUpdates.checkForUpdateAsync = mock;
Shouldn't this already be set to a mock function by the Jest preset? If the intent here is to clear the mock's state, call `ExpoUpdates.checkForUpdateAsync.mockReset()` in afterEach.

2020-02-07 01:25 UTC, esamelson commented on packages/expo-updates/src/Updates.ts
> +  if (typeof params === 'string') {
yes -- the manifest is a `JSONObject` in Java but afaict there is no natural way to convert `JSONObject` into an object readable by RN on the native side

2020-02-07 02:22 UTC, ide approved these changes

2020-02-07 02:22 UTC, ide commented on packages/expo-updates/src/Updates.ts
> +  if (typeof params === 'string') {
OK, will be nice to replace this with Turbomodules one day (no more emitters either)

2020-03-02 19:10 UTC, merged