Update account-permissions.md
expo/expo pull request #7261
Opened 2020-03-04 08:43 UTC by flexbox

# Why

Update the documentation and avoid some frustration.

If I visit https://expo.io/settings/permissions –as written on the documentation– I land on this page
<img width="712" alt="image" src="https://user-images.githubusercontent.com/360936/75860712-93246880-5dfc-11ea-8978-a111d547d1d0.png">

After some research I noticed that Account permissions are part of the paid plan.

2020-03-09 20:58 UTC, cruzach commented
Hi! Can you try this again? That page should still load fine even if you don't have developer services enabled (it will just show this: 

<img width="976" alt="Screen Shot 2020-03-09 at 4 58 02 PM" src="https://user-images.githubusercontent.com/35579283/76257005-40e1ae00-6227-11ea-8a13-d28b8d17f8df.png">

2020-03-09 20:59 UTC, cruzach requested changes

2020-03-09 20:59 UTC, cruzach commented on docs/pages/versions/unversioned/guides/account-permissions.md
> +> Some features on this page are [available with a paid plan](https://expo.io/developer-services).
```suggestion
> Some features on this page require [Developer Services](https://expo.io/developer-services).
```

2020-03-10 11:09 UTC, flexbox commented
I tried to Logout and Sign In again: same error

![image](https://user-images.githubusercontent.com/360936/76306629-8c4b9900-62c7-11ea-80cf-79522b01c66f.png)

I am wondering if it's because I created my account almost 4 years ago.

2020-03-12 13:44 UTC, cruzach commented
Can you send an email to secure@expo.io with your account name? I'd like to get this fixed for you!

2020-03-13 09:36 UTC, flexbox commented
Thank you for solving this!
it was a problem with my account 🚀

2020-03-13 09:36 UTC, closed without merging