[expo-network] Fix getMacAddressAsync as per docs
expo/expo pull request #7394
Opened 2020-03-18 15:21 UTC by sjchmiela

# Why

While QAing SDK37 with `test-suite` I noticed persistent failures on `getMacAddressAsync` method. Decided to investigate them and fix before release.

# How

- `mac` sometimes is `null`, looping over `null` threw an NPE — fixed by `if (mac != null)`
- logic of this function is somewhat convoluted and I may have not grasped it all, but my gut tells me that this `break;` should happen alongside `promise.resolve`, otherwise for an empty `interfaceName` we only ever try to get MAC address of one interface
- `getMacAddressAsync`'s documentation states that on Android
  
  > If undefined interface name passed in, the method would reject the promise with corresponding message.
  
  which it didn't. Added a simple `if (interfaceName === undefined)` check, which if true, throws a `CodedError`.
- also updated the test case in `test-suite` to reflect the documentation behavior
- while editing Android Studio also reformatted the `NetworkModule` so I just reformatted all the files in the module
- then I backported those changes to versioned SDK37

# Test Plan

The tests pass. 🎉

2020-03-18 18:50 UTC, ide requested changes
If we treat null and undefined the same way (`getMacAddressAsync(interfaceName: string | null = null)`) would there be any problems? This seems like it would be simpler for developers.

2020-03-18 19:16 UTC, sjchmiela commented
Changed as per your proposal 👍

2020-03-18 19:25 UTC, ide approved these changes

2020-03-19 02:24 UTC, esamelson approved these changes

2020-03-19 09:32 UTC, merged