[html-elements] Make BR View-based
expo/expo pull request #7395
Opened 2020-03-18 15:34 UTC by sjchmiela

# Why

`test-suite` was failing with an ominous error: **Views nested within a <Text> must have a width and height**.

# How

This took a while to debug (it seemed like the error was thrown while testing `Nav`, but in fact the logging was just slower than testing and it was thrown when testing `BR`). `test-suite` expects `BR` to be a view element, so I made it.

https://github.com/expo/expo/blob/90a1e11151ce0689ea0bf6d89b55cf37ceeff47b/apps/test-suite/tests/HTML.js#L74-L80

# Test Plan

Test no longer fails with **Views nested within…**.

2020-03-18 23:13 UTC, EvanBacon requested changes
Tests will need to be updated (`yarn test -u`)

2020-03-18 23:13 UTC, EvanBacon commented on packages/html-elements/src/elements/Text.tsx
> +export const BR = forwardRef(({ style, ...props }: ViewProps, ref) => {
Should probably move this to the `Rules.tsx` files (same with the tests).

2020-03-19 10:19 UTC, sjchmiela commented
- moved to `Rules`,
- reverted backing view to `Text`
- added a web-compatible implementation in `Rules.web.tsx` that uses native `<br />`
- added a special test case in `test-suite`, since neither `<Element>Test contents</Element>` nor `<Element><View /></Element>` applies to `<BR />` element.
- added a BR-ed paragraph to NCL to be able to test its functionality visually

2020-12-30 17:02 UTC, sjchmiela commented
Fixed by @esamelson in https://github.com/expo/expo/pull/8642.

2020-12-30 17:02 UTC, closed without merging