[file system][ios] Add multipart upload
expo/expo pull request #7403
Opened 2020-03-19 09:57 UTC by lukmccall

# Why

Part of https://github.com/expo/expo/issues/5841.

# How

- add multipart upload on iOS

# Test Plan

- https://snack.expo.io/@lukaszkosmaty/expo-file-system---add-multipart-upload ✅

2020-03-20 17:32 UTC, tsapeta requested changes
Missing docs and changelog entry 😉

2020-03-20 17:32 UTC, tsapeta commented on packages/expo-file-system/ios/EXFileSystem/EXFileSystem.m
> +- (NSString *)_guessMIMETypeFromPath:(NSString *)path {
```suggestion
- (NSString *)_guessMIMETypeFromPath:(NSString *)path
{
```

2020-03-20 17:32 UTC, tsapeta commented on packages/expo-file-system/ios/EXFileSystem/EXFileSystem.m
> +  return true;
```suggestion
  return ![uploadType isEqual:@1])
```
? 😄

2020-03-23 15:49 UTC, bbarthec commented on packages/expo-file-system/ios/EXFileSystem/EXFileSystem.m
> +  NSString *filename  = [[fileUri path] lastPathComponent];
```suggestion
  NSMutableData *body = [NSMutableData data];
  NSData *data = [NSData dataWithContentsOfURL:fileUri];
  NSString *filename  = [[fileUri path] lastPathComponent];
```
Why so many empty lines 🤔 ?

2020-03-23 15:49 UTC, bbarthec commented on packages/expo-file-system/ios/EXFileSystem/EXFileSystem.m
> +    [urlRequest setHTTPBody: httpBody];
```suggestion
    [urlRequest setHTTPBody:httpBody];
```
💅

2020-03-23 15:49 UTC, bbarthec commented on packages/expo-file-system/src/FileSystem.types.ts
> +  RAW = 0,
This name is borrowed from some web standard? 🤔

2020-03-25 10:02 UTC, bbarthec requested changes
LGTM 💯 But one little thing 😉

2020-03-25 10:02 UTC, bbarthec commented on packages/expo-file-system/ios/EXFileSystem/EXFileSystem.m
> +  return ![uploadType isEqual:@1];
I dislike this one .. 😞 
`1)` I saw that you decided on naming it differently than `RAW` (`BINARY_CONTENT` 🤔)
`2)` This magic number `1` is like an eyesore 😭

2020-04-28 12:46 UTC, bbarthec approved these changes
In general it LGTM 😉 💯 Good job. Left some minor comments.

2020-04-28 12:46 UTC, bbarthec commented on packages/expo-file-system/ios/EXFileSystem/EXFileSystem.m
> +- (EXFileSystemUploadType)_importUploadType:(NSNumber * _Nullable)type
```suggestion
- (EXFileSystemUploadType)getUploadTypeFrom:(NSNumber * _Nullable)type
```
Semantically what you're doing here is just getting import type from some integer value with fallback when value is not in available ENUM values.

2020-04-28 12:46 UTC, bbarthec commented on packages/expo-file-system/ios/EXFileSystem/EXFileSystem.m
> +  return EXFileSystemInvalidType;
That looks terrible TBH ... 😉 
I've googled a bit and found out some other tricky and not-so-pretty way:
```suggestion
  switch ([type intValue]) {
    case EXFileSystemBinaryContent:
    case EXFileSystemMultipart:
      return [type intValue];
  }
  
  return EXFileSystemInvalidType;
```

2020-04-29 09:27 UTC, merged