Add support for app.config.js in jest-expo
expo/expo pull request #7557
Opened 2020-03-31 21:39 UTC by EvanBacon

# Why

- Creates possible resolution for https://github.com/expo/expo/issues/4156
- Moved from https://github.com/expo/expo/pull/7447

# How

Use `getConfig` from `@expo/config` to read `app.config.js`.

# Test Plan

Tested in a different project.

2020-04-01 18:41 UTC, ide requested changes

2020-04-01 18:41 UTC, ide commented on packages/jest-expo/src/preset/createMockConstants.js
> +  const expoConfig = appConfig || {};
```suggestion
  const expoConfig = _readAppConfiguration() ?? {};
```

2020-04-01 18:41 UTC, ide commented on packages/jest-expo/src/preset/createMockConstants.js
>  function _readAppConfiguration() {
```suggestion
function _readExpoConfiguration() {
```

2020-04-01 18:41 UTC, ide commented on packages/jest-expo/src/preset/createMockConstants.js
> +      if (!e.message.includes('expected package.json path')) {
This seems really fragile. Someone could change the config package or whatever throws this error and break this code that's in a different repo. Is there some way we could avoid getting this error up front, or at least make it part of the public API (e.g. with an error code) of getConfig?

2020-06-18 18:17 UTC, pdugan20 commented
Is there a workaround for this or any idea as to why it might be merged?

2020-07-12 11:39 UTC, illBeRoy commented
ping! this seems like a really good idea...

2021-04-15 10:17 UTC, mvanroon commented
ping @EvanBacon @byCedric

2021-06-02 02:11 UTC, brentvatne commented
if someone wants to update this pr and reopen that'd be great, we're busy with some other projects right now

2021-07-07 22:01 UTC, brentvatne approved these changes

2021-07-08 00:46 UTC, merged