[expotools] Add command which will update changelog
expo/expo pull request #7570
Opened 2020-04-01 08:39 UTC by lukmccall

# Why

Part of https://github.com/expo/expo/issues/6178.

# How

- Added command which will add an changelog entry to the selected package. 

# Test Plan

- run `et add-changelog` ✅

2020-04-01 15:36 UTC, tsapeta requested changes

2020-04-06 12:39 UTC, lukmccall commented on tools/expotools/src/commands/AddChangelog.ts
> +    !options.pullRequest ||
Why should I remove this?

2020-04-06 12:41 UTC, lukmccall commented on tools/expotools/src/Changelogs.ts
> +const UNPUBLISHED_VERSION_NAME = 'master';
It's a good idea. However, then we need to change headers in all changelog files and it is better to do it in a separate PR.

2020-04-08 11:34 UTC, tsapeta approved these changes

2020-04-08 11:34 UTC, tsapeta commented on tools/expotools/src/Changelogs.ts
> +            text: `${message} ([#${entry.pullRequest}](http://github.com/expo/expo/pull/${entry.pullRequest}) by [@${entry.author}](http://github.com/${entry.author}))`,
```suggestion
            text: `${message} ([#${entry.pullRequest}](https://github.com/expo/expo/pull/${entry.pullRequest}) by [@${entry.author}](https://github.com/${entry.author}))`,
```

2020-04-08 11:34 UTC, tsapeta commented on tools/expotools/src/commands/AddChangelog.ts
> +    !options.pullRequest ||
Sometimes changes are pushed directly to master - it's not good if that happens, but I can imagine a case where we want do add changelog entry without PR number through this script 😉 So imho it should be optional.

2020-04-08 21:18 UTC, tsapeta approved these changes

2020-04-09 10:51 UTC, merged