[expo-in-app-purchase] Do not request purchase history in connectAsync()
expo/expo pull request #7943
Opened 2020-04-21 09:46 UTC by Strate

Fix for #7941

Apple guidelines says: Don't automatically restore purchases, especially when your app is launched. Restoring purchases prompts for the user’s App Store credentials, which interrupts the flow of your app.

# Why

Please describe the motivation for this PR, and link to relevant GitHub issues, forums posts, or feature requests.

# How

How did you build this feature or fix this bug and why?

# Test Plan

Please describe how you tested this change and how a reviewer could reproduce your test, especially if this PR does not include automated tests! If possible, please also provide terminal output and/or screenshots demonstrating your test/reproduction.

2020-04-21 10:12 UTC, Strate commented
This is of course incorrect fix, like RFC

2020-04-21 18:08 UTC, ide commented
Would the underlying use case be addressed by not calling `connectAsync()` except when you need it?

2020-04-21 20:40 UTC, Strate commented
@ide but looks like I need to setPurchaseListener as soon as app starts, so I want to be able to get some unacknowledged purchases (for example when app halts for some reason), but doc says that I should call connectAsync firstly

2020-04-22 06:29 UTC, Strate commented
@ide or another case: I want to show in-app store, for this view and need to call `getProductsAsync`, but I don't want to prompt for AppStore credentials just for show product list.

2020-04-22 06:49 UTC, ide commented
This seems reasonable. If you would like to propose an API change please:

- describe the change in behavior and any side effects
- describe the change in the method signatures and code
- consider changes needed in the docs and guides
- if we decide to move forward, include a descriptive / helpful breaking change entry in the changelog for this package. what apps does this affect? how should you update your code?

2020-05-02 12:24 UTC, Pczek commented
Was annoyed by this as well. Looking foward to the change. 👍

2020-05-19 19:52 UTC, ajsmth commented
> This seems reasonable. If you would like to propose an API change please:
> 
> * describe the change in behavior and any side effects
> * describe the change in the method signatures and code
> * consider changes needed in the docs and guides
> * if we decide to move forward, include a descriptive / helpful breaking change entry in the changelog for this package. what apps does this affect? how should you update your code?

not sure if @Strate has replied elsewhere but I'll answer some of these as I just bumped into this issue as well: 

describe the change in behavior and any side effects
- `connectAsync()` no longer attempts to restore the completed transactions automatically. There are no side effects to this.


describe the change in the method signatures and code
- the method signature would not really be async anymore as it would no longer resolve with a users purchase history

consider changes needed in the docs and guides
- would have to remove the details about how it returns a users purchase history, as this would no longer be the case

if we decide to move forward, include a descriptive / helpful breaking change entry in the changelog for this package. what apps does this affect? how should you update your code?

- any app that uses this method to fetch purchase history via this method would have to update to the `getPurchaseHistoryAsync` method instead. 

I'm not entirely familiar with how native modules handle promises, but the optimal solution would be to trigger the restore functionality only if the method has specified a resolve block, I would think that would prevent it from being a breaking change.

2020-05-27 01:55 UTC, ide commented
That sounds like a good set of changes. We definitely want connectAsync and disconnectAsync to stay async because they complete asynchronously. A method doesn't just return a value, it returns  when its side effects (connecting or disconnecting) are complete.

2020-05-27 01:56 UTC, ide requested changes
Requesting changes to implement the API commented above with changes to the docs and a test plan explaining how the code was tested on iOS and Android.

2020-05-27 02:07 UTC, ajsmth commented
ah, i thought the listen and unlisten functions are synchronous, but i could be wrong. 

if this package does get updated, i would love for a more complete example of proper usage - the docs are fairly brief about the connect and disconnect functions and i’ve found it quite difficult to use, especially with hooks. 

I don’t know if it’s fast refresh but i often get promise resolution errors about already being connected. 

overall i don’t quite understand the value of disconnecting as it’s one listener which commonly will be setup globally, once, in an app. and my understanding is that you need the purchase listener to be setup constantly to handle changes that might happen outside of the app (e.g unsubscribing from a purchase)

2020-05-27 03:01 UTC, ide commented
Everything has to be asynchronous because the bridge is asynchronous. I am not sure of the purpose of disconnecting but in general it seems very reasonable to me to let an application clean up after itself.

2020-05-27 04:14 UTC, ajsmth commented
ah okay, that makes sense! thanks. 

would love a more thorough example of how to use this library properly

2020-05-31 03:07 UTC, sergeichestakov commented
Hey thanks for bringing up this issue. I agree that it's better not to query purchase history as part of `connectAsync`.

I've opened https://github.com/expo/expo/pull/8577 as an alternative which is a superset of this PR that also includes the corresponding Android and TS changes as well as updates the example screen we have in NCL.

@ide that PR should be good to merge as is, but let me know if I've missed anything. Happy to help with this one.

2020-06-08 23:52 UTC, ide commented
Closing (superseded by https://github.com/expo/expo/pull/8577).

2020-06-08 23:52 UTC, closed without merging