fix(web): Allow createElement & unstable_createElement usage
expo/expo pull request #7995
Opened 2020-04-24 19:52 UTC by wood1986

fix #6384

2020-04-24 21:17 UTC, EvanBacon commented on packages/expo-gl/src/Canvas.tsx
> +const createElement = require('react-native').unstable_createElement || require('react-native').createElement;
We disallow `require(`react-native`)` because this breaks web tree-shaking, effectively bundling all of `react-native`.

2020-04-24 21:17 UTC, EvanBacon requested changes
Perhaps you could extract the required functionality from those methods

2020-04-26 20:46 UTC, wood1986 commented
How about this?

2020-04-27 17:14 UTC, wood1986 commented
Any updates?

2020-04-29 18:16 UTC, wood1986 commented
Hey guys, would you mind get this review? As for the errors, I am not sure if it is come from me.

2020-05-04 10:31 UTC, bbarthec requested changes
LGTM 💪👌👏
Regarding CI errors, please do the followings:
- rebase on the current `master`
- rebuild the package affected by your changes (`packages/expo-gl`) by invoking following command in this package directory:
	- `yarn build` - rebuild `.d.ts` files and `.js` files
- ensure correct format of your changes, by running `yarn lint`

2020-05-04 23:51 UTC, wood1986 commented
It is fixed

2020-05-05 08:14 UTC, bbarthec approved these changes

2020-05-05 08:16 UTC, bbarthec commented
One missing thing in your PR is `CHANGELOG` entry 😉 Please add `CHENGELOG` entry in correct package according to the style from the main `CHANGELOG` file and we'll be ready to merge it 😊

2020-05-05 09:09 UTC, wood1986 commented
> One missing thing in your PR is `CHANGELOG` entry 😉 Please add `CHENGELOG` entry in correct package according to the style from the main `CHANGELOG` file and we'll be ready to merge it 😊

Maybe you guys should use [conventional-changelog spec](https://www.conventionalcommits.org/en/v1.0.0/) and [conventional-changelog](https://github.com/conventional-changelog/conventional-changelog)

2020-05-05 09:13 UTC, wood1986 commented
Not sure if it is correct

2020-05-05 10:19 UTC, bbarthec requested changes

2020-05-05 10:19 UTC, bbarthec commented on packages/expo-gl/CHANGELOG.md
> +## 8.1.0
```suggestion
## master

### 🐛 Bug fixes

- Allow createElement & unstable_createElement usage for web. ([#7543](https://github.com/expo/expo/pull/7995) by [@wood1986](https://github.com/wood1986))
```
No version is released so just add your entry to correct section under `## master` tag 😉

2020-05-06 09:07 UTC, merged

2020-05-06 16:42 UTC, wood1986 commented
Thanks, when will you publish a new package?