[sentry docs] Use Updates.manifest.revisionId in bare
expo/expo pull request #8048
Opened 2020-04-27 23:13 UTC by raphaelrk

I think this is correct -- if you're in bare workflow, you should instead be using `Updates.manifest.revisionId`.

I'm sure there's better ways to word this / there may be someone else adding this right now. Feel free to edit or close 😄

# Why

Please describe the motivation for this PR, and link to relevant GitHub issues, forums posts, or feature requests.

# How

How did you build this feature or fix this bug and why?

# Test Plan

Please describe how you tested this change and how a reviewer could reproduce your test, especially if this PR does not include automated tests! If possible, please also provide terminal output and/or screenshots demonstrating your test/reproduction.

2020-04-30 15:42 UTC, cruzach requested changes
thanks! probably useful to link to that documentation

As for using in the bare workflow, you can just follow Sentry's documentation for that, since it's a vanilla React Native project at that point

2020-04-30 15:42 UTC, cruzach commented on docs/pages/guides/using-sentry.md
> +Note that the `revisionId` is not available in the manifest when running in development mode (using Expo CLI), defaulting to `undefined`. If you're using the bare workflow, you should use `Updates.ma
```suggestion
Note that the `revisionId` is not available in the manifest when running in development mode (using Expo CLI), defaulting to `undefined`. If you're using the bare workflow, you should use [`Updates.manifest.revisionId`](../../versions/latest/sdk/updates/#updatesmanifest).
```

2020-04-30 19:51 UTC, raphaelrk commented
Thanks @cruzach, would it make more sense to use [sentry-react-native](https://github.com/getsentry/sentry-react-native) then for bare workflow? If so, might be good to mention in the docs

2020-04-30 20:40 UTC, cruzach commented
Sure, it's a little more cumbersome to set up since we handle quite a bit for you in the postpublish hook, but I'm sure that's still configurable when doing it yourself

2020-05-22 19:11 UTC, cruzach approved these changes

2020-05-22 19:11 UTC, merged