Fix uuid imort syntax to use mandatory module syntax
expo/expo pull request #8114
Opened 2020-05-01 11:10 UTC by actuallymentor

# Why

While `uuid@6` refers named imports `uuid@8` requires it. Using this import gets rid of the `Deep requiring like `const uuidv4 = require('uuid/v4');` is deprecated as of uuid@7.x.` message in v7 and makes the constants package compatible with uuid v8.x

# How

Simple import syntax fix.

# Test Plan

Run any web project with constants.

2020-05-04 19:44 UTC, ide requested changes
Please rebuild the JS and add it to your commit: https://github.com/expo/expo/blob/master/CONTRIBUTING.md#-before-submitting

2020-05-05 12:48 UTC, actuallymentor commented
I foolishly didn't read the guidelines. Read then just now and:

- [x] Added build files
- [x] Added changelog

If I missed anything let me know.

2020-05-05 15:04 UTC, bbarthec approved these changes
LGTM 💯

2020-05-05 15:08 UTC, bbarthec commented on CHANGELOG.md
> +- Fixed `uuid`'s deprecation of deep requiring ([#8114](https://github.com/expo/expo/pull/8114) by [@actuallymentor](https://github.com/actuallymentor) )
```suggestion
- Fixed `uuid`'s deprecation of deep requiring ([#8114](https://github.com/expo/expo/pull/8114) by [@actuallymentor](https://github.com/actuallymentor))
```
Move this change to `packages/expo-constants/CHANGELOG` as this affects `expo-constants` module only and not whole repository 😉

2020-05-05 17:21 UTC, merged