[expo-task-manager][android] Fix removing tasks from repository when …
expo/expo pull request #8612
Opened 2020-06-02 11:35 UTC by mczernek

…unregistering them.

# Why

During QA @esamelson noticed an error while trying to unregister all tasks in TaskManager.

# How

Root cause of the problem was the fact, that we changed the way tasks are stored by adding storage layer. It turned out, that in some cases tasks were removed incorrectly by manipulating retrieved list from repository. Now, as we return copy of that list, those manipulations had no effect.

# Test Plan

NCL - add task in BackgroundFetch and then remove all tasks in TaskManger screen.

2020-06-02 12:01 UTC, tsapeta requested changes

2020-06-02 12:01 UTC, tsapeta commented on packages/expo-task-manager/CHANGELOG.md
> +- Fix removing tasks. ([#8348](https://github.com/expo/expo/pull/8612) by [@mczernek](https://github.com/mczernek))
Isn't it better not to have such changelog entry at all than to have one that says nothing?

2020-06-02 12:55 UTC, tsapeta commented on packages/expo-task-manager/android/src/main/java/expo/modules/taskManager/repository/ManagedTasksAndEventsRepository.java
> +    if(sTasks.containsKey(appId)) {
Still not resolved 😞 I wonder why it's been marked as resolved 🤔

2020-06-02 13:05 UTC, tsapeta approved these changes

2020-06-02 13:26 UTC, merged

2020-07-15 21:00 UTC, byCedric commented
Can we release this fix? It seems like it's causing various bugs in managed and bare at the moment.