[asset] Return assets when downloading completes
expo/expo pull request #8646
Opened 2020-06-04 01:56 UTC by EvanBacon

# Why

Getting a local URI is pretty verbose, when using something like three.js which requires local URIs, this can build up quickly. 

```js
const asset = Asset.fromModule(require('./img.png'));
await asset.downloadAsync();
const { localUri } = asset;
```

Now you can

```js
const asset = Asset.fromModule(require('./img.png'));
const { localUri } = await asset.downloadAsync();
```

Or in one line

```js
const [{ localUri }] = await Asset.loadAsync(require('./img.png'));
```

2020-06-04 05:05 UTC, ide reviewed
Need to update the docs, too.

2020-06-04 05:14 UTC, ide requested changes
Requesting changes for docs, but the code changes look good to me.

2020-06-04 08:59 UTC, tsapeta reviewed
PLEASE DON'T FORGET TO UPDATE CHANGELOGS !

Sorry for uppercasing, but it's not the first time when I or someone else is asking you to update changelog 😞

2020-06-05 00:11 UTC, ide approved these changes

2020-06-05 05:49 UTC, merged