Adding explicit codeVerifier parameter to the TokenRequest
expo/expo pull request #8665
Opened 2020-06-04 17:14 UTC by ashward

# Why

This adds an explicit codeVerifier parameter to the AccessTokenRequest so that an Authorisation Code flow using PKCE can be carried out.

# How

I added the extra property, along with some tests.

# Test Plan

This is the code I've been using to test the flow:

```ts
    const codeResponse = await promptAsync({ useProxy: false });

    if (codeResponse['error'] === null && codeResponse['type'] === 'success') {
        if (discovery === null) {
            throw new Error('Auto discovery failed');
        }

        const tokenResponse = await exchangeCodeAsync(
            {
                clientId: config.clientId,
                code: codeResponse.params.code,
                redirectUri: config.redirectUri,
                codeVerifier: request?.codeVerifier
            },
            discovery
        );
    }
```

2020-06-05 03:26 UTC, EvanBacon commented on packages/expo-auth-session/src/TokenRequest.types.ts
> +   * (https://tools.ietf.org/html/rfc7636)
```suggestion
   * [Section 4.5](https://tools.ietf.org/html/rfc7636#section-4.5)
```

2020-06-05 03:31 UTC, EvanBacon commented on packages/expo-auth-session/src/TokenRequest.ts
> +    if(this.codeVerifier) {
```suggestion
    if (this.codeVerifier) {
```

2020-06-05 03:35 UTC, EvanBacon requested changes
thanks, please also update the docs.

2020-06-05 03:36 UTC, EvanBacon commented on packages/expo-auth-session/src/TokenRequest.types.ts
> +   * If we are using PKCE then we include the original 'code_verifier' in the token request.
If possible, could you add a more informative doc block -- for instance I think people may not know what the original `code_verifer` is if they use the hooks API.

2020-06-22 23:43 UTC, closed without merging

2020-10-25 10:17 UTC, raarts commented
@EvanBacon, why was this closed? It seems this was never merged.