Fix React Native Appearance/useColorScheme support for SDK 38
expo/expo pull request #8793
Opened 2020-06-13 03:51 UTC by brentvatne

# Why

`useColorScheme` has two problems right now:
- It doesn't update on Android, but it does on iOS. Related issue: https://github.com/facebook/react-native/issues/28823 - it requires we override `onConfigurationChanged` in our activity.
- It doesn't respect the configuration when users force a particular color scheme via `userInterfaceStyle` in app.json.

# How

- Added the `onConfigurationChanged` method as required, verified that this fixes `useColorScheme` from `react-native`
- Copy over relevant code from `ExpoAppearanceModule` to give priority to the current activity local night mode configuration (which is what we use to enforce a specific scheme when `userInterfaceStyle` is set in app.json). This required bumping appcompat to 1.1.0 in ReactAndroid.

# TODO

- The changes to BaseExperienceActivity will apply to SDK38 just fine, but the ReactAndroid changes will not. These need to be applied to SDK38 too, and I'm not familiar with the process for this on Android.

# Test Plan

- Use the tabs template
- If TODO hasn't been resolved, set the sdkVersion to UNVERSIONED
- Set `userInterfaceStyle` to `light` in app.json and verify that it's light when you use dark mode, and nothing happens when you toggle between modes while it's open. Same for dark. Verify automatic works as expected.

2020-06-15 22:47 UTC, ide requested changes
Requesting changes to have a separate PR to expo/react-native on a branch prefixed with `expo/` so that we don't lose this commit in the future.

Talking to @esamelson if we want this in the release we need this to be in a shippable state soon (Tuesday or Wednesday) since we've already versioned the Android code (will need to re-version) and are otherwise ready to continue the release process.

2020-06-15 22:47 UTC, ide commented on android/expoview/src/main/java/host/exp/exponent/experience/BaseExperienceActivity.java
> +
Reviewed this part; looks fine to me.

2020-06-17 00:16 UTC, esamelson approved these changes

2020-06-17 00:45 UTC, merged

2020-06-17 00:50 UTC, brentvatne commented
Added to the react-native fork in https://github.com/expo/react-native/commit/48e27f6aa498d88c7399ffd6d8a211b6bd383e68