[expo-notifications] Get `channelId` from remote message
expo/expo pull request #9080
Opened 2020-07-03 11:36 UTC by lukmccall

# Why

Fixes https://github.com/expo/expo/issues/8990.

# How

- Get `channelId` from the remote message.

# Test Plan

- send notification via expo.io/notifications and check the channel ✅

# Changelog 

- Fixed remote notifications ignoring the `channelId` parameter.

2020-07-03 11:36 UTC, lukmccall commented
I think we should scope channels to 
cc @sjchmiela

2020-07-03 14:20 UTC, RodolfoGS approved these changes
I tested and works perfect now 👍

2020-07-07 08:24 UTC, mczernek requested changes

2020-07-07 08:24 UTC, mczernek commented on packages/expo-notifications/android/src/main/java/expo/modules/notifications/notifications/presentation/builders/ChannelAwareNotificationBuilder.java
> +      return firebaseNotificationTrigger.getRemoteMessage().getData().get("channelId");
I think this logic should in fact belong to NotificationTrigger.

I would see it like that: every notification in fact needs channel (for Android Oreo+). we might hence add `getChannelId` to NotificationTrigger and provide default which returns null. Here in the Builder, we would only check it for nullability and provide fallback channel if needed.

2020-07-08 08:13 UTC, mczernek approved these changes
Good work! 💯 🥇

2020-07-08 08:30 UTC, merged