[auth-session] Missing "usePKCE" and typo in Firebase guide for Google
expo/expo pull request #9177
Opened 2020-07-11 16:33 UTC by Vista1nik

# Why
- Not working example from #8719.
Running this code without `usePKCE: false` will result in "400 invalid_request" error.
```javascript
import * as React from 'react';
import * as WebBrowser from 'expo-web-browser';
import { makeRedirectUri, ResponseType, useAuthRequest, useAutoDiscovery, generateHexStringAsync } from 'expo-auth-session';
import firebase from 'firebase';
import { Button, Platform } from 'react-native';

// Initialize Firebase
if (!firebase.apps.length) {
  firebase.initializeApp({
    /* Config */
  });
}

WebBrowser.maybeCompleteAuthSession();

const useProxy = Platform.select({ web: false, default: true });

// Generate a random hex string for the nonce parameter
function useNonce() {
  const [nonce, setNonce] = React.useState(null);
  React.useEffect(() => {
    generateHexStringAsync(16).then(value => setNonce(value));
  }, []);
  return nonce;
}

export default function App() {
  const nonce = useNonce();
  // Endpoint
  const discovery = useAutoDiscovery('https://accounts.google.com');
  // Request
  const [request, response, promptAsync] = useAuthRequest(
    {
      responseType: ResponseType.IdToken,
      clientId: 'Your-Web-Client-ID.apps.googleusercontent.com',
      redirectUri: makeRedirectUri({
        // For usage in bare and standalone
        native: 'com.googleusercontent.apps.GOOGLE_GUID://redirect',
        useProxy,
      }),
      scopes: [
        'openid',
        'profile',
        'email',
      ],
      extraParams: {
        nonce,
      }
    },
    discovery
  );

  React.useEffect(() => {
    if (response?.type === 'success') {
      const { id_token } = response.params;
      
      const credential = firebase.auth.GoogleAuthProvider.credential(id_token);
      firebase.auth().signInWithCredential(credential);
    }
  }, [response]);

  return (
    <Button
      disabled={!request || !nonce)}
      title="Login"
      onPress={() => {
        promptAsync({ useProxy });
        }}
    />
  );
}
```
- Missing `(` in `disabled={!request || !nonce)}`
- `https` used in localhost.
# How
- Fixed Typo.
- Added `usePKCE: false` to `useAuthRequest`
# Test Plan

Running example code without `usePKCE: false` throws "400 invalid_request":
<img width="380" alt="Annotation 2020-07-11 191822" src="https://user-images.githubusercontent.com/16061243/87228765-f8402a00-c3ab-11ea-81bd-d3171cc93e16.png">

When `usePKCE: false` is added to code, auth successful.

2020-07-11 18:44 UTC, davitykale commented
@Vista1nik, does this work in a standalone app for you?

2020-07-12 10:22 UTC, Vista1nik commented
@davitykale Currently No, I found that AuthSession require `scheme` in app.json to work in standalone apps. 
https://docs.expo.io/versions/latest/sdk/auth-session/#usage-in-standalone-apps

I added `scheme` to app.json but now Google throws `Error 400: Custom schemes cannot have authority` on standalone apps.

2020-07-12 11:31 UTC, Vista1nik commented
I fixed custom scheme, it should look like this:
```javascript
      redirectUri: makeRedirectUri({
        // For usage in bare and standalone
        native: 'com.googleusercontent.apps.GUID:/redirect',
        useProxy,
      }),
```
Notice the single slash in `com.googleusercontent.apps.GUID:/redirect`

But, now Google throw error `Custom scheme URIs are not allowed for 'Web' client type`. 

Looks like we need to create Android and IOS clients ID and pass them to AuthSession if app is standalone. 
If app is expo client or web, we need to pass Web Client ID.

2020-08-04 23:10 UTC, EvanBacon commented on docs/pages/guides/authentication.md
> +  - Web dev: http://localhost:19006 -- this is assuming you want to invoke `WebBrowser.maybeCompleteAuthSession();` from the root URL of your app.
I don't understand? This is supposed to be https because auth-session uses crypto API which requires a secure origin.

2020-08-04 23:10 UTC, EvanBacon requested changes
just the https question.

2021-01-06 01:44 UTC, closed without merging

2021-11-10 13:27 UTC, yosukesuzuki commented
@Vista1nik Did you fix this error?  

I got the same message in SDK43.
`Custom scheme URIs are not allowed for 'Web' client type` 

Expo Go client is OK but does not work in a standalone app

2021-11-10 20:18 UTC, Vista1nik commented
@yosukesuzuki 
You need to use `expo-auth-session/providers/google` for expo go and web
and `expo-google-sign-in` for native google sign-in

Follow this guide for Native Google Auth:
https://docs.expo.dev/versions/latest/sdk/google-sign-in/

And this guide for web-based auth (Expo Go and Web):
https://docs.expo.dev/guides/authentication/#web-apps (see firebase tab)

This is example from my app code:
```js
import * as React from 'react';
import { Platform } from 'react-native';
import firebase from 'firebase';

// Browser Auth
import * as Google from 'expo-auth-session/providers/google';
// Native Auth
import * as GoogleSignIn from 'expo-google-sign-in';

import Constants from 'expo-constants';
import * as WebBrowser from 'expo-web-browser';

import { Button } from './ui'

WebBrowser.maybeCompleteAuthSession();

export default () => {
    const [request, response, promptAsync] = Google.useIdTokenAuthRequest({
      expoClientId: 'someExpoClientId.apps.googleusercontent.com',
      iosClientId: 'someIOSClientId.apps.googleusercontent.com',
      androidClientId: 'someAndroidClientId.apps.googleusercontent.com',
      webClientId: 'someWebClientId.apps.googleusercontent.com',
    })

    React.useEffect(() => {
      if (response?.type === 'success') {
        const { id_token } = response.params;

        const credential = firebase.auth.GoogleAuthProvider.credential(id_token);
        firebase.auth().signInWithCredential(credential)
        .catch(e => {
          alert(e)
        })
      }
    }, [response]);

  return (
        <Button
            title="Login"
            onPress={() => {
                if (Constants.appOwnership === "standalone") {
                  // Sign-in via native
                  GoogleSignIn.initAsync()
                  .then(() => {
                    GoogleSignIn.askForPlayServicesAsync()
                    .then(() => {
                      GoogleSignIn.signInAsync()
                      .then(res => {
                        if (res.type === 'success') {
                          const credential = firebase.auth.GoogleAuthProvider.credential(res.user.auth.idToken);

                          firebase.auth().signInWithCredential(credential)
                          .catch(e => {
                            alert(e)
                          })
                        } else {
                          alert(JSON.stringify(res))
                        }
                      })
                    })
                  })
                } else {
                  // Sign-in via browser
                  promptAsync()
                }
            }}
            primary
        >SIGN-IN WITH GOOGLE</Button>
    );
}
```

2021-11-10 20:43 UTC, yosukesuzuki commented
@Vista1nik Thanks. This is very helpful. I previously used `expo-google-app-auth` for the iOS standalone app, but the lib was dropped from the Expo SDK, so I was trying to switch to AuthSession.

I will implement with `GoogleSignIn`