[expo-updates] add projectIdentifier field to configuration and use when interacting with database
expo/expo pull request #9217
Opened 2020-07-15 00:42 UTC by esamelson

# TODO

- [ ] change base branch before merging

# Why

Allow updates for multiple projects to be stored in the same database.

# How

We previously added the project_identifier field in the database for this purpose -- it is meant to be a unique ID for a project that can be used to filter stored updates by project.

This PR adds a corresponding `projectIdentifier` field to the updates configuration object, and uses this `config.projectIdentifier` field both when inserting and selecting updates from the database. If no `projectIdentifier` is specified, it defaults to the manifest (update) URL.

# Test Plan

No behavior changes are expected, this just adds functionality that will be utilized when integrating the module into the App Store clients. Did manual smoke tests of building an app and loading remote updates on both iOS and Android, and verified that the `project_identifier` field in the database is correctly filled in on both platforms. (Also verified that it was filled in with the update URL in prior versions of the library.)

2020-07-16 03:20 UTC, ide requested changes
The code looks good but there are two things I think we may want to make two changes, discussion below:

One is to use the URL's origin instead of the whole URL. This aligns us with the same-origin policy that the web uses and makes it easier for people to move their manifest around their own site without breaking their project.

The second change is to rename "project identifier" everywhere to "scope" or "scope key" instead. "Project IDs" are an EAS-specific concept, while "scoping" is an Expo-specific concept. We use the EAS project ID as a scope key for EAS-hosted projects, but for self-hosted projects we use the URL for scoping. Additionally, we use the projectIdentifier field to keep updates from different projects separate, which is what scoping does for every other module.

2020-07-16 21:07 UTC, esamelson commented
@ide projectId -> scopeKey makes sense, will make that change now.

Re: the URL origin change, do you mean that we should use the URL's origin as the default, rather than the whole URL, but then in the managed workflow case, explicitly set a separate scope key instead?

2020-07-17 06:38 UTC, ide commented
> Re: the URL origin change, do you mean that we should use the URL's origin as the default, rather than the whole URL, but then in the managed workflow case, explicitly set a separate scope key instead?

My thinking is for the general case (namely, self-hosting), we should use the URL's origin. This is in line with the same-origin policy, which is the basis for a lot of web security. A lot of the web operates under the assumption that if you own one page with a given origin, you also own all the pages with the same origin. So I think Expo will naturally fit with how people think about their web security if we use the same-origin policy.

In the managed workflow since projects are served from our servers, we can't use the SOP. So we'll need to send down a "scope" field in the manifests and trust it only if the manifest comes from one of our origins.

2020-07-17 06:50 UTC, ide approved these changes
Approving but the origin needs to take the port into consideration. This is Node's logic for normalizing ports: https://github.com/nodejs/node/blob/master/src/node_url.cc#L726-L754

2020-07-17 06:50 UTC, ide commented on packages/expo-updates/android/src/main/java/expo/modules/updates/UpdatesConfiguration.java
> +        mScopeKey = mUpdateUrl.getScheme() + "://" + mUpdateUrl.getHost();
Need to get the port too and include it if it's not null and if it's not the default port for the scheme: https://url.spec.whatwg.org/#url-miscellaneous

2020-07-18 00:44 UTC, esamelson commented
Makes sense. I've added logic to include the port if nonnull/non-default, as well as unit tests for the normalized URL origin, in https://github.com/expo/expo/pull/9217/commits/ae50c118a8428f6dfdf29da0cf1295ff02caa00c .

2020-07-18 01:36 UTC, ide approved these changes

2020-07-20 18:46 UTC, merged