[location] expo-location audit and refactor
expo/expo pull request #9251
Opened 2020-07-16 16:31 UTC by tsapeta

# Why

`expo-location` wins the challenge for the number of issues being opened 😓 

# How

I've decided to do some audits over it which should result in fixing some of those reported bugs and generally improve its reliability and make API more consistent across platforms.

- `getLastKnownPositionAsync`
  - Now doesn't request for the new location on iOS
  - No longer rejects when the last known location is not available, returns `null` instead (more usable API)
- Some of TypeScript types have changed their names, but this is a change for the better
- Added some new tests
- Improve Web support, add missing methods, make types consistent with other platforms.
- Enabled `expo-location` tests on Web

# Test Plan

- Ran through `test-suite` tests on Android, iOS and Web – all is green.

2020-07-20 15:24 UTC, tsapeta commented
I already requested for review, but I will understand if you guys think it's too big to go through 😅 Sorry for that, it was unintentional but that's ok to me to split it up if you would need to.

2020-07-21 16:35 UTC, lukmccall approved these changes
I left some comments ;) but I think I will read this code one more time :D

2020-07-21 16:35 UTC, lukmccall commented on packages/expo-location/src/Location.types.ts
> +  scope: 'whenInUse' | 'always';
```suggestion
  scope: 'whenInUse' | 'always' | 'none';
```

2020-07-21 16:44 UTC, lukmccall commented
One more thing 😅

Currently, you added `isLocationValid` to every platform. I think we could get the last know position from the native side and validate through js code. In that way, we don't need to add the `isLocationValid` method to every platform. Moreover, in that case, we don't need to pass options to native code either.

2020-07-21 16:45 UTC, lukmccall requested changes
One more thing 😅

Currently, you added `isLocationValid` to every platform. I think we could get the last know position from the native side and validate through js code. In that way, we don't need to add the `isLocationValid` method to every platform. Moreover, in that case, we don't need to pass options to native code either.

2020-07-23 11:17 UTC, tsapeta commented on docs/pages/versions/unversioned/sdk/location.md
> +  - **accuracy : [LocationAccuracy](#locationaccuracy)** — Location manager accuracy. Pass one of [LocationAccuracy](#locationaccuracy) enum values. For low accuracy the implementation can avoid geol
Yeah, I've used em dash `—` (`-`, `Option`, `Shift`) for this which is for more more natural here, even more than single short dash. I think it's a good idea to change them all, but maybe not in this PR? 🤔

2020-07-23 11:28 UTC, tsapeta commented
@lukmccall I think it's a good point and I've been thinking about it, but for me it's always more clear to have the main implementation in one place and don't have to worry about switching between different contexts (code editors, languages and so on). Imho JS side should only be an interface to the native API (except web of course). Anyway, I can change this if you're still not convinced 😄

2020-07-23 12:15 UTC, lukmccall approved these changes

2020-07-23 12:24 UTC, merged