[expo-linear-gradient] Avoid unnecessary re-render of NativeLinearGradient on web
expo/expo pull request #9342
Opened 2020-07-21 22:56 UTC by danmaas

# Why

On react-native-web, the NativeLinearGradient component re-renders continuously, eating up CPU cycles.

This seems to be a new behavior with recent versions of `react-native-web`, since I did not notice it before updating from 0.11.7 to 0.13.3.

I believe the problem is that NativeLinearGradient's `onLayout` handler does not check if the layout has actually changed; it just always calls `setLayout()`, which triggers another `onLayout` event, which triggers `setLayout()` again, and so on.

# Test Plan

Use react-native-web 0.13.3, create a LinearGradient, and run a profile using the Chrome React Developer Tools plugin. Without this patch, the NativeLinearGradient component re-renders continuously with the reason "Hooks changed". With the patch, it renders once and then idles properly.

2020-07-22 07:21 UTC, barthap commented
You probably forgot to run `yarn build` from inside `expo-linear-gradient` package to generate js files.

2020-07-23 22:11 UTC, EvanBacon commented on packages/expo-linear-gradient/src/NativeLinearGradient.web.tsx
> +          !layout ||
```suggestion
          !layout ??
```

2020-07-23 22:11 UTC, EvanBacon commented on packages/expo-linear-gradient/src/NativeLinearGradient.web.tsx
> +          event.nativeEvent.layout.width !== layout.width ||
Check x, y as well

2020-07-23 22:12 UTC, EvanBacon requested changes
Be sure to ensure the whole object is validated first

2020-07-24 04:19 UTC, danmaas commented
Thanks for checking out this PR. I realized I had branched this from an ancient `master` commit, sorry. Fixed now.

I'm not 100% sure I got what you mean by ensuring the whole object is validated first - please check the updated PR and let me know?

2020-07-28 07:13 UTC, EvanBacon requested changes
Build files need to be updated (yarn build in packages/expo-linear-gradient) I tried but don't have push permission to your branch

2020-07-28 16:51 UTC, danmaas commented
Hmm, it looks like the CI jobs might be referencing an old commit, not the latest commit `cbd9222`, which I force-pushed. I might need to re-generate this PR on a fresh branch, is that OK?

(in the latest commit `cbd9222` I already ran `yarn build` and it includes diffs to `packages/expo-linear-gradient/build/NativeLinearGradient.web.js`).

2020-07-28 17:03 UTC, barthap commented
Just do another commit (change something that has no meaning) - it should reset the checks

2020-07-29 03:54 UTC, EvanBacon approved these changes
good work

2020-07-29 03:54 UTC, merged