[notifications][android] Add `sticky` property to notifications
expo/expo pull request #9351
Opened 2020-07-22 14:54 UTC by barthap

# Why
Implements changes proposed in #9302.

Current Notifications API provides [`autoDismiss` ](https://developer.android.com/reference/android/app/Notification.Builder#setAutoCancel(boolean))property, which directly corresponds to [`autoCancel`](https://developer.android.com/reference/android/app/Notification.Builder#setAutoCancel(boolean)) on Android - it specifies if notification can be dismissed by tapping it, however it can be dismissed by swipe. Android API can also set notification as [`ongoing`](https://developer.android.com/reference/android/app/Notification.Builder#setOngoing(boolean)) - it can be dismissed by tapping, but not by swiping.

Expo [legacy notification API](https://developer.android.com/reference/android/app/Notification.Builder#setAutoCancel(boolean)) had this property available, but it was replaced with `autoDismiss` in the new API. 

# How
Added `sticky` property to `NotificationContentInput` interface, used by local notifications. On native side - added it to `NotificationContent.Builder` where needed and connected it with Android's [`setOngoing()`](https://developer.android.com/reference/android/app/Notification.Builder#setOngoing(boolean)).

# Test Plan

- [x]  Test local notifications
- [ ]  Test FCM push notifications

2020-07-22 14:58 UTC, lukmccall requested changes

2020-07-22 14:58 UTC, lukmccall commented on packages/expo-notifications/CHANGELOG.md
> +> Note that the effect of this method is the same as if you called `Notifications.getPermissionsAsync()` (or `requestPermissionsAsync`) and then `Notifications.getDevicePushTokenAsync()`—it tries to
Please, revert that ;)

2020-07-22 15:00 UTC, lukmccall commented on packages/expo-notifications/CHANGELOG.md
> +> Note that the effect of this method is the same as if you called `Notifications.getPermissionsAsync()` (or `requestPermissionsAsync`) and then `Notifications.getDevicePushTokenAsync()`—it tries to
It's a result of the bug in the markdown parser used in the `et add-changelog` command :/

2020-07-23 09:07 UTC, lukmccall approved these changes
LGTM 🎉🎉🎉

2020-07-24 06:12 UTC, mczernek approved these changes
Solid work!

2020-07-24 07:20 UTC, merged