[expo-keep-awake] Add web implementation for expo-keep-awake
expo/expo pull request #9467
Opened 2020-07-29 09:37 UTC by jarvisluong

# Why

As mentioned in https://github.com/expo/expo/issues/6889

# How

I implemented as the implementation guide of https://web.dev/wakelock/

Since the wake lock request in web will return a Promise, I changed the public API of expo-keep-awake to reflect that also.

# Test Plan

To be updated

2020-07-29 09:53 UTC, jarvisluong commented
I will update the docs and change log as well if we are okay with the public API changes.

2020-07-29 20:47 UTC, EvanBacon commented on packages/expo-keep-awake/src/ExpoKeepAwake.ts
> +export function isAvailable() {
This must be implemented in native code.

2020-07-29 20:48 UTC, EvanBacon commented on packages/expo-keep-awake/src/ExpoKeepAwake.web.ts
> +export function isAvailable() {
```suggestion
export function isAvailableAsync(): Promise<boolean> {
```

There should only be one `default export {}` with all "native" methods inside of it.

2020-07-29 20:49 UTC, EvanBacon commented on packages/expo-keep-awake/src/ExpoKeepAwake.web.ts
> +export default createKeepAwakeManager();
Just export a default object like all of the other modules.

2020-07-29 20:50 UTC, EvanBacon commented on packages/expo-keep-awake/src/index.ts
> +};
Try to keep the export pattern similar to the other modules https://github.com/expo/expo/blob/master/packages/expo-battery/src/Battery.ts

All functions should be exported inline, all types can be exported at the end of the file.

2020-07-29 20:58 UTC, EvanBacon commented on packages/expo-keep-awake/src/ExpoKeepAwake.web.ts
> +        throw new Error(`The wake lock with tag ${tag} has not activated yet`);
```suggestion
        throw new CodedError('ERR_KEEP_AWAKE_TAG_INVALID', 'The wake lock with tag ${tag} has not activated yet');
```

2020-07-29 21:06 UTC, EvanBacon commented on packages/expo-keep-awake/src/index.ts
> +  }
```suggestion
  if (!(await isAvailableAsync())) {
    if (__DEV__) {
      console.warn('KeepAwake.activateKeepAwake() was invoked on a device that doesn't support the KeepAwake API.');
    }
    return;
  }
  if (ExpoKeepAwake.activate) {
    await ExpoKeepAwake.activate(tag);
  }
```

Let's warn in dev mode that the API has been misused (we do this in AuthSession API)

2020-07-29 21:06 UTC, EvanBacon commented on packages/expo-keep-awake/src/index.ts
> +  }
Apply the same to all methods

2020-07-29 21:09 UTC, EvanBacon requested changes
There are some core API changes that need to be changed in order to match the ecosystem.

2020-07-29 21:11 UTC, jarvisluong commented
> There are some core API changes that need to be changed in order to match the ecosystem.

could you elaborate which core API should be changed. By "ecosystem" do you mean this particular package?

2020-07-30 20:02 UTC, EvanBacon commented
ya, any of them but I linked a module in the comments that you can copy https://github.com/expo/expo/blob/master/packages/expo-battery/src/Battery.ts

2020-08-12 05:17 UTC, jarvisluong commented
@EvanBacon Hi! Any updates on this PR? (Sorry for disturbing 😬)

2021-05-02 04:14 UTC, Nfinley commented
This web keep awake feature would be incredible to have. Any updates on this? Anything I can do to help? @EvanBacon 

Thank you for all your work on expo

2022-02-03 22:34 UTC, brentvatne commented
replaced by https://github.com/expo/expo/pull/15826

2022-02-03 22:34 UTC, closed without merging