[docs] EAS Builds: add 'Setup' page & more
expo/expo pull request #9754
Opened 2020-08-14 11:35 UTC by dsokal

# Why

This is probably the last part of adding docs for EAS Builds. At least for now :)

Previous PRs: #9566, #9613, #9704, and #9721

# How

- I added a new page for EAS Builds - "Setup"
- I updated the "Introduction" page.
- I addressed Brent's suggestions with the last PR - using `/* @info */` for highlighting some parts of code.

# Test Plan

I ran the dev server and made sure the new page renders correctly.

2020-08-14 12:01 UTC, wkozyra95 approved these changes

2020-08-14 13:50 UTC, cruzach requested changes

2020-08-14 13:50 UTC, cruzach commented on docs/pages/build/eas-builds-in-5-minutes.md
> +- Install Expo CLI by running `npm install -g expo-cli` (or `yarn global add expo-cli`). _If you already have it, make sure you're using the latest version._ EAS Builds is in alpha and it's changing
```suggestion
- Install Expo CLI by running `npm install -g expo-cli` (or `yarn global add expo-cli`). _If you already have it, make sure you're using the latest version._ EAS Builds is in alpha and it's changing rapidly, so the only way to ensure that you will have the best experience is to use the latest expo-cli version. **This tutorial assumes you're using `expo-cli@3.24.0` or newer.**
```

2020-08-14 13:50 UTC, cruzach commented on docs/pages/build/eas-builds-in-5-minutes.md
>  - Sign in with `expo login` or sign up with `expo register` if you don't have an Expo account yet. You can check if you're logged in by running `expo whoami`.
```suggestion
- Sign in with `expo login`, or sign up with `expo register` if you don't have an Expo account yet. You can check if you're logged in by running `expo whoami`.
```

2020-08-14 13:50 UTC, cruzach commented on docs/pages/build/eas-json.md
> +- `credentialsSource` defines the credentials source for the project build. If you want to take advantage of your own `credentials.json` file, set it to `local` ([learn more on this here](../advanced
```suggestion
- `credentialsSource` defines the source of credentials for this build profile. If you want to take advantage of your own `credentials.json` file, set this to `local` ([learn more on this here](../advanced-credentials-configuration/)). If you want to use the credentials Expo already has stored for you, choose `remote`. If you're not sure what to do but you probably won't be running builds from a CI, choose `auto` (this is the default option).
```

2020-08-14 13:50 UTC, cruzach commented on docs/pages/build/eas-json.md
> +- `credentialsSource` defines the credentials source for the project build. If you want to take advantage of your own `credentials.json` file, set it to `local` ([learn more on this here](../advanced
```suggestion
- `credentialsSource` defines the source of credentials for this build profile. If you want to take advantage of your own `credentials.json` file, set this to `local` ([learn more on this here](../advanced-credentials-configuration/)). If you want to use the credentials Expo already has stored for you, choose `remote`. If you're not sure what to do but you probably won't be running builds from a CI, choose `auto` (this is the default option).
```

2020-08-14 13:50 UTC, cruzach commented on docs/pages/build/eas-json.md
> +If you'd like to build your iOS project with your custom `Gymfile` ([learn more on this here](../ios-builds/#building-ios-projects-with-fastlane)) and you've defined a different output directory than
```suggestion
If you'd like to build your iOS project with a custom `Gymfile` ([learn more on this here](../ios-builds/#building-ios-projects-with-fastlane)) where you've defined a different output directory than `ios/build`, use the following example:
```

2020-08-14 13:50 UTC, cruzach commented on docs/pages/build/setup.md
> +Install Expo CLI by running `npm install -g expo-cli` (or `yarn global add expo-cli`). If you already have it, make sure you're using the latest version. EAS Builds is in alpha and it's changing rapi
```suggestion
Install Expo CLI by running `npm install -g expo-cli` (or `yarn global add expo-cli`). If you already have it, make sure you're using the latest version. EAS Builds is in alpha and it's changing rapidly, so the only way to ensure that you will have the best experience is to use the latest expo-cli version.
```

2020-08-14 13:50 UTC, cruzach commented on docs/pages/build/setup.md
> +Sign in with `expo login` or sign up with `expo register` if you don't have an Expo account yet. You can check if you're logged in by running `expo whoami`.
```suggestion
Sign in with `expo login`, or sign up with `expo register` if you don't have an Expo account yet. You can check if you're logged in by running `expo whoami`.
```

2020-08-14 13:50 UTC, cruzach commented on docs/pages/build/setup.md
> +If you wish to build your application for Android but this is the first doing this, you'll have to generate a keystore. To do so, you'll need the `keytool` command installed and searchable in `PATH`.
```suggestion
If you're building your Android application for the first time, you'll have to generate a keystore. To do so, you'll need the `keytool` command installed and searchable in `PATH`. `keytool` is distributed with Java Development Kit. We recommend you [install JDK version 8](https://jdk.java.net/) as this specific version is needed for building Android apps.
```

2020-08-14 13:50 UTC, cruzach commented on docs/pages/build/setup.md
> +## 7. Run The Build
```suggestion
## 7. Run the Build
```

2020-08-14 13:50 UTC, cruzach commented on docs/pages/build/setup.md
> +By default, the `expo eas:build` command is waiting for your build to complete. However, if you interrupt this command you can still monitor the progress of your builds by either visiting [the Expo w
```suggestion
By default, the `expo eas:build` command will wait for your build to complete. However, if you interrupt this command you can still monitor the progress of your builds by either visiting [the Expo website](https://expo.io/) or running the `expo eas:build:status` command.
```

2020-08-14 13:50 UTC, cruzach commented on docs/pages/build/setup.md
> +- If you want to learn more about internals of Android and iOS builds, check out [Android Builds](../android-builds/) and [iOS Builds](../ios-builds/) pages.
```suggestion
- If you want to learn more about the internals of Android and iOS builds, check out our [Android Builds](../android-builds/) and [iOS Builds](../ios-builds/) pages.
```

2020-08-14 13:50 UTC, cruzach commented on docs/pages/build/setup.md
> +- Lastly, if you're feeling an expert on the credentials configuration, see the [Advanced Credentials Configuration](../advanced-credentials-configuration/) guide to customize the build process even
```suggestion
- Lastly, if you feel like an expert on credentials configuration, see the [Advanced Credentials Configuration](../advanced-credentials-configuration/) guide to customize the build process even further.
```

2020-08-14 13:50 UTC, cruzach commented on docs/pages/build/setup.md
> +## 9. See Other Docs and Stay Tuned
```suggestion
## 9. Learn More
```

2020-08-14 13:50 UTC, cruzach commented on docs/pages/build/setup.md
> +## 4. Eject Managed Project
```suggestion
## 4. Eject Your Managed Project
```

2020-08-14 13:50 UTC, cruzach commented on docs/pages/build/android-builds.md
> +  /* @info configure the release signing config */android.signingConfigs.release/* @end */ { config ->
```suggestion
  /* @info This is where you configure the release signing config */android.signingConfigs.release/* @end */ { config ->
```

2020-08-14 13:50 UTC, cruzach commented on docs/pages/build/android-builds.md
> +    /* @info don't read credentials.json if the task name contains debug */
```suggestion
    /* @info Don't read credentials.json if the task name contains debug */
```

2020-08-14 13:50 UTC, cruzach commented on docs/pages/build/android-builds.md
> +      /* @info don't do anything if the release signing config is already defined in build.gradle */
```suggestion
      /* @info Don't do anything if the release signing config is already defined in build.gradle */
```

2020-08-14 13:50 UTC, cruzach commented on docs/pages/build/android-builds.md
> +          /* @info configure the signing config with the credentials.json data */
```suggestion
          /* @info Use the data from credentials.json for the signing config */
```

2020-08-14 13:50 UTC, cruzach commented on docs/pages/build/android-builds.md
> +  /* @info use the above signing config for the release build type */
```suggestion
  /* @info Use the above signing config for the release build type */
```

2020-08-14 15:40 UTC, dsokal commented on docs/pages/build/android-builds.md
> +  /* @info This is where you configure the release signing config */android.signingConfigs.release/* @end */ { config ->
```suggestion
  /* @info This is where we configure the release signing config */android.signingConfigs.release/* @end */ { config ->
```

2020-08-17 08:31 UTC, dsokal commented
I addressed all comments from Charlie and I'm merging this PR. If anyone else has more comments please let me know or open a PR :)

2020-08-17 08:32 UTC, merged