[docs] Refactor s3 upload in multiple stages for reliabilty
expo/expo pull request #9814
Opened 2020-08-18 13:29 UTC by byCedric

# Why

This fixes two main things.

1. **Reliability of the deployments**
Unfortunately, it looks like `$ aws s3 sync` isn't doing exactly what we would expect. [It uses some methods to determine if a file needs to be updated](https://github.com/aws/aws-cli/issues/3273#issuecomment-643436849), which causes some issues on our end. Resulting in either JS or HTML files not being uploaded or updated. This change mostly uses `$ aws s3 cp` to do what `$ aws s3 sync` currently does. It's still used to clean up the old deployment files, but not for uploading the new one.

2. **Staged rollout**
Instead of copying everything alphabetically, this change also introduces stages. These are explained in the deployment script itself, so I don't think I need to highlight it. One thing to note is that I use `::group::` and `::endgroup::` to create collapsible items in Github Actions (making it more debuggable). It also adds `--no-progress` to keep the logs readable as well.

# How

See files.

# Test Plan

You can see [a test/staging deployment over here](https://cedrics-expo.s3.eu-central-1.amazonaws.com/index.html), using this exact script. Over here, you can see the [full output of the logs](https://cedrics-expo.s3.eu-central-1.amazonaws.com/deployment-log.txt).

2020-08-18 13:30 UTC, byCedric commented
@ide I think the staged rollout was exactly the thing you mentioned, right?

2020-08-18 20:45 UTC, ide requested changes
Does `aws s3 cp` avoid copying files if their checksums have not changed? We don't change our large images and videos on most builds. The reason we use `sync` is to simulate that behavior of rsync and other similar tools.

2020-08-18 20:45 UTC, ide commented on docs/deploy.sh
> +  --cache-control "public,max-age=31536000,immutable" \
I think this is going to cause very serious issues, don't think we want caching, this should be no-cache

2020-08-18 20:45 UTC, ide commented on docs/deploy.sh
>    --cache-control "public,max-age=31536000,immutable" \
The caching for `/static/` will likely cause serious issues, this should be a 1-hour cache maximum (that is, let the site be buggy for 1 hour max... if we want zero bugs then we should turn off caching). Only cache content-addressed files permanently.

2020-08-18 21:47 UTC, byCedric commented
> Does `aws s3 cp` avoid copying files if their checksums have not changed? We don't change our large images and videos on most builds. The reason we use `sync` is to simulate that behavior of rsync and other similar tools.

No it doesn't check for the checksum, it uploads the file directly and overwrites it in S3. The main problem is are the HTML files, sometimes they were skipped even though they refer to different JS checksums.

We could also opt-in to use `$ aws s3 sync` for `static/**` files. That could save some bandwidth because the assets don't change that often, and I don't think we encountered the HTML-mismatch with these files. For `_next/**` I don't think it has a lot of effect, every export has a different checksum somehow and that results in the files being different anyways.

2020-08-18 22:04 UTC, ide commented
OK. Maybe let's try `aws s3 sync` for `_next/**` (pr `cp` would work as you mentioned) and `static/**` and use `cp` for the HTML files, followed with a final `sync` to delete unused files. The important thing is to upload dependencies before dependents. And ideally we would delete old dependents (HTML) before old dependencies (JS).

2020-08-18 22:05 UTC, byCedric commented on docs/deploy.sh
> -  "s3://${bucket}/_next/static/"
This static folder contains the JS files of the pages. Looking at your comments James, I'm not sure if we should keep this. It doesn't contain assets like images or videos.

2020-08-18 22:12 UTC, byCedric commented
> And ideally we would delete old dependents (HTML) before old dependencies (JS).

When we `$ aws s3 cp` the HTML files, we actually "force-replace" these old dependents (HTML). Running `$ aws s3 sync --delete` will delete the outdated dependencies (JS). 

It would probably look like this:
1. Run `$ aws s3 sync` on `_next/**` and `static/**` only (without delete) 
2. Run `$ aws s3 cp` to force-overwriting HTML files.
3. Run `$ aws s3 sync --delete` on the full folder, for both assets and cleaning up the JS files.

2020-08-18 23:47 UTC, byCedric commented
All right, refactored it based on input and tested it again on my own bucket:
> You can see [a test/staging deployment over here](https://cedrics-expo.s3.eu-central-1.amazonaws.com/index.html), using this exact script. Over here, you can see the [full output of the logs](https://cedrics-expo.s3.eu-central-1.amazonaws.com/deployment-log.txt).

2020-08-19 00:30 UTC, ide approved these changes

2020-08-19 00:30 UTC, ide commented on docs/deploy.sh
> +# see: https://github.com/aws/aws-cli/issues/3273#issuecomment-643436849
Move this comment down to the cp section

2020-08-19 18:57 UTC, merged