[ios][expotools] Fixes for versioned TurboModules
expo/expo pull request #9862
Opened 2020-08-20 18:01 UTC by sjchmiela

# Why

After versioning, TurboModules integration started to make more harm than good.

# How

- moved creating of the `JSCExecutorFactory`, which should be versioned, to versioned realm (otherwise we try to pass an unversioned code into a versioned bridge) (huge thanks to C++ senpai @wkozyra95 for assistance)
  - to achieve this I unfortunately had to modify `react-native` to
    1. expect `void *` from `jsExecutorFactoryForBridge:`, otherwise we can't pass versioned factory through unversioned and back into versioned
    2. do not detect whether delegate is an instance of `RCTCxxBridgeDelegate` by protocol, but by the actual method used. This is because delegate for all bridges is always `EXReactAppManager` which is not versioned.
  - another change is that `EXVersionManager` now **holds strongly** one instance of the `JSCExecutorFactory` instead of just creating it on every call. I think this shouldn't break anything, as on each bridge reload we create a new instance of `EXVersionManager` and there shouldn't be more calls to `jsExecutorFactoryForBridge:` apart from when setting the bridge up, but I think it's a note-worthy mention here.
- then I bumped into the `XX is not a registered callable module` error which led me to update `expotools`'s pattern for adding `EX_REMOVE_VERSION` to `MessageQueue`.

# Test Plan

I have verified that these fixes work on a separate branch.

2020-08-21 07:28 UTC, wkozyra95 requested changes
Originally I misunderstand a bit what you wanted to do, change I suggested will still require a modifications in react-native but at least the lifecycle of object will be preserved.

In this PR I see pointer converted to void*, but I don't see anywhere that would restore it, am I missing sth?

2020-08-21 07:28 UTC, wkozyra95 commented on ios/Exponent/Kernel/ReactAppManager/EXReactAppManager.mm
> +- (void *)jsExecutorFactoryForBridge:(id)bridge
```suggestion
- (std::shared_ptr<void>)jsExecutorFactoryForBridge:(id)bridge
```

2020-08-21 07:28 UTC, wkozyra95 commented on ios/Exponent/Versioned/Core/EXVersionManager.mm
> +
```suggestion
- (std::shared_ptr<void>)versionedJsExecutorFactoryForBridge:(RCTBridge *)bridge
{
  __weak __typeof(self) weakSelf = self;
  return std::shared_ptr<void>(new facebook::react::JSCExecutorFactory(
    [weakSelf, bridge](facebook::jsi::Runtime &runtime) {
      if (!bridge) {
        return;
      }
      __typeof(self) strongSelf = weakSelf;
      if (strongSelf) {
        strongSelf->_turboModuleManager = [[RCTTurboModuleManager alloc] initWithBridge:bridge
                                                                               delegate:strongSelf
                                                                              jsInvoker:bridge.jsCallInvoker];
        [strongSelf->_turboModuleManager installJSBindingWithRuntime:&runtime];
      }
    },
    [](void* data) { delete (*reinterpret_cast<facebook::react::JSCExecutorFactory*>(data)) }));
}

```

2020-08-21 07:28 UTC, wkozyra95 commented on ios/Exponent/Versioned/Core/EXVersionManager.mm
> +}
```suggestion
@implementation EXVersionManager
```

2020-08-21 07:28 UTC, wkozyra95 commented on ios/Exponent/Versioned/Core/EXVersionManager.h
> +- (void *)versionedJsExecutorFactoryForBridge:(id)bridge;
```suggestion
- (std::shared_ptr<void>)versionedJsExecutorFactoryForBridge:(id)bridge;
```

2020-08-21 08:14 UTC, wkozyra95 commented
I updated my suggestion after looking into react-native changes

2020-08-21 08:39 UTC, bbarthec approved these changes

2020-08-21 08:39 UTC, bbarthec commented on ios/Exponent/Versioned/Core/EXVersionManager.mm
> +- (std::shared_ptr<facebook::react::TurboModule>)getTurboModule:(const std::string &)name instance:(id<RCTTurboModule>)instance jsInvoker:(std::shared_ptr<facebook::react::CallInvoker>)jsInvoker nati
```suggestion
- (std::shared_ptr<facebook::react::TurboModule>)getTurboModule:(const std::string &)name
                                                       instance:(id<RCTTurboModule>)instance 
                                                      jsInvoker:(std::shared_ptr<facebook::react::CallInvoker>)jsInvoker
                                                  nativeInvoker:(std::shared_ptr<facebook::react::CallInvoker>)nativeInvoker
                                                     perfLogger:(id<RCTTurboModulePerformanceLogger>)perfLogger
{
```

2020-08-21 08:39 UTC, bbarthec commented on ios/Exponent/Versioned/Core/EXVersionManager.mm
> +  __weak __typeof(self) weakSelf = self;
I'm not sure how Objective-C ↔️ Objective-Cpp Interoperability works, but is it possible to either use existing `WEKIFY` and `ENSURE_STRONGIFY` macros or create new one for Cpp realm?

2020-08-25 07:03 UTC, tsapeta approved these changes

2020-08-25 08:10 UTC, wkozyra95 approved these changes

2020-08-25 09:09 UTC, merged