[docs] configuration.md - grammar & word-smithing
expo/expo pull request #9938
Opened 2020-08-26 01:05 UTC by gregfenton

# Why

Overly worded and hard to parse.

# How

Docs fixes.

# Test Plan

(docs review)

2020-08-31 18:42 UTC, cruzach requested changes
thanks for fixing this up! Just a few wording changes from me

2020-08-31 18:42 UTC, cruzach commented on docs/pages/workflow/configuration.md
> +5. All functions in the config are evaluated and serialized before any tool in the Expo ecosystem uses it. The config must be a JSON manifest when it is hosted.
```suggestion
1. The static config will be read if `app.config.json` exists (falls back to `app.json`). If no static config exists, then default values are inferred from the `package.json` and your dependencies.
2. The dynamic config will be read if either `app.config.ts` or `app.config.js` exist. If both exist, then the TypeScript config is used.
3. If the dynamic config returns a function, then the static config is passed to the function with `({ config }) => ({})`. This function can then mutate the static config values.
4. Whatever is returned from the dynamic config is used as the final config. It cannot have any promises.
5. All functions in the config are evaluated and serialized before any tool in the Expo ecosystem uses it. The config must be a JSON manifest when it is hosted.
```

2020-08-31 18:42 UTC, cruzach commented on docs/pages/workflow/configuration.md
>  There are two different types of configs static (`app.config.json`, `app.json`) and dynamic (`app.config.js`, `app.config.ts`). Static configs can be automatically updated with CLI tools, whereas dyn
```suggestion
There are two different types of configs: static (`app.config.json`, `app.json`), and dynamic (`app.config.js`, `app.config.ts`). Static configs can be automatically updated with CLI tools, whereas dynamic configs must be manually updated by the developer.
```

2020-08-31 19:02 UTC, gregfenton reviewed
Reword to be explicit and clear - remove conditional wording

2020-08-31 19:19 UTC, cruzach commented on docs/pages/workflow/configuration.md
> +1. The static config are read if `app.config.json` exists (falls back to `app.json`). If no static config exists, then default values are inferred from the `package.json` and your dependencies.
```suggestion
1. The static config is read if `app.config.json` exists (falls back to `app.json`). If no static config exists, then default values are inferred from the `package.json` and your dependencies.
```

2020-08-31 19:19 UTC, cruzach commented on docs/pages/workflow/configuration.md
> +2. The dynamic config are read if either `app.config.ts` or `app.config.js` exist. If both exist, then the TypeScript config is used.
```suggestion
2. The dynamic config is read if either `app.config.ts` or `app.config.js` exist. If both exist, then the TypeScript config is used.
```

2020-09-01 22:46 UTC, cruzach approved these changes

2020-09-01 22:46 UTC, merged