[unimodules-sensors-interface] Remove unneeded separate interface package
expo/expo pull request #9943
Opened 2020-08-26 11:10 UTC by sjchmiela

# Why

Doing some cleaning. `unimodules-sensors-interface` was supposed to be an interface helping external developers and contributors provide their own sensors implementations if need be. There's no use in keeping it if we're the only ones using it.

# How

- iOS was very simple, as all the interfaces are actually implemented by one class, so I just created a protocol that encompassed all the interfaces and made the one class implement this protocol
- on Android there's a sophisticated structure of services and modules (about which I forgot) so it wasn't that easy — I had to move the interfaces into `expo-sensors` (they won't be used without it anyway).

# Test Plan

I have verified on devices of both platforms that sensors remain working well.

2020-08-26 21:43 UTC, ide approved these changes

2020-08-27 06:53 UTC, tsapeta approved these changes

2020-08-28 10:24 UTC, bbarthec requested changes
What about this package being published on npmjs? 🤔 
Do we want it to be orphaned just like that? (you've removed README.md and package.json) so no information is left 🤔 
I believe we must came up with some scenario for this to prevent us from having a bunch of orphaned modules on npm listed under our account/organisation in a year or two 🤓

2021-01-01 18:30 UTC, tsapeta approved these changes

2021-01-07 15:39 UTC, bbarthec approved these changes

2022-02-03 22:53 UTC, brentvatne commented
it looks like this is pretty outdated now. i'm going to close it but let's revisit if this change is still desired

2022-02-03 22:53 UTC, closed without merging