[expo-font] Miscallenous cleanup
expo/expo pull request #9957
Opened 2020-08-27 09:07 UTC by sjchmiela

# Why

Cleanup.

# How

I started with a task of wanting to remove `expo-font-interface`, but eventually I also added a dependency on React to `expo-font` (it remained a unimodule), which allowed me to move all font-related classes to inside `expo-font`, namely `UMReactFontManager`/`FontManager` (removing it from `@unimodules/react-native-adapter`, `expo-font-interface`). I've also unified error codes and messages, added filesystem permissions checks and removed scoping code from Android `expo-font`.

# Test Plan

I have verified that font loading still works on iOS and Android.

2020-08-27 09:09 UTC, sjchmiela commented
Let me know if this is too big, I sort of moved stuff around and implemented improvements until I was happy with the result, so I wasn't really knowing where I'd end up with the PR and couldn't plan commits parts ahead.

2020-08-27 09:13 UTC, sjchmiela commented
Going through only reviewable changes, i.e. commits that actually do something should be easier than the whole PR:

https://github.com/expo/expo/pull/9957/files/e3f603286360eb09afaa731c86aeb74189c999cd

(removed commits: _reinstall pods_ and _delete interface_)

2020-08-28 11:22 UTC, bbarthec requested changes
Looks good, but I believe we don't want to end up with another orphaned npm module published on npmjs registry 😞 
See https://github.com/expo/expo/pull/9943#pullrequestreview-477617749

2020-08-28 11:22 UTC, bbarthec commented on packages/expo-font/android/src/main/java/expo/modules/font/FontLoaderModule.java
> +    }
Extract to separate file 🙏 
Moreover this boilerplace is killing me 😞
I'd like to gradually move to kotlin whenever possible (every time a new chunk of code is created I wish it is kotlin and not java).

2020-08-28 11:22 UTC, bbarthec commented on packages/expo-font/ios/EXFont/Protocols/EXFontProcessorInterface.h
> +        scaleMultiplier:(CGFloat)scaleMultiplier;
```suggestion
                 style:(NSString *)style
               variant:(NSArray<NSDictionary *> *)variant
       scaleMultiplier:(CGFloat)scaleMultiplier;
```

2021-01-05 07:09 UTC, ide requested changes

2021-01-05 07:09 UTC, ide commented on android/expoview/src/main/java/versioned/host/exp/exponent/modules/universal/ScopedFontLoaderModule.kt
> +      return "ERR_LOCATION_ACCESS_UNAUTHORIZED"
```suggestion
      return "ERR_FONT_READ_FILE"
```

(This is not an expo-location error, and the error could occur if the file does not exist.)

2021-01-05 07:09 UTC, ide commented on android/expoview/src/main/java/versioned/host/exp/exponent/modules/universal/ScopedFontLoaderModule.kt
> +  class LocationAccessUnauthorizedError(uri: String) : CodedRuntimeException("You aren't authorized to load font file from: $uri") {
It looks like this error is also thrown if the file does not exist.

```suggestion
  class FontFileAccessError(uri: String) : CodedRuntimeException("No readable font file at: $uri") {
```

2021-01-05 07:09 UTC, ide commented on ios/Exponent/Versioned/Core/UniversalModules/EXScopedFontLoader.m
> +      reject(@"ERR_LOCATION_ACCESS_UNAUTHORIZED",
```suggestion
      reject(@"ERR_FONT_READ_FILE",
```

2021-01-05 07:09 UTC, ide commented on android/expoview/src/main/java/versioned/host/exp/exponent/modules/universal/ScopedFontLoaderModule.kt
> +      // If there's no constants module, or app ownership isn't "expo", we're not in Expo Client.
```suggestion
      // If there's no constants module, or app ownership isn't "expo", we're not in Expo Go.
```

2021-01-05 07:09 UTC, ide commented on ios/Exponent/Versioned/Core/UniversalModules/EXScopedFontLoader.m
> +             [NSString stringWithFormat:@"You aren't authorized to load font file from: %@", localUri],
```suggestion
             [NSString stringWithFormat:@"No readable font file at: %@", localUri],
```

2021-01-05 07:09 UTC, ide commented on packages/expo-font/android/src/main/java/expo/modules/font/FontLoaderModule.kt
> +      ?: throw InvalidArgumentException("Could not parse provided local font URI as a URI with a path component.")
It seems more robust to use the URI parser instead of the substring code above

2021-12-05 19:12 UTC, closed without merging